### ISSUE TITLE
Permanent ban (bantime=-1) causes failure when using firewalld

### ISSUE THREAD

**Issue by Tedderouni** [fail2ban/fail2ban#2179] opened 2018-07-15 00:58 UTC
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I've set up a vanilla install of CentOS 7.5 with firewalld and fail2ban.  When I try to set `bantime = -1`, fail2ban fails without warning.  I've tested this with the only other change to the default config being to enable the sshd jail.  When I leave bantime at the default setting it works as expected.

#### Steps to reproduce

1. Install CentOS 7.5 minimal installation
2. `sudo yum -y install epel-release`
3. `sudo yum -y install fail2ban-firewalld`
4. Create /etc/fail2ban/jail.local with the following contents:
```
[sshd]
enabled = true
bantime = -1
```
5. `sudo systemctl start fail2ban`

#### Expected behavior

Fail2ban starts and creates the appropriate firewall rule for the sshd jail.  The rule should look something like this:
```
# firewall-cmd --direct --get-all-rules
ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable
```

Also, an error message should be displayed from the startup script if the any errors occur while creating jails or in other steps.

#### Observed behavior

The startup command exits without displaying any error message, and the fail2ban service status also shows no error message.
The fail2ban process is running.
No firewall rule is created as shown by `firewall-cmd --direct --get-all-rules`.
Running `systemctl status fail2ban` looks as expected.
Running `systemctl status firewalld -l` shows the following error messages:
```
firewalld[703]: WARNING: '/usr/sbin/iptables-restore --wait=2 -n' failed: iptables-restore v1.4.21: Set fail2ban-sshd doesn't exist.

                Error occurred at line: 2
                Try 'iptables-restore -h' or 'iptables-restore --help' for more information.
firewalld[703]: ERROR: COMMAND_FAILED
```

The fail2ban log shows the messages shown below.

#### Any additional information
Running CentOS 7.5 (1804), with the following relevant package versions:
fail2ban-server-0.9.7-1.el7.noarch
fail2ban-firewalld-0.9.7-1.el7.noarch
ipset-6.29-1.el7.x86_64
firewalld-0.4.4.4-14.el7.noarch

#### Any customizations done to /etc/fail2ban/ configuration
Only the following settings as mentioned above:
```
# cat jail.local
[sshd]
enabled = true
bantime = -1
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2018-07-14 19:25:17,462 fail2ban.jail           [21346]: INFO    Jail 'sshd' started
2018-07-14 19:25:17,969 fail2ban.action         [21346]: ERROR   ipset create fail2ban-sshd hash:ip timeout -1
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable -- stdout: ''
2018-07-14 19:25:17,969 fail2ban.action         [21346]: ERROR   ipset create fail2ban-sshd hash:ip timeout -1
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable -- stderr: "ipset v6.29: Syntax error: '-1' is out of range 0-4294967\nError: COMMAND_FAILED\n"
2018-07-14 19:25:17,969 fail2ban.action         [21346]: ERROR   ipset create fail2ban-sshd hash:ip timeout -1
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable -- returned 13
2018-07-14 19:25:17,969 fail2ban.actions        [21346]: ERROR   Failed to start jail 'sshd' action 'firewallcmd-ipset': Error starting action
```

#### Relevant lines from monitored log files in question:
N/A

**Comment by sebres** [comment] 2018-07-16 10:44
This is fixed in newer versions. For 0.9 you can simply overwrite bantime (timeout) parameter in action inside the jail (parameter timeout for ipset persistent rule is 0).
```ini
[sshd]
bantime = -1
action = %(banaction)s[name=%(__name__)s, bantime=0, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
```

**Closed by sebres** 2018-07-16 10:44 UTC

**Comment by alaahariri** [comment] 2019-07-19 19:07
Hello, 

I have exactly the same error for firewalld. However, I am not using permanent bantime. In the firewalld log file, the following error repeating everytimg: 

`2018-12-11 01:24:39 ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set fail2ban-ssh doesn't exist.

Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
`

I have exactly the same configuration of the original post. In fail2ban log file, there is no any error. The problem is only with firewalld.  

Can you please help me on how to fix this?

**Comment by sebres** [comment] 2019-07-20 10:04
> I have exactly the same error for firewalld. 

Nope, the issue describes supplying of wrong timeout parameter (of persistent jails) caused error `Syntax error: '-1' is out of range`, your error seems to be `Set fail2ban-ssh doesn't exist`.
But if you nevertheless mean, you seems to have "exactly the same error" (and fail2ban v.0.9.x), I described above how to fix it... Simply set `bantime=0` as a parameter of `action` (not jail), or even set it as default in your jail.local:
```ini
[DEFAULT]
action_ = %(banaction)s[name=%(__name__)s, bantime="0", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
```
In newer versions of fail2ban it should be already fixed.

If it is not the same, then something seems to delete your chain or set `fail2ban-ssh` by running fail2ban.
E. g. that may be missing dependencies (so for example firewall reloaded without fail2ban), or some service which reset rules created by fail2ban.
In this case the only "repair" possibility I see at the moment - to restart fail2ban.
And try to find and fix the service which causes that to avoid it in the future.

---
Note to me: still one reason to fulfill #980.

**Comment by alaahariri** [comment] 2019-07-20 14:11
Dear Sergey, 

> But if you nevertheless mean, you seems to have "exactly the same error" (and fail2ban v.0.9.x), I described above how to fix it... Simply set bantime=0 as a parameter of action (not jail), or even set it as default in your jail.local

Yes, I meant I am getting exactly the same error message. I have fail2ban version 0.9.7-1.e17 However, I already followed your fix above with no luck. My server is Centos 7. Please see the output of the below commands: 

`# systemctl status fail2ban`

```
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-07-20 13:38:08 +03; 22min ago
     Docs: man:fail2ban(1)
  Process: 2727 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 2768 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=0/SUCCESS)
 Main PID: 2771 (fail2ban-server)
   CGroup: /system.slice/fail2ban.service
           └─2771 /usr/bin/python2 -s /usr/bin/fail2ban-server -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x -b

Jul 20 13:38:07  systemd[1]: Stopped Fail2Ban Service.
Jul 20 13:38:07  systemd[1]: Starting Fail2Ban Service...
Jul 20 13:38:08  fail2ban-client[2768]: 2019-07-20 13:38:08,011 fail2ban.server         [2769]: INFO    Starting Fail2ban v0.9.7
Jul 20 13:38:08  fail2ban-client[2768]: 2019-07-20 13:38:08,012 fail2ban.server         [2769]: INFO    Starting in daemon mode
Jul 20 13:38:08  systemd[1]: Started Fail2Ban Service.
```

`# firewall-cmd --direct --get-all-rules`

`ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable
ipv4 filter INPUT 0 -p tcp -m multiport --dports 0:65535 -m set --match-set fail2ban-ssh src -j REJECT --reject-with icmp-port-unreachable`

`# systemctl status firewalld`

```
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-07-20 15:50:32 +03; 1h 16min ago
     Docs: man:firewalld(1)
 Main PID: 643 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─643 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

Jul 20 15:50:30  systemd[1]: Starting firewalld - dynamic firewall daemon...
Jul 20 15:50:32  systemd[1]: Started firewalld - dynamic firewall daemon.
Jul 20 15:50:34  firewalld[643]: ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set fail2ban-ssh doesn't exist.

                                                Error occurred at line: 2
                                                Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Jul 20 15:50:34  firewalld[643]: ERROR: COMMAND_FAILED: Direct: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set fail2ban-ssh doesn't exist.

                                                Error occurred at line: 2
                                                Try `iptables-restore -h' or 'iptables-restore --help' for more information.

```

I reinstalled fail2ban and firwalld with no luck. The content of jail.local is as follows: 
```

[DEFAULT]
ignoreip = 127.0.0.0/8
bantime  = 86400
findtime = 86400
maxretry = 5

# Override /etc/fail2ban/jail.d/00-firewalld.conf:
banaction = firewallcmd-ipset

[sshd]
enabled = true

[ssh]
enabled  = true
filter   = sshd
action   = %(action_)s
logpath  = /var/log/secure
maxretry = 5
```

So what is going wrong? Am I missing anything? I am a developer who knows few about servers. 

Thank you!

**Comment by sebres** [comment] 2019-07-22 09:38
Hmm... 

Our action [firewallcmd-ipset](https://github.com/fail2ban/fail2ban/blob/0.9/config/action.d/firewallcmd-ipset.conf) does not create permanent rules.
I don't know firewalld innards (not use it and therefore not so familiar), but it seems to use iptables-restore, even to restore permanent rules. 
The error you see (`Set fail2ban-ssh doesn't exist.`), if you're starting firewalld, looks like some persistent rule.

The only one explanation I see at the moment: For some reasons something (or possibly you at some day) have obtained fail2ban chain as some permanent rule in firewalld, but because in chain related ipset is not yet created to start time point, it fails obviously.

Either you need to delete (manually) this rule (and possibly some others) in firewalld. Or you should create ipset's before firewalld going started (some service and add dependency in firewalld.service).
But normally you should not use fail2ban chains in your own firewalld rules (or other services).

If I were you, I'd stop fail2ban and delete all remaining rules with name matching `fail2ban-*` manually, something like:
```
firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable 
firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports 0:65535 -m set --match-set fail2ban-ssh src -j REJECT --reject-with icmp-port-unreachable
```

**Comment by alaahariri** [comment] 2019-07-22 11:43
Your solution worked like a charm. Thanks a million. I have been struggling with it especially that Google has no results related to the same error message except this page. 

I want to note that while manually deleting the 2 rules, I got the following warning for one of them only. 

`Warning: NOT_ENABLED: rule '['-p', 'tcp', '-m', 'multiport', '--dports', 'ssh', '-m', 'set', '--m                                                                                                    atch-set', 'fail2ban-sshd', 'src', '-j', 'REJECT', '--reject-with', 'icmp-port-unreachable']' is                                                                                                     not in 'ipv4:filter:INPUT'`

So having no warning for the other rule would confirm your explanation: 

> The only one explanation I see at the moment: For some reasons something (or possibly you at some day) have obtained fail2ban chain as some permanent rule in firewalld, but because in chain related ipset is not yet created to start time point, it fails obviously.

I have no error messages and clean log files now.

Have a wonderful life.

**Comment by raviktiwari007** [comment] 2020-08-16 21:29
Hi @sebres picking from the subject line, I am facing issues with Permanent ban (bantime=-1) 

I am using Virtualmin which has Fail2Ban v0.10.2

In order to configure permanent ban, in jail.local, I set the "bantime  = -1" 

But now logwatch has started throwing error:
7f0fc88522c0 --   stderr: "ipset v6.34: Syntax error: '-1' is out of range   0-4294967": 3 Time(s)

So I have 3 questions:

1.> I have now changed it to:  "bantime  = 4294967" but this is not a permanent block - so what else I can do?

2.> Where does all the blocked IP Address get stored (just in case I want to see all the banned ip in one place). Will it be in "hosts.deny"?

3.> What happens when I have thousands and millions of ip address in my blocked list? I mean the file size will increase, the initial scan will get longer, so will it slow down the system? So does that mean we should refresh the "blocked list" periodically?


Many Thanks,
Rav

**Comment by sebres** [comment] 2020-08-17 09:41
1. It is fixed in newest version
2. where the IPs are stored in net-filter is the matter of action used for that, ipset stores it in ipset hash tables (memory); in fail2ban they are stored internally in memory and sqlite database
3. this is the main reason why I say everywhere "don't use persistent banning". There are many better alternatives for instance version 0.11 has an incremental banning:
```ini
# incremental ban-time:
bantime.increment = true
# max ban-time 7 week:
bantime.maxtime = 7w
```

**Comment by raviktiwari007** [comment] 2020-08-17 10:20
Thanks @sebres 

1.> What is the latest version? Is it ready and available or about to be released? Is there a simple command to upgrade it without loosing previous settings and configurations?

2.> Does that mean all jails should have same action (as far as storing IP is concerned or else every jail will be stroring IP address at different locations)? Should I look for action.d and then respective jail.conf

3.>Thanks for this. Can I jsut go ahead and use the command that you suggested. Rememeber, I am still on "Fail2Ban v0.10.2". Will it still work?

**Comment by sebres** [comment] 2020-08-17 10:35
1. This will be released soon in 0.10.6 and 0.11.2
2. Same banning action is not equal same chain or in case of ipset it is a set (hash table). So in general it is indeed different "location".
But if you're asking for clean-up (unban of some old entries) - fail2ban-client has a command for that - `unban` or `unbanip` would remove it from ban-manager (memory/sqlite database of fail2ban) and from ipset (or whatever banaction is specified).
3. No. As already wrote, incremental banning is available starting from 0.11 (v.0.10 doesn't have it).

**Comment by raviktiwari007** [comment] 2020-08-17 11:02
Cool... Thanks... So I will leave my settings as it is... and wait for the new release to come through.

Thanks a lot for your time and support.

**Comment by raviktiwari007** [comment] 2020-08-17 11:16
Hey @sebres, I have one more trickey one for you...:-)

I know this is a wrong section/topic for this question, but I have tried looking for right topic for more than 3 hours and still could not find anyone... so I am posting it here and if you want to move it to right/better section, please feel free to do so.

I have been bombarded with following errors from logwatch (many of them I have been able to solve, but few of them are still bothering me). Sometime all the errors go away (except 1 or 2) and something all of them will come back - I don't know what I am doing wrong. So can you please have a look and suggest something:



** ERRORS **
--
7f0fc83f35f8 -- stderr: "ipset v6.34: Syntax error: '-1' is out   of range 0-4294967": 1 Time(s)
7f0fc83f35f8 -- stderr: 'Error: COMMAND_FAILED': 1 Time(s)
7f0fc8845030 -- stderr: "ipset v6.34: Syntax error: '-1' is out   of range 0-4294967": 1 Time(s)
7f0fc8845030 -- stderr: 'Error: COMMAND_FAILED': 1 Time(s)
7f0fc88522c0 -- stderr: "ipset v6.34: Syntax error: '-1' is out   of range 0-4294967": 2 Time(s)
7f0fc88522c0 -- stderr: 'Error: COMMAND_FAILED': 2 Time(s)
7f0fca615d40 -- exec: iptables -w -N f2b-SMTP-auth: 1 Time(s)
7f0fca615d40 -- killed with SIGTERM (return code: -15): 1 Time(s)
7f0fca615d40 -- stderr: 'Another app is currently holding the xtables   lock; waiting for it to exit...': 6 Time(s)
7f0fca615d40 -- timed out after 60 seconds.: 1 Time(s)

Failed to execute ban jail 'dovecot' action 'firewallcmd-ipset' info   'ActionInfo({'ip': '52.125.140.53', 'family': 'inet4', 'ip-rev':   '53.140.125.52.', 'ip-host': None, 'fid': '52.125.140.53', 'failures': 1,   'time': 1597420431.0, 'matches': 'Aug 14 16:53:51 mail dovecot: imap-login:   Disconnected (auth failed, 1 attempts in 5 secs): user=<info@esspl.co.uk>, method=LOGIN,   rip=52.125.140.53, lip=192.168.24.30, TLS, session=<E+oZbdisaJk0fYw1>',   'restored': 0, 'F-*': {'matches': [('', 'Aug 14 16:53:51', ' mail dovecot:   imap-login: Disconnected (auth failed, 1 attempts in 5 secs): user=<info@esspl.co.uk>, method=LOGIN,   rip=52.125.140.53, lip=192.168.24.30, TLS,   session=<E+oZbdisaJk0fYw1>')], 'failures': 1, 'ip4': '52.125.140.53'},   'ipmatches': 'Aug 14 16:53:51 mail dovecot: imap-login: Disconnected (auth   failed, 1 attempts in 5 secs): user=<info@esspl.co.uk>,   method=LOGIN, rip=52.125.140.53, lip=192.168.24.30, TLS, sessio   n=<E+oZbdisaJk0fYw1>', 'ipjailmatches': 'Aug 14 16:53:51 mail dovecot:   imap-login: Disconnected (auth failed, 1 attempts in 5 secs): user=<info@esspl.co.uk>, method=LOGIN,   rip=52.125.140.53, lip=192.168.24.30, TLS, session=<E+oZbdisaJk0fYw1>',   'ipfailures': 1, 'ipjailfailures': 1})': Error starting action   Jail('dovecot')/firewallcmd-ipset: 1 Time(s)

Failed to execute ban jail 'postfix-auth' action 'iptables' info   'ActionInfo({'ip': '87.246.7.141', 'family': 'inet4', 'ip-rev':   '141.7.246.87.', 'ip-host': 'net6-ip141.linkbg.com', 'fid': '87.246.7.141',   'failures': 1, 'time': 1597365917.0, 'matches': 'Aug 14 01:45:17 mail   postfix/smtpd[8527]: lost connection after AUTH from unknown[87.246.7.141]',   'restored': 0, 'F-*': {'matches': [('', 'Aug 14 01:45:17', ' mail   postfix/smtpd[8527]: lost connection after AUTH from   unknown[87.246.7.141]')], 'failures': 1, 'ip4': '87.246.7.141'}, 'ipmatches':   'Aug 14 01:45:17 mail postfix/smtpd[8527]: lost connection after AUTH from   unknown[87.246.7.141]\nAug 14 01:45:17 mail postfix/smtpd[8527]: warning:   unknown[87.246.7.141]: SASL LOGIN authentication failed: authentication   failure\nAug 14 01:45:35 mail postfix/smtpd[8527]: lost connection after AUTH   from unknown[87.246.7.141]\nAug 14 01:45:35 mail postfix/smtpd[8527]:   warning: unknown[87.246.7.141]: SASL LOGI N authentication failed:   authentication failure\nAug 14 01:45:51 mail postfix/smtpd[8527]: lost   connection after AUTH from unknown[87.246.7.141]\nAug 14 01:45:51 mail   postfix/smtpd[8527]: warning: unknown[87.246.7.141]: SASL LOGIN authentication   failed: authentication failure\nAug 14 01:46:08 mail postfix/smtpd[8527]:   lost connection after AUTH from unknown[87.246.7.141]\nAug 14 01:46:08 mail   postfix/smtpd[8527]: warning: unknown[87.246.7.141]: SASL LOGIN   authentication failed: authentication failure', 'ipjailmatches': 'Aug 14   01:45:17 mail postfix/smtpd[8527]: lost connection after AUTH from   unknown[87.246.7.141]\nAug 14 01:45:35 mail postfix/smtpd[8527]: lost   connection after AUTH from unknown[87.246.7.141]\nAug 14 01:45:51 mail   postfix/smtpd[8527]: lost connection after AUTH from   unknown[87.246.7.141]\nAug 14 01:46:08 mail postfix/smtpd[8527]: lost   connection after AUTH from unknown[87.246.7.141]', 'ipfailures': 8,   'ipjailfailures': 4})': Error starting action Jail('postfix-auth' )/iptables:   1 Time(s)

Failed to execute ban jail 'postfix-rbl' action 'firewallcmd-ipset'   info 'ActionInfo({'ip': '212.70.149.19', 'family': 'inet4', 'ip-rev':   '19.149.70.212.', 'ip-host': None, 'fid': '212.70.149.19', 'failures': 1,   'time': 1597434612.187076, 'matches': '', 'restored': 0, 'F-*': {'matches':   [], 'failures': 1}, 'ipmatches': 'Aug 14 20:31:18 mail postfix/smtpd[17028]:   warning: unknown[212.70.149.19]: SASL LOGIN authentication failed:   authentication failure\nAug 14 20:31:40 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:32:03 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:32:25 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:32:47 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:33:09 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:33:31 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:33:54 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:34:17 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:34:39 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:35:02 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication failure\nAug   14 20:35:24 mail postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL   LOGIN authentication failed: authentication failure\nAug 14 20:35:47 mail   postf ix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:36:09 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:36:31 mail   postfix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:36:54 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:37:17 mail   postfix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN authentication   failed: authentication failure\nAug 14 20:37:38 mail postfix/smtpd[32883]:   warning: unknown[212.70.149.19]: SASL LOGIN authentication failed:   authentication failure\nAug 14 20:38:01 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:38:23 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGI N authentication failed: authentication   failure\nAug 14 20:38:45 mail postfix/smtpd[17028]: warning: unknown[212.70.149.19]:   SASL LOGIN authentication failed: authentication failure\nAug 14 20:39:07   mail postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:39:29 mail   postfix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:39:52 mail   postfix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:40:14 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:40:36 mail   postfix/smtpd[17028]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:40:59 mail postfix/smtpd[32883]:   warning: unknown[212.70.149.19]: SASL LOGIN authentication failed:   authentication failure\nAug 14 20: 41:21 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:41:44 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:42:06 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:42:29 mail postfix/smtpd[32883]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:42:51 mail postfix/smtpd[17028]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication failure\nAug   14 20:43:12 mail postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL   LOGIN authentication failed: authentication failure\nAug 14 20:43:36 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:43:58 mail   postfix/smtpd[32883]: warning: unknown[212.70.14 9.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:44:20 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:44:41 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:45:04 mail   postfix/smtpd[32883]: warning: unknown[212.70.149.19]: SASL LOGIN authentication   failed: authentication failure\nAug 14 20:45:27 mail postfix/smtpd[32883]:   warning: unknown[212.70.149.19]: SASL LOGIN authentication failed:   authentication failure\nAug 14 20:45:49 mail postfix/smtpd[98684]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:46:12 mail postfix/smtpd[98684]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:46:35 mail postfix/smtpd[98684]: warning: unknown[212.70.149.19]:   SASL LOGIN authentication failed: authentication fai lure\nAug 14 20:46:58   mail postfix/smtpd[98684]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:47:20 mail   postfix/smtpd[98684]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:47:43 mail   postfix/smtpd[98684]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:48:06 mail   postfix/smtpd[98684]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:48:28 mail   postfix/smtpd[98684]: warning: unknown[212.70.149.19]: SASL LOGIN   authentication failed: authentication failure\nAug 14 20:48:50 mail postfix/smtpd[100939]:   warning: unknown[212.70.149.19]: SASL LOGIN authentication failed:   authentication failure\nAug 14 20:49:13 mail postfix/smtpd[100939]: warning:   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure\nAug 14 20:49:35 mail postfix/smtpd[100939]: warning :   unknown[212.70.149.19]: SASL LOGIN authentication failed: authentication   failure', 'ipjailmatches': '', 'ipfailures': 15350, 'ipjailfailures': 1})':   Error starting action Jail('postfix-rbl')/firewallcmd-ipset: 1 Time(s)

Failed to execute ban jail 'postfix-sasl' action 'firewallcmd-ipset'   info 'ActionInfo({'ip': '87.246.7.133', 'family': 'inet4', 'ip-rev':   '133.7.246.87.', 'ip-host': 'net6-ip133.linkbg.com', 'fid': '87.246.7.133',   'failures': 1, 'time': 1597396466.0, 'matches': 'Aug 14 10:14:26 mail   postfix/smtpd[7828]: warning: unknown[87.246.7.133]: SASL LOGIN   authentication failed: authentication failure', 'restored': 0, 'F-*':   {'matches': [('', 'Aug 14 10:14:26', ' mail postfix/smtpd[7828]: warning:   unknown[87.246.7.133]: SASL LOGIN authentication failed: authentication   failure')], 'failures': 1, 'ip4': '87.246.7.133'}, 'ipmatches': 'Aug 14   10:14:26 mail postfix/smtpd[7828]: lost connection after AUTH from   unknown[87.246.7.133]\nAug 14 10:14:26 mail postfix/smtpd[7828]: warning:   unknown[87.246.7.133]: SASL LOGIN authentication failed: authentication   failure', 'ipjailmatches': 'Aug 14 10:14:26 mail postfix/smtpd[7828]:   warning: unknown[87.246.7.133]: SASL LOG IN authentication failed:   authentication failure', 'ipfailures': 2, 'ipjailfailures': 1})': Error   starting action Jail('postfix-sasl')/firewallcmd-ipset: 1 Time(s)

Failed to execute ban jail 'postfix-sasl' action 'firewallcmd-ipset'   info 'ActionInfo({'ip': '87.246.7.141', 'family': 'inet4', 'ip-rev': '141.7.246.87.',   'ip-host': 'net6-ip141.linkbg.com', 'fid': '87.246.7.141', 'failures': 1,   'time': 1597365917.0, 'matches': 'Aug 14 01:45:17 mail postfix/smtpd[8527]:   warning: unknown[87.246.7.141]: SASL LOGIN authentication failed:   authentication failure', 'restored': 0, 'F-*': {'matches': [('', 'Aug 14   01:45:17', ' mail postfix/smtpd[8527]: warning: unknown[87.246.7.141]: SASL   LOGIN authentication failed: authentication failure')], 'failures': 1, 'ip4':   '87.246.7.141'}, 'ipmatches': 'Aug 14 01:45:17 mail postfix/smtpd[8527]: lost   connection after AUTH from unknown[87.246.7.141]\nAug 14 01:45:17 mail   postfix/smtpd[8527]: warning: unknown[87.246.7.141]: SASL LOGIN   authentication failed: authentication failure', 'ipjailmatches': 'Aug 14   01:45:17 mail postfix/smtpd[8527]: warning: unknown[87.246.7.141]: SASL LOG   IN authentication failed: authentication failure', 'ipfailures': 2,   'ipjailfailures': 1})': Error starting action   Jail('postfix-sasl')/firewallcmd-ipset: 1 Time(s)
 
** WARNINGS **
Command ['set', 'postfix-smtp', 'banip', '212.70.149.19'] has failed.   Received UnknownJailException('postfix-smtp',): 1 Time(s)
Command ['set', 'postfix/smtp', 'banip', '212.70.149.19'] has failed.   Received UnknownJailException('postfix/smtp',): 1 Time(s)
 
3 error(s) returned   from actions:
2020-08-14   01:45:21,377 fail2ban.utils          [1273]: ERROR     7f0fc88522c0 -- returned 13
2020-08-14   10:14:29,209 fail2ban.utils          [1273]: ERROR     7f0fc88522c0 -- returned 13
2020-08-14   16:53:54,031 fail2ban.utils          [1273]: ERROR     7f0fc8845030 -- returned 13
2020-08-14   20:50:13,956 fail2ban.utils          [1273]: ERROR     7f0fc83f35f8 -- returned 13
 
**Unmatched Entries**
2020-08-14 01:45:21,377 fail2ban.utils          [1273]:   Level 39 7f0fc88522c0 -- exec: ipset create f2b-postfix-sasl hash:ip timeout   -1: 1 Time(s)
2020-08-14 10:14:29,208 fail2ban.utils            [1273]: Level 39 7f0fc88522c0 -- exec: ipset create f2b-postfix-sasl   hash:ip timeout -1: 1 Time(s)
2020-08-14 16:53:54,029 fail2ban.utils            [1273]: Level 39 7f0fc8845030 -- exec: ipset create f2b-dovecot hash:ip   timeout -1: 1 Time(s)
2020-08-14 20:50:13,956 fail2ban.utils            [1273]: Level 39 7f0fc83f35f8 -- exec: ipset create f2b-postfix-rbl   hash:ip timeout -1: 1 Time(s)


As you can see there are 5 sections of errors and warning - I am not sure how to decode it and what should I do to resolve it.

As you know I am new to f2b, so if you can please explain with example and path of file where the changes needs to be made - it will be highy appreciated.

**Comment by sebres** [comment] 2020-08-17 11:54
As already said it is fixed in newest version, so you could:
- either wait for newest version (probably better because you seem to be not familiar);
- or update fail2ban config files or related actions from latest version (here [action.d/firewallcmd-ipset.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/firewallcmd-ipset.conf) of 0.10)
- or use a suggestion from above (https://github.com/fail2ban/fail2ban/issues/2179#issuecomment-405209344) configuration - set bantime to 0 **in action parameters** (not a jail parameter).

> so if you can please explain with example and path of file where the changes needs to be made

Please note that this is a developer repository and here is basically not a place for how-to's.

**Comment by raviktiwari007** [comment] 2020-08-17 12:45
Thanks @sebres that's helpful... I will have a look based on your suggestion and also wait for the new release.

Many Thanks.
