### ISSUE TITLE
record duplication in fail2ban.sqlite3 database

### ISSUE THREAD

**Issue by malkhamis** [fail2ban/fail2ban#1844] opened 2017-07-24 04:25 UTC
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.9.7
- OS, including release name/version: openSUSE Leap 42.2
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:
many banned IPs are duplicated in the SQLite3 database located in /var/lib/fail2ban/fail2ban.sqlite3

#### Steps to reproduce
1. navigate to `/var/lib/fail2ban` in the shell
2. type `su`, then `sqlite3`
3. execute this query: 
    * `attach "fail2ban.sqlite3" as db1;`
    * `SELECT * FROM bans ORDER BY ip ASC;`

#### Expected behavior
Duplicate records should not be present
#### Observed behavior
there exists man duplicate records.. Here is an example from my system:

sshd|103.207.36.31|1499920211|{"matches": ["2017-07-12T21:30:11.450747linux-bvk4 sshd[23649]: Invalid user ubnt from 103.207.36.31"], "failures": 1}
sshd|103.207.36.31|1499920211|{"matches": ["2017-07-12T21:30:11.450747linux-bvk4 sshd[23649]: Invalid user ubnt from 103.207.36.31"], "failures": 1}
sshd|103.207.36.31|1499920211|{"matches": ["2017-07-12T21:30:11.450747linux-bvk4 sshd[23649]: Invalid user ubnt from 103.207.36.31"], "failures": 1}

#### Any additional information
I modified the `sshd.conf` regex file to add new regexes. Although this duplication in the database might be due to the same log matching multiple regexes, this should not result in record duplication.
#### Any customizations done to /etc/fail2ban/ configuration
jail.local
[DEFAULT]
backend = systemd

```
```

**Comment by sebres** [comment] 2017-07-28 14:34
should be fixed in #1460

**Comment by sebres** [comment] 2017-11-26 22:50
> Although this duplication in the database might be due to the same log matching multiple regexes, this should not result in record duplication.

Exactly this one was never an issue in fail2ban, because the first match of `failregex` wins (and it will not check/search for more). 
The entry (with all matches) will be written in database after ban, therefore I assume only restart/reload could do this (if active ban from restored ticket will be written into database after reban), but as already said it should be already fixed, I cannot reproduce it anyway.

Thus closing, please reopen if still acute in newer version.

**Closed by sebres** 2017-11-26 22:50 UTC
