### ISSUE TITLE
asyncore: (9, 'Bad file descriptor')

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#161] opened 2013-03-27 16:13 UTC
```
Testing using /usr/bin/python2.6
Fail2ban 0.8.8 test suite. Python 2.6.8 (unknown, Jan 26 2013, 14:35:25) [GCC 4.7.2]. Please wait...
.........................................Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yoh/deb/gits/fail2ban/server/asyncserver.py", line 144, in start
    asyncore.loop(use_poll = False) # fixes the "Unexpected communication problem" issue on Python 2.6 and 3.0
  File "/usr/lib/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 140, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')

.....................................F....
```

Never ran into this one before (or at least not for a while ;) )

**Comment by sebres** [comment] 2015-01-20 12:41
pong...
It is today extremely reproducible for me with python 2.7.6, with ...
```
PYTHONPATH=. ./bin/fail2ban-testcases Socket Helpers Setup
```
And because of <a href="http://bugs.python.org/issue10878">issue10878</a>, resp. because of <blockquote>I am re-closing as there is no defined bug to fix, and 2.7 is closed to enhancements</blockquote>... we can only workaround this one with `use_poll = True` for 2.7.
Ready, will commit it after all test cases done.

**Closed** 2015-02-03 02:44 UTC
Labels: moreinfo
