### ISSUE TITLE
Avoid hardcoded relative paths in the sample test config files

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1772] opened 2017-05-11 03:08 UTC
Original report is below.  The failure is due to hardcoded relative paths in fail2ban/tests/config/filter.d/zzz-generic-example.conf etc, which are no longer valid if testing out of source build (as in original report).
Proper resolution might be either of
- construct those files on the fly during tests while using `fail2ban.tests.utils.CONFIG_DIR`
- provide some special handling for having something like `before = %(CONFIG_DIR)s/...`
For now, as a quick and dirty fix, I will just patch those paths while building debian package

```shell
make[1]: Entering directory '/build/fail2ban-0.9.7'
cd build && LC_ALL=C.UTF-8 FAIL2BAN_CONFIG_DIR="/build/fail2ban-0.9.7/config" PYTHONPATH="/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/" scripts-*/fail2ban-testcases --no-network
Fail2ban 0.9.7 test suite. Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]. Please wait...
........................s...................................................................s..........s.......................................................................................................................................E............................s..
======================================================================
ERROR: testSampleRegexsZZZ-GENERIC-EXAMPLE (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/fail2ban/tests/samplestestcase.py", line 90, in testFilter
    filterConf.getOptions({})
  File "/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/fail2ban/client/configreader.py", line 284, in getOptions
    self, "Definition", self._configOpts, pOpts)
  File "/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/fail2ban/client/configreader.py", line 137, in getOptions
    return self._cfg.getOptions(*args, **kwargs)
  File "/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/fail2ban/client/configreader.py", line 220, in getOptions
    v = self.get(sec, option[1])
  File "/usr/lib/python3.5/configparser.py", line 797, in get
    d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/build/fail2ban-0.9.7/.pybuild/pythonX.Y_3.5/build/fail2ban/client/configparserinc.py", line 59, in _interpolate_some
    parser, option, accum, rest, section, map, depth)
  File "/usr/lib/python3.5/configparser.py", line 433, in _interpolate_some
    option, section, rawval, var) from None
configparser.InterpolationMissingOptionError: Bad value substitution: option 'failregex' in section 'Definition' contains an interpolation key '__prefix_line' which is not a valid option name. Raw value: '^%(__prefix_line)sF2B: failure from <HOST>$'

----------------------------------------------------------------------
Ran 271 tests in 71.277s

FAILED (errors=1, skipped=4)

```
@sebres -- may be sounds familiar?  I think it is due to

```
--- a/config/filter.d/sshd.conf
+++ b/config/filter.d/sshd.conf
@@ -14,27 +14,54 @@
 # common.local
 before = common.conf
 
-[Definition]
+[DEFAULT]
 
```
change since 0.9.6 ... but not sure why it triggers only on python 3.5 here (passed fine on my laptop with 2.7).

**Comment by yarikoptic** [comment] 2017-05-11 03:22
ah no -- it is because of the 
```
-before = common.conf
+before = ../../../../config/filter.d/common.conf
```
... I am surprised somewhat that we do not fail if file listed in before doesn't exist :-/

**Comment by yarikoptic** [comment] 2018-01-22 02:26
uff, hit it again (#2024) so I guess I have not addressed it properly :-/

**Comment by sebres** [comment] 2018-01-24 07:43
fixed in #2025

**Closed by sebres** 2018-01-24 07:43 UTC

**Comment by Zeba126** [comment] 2025-01-06 09:32
hi @yarikoptic 

We have observed that tests are failing with this patch as well [https://salsa.debian.org/python-team/packages/fail2ban/-/blob/master/debian/patches/deb_path_to_common?ref_type=heads](url) , and the debian build log indicates this too [https://buildd.debian.org/status/fetch.php?pkg=fail2ban&arch=all&ver=1.1.0-7&stamp=1725174764&raw=0](url)

Do you have any suggestions on how we should address this issue, or is there a particular approach that you believe will resolve this? any input will be of great help .

**Comment by yarikoptic** [comment] 2025-01-06 14:28
@Zeba126 sorry, can't look ATM in detail , but what should be the relative path there -- did you look if it might need tune up?  anyways -- this is way too old issue which was addressed. If there is smth debian specific -- better file in debian bts

**Comment by sebres** [comment] 2025-01-12 16:36
Just for the record: if I follow this correctly, it seems to be fixed by deletion of `debian/patches/deb_path_to_common` patch in [salsa/.../commit/fd9a2111c9a80be3f6ae873e0b981a4fa84a765c](https://salsa.debian.org/python-team/packages/fail2ban/-/commit/fd9a2111c9a80be3f6ae873e0b981a4fa84a765c)

Otherwise, since the error caused by missing interpolation variable (include), one could start the test-suite with heavy debug level, to investigate deeper what exactly happens here, for instance check which config-files did not read, e. g.:
```bash
bin/fail2ban-testcases -l 10 'testSampleRegexsZZZ-GENERIC-EXAMPLE'
```
<details><summary>This is the expected output (from folder `/prj/fail2ban`)...</summary>

```
sebres@deb:/prj/fail2ban$ PYTHONPATH=. bin/fail2ban-testcases -l 10 'testSampleRegexsZZZ-GENERIC-EXAMPLE'
Fail2ban 1.1.1.dev1 test suite. Python 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]. Please wait...
testSampleRegexsZZZ-GENERIC-EXAMPLE (fail2ban.tests.samplestestcase.FilterSamplesRegex.testSampleRegexsZZZ-GENERIC-EXAMPLE) ...
 +  148 7F7B9CB8B040 fail2ban                  DEBUG ========== fail2ban.tests.samplestestcase.FilterSamplesRegex.testSampleRegexsZZZ-GENERIC-EXAMPLE ====================
 +  149 7F7B9CB8B040 fail2ban.filter           DEBUG Setting usedns = warn for Filter(None)
 +  149 7F7B9CB8B040 fail2ban.filter           DEBUG Created Filter(None)
 +  150 7F7B9CB8B040 fail2ban.configreader     INFO  Loading configs for filter.d/zzz-generic-example under /prj/fail2ban/fail2ban/tests/config
 +  150 7F7B9CB8B040 fail2ban.configreader     DEBUG Reading configs for filter.d/zzz-generic-example under /prj/fail2ban/fail2ban/tests/config
 +  150 7F7B9CB8B040 fail2ban.configreader     DEBUG Reading config files: /prj/fail2ban/fail2ban/tests/config/filter.d/zzz-generic-example.conf
 +  150 7F7B9CB8B040 fail2ban.configparserinc  INFO    Loading files: ['/prj/fail2ban/fail2ban/tests/config/filter.d/zzz-generic-example.conf']
 +  151 7F7B9CB8B040 fail2ban.configparserinc  INFO    Loading files: ['/prj/fail2ban/fail2ban/tests/config/filter.d/../../../../config/filter.d/common.conf']
 +  152 7F7B9CB8B040 fail2ban.configparserinc  INFO    Loading files: ['/prj/fail2ban/fail2ban/tests/config/filter.d/../../../../config/filter.d/common.local']
 +  152 7F7B9CB8B040 fail2ban.configparserinc  INFO    Loading files: ['/prj/fail2ban/fail2ban/tests/config/filter.d/../../../../config/filter.d/common.conf', '/prj/fail2ban/fail2ban/tests/config/filter.d/zzz-generic-example.conf']
 +  155 7F7B9CB8B040 fail2ban.datedetector     INFO    date pattern `'{^LN-BEG}%ExY(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\\s*%z)?'`: `{^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day[T ]24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?`
 +  155 7F7B9CB8B040 fail2ban.datedetector     DEBUG   date pattern regex for '{^LN-BEG}%ExY(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\\s*%z)?': ^(?:\W{0,2})?((?P<Y>20[012]\d)(?P<_sep>[-/.])(?P<m>0?[1-9]|1[0-2])(?P=_sep)(?P<d>[1-2]\d|[0 ]?[1-9]|3[0-1])[T ](?P<H>[0-1]?\d|2[0-3]):(?P<M>[0-5]?\d):(?P<S>[0-5]?\d|6[0-1])(?:[.,](?P<f>[0-9]{1,6}))?(?:\s*(?P<z>Z|UTC|GMT|[+-][01]\d(?::?\d{2})?))?)(?=\b|\W|$)
 +  155 7F7B9CB8B040 fail2ban.datedetector     INFO    date pattern `'{^LN-BEG}(?:%a )?%b %d %H:%M:%S(?:\\.%f)?(?: %ExY)?'`: `{^LN-BEG}(?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: ExYear)?`
 +  156 7F7B9CB8B040 fail2ban.datedetector     DEBUG   date pattern regex for '{^LN-BEG}(?:%a )?%b %d %H:%M:%S(?:\\.%f)?(?: %ExY)?': (?iu)^(?:\W{0,2})?((?:(?P<a>mon|tue|wed|thu|fri|sat|sun) )?(?P<b>jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec) (?P<d>[1-2]\d|[0 ]?[1-9]|3[0-1]) (?P<H>[0-1]?\d|2[0-3]):(?P<M>[0-5]?\d):(?P<S>[0-5]?\d|6[0-1])(?:\.(?P<f>[0-9]{1,6}))?(?: (?P<Y>20[012]\d))?)(?=\b|\W|$)
 +  156 7F7B9CB8B040 fail2ban.datedetector     INFO    date pattern `'{^LN-BEG}%Y(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\\s*%z)?'`: `{^LN-BEG}Year(?P<_sep>[-/.])Month(?P=_sep)Day[T ]24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?`
 +  156 7F7B9CB8B040 fail2ban.datedetector     DEBUG   date pattern regex for '{^LN-BEG}%Y(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\\s*%z)?': ^(?:\W{0,2})?((?P<Y>\d{4})(?P<_sep>[-/.])(?P<m>0?[1-9]|1[0-2])(?P=_sep)(?P<d>[1-2]\d|[0 ]?[1-9]|3[0-1])[T ](?P<H>[0-1]?\d|2[0-3]):(?P<M>[0-5]?\d):(?P<S>[0-5]?\d|6[0-1])(?:[.,](?P<f>[0-9]{1,6}))?(?:\s*(?P<z>Z|UTC|GMT|[+-][01]\d(?::?\d{2})?))?)(?=\b|\W|$)
 +  159 7F7B9CB8B040 fail2ban.filter           ERROR findFailure failed to parse timeText: 0000-12-30 00:00:00
 +  160 7F7B9CB8B040 fail2ban.filter           WARNI [~jailless~] Found a match but no valid date/time found for '0000-12-30 00:00:00'.
 +  160 7F7B9CB8B040 fail2ban.filter           WARNI [~jailless~] Match without a timestamp: 0000-12-30 00:00:00 server test-demo[47831]:  F2B: failure from 192.0.2.1
 +  160 7F7B9CB8B040 fail2ban.filter           WARNI [~jailless~] Please try setting a custom date pattern (see man page jail.conf(5)).
 +  161 7F7B9CB8B040 fail2ban.filter           ERROR findFailure failed to parse timeText: 0000-12-30 00:00:00
 0.014s -- ok

----------------------------------------------------------------------
Ran 1 test in 0.014s

OK
```
</details>
