### ISSUE TITLE
fail2ban CloudFlare v4 API Integration

### ISSUE THREAD

**Issue by wpbullet** [fail2ban/fail2ban#1546] opened 2016-09-15 22:02 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

The old CloudFlare API is being deprecated in November, 2016 so migrating to v4 is necessary

### Configuration, dump and another helpful excerpts

I have detailed the method I am using for [integrating fail2ban with CloudFlare v4 API here](https://guides.wp-bullet.com/integrate-fail2ban-cloudflare-api-v4-guide/)

#### Any customizations done to /etc/fail2ban/ configuration

Custom action created following guide

**Comment by sebres** [comment] 2016-09-16 06:45
Thx for details, but ... 
I'll nevertheless close it as duplicate of #1420.

**Closed by sebres** 2016-09-16 06:45 UTC
Labels: closed-as-duplicate

**Comment by blindpet** [comment] 2016-09-16 06:48
Mine does not use external dependencies like jq, it only uses curl and awk.

**Comment by sebres** [comment] 2016-09-16 06:53
In any case, we have already one issue about subject, so...  let's not have duplicates
The PR is any time welcome.

**Comment by blindpet** [comment] 2016-09-16 07:08
OK, I will find time to make a PR, do you want it on the 0.9.4 and newer branch?

**Comment by sebres** [comment] 2016-09-16 08:46
0.9 (master) is more desirable for common (version independent) things like configuration, etc.
Because we make periodically merge into 0.10, so all changes occurred in 0.9 apply for both branches.
