### ISSUE TITLE
After bantime times out, the disabled ip cannot be cleared

### ISSUE THREAD

**Issue by you-can-change** [fail2ban/fail2ban#2699] opened 2020-04-23 04:45 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version: CentOS Linux release 7.6.1810
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I enabled fail2ban to disable a certain ip through the action of firewallcmd-ipset.conf on centos7. After reaching bantime, the fail2ban-client status service-name command to view this ip will not be automatically removed, but the ip in ipset will expire Automatically cleared, the firewalld rule could not find the source ip, unable to prevent the request of the ip,
And because the status shows that the ip is still there, it is impossible to re-ban this ip, and it is impossible to add this ip to the list of ipset again.

#### Steps to reproduce
1. Configure by dump information
2. Restart fail2ban
3. According to filter rules, simulation is prohibited,
4. Wait for the prohibition time to expire,
#### Expected behavior
1. After the forbidden time expires, the ip is removed from the ipset
2. After the ban time expires, the banned ip in the output of fail2ban status freeswitch is removed
#### Observed behavior
1. After the forbidden time expires, the ip is removed from the ipset, --- pass
2. After the ban time expires, the banned ip in the output of fail2ban status freeswitch is removed, --- failed

### dump
```
[root@localhost fail2ban]# fail2ban-client --dp
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'DEBUG']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', '120']
['add', 'freeswitch', 'auto']
['multi-set', 'freeswitch', 'addfailregex', ["^\\.\\d+ \\[WARNING\\] sofia_reg\\.c:\\d+ SIP auth (failure|challenge) \\((REGISTER|INVITE)\\) on sofia profile \\'[^']+\\' for \\[.*\\] from ip <HOST>$", "\\[WARNING\\] sofia_reg\\.c:\\d+ SIP auth (failure|challenge) \\((REGISTER|INVITE)\\) on sofia profile \\'[^']+\\' for \\[.*\\] from ip <HOST>$", "^\\.\\d+ \\[WARNING\\] sofia_reg\\.c:\\d+ Can't find user \\[\\d+@\\d+\\.\\d+\\.\\d+\\.\\d+\\] from <HOST>$", '^.+fail2ban on inbound <HOST>$']]
['set', 'freeswitch', 'usedns', 'warn']
['set', 'freeswitch', 'addlogpath', '/my/freeswitch.log', 'head']
['set', 'freeswitch', 'maxretry', 3]
['set', 'freeswitch', 'addignoreip', '127.0.0.1/8']
['set', 'freeswitch', 'logencoding', 'auto']
['set', 'freeswitch', 'ignorecommand', '']
['set', 'freeswitch', 'findtime', '600']
['set', 'freeswitch', 'bantime', '86400']
['set', 'freeswitch', 'addaction', 'firewallcmd-ipset-tcp']
[ 'multi-set',
  'freeswitch',
  'action',
  'firewallcmd-ipset-tcp',
  [['actionunban', 'ipset del fail2ban-freeswitch-tcp <ip> -exist'], ['actionban', 'ipset add fail2ban-freeswitch-tcp <ip> timeout <bantime> -exist'], ['actionstart', 'ipset create fail2ban-freeswitch-tcp hash:ip timeout <bantime>\nfirewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports 5060 -m set --match-set fail2ban-freeswitch-tcp src -j REJECT --reject-with icmp-port-unreachable'], ['actionstop', 'firewall-cmd --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports 5060 -m set --match-set fail2ban-freeswitch-tcp src -j REJECT --reject-with icmp-port-unreachable\nipset flush fail2ban-freeswitch-tcp\nipset destroy fail2ban-freeswitch-tcp'], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['protocol', 'tcp'], ['name', 'freeswitch-tcp'], ['chain', 'INPUT'], ['returntype', 'RETURN'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'firewallcmd-ipset-tcp'], ['port', '5060'], ['bantime', '120']]]
['set', 'freeswitch', 'addaction', 'firewallcmd-ipset-udp']
[ 'multi-set',
  'freeswitch',
  'action',
  'firewallcmd-ipset-udp',
  [['actionunban', 'ipset del fail2ban-freeswitch-udp <ip> -exist'], ['actionban', 'ipset add fail2ban-freeswitch-udp <ip> timeout <bantime> -exist'], ['actionstart', 'ipset create fail2ban-freeswitch-udp hash:ip timeout <bantime>\nfirewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p udp -m multiport --dports 5060 -m set --match-set fail2ban-freeswitch-udp src -j REJECT --reject-with icmp-port-unreachable'], ['actionstop', 'firewall-cmd --direct --remove-rule ipv4 filter INPUT 0 -p udp -m multiport --dports 5060 -m set --match-set fail2ban-freeswitch-udp src -j REJECT --reject-with icmp-port-unreachable\nipset flush fail2ban-freeswitch-udp\nipset destroy fail2ban-freeswitch-udp'], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['protocol', 'udp'], ['name', 'freeswitch-udp'], ['chain', 'INPUT'], ['returntype', 'RETURN'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'firewallcmd-ipset-udp'], ['port', '5060'], ['bantime', '120']]]
['set', 'freeswitch', 'addaction', 'sendmail-whois']
[ 'multi-set',
  'freeswitch',
  'action',
  'sendmail-whois',
  [ ['actionunban', ''],
    ['actionstop', 'printf %b "Subject: [Fail2Ban] freeswitch: stopped on `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail freeswitch has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban root@localhost'],
    ['actionban', 'printf %b "Subject: [Fail2Ban] freeswitch: banned <ip> from `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against freeswitch.\\n\\n\nHere is more information about <ip> :\\n\n`/usr/bin/whois <ip> || echo missing whois program`\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban root@localhost'],
    ['actioncheck', ''],
    ['actionstart', 'printf %b "Subject: [Fail2Ban] freeswitch: started on `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail freeswitch has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban root@localhost'],
    ['sender', 'fail2ban'],
    ['dest', 'root@localhost'],
    ['actname', 'sendmail-whois'],
    ['sendername', 'Fail2Ban'],
    ['name', 'freeswitch']]]
['start', 'freeswitch']

```
#### customizations done to /etc/fail2ban/ configuration
**filter.d/freeswitch.conf**
```
[Definition]
failregex = ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ SIP auth (failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[.*\] from ip <HOST>$
            \[WARNING\] sofia_reg\.c:\d+ SIP auth (failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[.*\] from ip <HOST>$
            ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ Can't find user \[\d+@\d+\.\d+\.\d+\.\d+\] from <HOST>$
            ^.+fail2ban on inbound <HOST>$
ignoreregex =
```

#### additional information
```
fail2ban-0.10.4 does not have this feature? Still a bug?
Hope to educate me.
```

**Comment by sebres** [comment] 2020-04-23 10:38
This may be a duplicate of #2410, if so it is fixed then (and the fix got released with 0.10.5).
Otherwise there is another still open issue #2670 targeting similar stuff (basically ipset should not handle the timeout by itself anymore).
Unless it is not fixed for you, possible workaround would be to rewrite the action (`0` instead of `<bantime>`):
- either in `action.d/firewallcmd-ipset.local`:
```
[Definition]
actionban = ipset add <ipmset> <ip> timeout 0 -exist
```
- or in `jail.local` per jail or in default section:
```
[DEFAULT]
banaction = firewallcmd-ipset[actionban="ipset add <ipmset> <ip> timeout 0 -exist"]
banaction_allports = firewallcmd-ipset[actiontype=<allports>, actionban="ipset add <ipmset> <ip> timeout 0 -exist"]
```
This way the IP will be banned in ipset unless fail2ban will really unban the IP.

Although this is not a direct duplicate of #2670, but let us avoid a couple of issues about same thing.

**Closed by sebres** 2020-04-23 10:38 UTC
Labels: closed-as-duplicate

**Comment by you-can-change** [comment] 2020-04-24 03:10
Thanks for your prompt reply.
However, your method is a bit unsuitable for my current production environment. According to your method, the bantime setting does not take effect. You must manually go to unban to remove it. Hope that the next version can achieve this small function

In the production environment, I temporarily set a longer ban time directly, and then restarted fail2ban by crond before the ipset timed out.

Anyway, thanks for your prompt reply!

**Comment by sebres** [comment] 2020-04-24 09:04
> According to your method, the bantime setting does not take effect.

Well, basically not really so. It should avoid a time control in ipset only, but bantime setting is further valid for fail2ban self (so it must unban if it is reached).

> You must manually go to unban to remove it.

Hmm... This is a bit unexpected. According to above mentioned issues, it can be delayed for certain time (also minutes in worse case), but that fail2ban does not unban at all is new.
Are you really sure?

**Comment by you-can-change** [comment] 2020-04-26 08:35
Sorry, this problem is because my bantime configuration is wrong, I just configured bantime in firewalld-ipset.conf, it should be configured in jail.conf,
Now it is normal, thank you very much.
