### ISSUE TITLE
Why is dbpurgeage 60 days?

### ISSUE THREAD

**Issue by shadowym** [fail2ban/fail2ban#1316] opened 2016-02-02 19:00 UTC
fail2ban-0.9.3-1.el6.1.noarch.rpm

I have not changed dbpurgeage from the default 86400 seconds (24 hours) in fail2ban.conf and have not overriden it anywhere else.

I have global bantime set to 2592000 (30 days)

Looking at /var/lib/fail2ban/fail2ban.sqlite3 database it is retaining the last 60 days worth of data.  That is just fine for what I am doing.  

My question is why?  I did a search and could not find any info about this.  Everything I have read says it should only be saving the last 86400 seconds worth of data since that is what dbpurgeage is set to.  I tried running "get dbpurgeage" in the CLI and it also shows 86400.  So is the retention of 60 days worth of data instead of 24 hours a bug or a feature?  If a feature (because of my bantime?) where is the info describing this?

**Comment by sebres** [comment] 2016-02-02 20:13
`dbpurgeage` currently does not affect (because no purge takes place at all, only in test cases currently)...
At the moment implemented in #716 branch only (in observer module).

**Comment by shadowym** [comment] 2016-02-02 20:37
What is purging the database of data older than 60 days then?

**Comment by sebres** [comment] 2016-02-02 20:59
Still again, in our version nowhere purge will be called (except the test cases).
Maybe maintainer of your fail2ban-packet do this somewhere... (what I don't believe).

As long as it is not implemented, you can create a cron with following command (verify path to `/var/lib/fail2ban/fail2ban.sqlite3`):
```
python -c "import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.INFO); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb('/var/lib/fail2ban/fail2ban.sqlite3'); db.purge()"
```
@yarikoptic What do you think about the feature `fail2ban-client dbpurge`?

**Comment by shadowym** [comment] 2016-02-03 00:53
I am not doing anything.  I have multiple servers running fail2ban-0.9.3-1.el6.1.noarch.rpm and the database is being purged of data that is older than 60 days.  I did not have to configure this.  It is already doing it.

So I will ask again.  What is doing this?  Is there a document somewhere that describes this?

**Comment by sebres** [comment] 2016-02-03 08:06
> What is doing this? 

What is not understandable by "maybe the maintainers of your fail2ban-packet has made something".
fail2ban-0.9.3-1.el6.1.noarch.rpm is some stock version... (not original developed from us).

So I will answer again, the version, that we develop here, makes at all no purge (still not).
The cron job is only one opportunity to do that (there are postscript in logrotate, init scripts, etc.), and my suggestion with script was to do that with standard functionality of fail2ban self (that should take dbpurgeage into account also) and rather for people, that have no purge at all.

I will close this issue as duplicate of #1267.

**Closed by sebres** 2016-02-03 08:06 UTC
