### ISSUE TITLE
Aptitude install of fail2ban does not install sample configs

### ISSUE THREAD

**Issue by aaplmike** [fail2ban/fail2ban#2079] opened 2018-03-15 02:53 UTC
Hey all.

I've just completed an update to one of my Debian 8 servers, and received errors on startup. When I checked /etc/fail2ban, I found there are no config files installed, just 4 empty directories: action.d, fail2ban.d, filter.d and jail.d. My previous configs are gone. Do configs have to be installed separately now?

**Comment by sebres** [comment] 2018-03-15 10:34
> Do configs have to be installed separately now?

No... It was nothing changed on the setup process in this direction.

From where you've obtained the distribution to install?
Which version of fail2ban exactly?
How the update process was executed?

**Comment by aaplmike** [comment] 2018-03-15 15:24
Howdee. It was updated as part of moving from Jessie -> Stretch, so, from the debian stretch apt repos:

deb http://ftp.us.debian.org/debian/ stretch main
deb-src http://ftp.us.debian.org/debian/ stretch main

During the upgrade, 0.9.6 was selected:

pilotmc@util1:~$ apt-cache madison fail2ban
  fail2ban |    0.9.6-2 | http://ftp.us.debian.org/debian stretch/main amd64 Packages
  fail2ban |    0.9.6-2 | http://ftp.us.debian.org/debian stretch/main Sources

I uninstalled and reinstalled fail2ban after noticing that no configs were installed:

root@util1:/usr/bin# apt-get install fail2ban
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-pyinotify python3-systemd
Suggested packages:
  monit python-pyinotify-doc
The following NEW packages will be installed:
  fail2ban python3-pyinotify python3-systemd
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/348 kB of archives.
After this operation, 1,616 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package fail2ban.
(Reading database ... 61658 files and directories currently installed.)
Preparing to unpack .../fail2ban_0.9.6-2_all.deb ...
Unpacking fail2ban (0.9.6-2) ...
Selecting previously unselected package python3-pyinotify.
Preparing to unpack .../python3-pyinotify_0.9.6-1_all.deb ...
Unpacking python3-pyinotify (0.9.6-1) ...
Selecting previously unselected package python3-systemd.
Preparing to unpack .../python3-systemd_233-1_amd64.deb ...
Unpacking python3-systemd (233-1) ...
Setting up fail2ban (0.9.6-2) ...
Setting up python3-systemd (233-1) ...
Processing triggers for systemd (232-25+deb9u2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up python3-pyinotify (0.9.6-1) ...
root@util1:/usr/bin# fail2ban-server -V
Fail2Ban v0.9.6

**Comment by sebres** [comment] 2018-03-15 15:35
Hmm, strange.

If both versions (new as well as previously installed) was packaged for debian (and installed via aptitude), in this case it is rather an issue of debian package (I assume just something going wrong by update), or possibly an error of python-setuptools (what I not believe). 

So the maintainer of this package should be notified/involved. I'll close it here as 3rd party.

@yarikoptic, @fail2ban/maintainers any thoughts?

**Closed by sebres** 2018-03-15 15:35 UTC
Labels: 3rd party  issue

**Comment by sebres** [comment] 2018-03-15 15:38
I assume it was an update:
- fail2ban (0.8.13-1) on jessie 
- fail2ban (0.9.6-2) on stretch

**Comment by sebres** [comment] 2018-03-15 15:41
@yarikoptic Could it be caused by python version switch: py2 (previously) to py3 (newest)?

**Comment by aaplmike** [comment] 2018-03-15 15:58
Yes, it was that update, Sebres.
I'll go ahead and remove it and build it from source. Looks like 10 is current?

**Comment by sebres** [comment] 2018-03-15 16:58
> Looks like 10 is current?

Current stable. Otherwise 0.11.

> I'll go ahead and remove it and build it from source.

If you are familiar... otherwise you could just install it from testing repo's (buster/sid).

**Comment by yarikoptic** [comment] 2018-03-15 17:07
dunno what went wrong @aaplmike ... configs are shipped along and I haven't heard about similar problem before -- so might somehow be specifics of your setup... did installation in a clean stretch docker now and everything looks good:
```shell
$> docker run -it --rm debian:stretch 
root@5c3b2554d56d:/# apt-get update -qqq; apt-get install -y fail2ban
Reading package lists... Done
...
Setting up fail2ban (0.9.6-2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.24-10) ...
root@5c3b2554d56d:/# find /etc/fail2ban/
/etc/fail2ban/
/etc/fail2ban/fail2ban.conf
/etc/fail2ban/paths-common.conf
/etc/fail2ban/jail.conf
/etc/fail2ban/fail2ban.d
/etc/fail2ban/jail.d
/etc/fail2ban/jail.d/defaults-debian.conf
/etc/fail2ban/paths-debian.conf
/etc/fail2ban/paths-opensuse.conf
```
if you could reproducibly demonstrate the problem, we could fix it. If not -- not sure what to tackle.

**Comment by sebres** [comment] 2018-03-15 17:15
> did installation in a clean stretch docker now and everything looks good

Just BTW, not really comparable, because he had an update (even system upgrade).

**Comment by aaplmike** [comment] 2018-03-15 17:23
Yes, seems odd, but I've built from source now and it appears to be fine.

**Comment by yarikoptic** [comment] 2018-03-15 17:26
not aptitude but apt -- full upgrade path
```shell
$> docker run -it --rm debian:jessie 
root@8e8612689433:/# apt-get update -qqq; apt-get install -y fail2ban >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@8e8612689433:/# apt-cache policy fail2ban
fail2ban:
  Installed: 0.8.13-1
  Candidate: 0.8.13-1
  Version table:
 *** 0.8.13-1 0
        500 http://deb.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
root@8e8612689433:/# find /etc/fail2ban | head
/etc/fail2ban
/etc/fail2ban/fail2ban.conf
/etc/fail2ban/jail.conf
/etc/fail2ban/fail2ban.d
/etc/fail2ban/jail.d
/etc/fail2ban/filter.d
/etc/fail2ban/filter.d/lighttpd-auth.conf
/etc/fail2ban/filter.d/cyrus-imap.conf
/etc/fail2ban/filter.d/uwimap-auth.conf
/etc/fail2ban/filter.d/wuftpd.conf
root@8e8612689433:/# sed -i -e 's,jessie,stretch,g' /etc/apt/sources.list
root@8e8612689433:/# apt-get update -qqq; apt-get install -y fail2ban >/dev/null
W: There is no public key available for the following key IDs:
EF0F382A1A7B6500
debconf: delaying package configuration, since apt-utils is not installed
root@8e8612689433:/# apt-cache policy fail2ban
fail2ban:
  Installed: 0.9.6-2
  Candidate: 0.9.6-2
  Version table:
 *** 0.9.6-2 0
        500 http://deb.debian.org/debian/ stretch/main amd64 Packages
        100 /var/lib/dpkg/status
root@8e8612689433:/# find /etc/fail2ban | head
/etc/fail2ban
/etc/fail2ban/fail2ban.conf
/etc/fail2ban/paths-common.conf
/etc/fail2ban/jail.conf
/etc/fail2ban/fail2ban.d
/etc/fail2ban/jail.d
/etc/fail2ban/jail.d/defaults-debian.conf
/etc/fail2ban/paths-debian.conf
/etc/fail2ban/paths-opensuse.conf
/etc/fail2ban/filter.d
```

**Comment by sebres** [comment] 2018-03-15 17:55
Hmm, was this really successful? I mean this:
```
root@8e8612689433:/# apt-get update -qqq; apt-get install -y fail2ban >/dev/null
...
debconf: delaying package configuration, since apt-utils is not installed
```
But otherwise why it said 0.9.6-2 is installed. Weird.

Anyway, the configs are preserved.
