### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position

### ISSUE THREAD

**Issue by hobbes1069** [fail2ban/fail2ban#2936] opened 2021-02-12 13:00 UTC
- Fail2Ban version (including any possible distribution suffixes): fail2ban-0.11.2-3.fc35
- OS, including release name/version: EPEL 7

### The issue:

Test failures I assume are due to ascii vs. UTF-8 issues. EPEL 7 uses Python 2 because not all the dependencies are available in Python 3. I'm not sure how they crept in to 0.11.2 as the last successful build was 0.11.1.

There are several failures but a sample is:
```
======================================================================
ERROR: testNewChangeViaGetFailures_move (fail2ban.tests.filtertestcase.LogFileMonitor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 954, in testNewChangeViaGetFailures_move
    n=14, mode='w')
  File "./fail2ban/tests/filtertestcase.py", line 218, in _copy_lines_between_files
    fout.write('\n'.join(lines)+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 1: ordinal not in range(128)
```

https://kojipkgs.fedoraproject.org//work/tasks/330/61820330/build.log

**Comment by sebres** [comment] 2021-02-12 16:17
Hmm... strange, there is nothing what can cause that between 0.11.1 and 0.11.2.
It's something like not proper default encoding in python (which normally must be set in helpers to `utf-8`, but seemed to be `ascii`, no matter in client/server or test suite, and this already long long time the case). So the join of bytes (as a string) by new-lines seems to fail now for some reason.
Sure we could change all the tests to switch to copy/append raw data (bytes), but I don't follow what causing that now.
Oh wait, I see some changes that can indeed affect this, e. g. change `r` to `rb`, made in b3644ad4134c78592106bc6bec2ed18d6949a0ba (released with 0.11.2).
But it works well in CI (GHA/Travis) in 2.7 without any issue (e. g. https://github.com/fail2ban/fail2ban/runs/1444330050?check_suite_focus=true#step:7:273).

Which python 2.7 version is it exactly?

Can you also check which LANG and default encoding are set before this command gets executed
```diff
+ locale
+ /usr/bin/python2 -c 'from fail2ban.helpers import PREFER_ENC; import sys; print(PREFER_ENC, sys.getdefaultencoding())'
/usr/bin/python2 bin/fail2ban-testcases --verbosity=2 --no-network
```
and provide the output of both commands?
Then I could try to reproduce it with your settings (or provide some workaround for that).

**Comment by sebres** [comment] 2021-04-03 15:08
I guess one could rewrite it like:
```diff
- fout.write('\n'.join(lines)+'\n')
+ fout.write(b'\n'.join(lines)+b'\n')
```
but I'd like to reproduce it firstly.

**Comment by sebres** [comment] 2021-12-17 01:16
I'll close it for now... Don't hesitate to reopen or to ping me if it's still acute.

**Closed by sebres** 2021-12-17 01:16 UTC
Labels: moreinfo, closed-for-no-activity

**Comment by opoplawski** [comment] 2023-04-04 00:48
We're still seeing this on EPEL7.  It has python-2.7.5-92.el7_9, presumably a heavily patched version of 2.7.5.  Testing in an EL7 container is probably your best bet for reproducing it.

Looks like setting LANG=en_US.UTF-8 fixes it.  Seems that the locale was defaulting to C.

**Comment by sebres** [comment] 2023-04-04 11:11
Thx for the hint... Indeed I could reproduce it with `LANG=C`...
56485c8548785de5083f53beb33b42228d756fc9 must fix it (it makes the tests locale independent, since switched to byte-related copy inside the tests).

**Comment by opoplawski** [comment] 2023-04-04 16:35
That does the trick, thanks!
