### ISSUE TITLE
Dovecot NOTICE Jail started without 'journalmatch' set.

### ISSUE THREAD

**Issue by beckspaced** [fail2ban/fail2ban#1729] opened 2017-03-21 16:18 UTC
Hello there

just a quick question about dovecot jail and a notice in the fail2ban log

I'm running fail2ban version 0.9.6 on an openSUSE box 42.1

I'm using the dovecot jail:

```
[dovecot-cx20]

enabled  = true
filter   = dovecot
port    = pop3,pop3s,imap,imaps
action = %(action_mwl)s
logpath = %(dovecot_log)s
backend = %(dovecot_backend)s
maxretry = 5
bantime = 259200
```

and in /filter.d/dovecot.conf I also got the Init section for the journalmatch:

```
[Init]

journalmatch = _SYSTEMD_UNIT=dovecot.service
```

If i start fail2ban the log says:

```
2017-03-21 10:09:02,411 fail2ban.server         [30179]: INFO Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.6
2017-03-21 10:09:02,412 fail2ban.database       [30179]: INFO Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
...
2017-03-21 10:09:02,912 fail2ban.jail           [30179]: INFO Creating new jail 'dovecot-cx20'
2017-03-21 10:09:02,913 fail2ban.jail           [30179]: INFO Jail 'dovecot-cx20' uses systemd {}
2017-03-21 10:09:02,917 fail2ban.jail           [30179]: INFO Initiated 'systemd' backend
2017-03-21 10:09:02,918 fail2ban.filter         [30179]: INFO    Set maxRetry = 5
2017-03-21 10:09:02,920 fail2ban.filter         [30179]: INFO    Set jail log file encoding to UTF-8
2017-03-21 10:09:02,920 fail2ban.actions        [30179]: INFO    Set banTime = 259200
2017-03-21 10:09:02,921 fail2ban.filter         [30179]: INFO    Set findtime = 600
2017-03-21 10:09:02,957 fail2ban.filtersystemd  [30179]: INFO Added journal match for: '_SYSTEMD_UNIT=dovecot.service'
2017-03-21 10:09:02,978 fail2ban.filtersystemd  [30179]: NOTICE Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
```

So it seems fail2ban is having an issue with journalmatch for dovecot jail
How can i fix this?

I also do not receive the log lines in the notification email. i t just says:

`Lines containing IP:115.202.188.141 in /var/log/mail`
but no listing of lines from the log

I have a similar setup for postfix with journalmatch and there it doesn't throw an error:

```
2017-03-21 10:09:02,739 fail2ban.jail           [30179]: INFO Creating new jail 'postfix-sasl-cx20'
2017-03-21 10:09:02,739 fail2ban.jail           [30179]: INFO Jail 'postfix-sasl-cx20' uses systemd {}
2017-03-21 10:09:02,744 fail2ban.jail           [30179]: INFO Initiated 'systemd' backend
2017-03-21 10:09:02,746 fail2ban.filter         [30179]: INFO    Set maxRetry = 5
2017-03-21 10:09:02,747 fail2ban.filter         [30179]: INFO    Set jail log file encoding to UTF-8
2017-03-21 10:09:02,748 fail2ban.actions        [30179]: INFO    Set banTime = 259200
2017-03-21 10:09:02,749 fail2ban.filter         [30179]: INFO    Set findtime = 3600
2017-03-21 10:09:02,759 fail2ban.filtersystemd  [30179]: INFO Added journal match for: '_SYSTEMD_UNIT=postfix.service'
```

with postfix jail I do receive log lines in the notification email:

```
Lines containing IP:46.217.64.108 in /var/log/mail

2017-03-21T10:11:39.631356+01:00 cx20 postfix/smtpd[29196]: connect from unknown[46.217.64.108]
2017-03-21T10:11:40.311477+01:00 cx20 postfix/smtpd[29196]: NOQUEUE: reject_warning: RCPT from unknown[46.217.64.108]: 450 4.7.1 Client host rejected: cannot find your hostname, [46.217.64.108]; from=<jackm1@b4pph115.bnr.ca> to=<motahir@sadsadas.de> proto=ESMTP helo=<[46.217.64.108]>
2017-03-21T10:11:40.420446+01:00 cx20 postfix/smtpd[29196]: NOQUEUE: reject: RCPT from unknown[46.217.64.108]: 554 5.7.1 Service unavailable; Client host [46.217.64.108] blocked using bl.spamcop.net; Blocked - see http://www.spamcop.net/bl.shtml?46.217.64.108; from=<jackm1@b4pph115.bnr.ca> to=<motahir@sdsad.de> proto=ESMTP helo=<[46.217.64.108]>
```

thanks & greetings
Becki

**Comment by sebres** [comment] 2017-06-30 15:52
> Jail started without 'journalmatch' set.

I cannot reproduce it with our fail2ban version 0.9...
In addition corresponding the source code following two log-lines are mutually exclusive:
```
fail2ban.filtersystemd : INFO Added journal match for: '_SYSTEMD_UNIT=dovecot.service'
fail2ban.filtersystemd : NOTICE Jail started without 'journalmatch' set. Jail regexs will ...
```
If you can start it with debug mode, please provide additional debug-info between this 2 lines...

> I also do not receive the log lines in the notification email. 

Either your dovecot (resp. systemd) logs into another file, as specified in fail2ban with `logpath`.
Or systemd logs into journal only (without duplication log-entries into log-file).
In both cases you'll be not able to get this lines from file with this mail-action (I assume it uses grep). 
This action should be rewritten using something gathering log-excerpt from journal (using `journalctl`) instead of grep from file. 
Or you can try to use another mail action, e. g. instead of `sendmail-whois-lines` you can use a `sendmail-whois-matches` action, that sends failure lines (matches) also, but does not need a log file at all.

Thus I'll close this until further notice.

**Closed by sebres** 2017-06-30 15:52 UTC

**Comment by beckspaced** [comment] 2017-07-01 07:10
Hello @sebres 

totally forgot about this, glad you replied ...
recently updated my system to openSuSE 42.2 and just had a look in the fail2ban log.

I'm running Fail2ban v0.9.7 and the log notice is gone ;)

> 2017-06-13 10:48:25,991 fail2ban.jail           [21787]: INFO    Creating new jail 'dovecot-cx20'
> 2017-06-13 10:48:25,991 fail2ban.jail           [21787]: INFO    Jail 'dovecot-cx20' uses systemd {}
> 2017-06-13 10:48:25,994 fail2ban.jail           [21787]: INFO    Initiated 'systemd' backend
> 2017-06-13 10:48:25,996 fail2ban.filter         [21787]: INFO    Set maxRetry = 5
> 2017-06-13 10:48:25,997 fail2ban.filter         [21787]: INFO    Set jail log file encoding to UTF-8
> 2017-06-13 10:48:25,998 fail2ban.actions        [21787]: INFO    Set banTime = 86400
> 2017-06-13 10:48:25,999 fail2ban.filter         [21787]: INFO    Set findtime = 3600
> 2017-06-13 10:48:26,040 fail2ban.filtersystemd  [21787]: INFO    Added journal match for: '_SYSTEMD_UNIT=dovecot.service'
> 2017-06-13 10:48:26,127 fail2ban.jail           [21787]: INFO    Jail 'dovecot-cx20' started

so it all seems to be good again. Case closed ;)

Thanks & greetings
Becki
