### ISSUE TITLE
Exception "Socket is not connected" when starting the fail2ban service

### ISSUE THREAD

**Issue by chtheis** [fail2ban/fail2ban#2109] opened 2018-04-08 07:36 UTC
I'm maintinaing the fail2ban port on FreeBSD and I encountered this issue when preparing the update for 0.10.3. 

### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.10.3
- OS, including release name/version:  FreeBSD 11.1 with python 2.7

### The issue:

When I start the service I get an exception
Exception socket error: (57 'Socket is not connected') in <bound method CSocket.__del__ of <fail2ban.client.csocket.CSocket instance at ...>> ignored
Otherwise fail2ban seems to run OK and I can query jail status with fail2ban-client without errors.

I guess this bug was introduced with the commit https://github.com/fail2ban/fail2ban/commit/5f021aa648c42ee188d8c31a81937d764982a58a#diff-eb62959e572309e6c2cb840f5426b77c
If I comment out line 64 in csocket.py (which was added with that commit), I don't get the exception anymore.

Unfortunately I don't know how to get a stacktrace so I don't know why the socket is not connected at that time.

**Comment by sebres** [comment] 2018-04-09 12:24
Thank you.
Although I cannot reproduce it with python2.7, I think it may be indeed an issue of some older socket module.
Thus should be fixed now in 22e9ccb3876112da231a4c89f7d3882e8ffdaaf9.
Would be great if you could test it.

**Comment by chtheis** [comment] 2018-04-09 12:43
Am 09.04.2018 um 14:24 schrieb Sergey G. Brester:
> Thank you.
> Although I cannot reproduce it with python2.7, I think it may be indeed 
> an issue of some older socket module.
> Thus should be fixed now in 22e9ccb 
> <https://github.com/fail2ban/fail2ban/commit/22e9ccb3876112da231a4c89f7d3882e8ffdaaf9>.
> Would be great if you could test it.

With the patch it works. Or: I don't see the exception any more, of course.

Thanks a lot

Christoph

**Comment by sebres** [comment] 2018-04-09 12:45
Great, thanks again. 
Thus merged.

**Closed by sebres** 2018-04-09 12:45 UTC
