### ISSUE TITLE
[FR]: Is it possible to write a filter that can match IPs belonging to the same subnet segment?

### ISSUE THREAD

**Issue by wx2020** [fail2ban/fail2ban#3879] opened 2024-11-09 15:07 UTC
My server is always repeatedly scanned by addresses from the same network segment (/24), and now I can't find a way to block this network segment using the jail.local configuration file. Does anyone have a similar solution?

**Comment by sebres** [comment] 2024-11-09 23:16
Duplicate of #927.

It is not possible yet in a really proper way, like auto detection of subnet from IP (whois, geoip, etc) or combining multiple IPs to a subnet by some burst/threshold/max-width...
However if you just want to ban a subnet for every single IP, it is indeed possible - so one can write own action which could ban fixed subnet instead of IP. For example something like this:

#### Derivate of iptables-ipset
```ini
[INCLUDES]
before = iptables-ipset.conf

[Definition]
actionban = ipset -exist add <ipmset> <ip><netcidr> timeout <ipsettime>
actionunban = ipset -exist del <ipmset> <ip><netcidr>

[Init]
ipsettype = hash:net
netcidr = /24

[Init?family=inet6]
netcidr = /64
```
(important: `iptables-ipset` action need to support `ipsettype` or you have to update it to newer version, see 25335268276184b5339bb066f19e178da07e3366)

#### Derivate of nftables
```ini
[INCLUDES]
before = nftables.conf

[Definition]
_nft_add_set = <nftables> add set <table_family> <table> <addr_set> \{ type <addr_type>\; flags interval\; \}
actionban = <nftables> add element <table_family> <table> <addr_set> \{ <ip><netcidr> \}
actionunban = <nftables> delete element <table_family> <table> <addr_set> \{ <ip><netcidr> \}

[Init]
netcidr = /24

[Init?family=inet6]
netcidr = /64
```

**Closed by sebres** 2024-11-09 23:16 UTC
Labels: closed-as-duplicate, filter-request
