### ISSUE TITLE
Dont excecute actionunban when IP's are unbanned on stopping the service

### ISSUE THREAD

**Issue by sleeplessnight2** [fail2ban/fail2ban#3627] opened 2023-11-15 20:13 UTC
#### Description

I have set actionunban to send a message.

This also works great.

Unfortunately, this action is also executed when the fail2ban service is stopped, which then massively sends emails.

The value norestored is set to 1.
When the service is started, "actionban" is not executed either.

What am I doing wrong?

**Comment by sebres** [comment] 2023-11-16 00:20
Basically `actionunban` will always be executed (if an action doesn't have `actionflush`) when a tickets get unbanned also on stop of jail or fail2ban.
This way it works as designed...
You may implement `actionflush` to do flush (unban everything) or simply set it to `true` to avoid single unbanning per ticket.
See also https://github.com/fail2ban/fail2ban/issues/3451#issuecomment-1401737144 and co.
Thus closed as duplicate of #3038, #3451 etc.

**Closed by sebres** 2023-11-16 00:20 UTC
Labels: enhancement, closed-as-duplicate, how-to
