### ISSUE TITLE
Filter performance degrade on high number of log files

### ISSUE THREAD

**Issue by kshetragia** [fail2ban/fail2ban#1265] opened 2015-12-02 11:46 UTC
I have web hosting with > 300 domains and every domain has a couple log files which i want to monitor by f2b.

A jail config:
>[apache-badbot]
>enabled  = false
>filter   = apache-badbots
>action   = iptables-multiport[name=BadBots, port="http,https"]
>logpath  = /var/www/vhosts/*/logs/*access_log
>           /var/log/httpd/*access_log
>bantime  = 172800
>maxretry = 1

I'm trying to enable jails and see multiple strings in fail2ban.log:
>2015-12-02 15:25:25,546 fail2ban.filter         [19153]: INFO    Added logfile = /var/www/vhosts/example280.com/logs/proxy_access_log
>2015-12-02 15:25:27,495 fail2ban.filter         [19153]: INFO    Added logfile = /var/www/vhosts/example280.com/logs/access_log

But the enable jails process goes to performance degrade and holds after 580-590 added logfiles.

After the brief research i've found the possible root cause in [server/filter.py](https://github.com/fail2ban/fail2ban/blob/master/fail2ban/server/filter.py) well known as [Shlemiel algorithm](https://en.wikipedia.org/wiki/Joel_Spolsky#Schlemiel_the_Painter.27s_algorithm)

```python
self.__logPath = []

def addLogPath(self, path, tail = False):
        if self.containsLogPath(path):
            ...........
        else:
            ...........
            self.__logPath.append(container)

def containsLogPath(self, path):
        for log in self.__logPath:
            if log.getFileName() == path:
                return True
        return False
```

Please review all f2b source code and fix this. I sure this is not a single place with such algorithm. As far as i see there are follow functions with the same problem:
```python
   def delLogPath(self, path):
   def status(self, flavor="basic"):
   def getFileContainer(self, path):
```

**Comment by sebres** [comment] 2015-12-02 17:37
Firstly the log files will be added ONCE by starting of jail...

Secondly I see here no problem and the piece of code above will work even up to 5000 logs without great degradation... (see an example below).
Of course degrade that, and of course we can rewrite it as ordered dict or something else. BUT by monitoring of 5000 files you will get another problems as this small few "not pretty" piece of code.
Started by initial searching of failure inside this couple of log file, including monitoring of all this files in single thread. 
And if you use such backends as `polling` (instead of for example `pyinotify`) you lose twice and triple.

Also - no, "the possible root" of the issue is in monitoring of really large files inside a single thread (jail)!

Example with time measurement of execution of the non "pretty" code:
```python
class FileContainer: 
  def __init__(self, path):
    self.path = path;
  def getFileName(self):
    return self.path;

class Test:
  def __init__(self):
    self.__logPath = list()
  def addLogPath(self, path, tail=False, autoSeek=True):
    if self.containsLogPath(path):
      print(path + " already exists")
    else:
      container = FileContainer(path)
      self.__logPath.append(container)
  def containsLogPath(self, path):
    for log in self.__logPath:
      if log.getFileName() == path:
        return True
    return False

import time
def test(max):
  t = Test()
  starttime = time.time()
  for i in range(0, max):
    t.addLogPath("test %d" % (i,))
  print("%s seconds" % (time.time() - starttime,))

>>> test(1000)
0.13750600814819336 seconds
>>> test(2000)
0.4875199794769287 seconds
>>> test(3000)
1.052541971206665 seconds
>>> test(5000)
2.927617073059082 seconds
```

BTW. I've made a much faster version of fail2ban, here you will find a previous (obsolete and closed) pull request #1116.
You can try the newest version of this here: https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716

But I think the better way in your case would be to split this into several jails (equivalent several threads).

I will close this issue, because that borders to the wrong usage of solution (at least not trivial task, expected not simple hardware, etc, etc.). 
For example I have a server that observes with fail2ban more as 1000 log-files without any problem.

**Closed by sebres** 2015-12-02 17:37 UTC

**Comment by sebres** [comment] 2015-12-02 18:59
In commit bfb077bbb52efc6640628ae57420b2f3ec67005f of https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716 I've made a small code review: (much pretty) handling of filename as key - FileFilter contains (ordered) dict of files (not list), as discussed here. I can cherry pick it into master as PR if someone needs it.

BTW. I've tried it with 1000 log files (in single jail) - it is not noticeably faster... (just a little bit). But I've not tested resp. not simulated a large load.

**Comment by yarikoptic** [comment] 2015-12-02 19:13
Sounds like a good enhancement/refactoring to have indeed. Left some comments on that commit

On December 2, 2015 1:59:55 PM EST, "Serg G. Brester" <notifications@github.com> wrote:
>In commit bfb077bbb52efc6640628ae57420b2f3ec67005f of
>https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716 I've
>made a small code review: (much pretty) handling of filename as key -
>FileFilter contains (ordered) dict of files (not list), as discussed
>here. I can cherry pick it into master as PR if someone needs it.
>
>BTW. I've tried it with 1000 log files (in single jail) - it is not
>noticeably faster... (just a little bit). But I've not tested resp. not
>simulated a large load.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1265#issuecomment-161398724

-- 
Sent from a phone which beats iPhone.

**Comment by sebres** [comment] 2015-12-02 19:32
I've committed a new version ameded - 3efc155e5cc295c1a1cf3c6daecd4693e4f33a16. The same branch.

**Comment by sebres** [comment] 2015-12-02 20:07
@kshetragia BTW. Don't touch our Tux!

**Comment by yarikoptic** [comment] 2015-12-02 20:28
Could you prepare a PR for this particular change? Thanks in advance

**Comment by yarikoptic** [comment] 2015-12-02 20:29
Ah saw now #1266

**Comment by sebres** [comment] 2015-12-02 20:34
Just amended a small fix for a py2.6 (where it's a unordered) and coverage fix.

**Comment by kshetragia** [comment] 2015-12-04 06:27
Thank you for the fast answer and provided solution.

I agree with you these issues in filter.py are not a root cause of problem and i mentioned ones as POSSIBLE root cause. But problem is real. I've tried to split f2b jail to four ones and pyinotify was used, but f2b performance still is not enough for big amount of log files.

I try to enable these four jails and f2b client process do not stuck anymore but --enable-jails is still very very slow and takes about 10 minutes.

Please investigate further. I can provide all additional information.
