### ISSUE TITLE
Fail2ban eating memory daily, till i restart it

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [fail2ban/fail2ban#2843] opened 2020-10-04 12:45 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.2-dev
- OS, including release name/version: Ubuntu 18.04.3 LTS
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban day by day keeps eating the memory without any logical reason, i have to restart the service every 2-3 weeks to avoid memory consumption and save some for the other services!
After 4 weeks now it is using around 4.5 GB for the total ram, after some days it will reach 5 GB ...etc
When i restart it, it is only 0.7% from the total memory (8 GB)

Didn't face that issue in older versions (0.9.x or 0.10.x), with same customization.
#### Steps to reproduce
Just install this version and monitor the memory for days
#### Expected behavior
Use memory as much as it needs logically
#### Observed behavior
Eating memory daily...
#### Any customizations done to /etc/fail2ban/ configuration

Just added apache filter
![image](https://user-images.githubusercontent.com/47364489/95015862-bbed3480-064f-11eb-9123-efb4ec31aef6.png)

![image](https://user-images.githubusercontent.com/47364489/95015876-cc9daa80-064f-11eb-9ce7-fa017c5bf4d1.png)

#### Relevant parts of /var/log/fail2ban.log file:
Nothing in logs related to that issue
And no process stuck in the background related to fail2ban.
#### Relevant lines from monitored log files in question:
![image](https://user-images.githubusercontent.com/47364489/95015720-c65afe80-064e-11eb-87ec-dfe9731c3d2d.png)

**Comment by sebres** [comment] 2020-10-05 12:37
> After 4 weeks now it is using around 4.5 GB for the total ram, after some days it will reach 5 GB ...etc
When i restart it, it is only 0.7% from the total memory (8 GB)

You have `bantime` set to 1 year, so many active IPs get banned after restart. This may need some time. Can you confirm that this is not growing at some point after restart (e. g. several minutes hereafter).

How many tickets are banned?

> Didn't face that issue in older versions (0.9.x or 0.10.x), with same customization.

Hmm... weird (I'd swear it would be rather vice versa). I'll try to investigate the cause.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-05 13:05
> You have `bantime` set to 1 year, so many active IPs get banned after restart. This may need some time. Can you confirm that this is not growing at some point after restart (e. g. several minutes hereafter).

After restart by few minutes or one hour, it takes very few percentage max 2%, after it finishes restoring banned IPs. 
But day after day it keeps growing in memory consumption, for example yesterday when i opened the issue it was 50.7 %, now it raised by around 2%  and only 10 IPs where banned since yesterday
![image](https://user-images.githubusercontent.com/47364489/95081782-5a45cc80-071a-11eb-930f-79e1455307af.png)




> How many tickets are banned?
> 
> >

Total is around 19K on both jails ssh and apache



> Hmm... weird (I'd swear it would be rather vice versa). I'll try to investigate the cause.

Can't agree more, everything is much better since i started using this version, except this issue :(

**Comment by sebres** [comment] 2020-10-05 13:57
Since current 0.11 has a named threads, can you please provide output of `sudo top -b -n 1 -H | grep -P 'f2b|%MEM'`, once you'd get the large memory usage again? This could probably explain which thread exactly causing that (has mem leak).

Also I could need info which jail uses which backend, e. g. after start the messages like `INFO    Jail 'sshd' uses pyinotify` in /var/log/fail2ban.log.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-05 18:50
> Since current 0.11 has a named threads, can you please provide output of `sudo top -b -n 1 -H | grep -P 'f2b|%MEM'`, once you'd get the large memory usage again? This could probably explain which thread exactly causing that (has mem leak).

Didn't restart the service yet to get any needed info, so it is still high :)
![image](https://user-images.githubusercontent.com/47364489/95118968-80379500-074b-11eb-95fd-62c79be960c5.png)




> Also I could need info which jail uses which backend, e. g. after start the messages like `INFO Jail 'sshd' uses pyinotify` in /var/log/fail2ban.log.

Okay now restarted :D, backend Gamin
![image](https://user-images.githubusercontent.com/47364489/95119344-1966ab80-074c-11eb-9a42-8a72b8208160.png)

You can check also the memory usage during IPs restoring:
![image](https://user-images.githubusercontent.com/47364489/95119496-57fc6600-074c-11eb-980c-9800dc84db9f.png)

**Comment by sebres** [comment] 2020-10-05 19:16
Unfortunately it shows the same mem-usage for all threads :(

OK, I'll check gamin backend for some possible leaks.
Since this is the least usable backend ever (and to ensure it's filter-related issue), can you please switch your backend to `pyinotify`?
If you install `python-pyinotify` module (or `python3-pyinotify` if your fail2ban-python saying v.3.x), and your configuration for `backend` is `auto`, it will prefer `pyinotify` (trying this at first before `gamin`).
I don't see any difference in gamin-filter module of fail2ban (between 0.10 and 0.11) or even other filter-related changes in 0.11, as well as I did never see such issue with pyinotify and systemd backends (no matter which version), so really interesting to know whether it would disappear after switch to other backend.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-06 13:15
> Unfortunately it shows the same mem-usage for all threads :(

I noticed same as well, but thought if you can figure out something else from it 

I got you, I just installed the package of pyinotify, and restarted fail2ban, as you expected exactly it auto detected the new backend pyinotify and got switched:

![image](https://user-images.githubusercontent.com/47364489/95205228-5f238280-07e5-11eb-8e98-fa28972c5a9f.png)

Now it is time to wait and monitor, i hope changing the backend do the trick.

But Thank you for all your support so far :)

**Comment by torsson** [comment] 2020-10-12 07:54
How big is your /var/lib/fail2ban/fail2ban.sqlite3 ?. Mine dosen't seem to clean and was over 4gb, clearing it seems to help for me on v0.9.3.

**Comment by sebres** [comment] 2020-10-12 09:34
> Mine dosen't seem to clean and was over 4gb, ...

As you can see it is 0.11.2 version - the issue with purgedb is fixed there. 
Thus I'll remove this comment as unrelated.

**Comment by Ddcdom** [comment] 2020-10-13 10:17
I'm experiencing an identical problem, with memory usage increasing daily by between 5 and 10MB.
I've been monitoring memory usage for a month. After a restart of fail2ban, memory usage was 125MB, but it has climbed to 359MB.

Fail2ban was installed via Plesk and its version 0.9.6.

Only large numbers I could see in the fail2ban jail statuses was for my ssh jail, which had ~40000 total banned and ~300000 total failed (current banned 14 and current failed 17).

**Comment by sebres** [comment] 2020-10-13 10:30
Well 0.9.6 is old, but if the source of issue is the same (gamin api or gamin backend), you can try to switch to another backend e. g. pyinotify.
If it is something else (like a known old issue of missing purge for database), it is fixed in new versions (anyway, I never saw something like that in 0.11).

@mohammedragabsoftxpert do you have some new values in-between?

**Comment by mohammedragabsoftxpert** [comment] 2020-10-13 11:35
@sebres So far after 3 days of restarting the memory raised up to almost 9% in 3 days:
![image](https://user-images.githubusercontent.com/47364489/95855098-2c830800-0d58-11eb-8b27-39807eb64466.png)

![image](https://user-images.githubusercontent.com/47364489/95855198-4fadb780-0d58-11eb-8af8-c520760afc97.png)

I installed same version with same exact environment on another server same number of banned IPs, same jails, same config, same everything.
After 6 days, it is only 0.9% percentage only, and with backend Gamin !!
![image](https://user-images.githubusercontent.com/47364489/95855261-648a4b00-0d58-11eb-855a-d0e305066465.png)

![image](https://user-images.githubusercontent.com/47364489/95855302-72d86700-0d58-11eb-9d78-afbb608ba904.png)

**Comment by sebres** [comment] 2020-10-13 13:26
Thx for feedback. Indeed, it's confusing a bit.

**Comment by sebres** [comment] 2020-10-13 17:58
> same everything.

As for same, how many failures and bans do you observe on second server (compared with first with leaking memory). 
Is it comparable at all?

If I compare TIME+ columns of both fail2ban, they look similar, but observer thread is conspicuous a bit, on first server it had much more time to work, so I assume there are just more known as "bad" IPs in the database.
How large is the database at all? And your value of `dbpurgeage`? Just for IPs banning for very long time (by incremented banning),  they could remain in the database up to `3 * bantime`.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-13 21:58
Let's agree on symbols like:
- "Bad Server" the one that has the issue
- "Good Server" the one which is actually good :D

### Please check below the results:

- Number of banned and failed:

**SSH Jail failed and banned IPs, Good server on the left, Bad on the right**
![image](https://user-images.githubusercontent.com/47364489/95918591-5f56eb80-0dac-11eb-800d-aa1ae9e579f3.png)

**Apache Jail failed and banned IPs, Good server on the left, Bad on the right**
![image](https://user-images.githubusercontent.com/47364489/95918701-8f9e8a00-0dac-11eb-8e69-540ab8afe52a.png)
![image](https://user-images.githubusercontent.com/47364489/95918715-93caa780-0dac-11eb-9221-497eb07d8c9a.png)

The number in Apache jail not comparable at all, as you can see.

- **DB Size**

![image](https://user-images.githubusercontent.com/47364489/95919328-aee9e700-0dad-11eb-8bb4-501a448773a0.png)
Both same size, or did you mean to get the size by another way?

- **Both has same** `dbpurgeage= 1d`

- **DB statistics, Bad Server in the left, Good in the right**

> ```shell
> # counts:
> sqlite3 -header "file:$db?mode=ro" "select (select count(ip) from bips) as 'bad', (select count(ip) from bans) as 'last'"
> ```
![image](https://user-images.githubusercontent.com/47364489/95919945-c83f6300-0dae-11eb-9b21-29cfcfd4adc1.png)




> ```shell
> # works only if compiled with dbstat:
> sqlite3 -header "file:$db?mode=ro" "select name, sum(pgsize) as 'pgsize' from dbstat group by name order by 'pgsize' desc"
> ```

![image](https://user-images.githubusercontent.com/47364489/95919984-db523300-0dae-11eb-9628-d2f72bbbaf9d.png)


If you don't mind, i would like to ask few questions as well:
- what "currently failed" actually means?
- what "bad ips" means? the banned ones?

> Just for IPs banning for very long time (by incremented banning), they could remain in the database up to `3 * bantime`.

- Can you clarify more that line info please?

**Comment by sebres** [comment] 2020-10-14 10:23
> The number in Apache jail not comparable at all, as you can see.

It is explainable, if we'll consider the working time of filter worker (9:29 vs. 1:00 from your previous comment).
Newer server has simply cumulated few intruders, so fewer amount of attempts yet.
So yes, at the moment it looks like this would be the only difference here.

I don't know how large are the stored failure tickets by `maxretry=900` (do you really need such large value?), because the count of messages as well as the content of matched messages can be very different. 
But it could be indeed a lot memory by 17K tickets * 50 failures (default `maxmatches` stored per ticket can be considered as `min(50, 900 /*maxretry*/)`). 
Let estimate it by assumed average message size 250 bytes and 30 messages per ticket - `17000 * 30 * 250 = 127MB`. If it reaches 50 messages, you'll notice 212MB.
May be you could try to set `maxmatches = 0` (or some other small value), if you don't need that (see #2402).

But I'm still unsure whether this is the reason of the "leak" solely. 
Because you said, you did not see that with 0.10.x previously (and before PR with `maxmatches` got merged, it had cumulated up to 900 matched messages per ticket).
So either it should generate still larger memory consumption previously, or your configuration is really changed, or it is simply a "wrong" timing and now you have just more "visitors" (legitimate with wrong false positives as well as evildoers that simply don't generate 900 attempts in 5 minutes).

Also read [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice) - maybe you could find some way to optimize your apache monitoring.

----

> what "currently failed" actually means?

this is count of "active" (pending) tickets with failures, recognized by fail2ban (which is not removed, so found in `findtime` interval, but not yet causing ban, because `maxretry` is still unreached for them).

> what "bad ips" means? the banned ones?

yes, this is feature of 0.11 to be able to increase bantime (decrease maxrerty) for known as bad intruders.

> Can you clarify more that line info please?

well, because of the `bantime.increment` feature, the bantime can be prolonged (for recidive evildoers), so removal of all known IPs only considering `dbpurgeage=1d` would cause, that this long-time banning evildoers disappear after 1d, regardless its bantime can be 20d for example, so after unban, if the intruder starts his attempts, he would be not found and banned for shorter time (the cycle starts from scratch for everyone with bans longer than 1d).
So the formula to purge table `bips` is a bit different (extended with second part):
`timeofban < now - purgeage and (timeofban + (bantime * outdateFactor)) < now - purgeage`
where outdateFactor is 3 at the moment.

**Comment by sebres** [comment] 2020-10-14 10:26
Just to link: related issue - #2118 and possible solution - #2402.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-16 00:56
> `maxretry=900` (do you really need such large value?)

Actually yes, because of the huge number of resources some requests calls during single click, reducing this number before caused to ban good IPs



> well, because of the `bantime.increment` feature, the bantime can be prolonged (for recidive evildoers), so removal of all known IPs only considering `dbpurgeage=1d` would cause, that this long-time banning evildoers disappear after 1d, regardless its bantime can be 20d for example, so after unban, if the intruder starts his attempts, he would be not found and banned for shorter time (the cycle starts from scratch for everyone with bans longer than 1d).
> So the formula to purge table `bips` is a bit different (extended with second part):
> `timeofban < now - purgeage and (timeofban + (bantime * outdateFactor)) < now - purgeage`
> where outdateFactor is 3 at the moment.

I didn't notice the bantime.increment feature before now, and after your explanation i find it great feature to use, also i will check carefully our default configuration and check how we can optimize it according to apache logs we need.

> it is simply a "wrong" timing and now you have just more "visitors"

I believe i have to go with that possibility, as on my side, the difference between both websites is the number of visitors, and the traffic load, not comparable between both of them.
I didn't deal with maxmatch before, but after i understood its purpose and functionality i proceeded with `maxmatches = 0` and did a restart on fail2ban, as we don't do process on matched lines more than just fail2ban count and ban.

Just to mention, we are living with this issue for few months, not when i opened the issue, so could be when we had 0.10 the traffic wasn't that high, and as you said it can be bad timing

Now i will monitor it after that new change, and keep you updated

Again and Again, thanks a million for your support, and flood of info and details you are providing in every comment :)

**Comment by sebres** [comment] 2020-10-16 14:54
> Actually yes, because of the huge number of resources some requests calls during single click, reducing this number before caused to ban good IPs

Then I'll say something is wrong with your config (apache or fail2ban or both).
Ideally it should not generate so many "failures" to signal a DOS or flood... For example if you had nginx you could use pre-filtering on side of nginx (in order to be notified by potential flood only), using something like [nginx-limit-req](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-limit-req.conf) filter, or even other procedures which would only log from locations in some suspicious cases, so not just a monitoring of common access log.
This is what I was trying to illustrate for you with providing a link to the Best practice at wiki page.

> Now i will monitor it after that new change, and keep you updated

Thx, waiting for the feedback.
In-between I must admit we should rethink the default value of `maxmatches` (currently 50) to be drastically reduced (to 5 or so). So someone who really needs larger amount of matches per ticket (e. g. in actions) could increase that in config files, but it would not bother the people, which using ban actions only.

**Comment by mohammedragabsoftxpert** [comment] 2020-10-18 19:00
> This is what I was trying to illustrate for you with providing a link to the Best practice at wiki page.
> 
> >

Yes totally agree with you, and totally got you in both comments. I believe i have to re-visit both apache and fail2ban configs for more optimization and using the link you shared, as in other websites with high traffic and this one as well, i am already suffering with `maxretry` value tuning, to avoid good ones. Thank you for bringing that up and lighting that up to my attention. 



> In-between I must admit we should rethink the default value of `maxmatches` (currently 50) to be drastically reduced (to 5 or so). So someone who really needs larger amount of matches per ticket (e. g. in actions) could increase that in config files, but it would not bother the people, which using ban actions only.

Can't agree more, in our case here after almost 3 days, it is only 0.8% of the total memory, i hope i am not judging very early, but so far i believe the `maxmatches` did the trick
![image](https://user-images.githubusercontent.com/47364489/96377228-9ea68300-1184-11eb-934f-063cdc3ea805.png)

**Comment by mohammedragabsoftxpert** [comment] 2020-10-22 14:44
@sebres So far after 7 days of running, the usage is only 1% of the memory
![image](https://user-images.githubusercontent.com/47364489/96887748-2b06bd80-1485-11eb-8f3c-fd5f2a215e9d.png)

So far i can consider my issue is fixed with the maxmatches, but i really need to take further step about optimizing the fail2ban with apache logs.
Even if this thread got closed, i will update my findings here in same thread.

Thanks a million for your time and support :)

**Closed** 2020-11-05 15:16 UTC
