### ISSUE TITLE
0.10: Retrieving Own IPs + cannot remove WD=2

### ISSUE THREAD

**Issue by qcybb** [fail2ban/fail2ban#1865] opened 2017-08-15 19:15 UTC
These warning pops up in the Fail2Ban log when starting it up.

> 2017-08-15 12:04:18,637 fail2ban.ipdns [90363]: WARNING Retrieving own IPs of localhost failed: inet_pton() argument 2 must be string, not int
> 
> 2017-08-15 12:04:18,637 fail2ban.ipdns [90363]: WARNING Retrieving own IPs of localhost.my.domain failed: inet_pton() argument 2 must be string, not int

**Comment by qcybb** [comment] 2017-08-16 07:48
Another issue popped up. It fails at midnight (during log rotate) and have to restart the server for it to work again.

> 2017-08-16 00:00:00,079 fail2ban.filterpyinotify[5012]: ERROR   rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)

**Comment by sebres** [comment] 2017-08-16 07:54
Hm, strange...

Can you please test following example and post here the output:
```
python -c "import socket; print([socket.getaddrinfo('localhost', None, fam, 0, socket.IPPROTO_TCP) for fam in (socket.AF_INET, socket.AF_INET6)])"
```

**Comment by sebres** [comment] 2017-08-16 07:59
>  rm_watch: cannot remove WD=2

Which version of 0.10 exactly do you use? Before a73b0c00647ba9a7172c361174a145743c41511c (16 May), 96c3b06abbb11f7eb8735acd7741d62854e425ba (19 May) or newest one?

**Comment by qcybb** [comment] 2017-08-16 08:05
> Can you please test following example and post here the output:

[[(2, 1, 6, '', ('127.0.0.1', 0))], [(28, 1, 6, '', (28, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))]]

**Comment by qcybb** [comment] 2017-08-16 08:07
I'm using the latest version from this page :

[https://github.com/fail2ban/fail2ban/releases/tag/0.10.0](https://github.com/fail2ban/fail2ban/releases/tag/0.10.0)

**Comment by sebres** [comment] 2017-08-16 08:08
Both seems to be a bugs...
Fix follows...
Thanks!

**Comment by sebres** [comment] 2017-08-16 09:07
Nr. 1. Retrieving own IPs is fixed in 786722814682a7279314505ad2a1602e52e997c8.

Now as regards the case Nr. 2.

> rm_watch: cannot remove WD=2

This error alone is harmless (just trying to remove watch, that already removed from pyinotify self).
Have you seen another error there?
There were an entry ""Log absence detected (possibly rotation)" in log? Or something similar?
If you've more please provide a log-excerpt...

> have to restart the server for it to work again.

Jail idle? Resp. no more failure noticed (recognized) from fail2ban in rotated log-file?
Can you describe a bit more the rotate scenario (file or directory based, what exactly, etc.), e. g.:
- watching `/var/log/a/b/c.log`
- rotate `/var/log/a/b/c.log` to `/var/log/a/b/c.log.1`, or directory `/var/log/a/b` to `/var/log/a/b.1`
- can you reproduce it with fail2ban started with DEBUG and manual force the logrotate:
```
fail2ban-client restart --loglevel DEBUG
logrotate -f ...rotation-config-file...
```
If so, please post here corresponding log-excerpt of the fail2ban.log...

**Comment by sebres** [comment] 2017-08-16 09:12
Can you also please test following:
```
python -c "import pyinotify; monitor = pyinotify.WatchManager(); print('test-1'); monitor.rm_watch(2); print('test-2')"
```
Do you see then?
```
test-1
[... pyinotify ERROR] rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)
test-2
```
Important is line `test-2`...

**Comment by qcybb** [comment] 2017-08-16 16:04
> test-1
> [2017-08-16 09:02:07,604 pyinotify ERROR] rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)
> test-2

I'll have to get the logs for you tonight. Logrotate isn't doing anything because other criteria is not matching (log file has to be XX size before rotating, etc). I really don't want to mess with those variables.

**Comment by qcybb** [comment] 2017-08-17 08:16
It appears I was wrong about it failing to restart after log rotate. It's working just fine tonight.

> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   Ignoring creation of /var/log/maillog.1.bz2 we do not monitor
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   Ignoring creation of /var/log/maillog.3.bz2 we do not monitor
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   Ignoring creation of /var/log/maillog.2.bz2 we do not monitor
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   Ignoring creation of /var/log/maillog.0 we do not monitor
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: ERROR   rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   New <Watch wd=3 path=/var/log/maillog mask=2 proc_fun=None auto_add=False exclude_filter=<function <lambda> at 0x803959aa0> dir=False >
> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG   Added file watcher for /var/log/maillog
> 2017-08-17 00:00:00,032 fail2ban.filter         [20591]: MSG     Log rotation detected for /var/log/maillog

**Comment by sebres** [comment] 2017-08-17 08:31
Glad it works. 
Because of "Retrieving own IPs" bug you can update from current branch.
Thus closing.

**Comment by sebres** [comment] 2017-08-25 17:20
The "annoying" log-error should be fixed, so reopen, see also https://github.com/fail2ban/fail2ban/issues/1875#issuecomment-324978171

**Comment by qcybb** [comment] 2017-10-17 08:13
It appears I may have spoken too soon ... I'm seeing the same issue in v0.10.1

If the fail2ban log gets rotated (file size > 100k), everything is fine. If the file is not rotated, this error appears :

> 2017-10-17 00:00:00,138 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=3, Errno=Invalid argument (EINVAL)

**Comment by sebres** [comment] 2017-10-17 08:53
@qcybb It is recidive jail? (is enabled?)

**Comment by qcybb** [comment] 2017-10-17 16:35
I'm sorry, I don't know what your talking about. Here is my jail.local file :

> [DEFAULT]
> bantime = 86400
> findtime = 900
> maxretry = 2
> banaction = pf-custom
> backend = pyinotify
> protocol = all
> port = 25
> 
> [postfix]
> enabled = true
> filter  = postfix-custom

**Comment by sebres** [comment] 2017-10-17 17:27
You told about the rotating of `fail2ban.log`, the observation of this log from pyinotify filter occurs only if configured for the jail. Fail2ban has currently only one such jail - `recidive`. Jail `postfix` does monitoring of the postfix log-files.
Therefore your statement "If the fail2ban log is not rotated, this error appears" makes not really sense.
Much more interesting how the postfix log-files will be rotated...

**Comment by qcybb** [comment] 2017-10-17 19:14
Oh I see. The file newsyslog.conf in FreeBSD handles all the log rotating.

> # logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
> /var/log/maillog                        640  4     *    @T00  JC
> /var/log/fail2ban.log                 640  1     *    $W1D0 J     /var/run/fail2ban/fail2ban.pid 30

**Comment by neildarlow** [comment] 2017-10-19 10:57
I am seeing the same problem myself. I'm also using fail2ban to monitor postfix on FreeBSD-11.1.

Here is output from my scenario:
2017-10-18 23:52:07,992 fail2ban.filter         [17019]: INFO    [postfix] Found 190.60.122.229 - 2017-10-18 23:52:07
2017-10-18 23:52:08,309 fail2ban.actions        [17019]: NOTICE  [postfix] Ban 190.60.122.229
2017-10-18 23:54:36,080 fail2ban.filter         [17019]: INFO    [postfix] Found 89.146.35.189 - 2017-10-18 23:54:36
2017-10-18 23:55:34,746 fail2ban.actions        [17019]: NOTICE  [nginx-botsearch] Unban 178.159.37.11
2017-10-19 00:00:00,233 fail2ban.filterpyinotify[17019]: ERROR   rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)
2017-10-19 00:00:00,872 fail2ban.server         [17019]: INFO    rollover performed on /var/log/fail2ban.log
2017-10-19 00:04:49,593 fail2ban.filter         [17019]: INFO    [postfix] Found 85.194.87.126 - 2017-10-19 00:04:49
2017-10-19 00:05:17,600 fail2ban.filter         [17019]: INFO    [postfix] Found 91.200.12.50 - 2017-10-19 00:05:17
2017-10-19 00:05:17,682 fail2ban.filter         [17019]: INFO    [postfix] Found 91.200.12.50 - 2017-10-19 00:05:17
2017-10-19 00:05:18,015 fail2ban.actions        [17019]: NOTICE  [postfix] Ban 91.200.12.50

A lot of log rotation occurs around midnight including /var/log/maillog and also /var/log/fail2ban.log as shown in the above excerpt.

**Comment by sebres** [comment] 2017-10-19 12:01
> I am seeing the same problem myself...

Well, it is not really a "problem". The rotation is successful recognized and the monitoring continues.
Just annoying error message in fail2ban.log... (that will be written directly from module pyinotify).
I've tried several things (like [here](https://github.com/fail2ban/fail2ban/commit/a4459765ef438db83a2898ba832ff7acba033e29#diff-c39443ec7a0a65afa3c20feb3ceb9c32R231)) but currently I don't know, how it could be "fixed"... (but the priority of issue is low).
Seems to be something multi-threaded, like this:
<table><tr><th>filter-thread</th><th>pyinotify-thread</th></tr>
<tr><td>

```python
if self.__monitor.get_path(wdInt) is not None:
#... context-switch ...
  wd = self.__monitor.rm_watch(wdInt)
# we see error in log
```
</td><td>

```
# Recognized wdInt should be removed and do it.
self.rm_watch(wdInt); 
#... context-switch ...
Logging error because wdInt was already removed.
```
</td></tr>
</table>

Possibly we should just retard the call of _delFileWatcher, or use common synchronization mechanism for both threads...
<br/>

> Could it be significant ... compressed during rotation

Maybe, but ATM I don't thing so.

**Comment by qcybb** [comment] 2017-10-22 03:09
I'm not sure if this is important or helps at all, but WD=? increases by one every night that /var/log/maillog file is rotated.

> 2017-10-17 00:00:00,138 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=3, Errno=Invalid argument (EINVAL)
> 2017-10-18 00:00:00,045 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=4, Errno=Invalid argument (EINVAL)
> 2017-10-19 00:00:00,034 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=5, Errno=Invalid argument (EINVAL)
> 2017-10-20 00:00:00,056 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=6, Errno=Invalid argument (EINVAL)
> 2017-10-21 00:00:00,103 fail2ban.filterpyinotify[91463]: ERROR   rm_watch: cannot remove WD=7, Errno=Invalid argument (EINVAL)

**Comment by sebres** [comment] 2018-01-15 14:42
So I think, I found the way to remove this annoying error:
The parameter `quiet` (default True) is responsible to log the error, see https://github.com/seb-m/pyinotify/commit/8da69de7c06c68aed453c8a97d49f4e64bd41711#diff-f7f68228921bcd5418bf831d1453a4e5R1530

**Closed** 2018-01-15 16:22 UTC

**Comment by qcybb** [comment] 2018-01-15 16:23
Sounds good to me! It'll be nice to not have that warning show up every night :)

**Comment by sebres** [comment] 2018-01-15 16:29
> every night

Looks like it is pyinotify version-related, because I cannot reproduce it (also if I tried it using multi-threaded mock-up's, where one thread intentionally tries to cause this case).

**Comment by qcybb** [comment] 2018-01-15 16:48
I'm using pyinotify 0.9.6 - which appears to be the latest version available.

Like I mentioned before, the error shows up at 12AM every night in the fail2ban.log file. My postfix maillog file is rotated at the same time each night - so if that's not causing the issue, I'm not sure what is.

**Comment by sebres** [comment] 2018-01-15 17:03
> so if that's not causing the issue, I'm not sure what is.

It is definitely the rotation. 
But on my systems I don't see the message, no matter how I'm trying to produce it...
