### ISSUE TITLE
Date based jail just works until next day

### ISSUE THREAD

**Issue by Marook332** [fail2ban/fail2ban#2947] opened 2021-02-23 13:41 UTC
### Environment:
- fail2ban/focal,now 0.11.1-1 all [installed]
- Ubuntu 20.04 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I created a custom filter to detect DNS-requests [ANY] and block them. My DNS Server logs into a special location and is configured to keep the recent 7 days of logs.

> root@nc ~ # ll -h /etc/dns/config/logs/
> total 118M
> drwxr-xr-x 2 root root 4.0K Feb 23 01:53 ./
> drwxr-xr-x 7 root root 4.0K Jan 11 11:55 ../
> -rw-r--r-- 1 root root  13M Feb 18 01:00 2021-02-17.log
> -rw-r--r-- 1 root root  12M Feb 19 01:00 2021-02-18.log
> -rw-r--r-- 1 root root 5.0M Feb 20 01:00 2021-02-19.log
> -rw-r--r-- 1 root root 4.7M Feb 21 01:00 2021-02-20.log
> -rw-r--r-- 1 root root  22M Feb 22 01:00 2021-02-21.log
> -rw-r--r-- 1 root root  41M Feb 23 01:00 2021-02-22.log
> -rw-r--r-- 1 root root  23M Feb 23 14:25 2021-02-23.log

The jail works fine until a new logfile is used.
If i run `fail2ban-client status tdns`, i got this:

> root@nc ~ # fail2ban-client status tdns
> Status for the jail: tdns
> |- Filter
> |  |- Currently failed: 0
> |  |- Total failed:     548
> |  `- File list:        /etc/dns/config/logs/2021-02-15.log /etc/dns/config/logs/2021-02-16.log /etc/dns/config/logs/2021-02-17.log /etc/dns/config/logs/2021-02-13.log /etc/dns/config/logs/2021-02-19.log /etc/dns/config/logs/2021-02-18.log /etc/dns/config/logs/2021-02-14.log
> `- Actions
>    |- Currently banned: 2
>    |- Total banned:     70
>    `- Banned IP list:   74.91.120.250 103.95.221.0

As you can see, there are no newer logfiles than `2021-02-19`
But `fail2ban-client -d` gives me this output:

> root@nc ~ # fail2ban-client -d | grep ", 'tdns'" | grep -E "'((add)?(logpath|journalmatch)|start|add)'"
> ['add', 'tdns', 'pyinotify']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-20.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-17.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-19.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-23.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-22.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-18.log', 'head']
> ['set', 'tdns', 'addlogpath', '/etc/dns/config/logs/2021-02-21.log', 'head']
> ['multi-set', 'tdns', 'action', 'sendmail-whois-lines', [['actionstart', 'printf %b "Subject: [Fail2Ban] tdns: started on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban@<fq-hostname>>\nTo: info@xxx.com\\n\nHi,\\n\nThe jail tdns has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban@<fq-hostname>" "info@xxx.com"'], ['actionstop', 'printf %b "Subject: [Fail2Ban] tdns: stopped on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban@<fq-hostname>>\nTo: info@xxx.com\\n\nHi,\\n\nThe jail tdns has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban@<fq-hostname>" "info@xxx.com"'], ['actioncheck', ''], ['actionban', '( printf %b "Subject: [Fail2Ban] tdns: banned <ip> from <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban@<fq-hostname>>\nTo: info@xxx.com\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against tdns.\\n\\n\nHere is more information about <ip> :\\n"\nwhois <ip> || echo "missing whois program";\nprintf %b "\\nLines containing failures of <ip> (max 1000)\\n";\nlogpath="/etc/dns/config/logs/*.log"; grep -m 1000 -wF "<ip>" $logpath | tail -n 1000;\nprintf %b "\\n\nRegards,\\n\nFail2Ban" ) | /usr/sbin/sendmail -f "fail2ban@<fq-hostname>" "info@xxx.com"'], ['actionunban', ''], ['norestored', True], ['name', 'tdns'], ['sender', 'fail2ban@<fq-hostname>'], ['dest', 'info@xxx.com'], ['logpath', '/etc/dns/config/logs/*.log'], ['chain', '<known/chain>'], ['actname', 'sendmail-whois-lines'], ['mailcmd', '/usr/sbin/sendmail -f "<sender>" "<dest>"'], ['sendername', 'Fail2Ban'], ['greplimit', 'tail -n <grepmax>'], ['grepmax', '1000'], ['grepopts', '-m <grepmax>']]]
> ['start', 'tdns']

Here you can see, threr are all recent logfiles listed... any idea whats wrong ?

### Configuration, dump and another helpful excerpts
Jail:

> [tdns]
> backend = pyinotify
> findtime = 5s
> enabled = true
> port = 53
> logpath = /etc/dns/config/logs/*.log
> protocol = udp

Filter:
```
[INCLUDES]

before = common.conf

[Definition]

failregex = \[<HOST>:\d+\] \[UDP\] QNAME: \; QTYPE: ANY\;
            \[<HOST>:\d+\] \[UDP\] QNAME: \S+\; QTYPE: ANY\;
```

#### Any customizations done to /etc/fail2ban/ configuration
```none
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment] 2021-02-23 14:10
duplicate of #1407, #1379 et all...

Shortly: fail2ban does not update files matching logpath pattern during the run-time at the moment (this happens only at (re)start or reload).
So right now few solutions are possible:
- either reconfigure the service to generate **active** log-file with the fixed constant name;
- or use some post-logrotate script making a fixed link name to `/path/YYYY-MM-DD.log` (see also https://github.com/fail2ban/fail2ban/issues/1735#issuecomment-289382744 and below)
- or reload jail after rotation (or by some cron)
- or switch to systemd journal (if service supporting it)

**Closed by sebres** 2021-02-23 14:10 UTC
Labels: closed-as-duplicate
