### ISSUE TITLE
[BR]: IndexError(string index out of range) despite regex test worked

### ISSUE THREAD

**Issue by Sin4th** [fail2ban/fail2ban#3366] opened 2022-09-27 18:58 UTC
### Environment:

- fail2ban 0.11.2
- debian
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hey i have fail2ban 0.11.2 and an error on a json traefik log line.
Regex tester shows no match (correctly) but i still get error messages in the log.

regex: `^.*ClientHost":"<HOST>".*POST.*xmlrpc\.php.*`

logline (replaced ips): 
```
{"ClientAddr":"12.12.12.12:41046","ClientHost":"12.12.12.12","ClientPort":"41046","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":240708,"OriginContentSize":19,"OriginDuration":20342,"OriginStatus":404,"Overhead":220366,"RequestAddr":"12.12.12.12:443","RequestContentSize":0,"RequestCount":23,"RequestHost":"5.255.77.9","RequestMethod":"GET","RequestPath":"/","RequestPort":"443","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2022-09-27T18:44:25.457733309Z","StartUTC":"2022-09-27T18:44:25.457733309Z","entryPointName":"websecure","level":"info","msg":"","time":"2022-09-27T18:44:25Z"}
```
regex test output: `Lines: 1 lines, 0 ignored, 0 matched, 1 missed`

fail2ban log output (changed ips): 
```
2022-09-27 20:44:27 | 2022-09-27 20:44:27,365 fail2ban.filter         [3628179]: ERROR   Failed to process line: '{"ClientAddr":"12.12.12.12:41046","ClientHost":"12.12.12.12","ClientPort":"41046","ClientUsername":"-","DownstreamContentSize":19,"DownstreamStatus":404,"Duration":240708,"OriginContentSize":19,"OriginDuration":20342,"OriginStatus":404,"Overhead":220366,"RequestAddr":"12.12.12.12:443","RequestContentSize":0,"RequestCount":23,"RequestHost":"12.12.12.12","RequestMethod":"GET","RequestPath":"/","RequestPort":"443","RequestProtocol":"HTTP/1.1","RequestScheme":"http","RetryAttempts":0,"StartLocal":"2022-09-27T18:44:25.457733309Z","StartUTC":"2022-09-27T18:44:25.457733309Z","entryPointName":"websecure","level":"info","msg":"","time":"2022-09-27T18:44:25Z"}', caught exception: IndexError('string index out of range')
```

xmlrpc.conf:
```
#config file for xmlrpc attacks on websites
[Definition]
failregex = ^.*ClientHost":"<HOST>".*POST.*xmlrpc\.php.*
ignoreregex =`
```
jail.local:
```
[sshd]
enabled = True
port = 22
logpath = /var/log/auth.log
maxretry = 3
findtime = 300
bantime = -1

[xmlrpc]
enabled = True
filter = xmlrpc
action = iptables-allports[blocktype=”DROP”, name=”xmlrpc”, protocol=”tcp”, chain=”INPUT”]
logpath = /docker/web/traefik/log/traefik_access.log
findtime = 300000
bantime = 43600
maxretry = 4
```

**Comment by sebres** [comment] 2022-09-27 20:51
Dup of #3020

See also https://github.com/fail2ban/fail2ban/issues/3226#issuecomment-1046898405

Shortly it known bug and it is fixed, but after 0.11.2 (atm released with 1.0.1 only).
The issue is with dynamic offset to the timestamp `"StartLocal":"2022-09-27T18:44:25.457733309Z"` (since it is different from line to line) and unanchored nature of the datepattern (fail2ban is trying to find better matching pattern from default date-patterns).

Workaround is simply - specify exactly one "anchored" pattern.
In your case it is something like:
```ini
datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S%%Z".*$
```
(I know that it is not really anchored, due to catch-all `.*$` - but it "tells" fail2ban the datepattern is anchored, don't try lookup for its position.)

And see https://github.com/fail2ban/fail2ban/issues/2330#issuecomment-459965597 for better regex for your filter (very similar).
The log-line you provided as example is not matching to your RE, so I don't know what it needed to match to give you better filter.

**Closed by sebres** 2022-09-27 20:51 UTC
Labels: closed-as-duplicate, implemented-in-newer-version, bug
