### ISSUE TITLE
IPv6 addresses seemingly can be misinterpreted as IPv4 addresses (0.9 branch)

### ISSUE THREAD

**Issue by m-ueberall** [fail2ban/fail2ban#1493] opened 2016-07-30 10:57 UTC
### Environment:
- Fail2Ban version (including any possible distribution suffixes): _0.9.5-1_
- OS, including release name/version: _Ubuntu Xenial (16.04.1 LTS)_

[(x)] Fail2Ban installed via OS/distribution mechanisms
[(x)] You have not applied any additional foreign patches to the codebase
Rebuilt and installed https://launchpad.net/ubuntu/+source/fail2ban/0.9.5-1
- [x] Some customizations were done to the configuration

### The issue:
Using the above version 0.9.5, it looks as if IPv6 addresses in logs can be misinterpreted as IPv4 addresses, leading to "spurious" bans.

#### Steps to reproduce
1. Install a custom filter (see https://github.com/DenisChatenay/seafile-authentication-fail2ban/blob/master/etc/fail2ban/filter.d/seafile-auth.conf) containing the following:
`failregex = Login attempt limit reached.*, ip: <HOST>`
`ignoreregex =`

2. Make sure the above is active
3. Access the service in question / make sure to fill the monitored log with messages containing IPv6 addresses (e.g., `nnnn:nnnn:nnnn:nnnn:81e4:aa21:4320:9a84`)

#### Expected behavior
As the 0.9 branch has no IPv6 support and there's no notion that the Ubuntu package contains patches which are supposed to add it, the "Banned IP list" should stay *empty* as long as no IPv4 addresses turn up in the monitored log.

#### Observed behavior
The IPv6 addresses in the aforementioned log were somehow misinterpreted as IPv4 addresses:
```
# grep eumel /var/www/apps/seafile/logs/seahub.log
2016-07-30 12:06:39,595 [WARNING] seahub.auth.views:191 login Login attempt limit reached, show Captcha, email/username: eumel, ip: nnnn:nnnn:nnnn:nnnn:81e4:aa21:4320:9a84, attemps: 5
# fail2ban-client status seafile
Status for the jail: seafile
|- Filter
| |- Currently failed: 1
| |- Total failed: 3
| `- File list: /var/www/apps/seafile/logs/seahub.log
`- Actions
   |- Currently banned: 1
   |- Total banned: 1
   `- Banned IP list: 0.0.7.209
```
(I.e., even w/o IPv6 support, the 0.9 branch should try harder to identify valid IPv4 addresses.)

**Comment by sebres** [comment] 2016-07-30 12:22
duplicate of #1375

**Closed** 2016-08-01 11:39 UTC
Labels: closed-as-duplicate
