### ISSUE TITLE
[BR]: Error "string index out of range" on log-lines without timestamp

### ISSUE THREAD

**Issue by abraxasnew** [fail2ban/fail2ban#3226] opened 2022-02-19 14:05 UTC
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban throws errors on log lines that do no contain dates.
Freeswitch logs some messages on multiple lines (especially SDP messages), and the subsequent lines form the same message has no date.

#### Steps to reproduce
For logs like:
```
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] sofia.c:7094 Remote SDP:
639eacf2-908f-11ec-96f0-f19b85175ba0 v=0
639eacf2-908f-11ec-96f0-f19b85175ba0 o=FreeSWITCH 1645143180 1645143181 IN IP4 192.168.253.99
639eacf2-908f-11ec-96f0-f19b85175ba0 s=FreeSWITCH
639eacf2-908f-11ec-96f0-f19b85175ba0 c=IN IP4 192.168.253.99
639eacf2-908f-11ec-96f0-f19b85175ba0 t=0 0
639eacf2-908f-11ec-96f0-f19b85175ba0 m=audio 27426 RTP/AVP 0 18 8 101
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:0 PCMU/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:18 G729/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:18 annexb=no
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:8 PCMA/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:101 telephone-event/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:101 0-15
639eacf2-908f-11ec-96f0-f19b85175ba0 a=silenceSupp:off - - - -
639eacf2-908f-11ec-96f0-f19b85175ba0 a=ptime:20
639eacf2-908f-11ec-96f0-f19b85175ba0 
```
#### Expected behavior
Fail2ban should ignore those lines.
#### Observed behavior
Fail2Ban logs errors for each line:
```
2022-02-18 11:19:51,678 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 v=0', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:51,679 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 v=0', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:53,681 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 s=FreeSWITCH', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:53,682 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 s=FreeSWITCH', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:55,685 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 c=IN IP4 [192.168.253.98](https://192.168.253.98/)', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:55,685 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 c=IN IP4 [192.168.253.98](https://192.168.253.98/)', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:57,688 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 t=0 0', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:57,688 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 t=0 0', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:59,692 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:0 PCMU/8000', caught exception: IndexError('string index out of range',)
2022-02-18 11:19:59,693 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:0 PCMU/8000', caught exception: IndexError('string index out of range',)
2022-02-18 11:20:01,698 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:101 0-16', caught exception: IndexError('string index out of range',)
2022-02-18 11:20:01,697 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:101 0-16', caught exception: IndexError('string index out of range',)
2022-02-18 11:20:03,701 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=ptime:20', caught exception: IndexError('string index out of range',)
2022-02-18 11:20:03,702 fail2ban.filter [16177]: ERROR Failed to process line: u'639eacf2-908f-11ec-96f0-f19b85175ba0 a=pt
```

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
freeswitch.conf filter:
[root@voice ~]# cat /etc/fail2ban/filter.d/freeswitch.conf 

[INCLUDES]
before = common.conf

[Definition]
_daemon = freeswitch

mode = extra
              
_pref_line = ^%(__prefix_line)s(?:(?:\d+-)?\d+-\d+ \d+:\d+:\d+\.\d+)?
prefregex = ^%(_pref_line)s \[WARN(?:ING)?\](?: \[SOFIA\])? \[?sofia_reg\.c:\d+\]? <F-CONTENT>.+</F-CONTENT>$
cmnfailre = ^Can't find user \[[^@]+@[^\]]+\] from <HOST>$
mdre-normal = %(cmnfailre)s
              ^SIP auth failure \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[[^\]]*\] from ip <HOST>$
mdre-ddos   = ^SIP auth (?:failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[[^\]]*\] from ip <HOST>$

mdre-extra  = %(cmnfailre)s
              <mdre-ddos>

failregex = <mdre-<mode>>
ignoreregex =
datepattern = ^(?:%%Y-)?%%m-%%d[ T]%%H:%%M:%%S(?:\.%%f)?
              {^LN-BEG}
```
#### Relevant lines from monitored log files:

jail.local
```
[freeswitch-udp]
enabled  = true
port     = 5060
protocol = all
filter   = sip-auth-failure
logpath = /var/log/freeswitch/freeswitch.log
action   = firewallcmd-allports[name=freeswitch-udp, port="%(port)s", protocol=udp]
maxretry = 5
findtime = 600
bantime  = 3600
```

```
097e26a8-9035-11ec-b339-f19b85175ba0 2022-02-17 23:03:30.899679 [NOTICE] switch_core_session.c:1687 Close Channel sofia/External5060...skipping...
 receiving invite from 192.168.253.99:5081 version: 1.6.20  64bit
2022-02-18 09:50:06.759675 [DEBUG] sofia.c:10044 IP 192.168.253.99 Rejected by acl "default". Falling back to Digest auth.
2022-02-18 09:50:06.759675 [WARNING] sofia_reg.c:1792 SIP auth challenge (INVITE) on sofia profile 'LanSideProfile' for [27833337071
@192.168.253.98] from ip 192.168.253.99
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.759675 [DEBUG] switch_core_state_machine.c:603 (sofia/LanSideProfile/271247
60025@192.168.253.99) State NEW
2022-02-18 09:50:06.759675 [DEBUG] sofia.c:2334 detaching session 639eacf2-908f-11ec-96f0-f19b85175ba0
2022-02-18 09:50:06.759675 [DEBUG] sofia.c:2442 Re-attaching to session 639eacf2-908f-11ec-96f0-f19b85175ba0
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.779648 [DEBUG] sofia.c:9873 sofia/LanSideProfile/27124760025@192.168.253.99
 receiving invite from 192.168.253.99:5081 version: 1.6.20  64bit
2022-02-18 09:50:06.779648 [DEBUG] sofia.c:10044 IP 192.168.253.99 Rejected by acl "default". Falling back to Digest auth.
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] sofia.c:7084 Channel sofia/LanSideProfile/27124760025@192.16
8.253.99 entering state [received][100]
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] sofia.c:7094 Remote SDP:
639eacf2-908f-11ec-96f0-f19b85175ba0 v=0
639eacf2-908f-11ec-96f0-f19b85175ba0 o=FreeSWITCH 1645143180 1645143181 IN IP4 192.168.253.99
639eacf2-908f-11ec-96f0-f19b85175ba0 s=FreeSWITCH
639eacf2-908f-11ec-96f0-f19b85175ba0 c=IN IP4 192.168.253.99
639eacf2-908f-11ec-96f0-f19b85175ba0 t=0 0
639eacf2-908f-11ec-96f0-f19b85175ba0 m=audio 27426 RTP/AVP 0 18 8 101
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:0 PCMU/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:18 G729/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:18 annexb=no
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:8 PCMA/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=rtpmap:101 telephone-event/8000
639eacf2-908f-11ec-96f0-f19b85175ba0 a=fmtp:101 0-15
639eacf2-908f-11ec-96f0-f19b85175ba0 a=silenceSupp:off - - - -
639eacf2-908f-11ec-96f0-f19b85175ba0 a=ptime:20
639eacf2-908f-11ec-96f0-f19b85175ba0 
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4449 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[PCMU:0:8000:20:64000:1]
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4504 Audio Codec Compare [PCMU:0:8000:20:64000:1] ++++ is saved as a match
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4449 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[PCMA:8:8000:20:64000:1]
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4449 Audio Codec Compare [PCMU:0:8000:20:64000:1]/[G729:18:8000:20:8000:1]
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4449 Audio Codec Compare [G729:18:8000:20:8000:1]/[PCMU:0:8000:20:64000:1]
639eacf2-908f-11ec-96f0-f19b85175ba0 2022-02-18 09:50:06.799659 [DEBUG] switch_core_media.c:4449 Audio Codec Compare [G729:18:8000:20:8000:1]/[PCMA:8:8000:20:64000:1]
```

**Comment by sebres** [comment] 2022-02-21 13:46
Already answered in https://stackoverflow.com/a/71175802/7161854 :

1. see #3020
Shortly it is fixed in newer versions, but you can workaround it using precise datepattern (like `'^\S+ {DATE}`), if the message you're searching for contain the timestamp, otherwise...
2. see #2814 (released with 0.11.2/0.10.6), for instance set `datepattern = {NONE}` would allow to find failures totally without date-time in log messages.
3. 1645143180 is also timestamp (posix unix time since epoch), fail2ban has also a special datepattern for such format (`EPOCH` or as part of RE `{EPOCH}`), but you may need also use more precise pattern.

Anyway I don't see any failure in log, thus don't really know which lines may be interesting here.

----

So what exactly is not clear there?

Basically the error `string index out of range` on log lines without timestamps is already fixed in ef5c826c74c160d33d4b79b23d564f944d16a9dd, so it is duplicate of #3020
The solution for older version (also valid for 0.11.2) is described there too - you need simply more precise (anchored) `datepattern` to avoid it.
Moreover the `datepattern` of `freeswitch` filter is precise enough, so it should not produce this error at all.
Did you reset `datepattern` in `/etc/fail2ban/filter.d/freeswitch.local` or `/etc/fail2ban/jail.local` for freeswitch jail?
Because I can't explain otherwise how this error occurs there.

<details><summary>PoC (fail2ban-regex of fail2ban 0.11.2) ...</summary>

```
# --------------------------------------------------------------------
# no error (anchored datepatterns):
# --------------------------------------------------------------------
$ fail2ban-regex /tmp/log 'freeswitch'

Running tests
=============

Use   failregex filter file : freeswitch, basedir: /tmp/fail2ban.0.11.2/config/
Use      datepattern : ^(?:%Y-)?%m-%d[ T]%H:%M:%S(?:\.%f)?
{^LN-BEG} : Default Detectors
Use         log file : /tmp/log
Use         encoding : UTF-8


Results
=======

Prefregex: 1 total
|  ^^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?freeswitch(?:\(\S+\))?[\]\)]?:?|[\[\(]?freeswitch(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?(?:(?:\d+-)?\d+-\d+ \d+:\d+:\d+\.\d+)? \[WARN(?:ING)?\](?: \[SOFIA\])? \[?sofia_reg\.c:\d+\]? (?P<content>.+)$
`-

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [5] ^(?:Year-)?Month-Day[ T]24hour:Minute:Second(?:\.Microseconds)?
`-

Lines: 36 lines, 0 ignored, 0 matched, 36 missed
[processed in 0.01 sec]

# --------------------------------------------------------------------
# generate an error (reset datepattern to default list with unanchored REs):
# --------------------------------------------------------------------
$ fail2ban-regex /tmp/log 'freeswitch[datepattern=""]'

Running tests
=============

Use   failregex filter file : freeswitch, basedir: /tmp/fail2ban.0.11.2/config/
Use   filter options : {'datepattern': ''}
Use      datepattern :  : Default Detectors
Use         log file : /tmp/log
Use         encoding : UTF-8
...
IndexError: string index out of range

# --------------------------------------------------------------------
# test datepattern anchored after some GUID:
# --------------------------------------------------------------------
$ fail2ban-regex /tmp/log 'freeswitch[datepattern="^\S+\s(?:%Y-)?%m-%d[ T]%H:%M:%S(?:\.%f)?"]'

Running tests
=============

Use   failregex filter file : freeswitch, basedir: /tmp/fail2ban.0.11.2/config/
Use   filter options : {'datepattern': '^\\S+\\s(?:%Y-)?%m-%d[ T]%H:%M:%S(?:\\.%f)?'}
Use      datepattern : ^\S+\s(?:%Y-)?%m-%d[ T]%H:%M:%S(?:\.%f)? : ^\S+\s(?:Year-)?Month-Day[ T]24hour:Minute:Second(?:\.Microseconds)?
Use         log file : /tmp/log
Use         encoding : UTF-8


Results
=======

Prefregex: 1 total
|  ^^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?freeswitch(?:\(\S+\))?[\]\)]?:?|[\[\(]?freeswitch(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?(?:(?:\d+-)?\d+-\d+ \d+:\d+:\d+\.\d+)? \[WARN(?:ING)?\](?: \[SOFIA\])? \[?sofia_reg\.c:\d+\]? (?P<content>.+)$
`-

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [11] ^\S+\s(?:Year-)?Month-Day[ T]24hour:Minute:Second(?:\.Microseconds)?
`-

Lines: 36 lines, 0 ignored, 0 matched, 36 missed
[processed in 0.00 sec]
```
</details>

And as already said I don't see any failure in this log-excerpt (at least the filter does not target something like that).
Also consider:
https://github.com/fail2ban/fail2ban/blob/8ac49b58582cfe82626307b5a8b0574a63499d95/config/filter.d/freeswitch.conf#L3-L5

**Closed by sebres** 2022-02-21 13:46 UTC
Labels: closed-as-incorrect, closed-as-duplicate, implemented-in-newer-version, bug
