### ISSUE TITLE
Actionstart/actionstop executed twice with actionstart_on_demand=false

### ISSUE THREAD

**Issue by balushen284** [fail2ban/fail2ban#3342] opened 2022-08-31 16:40 UTC
Hello
I have found an strange behaviour using fail2ban with nftables on Raspberry OS and actionstart/actionstop

- Fail2Ban version 0.11.2 : 
- OS, Raspberry OS Bullseye : 
- Fail2Ban installed via apt-get
- Using nftables 

The issue:
If you define a jail using nftables (for example "nftables-allports.conf"), and use "actionstart_on_demand=false", the commands included into "actionstart" and "actionstop" are executed twice

#### Steps to reproduce
Define an aditional command into actionstart/actionstop (for example echo something to a file), and you will have two lines when you start fail2ban service and two lines when stopping it, so it seems actionstart/actionstop is being executed twice.

#### Expected behavior
Only one execution should be done (for the echo example, only one line should be written).

#### Observed behavior
Two lines written each time fail2ban starts/stops although on logs you only see one actionstart/actionstop.

**Comment by sebres** [comment] 2022-09-01 16:55
OK, reproduced. Thx for notice!

The issue occurs only if action has a conditional section `[Init?family=inet6]`. Thereby it does no matter, whether the `actionstart` doesn't use IPv6-related parameters or does it (where it would be expected case).

**Comment by sebres** [comment] 2022-09-01 17:40
Nope. I was wrong with my assumption above, it's only executing "twice" if commands for IPv4 and IPv6 are different (using some parameters).
I I use following config:
```diff
  [sshd]
- action = dummy[target="/tmp/f2b-dummy.txt", actionstart_on_demand=false]
+ action = dummy[target="/tmp/f2b-dummy.txt", actionstart_on_demand=false, actionstart="<known/actionstart> <family>"]
```
there are following results:
```diff
- [A]: DEBUG     Set actionstart = 'if [ ! -z \'/tmp/f2b-dummy.txt\' ]; then touch /tmp/f2b-dummy.txt; fi;\nprintf %b "123\\n" >> /tmp/f2b-dummy.txt\necho "[sshd] dummy /tmp/f2b-dummy.txt -- started"'
+ [B]: DEBUG     Set actionstart = 'if [ ! -z \'/tmp/f2b-dummy.txt\' ]; then touch /tmp/f2b-dummy.txt; fi;\nprintf %b "123\\n" >> /tmp/f2b-dummy.txt\necho "[sshd] dummy /tmp/f2b-dummy.txt -- started" <family>'
...
- [A]: DEBUG   7f3ecd5dcc60 -- stdout: '[sshd] dummy /tmp/f2b-dummy.txt -- started'
- [A]: DEBUG   7f3ecd5dcc60 -- returned successfully 0
+ [B]: DEBUG   7fc98d94fd30 -- stdout: '[sshd] dummy /tmp/f2b-dummy.txt -- started inet4'
+ [B]: DEBUG   7fc98d94fd30 -- returned successfully 0
+ [B]: DEBUG   7fc98d94fed0 -- stdout: '[sshd] dummy /tmp/f2b-dummy.txt -- started inet6'
+ [B]: DEBUG   7fc98d94fed0 -- returned successfully 0
```
But it is intended since I added `<family>` for the case `[B]`, so the start commands are different for both families.
Fail2ban's action has a preventive mechanism to avoid double execution, it'd do that only if conditional IP-family related parameters are used somewhere in the actionstart or actionstop.
Parameter `actionstart_on_demand` doesn't really matter,  it'd just retard the execution of command, which is invoked by first ban (family related) if `actionstart_on_demand` sets to true.

I cannot reproduce it, neither with 0.11.2, nor with current major branches.
Thus close it as incorrect.
Please provide your configuration (action and jail) if you'd still mean it happens on your side nevertheless.

**Closed by sebres** 2022-09-01 17:40 UTC
Labels: moreinfo, closed-as-incorrect, bug
