### ISSUE TITLE
fail2ban-server kernel general protection fault

### ISSUE THREAD

**Issue by HolgerHees** [fail2ban/fail2ban#1480] opened 2016-07-10 14:40 UTC
Hi,

I don't know if this kernel log is helpful enough. But I think the fail2ban-server process has crashes my kernel. After this trace the whole server restarts.

Jul 09 23:44:05 knx kernel: general protection fault: 0000 [#1] SMP 
Jul 09 23:44:05 knx kernel: Modules linked in: ipt_REJECT xt_multiport iptable_filter ip_tables x_tables af_packet iscsi_ibft iscsi_boot_sysfs nct6775 hwmon_vid ftdi_sio cp210x 
Jul 09 23:44:05 knx kernel: CPU: 3 PID: 14124 Comm: fail2ban-server Not tainted 3.16.7-35-default #1
Jul 09 23:44:05 knx kernel: Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./Q1900-ITX, BIOS P1.20 05/13/2014
Jul 09 23:44:05 knx kernel: task: ffff880273d78350 ti: ffff88027431c000 task.ti: ffff88027431c000
Jul 09 23:44:05 knx kernel: RIP: 0010:[<ffffffff810a61d0>]  [<ffffffff810a61d0>] __rwsem_do_wake+0x80/0x160
Jul 09 23:44:05 knx kernel: RSP: 0000:ffff88027431fdc8  EFLAGS: 00010086
Jul 09 23:44:05 knx kernel: RAX: ffffffff815d0920 RBX: 0000000000000002 RCX: 00a98025048b4865
Jul 09 23:44:05 knx kernel: RDX: ffff8802597ebea0 RSI: 0000000000000001 RDI: 000000005641fe63
Jul 09 23:44:05 knx kernel: RBP: ffff8802728bb878 R08: 0000000000001903 R09: a8001f382be00000
Jul 09 23:44:05 knx kernel: R10: 57ffcac7dbee0af8 R11: 0000000000000220 R12: ffff8802728bb860
Jul 09 23:44:05 knx kernel: R13: ffff8802728bb868 R14: ffff8802728bb800 R15: ffff880273d78350
Jul 09 23:44:05 knx kernel: FS:  00007fca40bfe700(0000) GS:ffff88027fd80000(0000) knlGS:0000000000000000
Jul 09 23:44:05 knx kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Jul 09 23:44:05 knx kernel: CR2: 00007fc9d3c59838 CR3: 0000000273065000 CR4: 00000000001007e0
Jul 09 23:44:05 knx kernel: Stack:
Jul 09 23:44:05 knx kernel:  ffff8802728bb860 ffff8802728bb878 0000000000000247 ffff88027431ff58
Jul 09 23:44:05 knx kernel:  ffff8802728bb800 ffffffff810a62df 00000000000000a8 00007fc9d3c59838
Jul 09 23:44:05 knx kernel:  0000000000000004 ffffffff81319397 0000000000000220 57ffcac7dbee0af8
Jul 09 23:44:05 knx kernel: Call Trace:
Jul 09 23:44:05 knx kernel:  [<ffffffff810a62df>] rwsem_wake+0x2f/0x50
Jul 09 23:44:05 knx kernel:  [<ffffffff81319397>] call_rwsem_wake+0x17/0x30
Jul 09 23:44:05 knx kernel:  [<ffffffff810a518b>] up_read+0x1b/0x20
Jul 09 23:44:05 knx kernel:  [<ffffffff81049489>] __do_page_fault+0x1c9/0x4d0
Jul 09 23:44:05 knx kernel:  [<ffffffff815d4208>] page_fault+0x28/0x30
Jul 09 23:44:05 knx kernel:  [<00007fca780490de>] 0x7fca780490dd
Jul 09 23:44:05 knx kernel: Code: ff ff 48 89 f2 f0 49 0f c1 14 24 48 39 ca 0f 8c d9 00 00 00 49 8b 54 24 08 be 01 00 00 00 4d 8d 6c 24 08 31 db eb 12 0f 1f 40 00 <8b> 79 18 85 
Jul 09 23:44:05 knx kernel: RIP  [<ffffffff810a61d0>] __rwsem_do_wake+0x80/0x160

**Comment by yarikoptic** [comment] 2016-07-10 14:45
is it reproducible or one time occasion?

unlikely anything we could be blamed for directly ;)

On Sun, 10 Jul 2016, Holger Hees wrote:

>    Hi,

>    I don't know if this kernel log is helpful enough. But I think the
>    fail2ban-server process has crashes my kernel.

>    Jul 09 23:44:05 knx kernel: general protection fault: 0000 [#1] SMP
>    Jul 09 23:44:05 knx kernel: Modules linked in: ipt_REJECT xt_multiport
>    iptable_filter ip_tables x_tables af_packet iscsi_ibft iscsi_boot_sysfs
>    nct6775 hwmon_vid ftdi_sio cp210x
>    Jul 09 23:44:05 knx kernel: CPU: 3 PID: 14124 Comm: fail2ban-server Not
>    tainted 3.16.7-35-default #1
>    Jul 09 23:44:05 knx kernel: Hardware name: To Be Filled By O.E.M. To Be
>    Filled By O.E.M./Q1900-ITX, BIOS P1.20 05/13/2014
>    Jul 09 23:44:05 knx kernel: task: ffff880273d78350 ti: ffff88027431c000
>    task.ti: ffff88027431c000
>    Jul 09 23:44:05 knx kernel: RIP: 0010:[] [] __rwsem_do_wake+0x80/0x160
>    Jul 09 23:44:05 knx kernel: RSP: 0000:ffff88027431fdc8 EFLAGS: 00010086
>    Jul 09 23:44:05 knx kernel: RAX: ffffffff815d0920 RBX: 0000000000000002
>    RCX: 00a98025048b4865
>    Jul 09 23:44:05 knx kernel: RDX: ffff8802597ebea0 RSI: 0000000000000001
>    RDI: 000000005641fe63
>    Jul 09 23:44:05 knx kernel: RBP: ffff8802728bb878 R08: 0000000000001903
>    R09: a8001f382be00000
>    Jul 09 23:44:05 knx kernel: R10: 57ffcac7dbee0af8 R11: 0000000000000220
>    R12: ffff8802728bb860
>    Jul 09 23:44:05 knx kernel: R13: ffff8802728bb868 R14: ffff8802728bb800
>    R15: ffff880273d78350
>    Jul 09 23:44:05 knx kernel: FS: 00007fca40bfe700(0000)
>    GS:ffff88027fd80000(0000) knlGS:0000000000000000
>    Jul 09 23:44:05 knx kernel: CS: 0010 DS: 0000 ES: 0000 CR0:
>    000000008005003b
>    Jul 09 23:44:05 knx kernel: CR2: 00007fc9d3c59838 CR3: 0000000273065000
>    CR4: 00000000001007e0
>    Jul 09 23:44:05 knx kernel: Stack:
>    Jul 09 23:44:05 knx kernel: ffff8802728bb860 ffff8802728bb878
>    0000000000000247 ffff88027431ff58
>    Jul 09 23:44:05 knx kernel: ffff8802728bb800 ffffffff810a62df
>    00000000000000a8 00007fc9d3c59838
>    Jul 09 23:44:05 knx kernel: 0000000000000004 ffffffff81319397
>    0000000000000220 57ffcac7dbee0af8
>    Jul 09 23:44:05 knx kernel: Call Trace:
>    Jul 09 23:44:05 knx kernel: [] rwsem_wake+0x2f/0x50
>    Jul 09 23:44:05 knx kernel: [] call_rwsem_wake+0x17/0x30
>    Jul 09 23:44:05 knx kernel: [] up_read+0x1b/0x20
>    Jul 09 23:44:05 knx kernel: [] __do_page_fault+0x1c9/0x4d0
>    Jul 09 23:44:05 knx kernel: [] page_fault+0x28/0x30
>    Jul 09 23:44:05 knx kernel: [<00007fca780490de>] 0x7fca780490dd
>    Jul 09 23:44:05 knx kernel: Code: ff ff 48 89 f2 f0 49 0f c1 14 24 48 39
>    ca 0f 8c d9 00 00 00 49 8b 54 24 08 be 01 00 00 00 4d 8d 6c 24 08 31 db eb
>    12 0f 1f 40 00 <8b> 79 18 85
>    Jul 09 23:44:05 knx kernel: RIP [] __rwsem_do_wake+0x80/0x160

>    -
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly, view it on GitHub, or mute the thread.

>    Link: https://github.com/fail2ban/fail2ban/issues/1480

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by HolgerHees** [comment] 2016-07-10 15:33
With this fail2ban version (0.9.4 from github), it was the first kernel crash. But before, I was running fail2ban version 0.9.3 provided by opensuse. For this old version another crash happened, but with only a single line crash log. I don't remember on the exact error message. With this old version I was also not able to start and stop the process properly. There was every time a defunc fail2ban-server process.

Until I'm waiting for the next crash, I will provide some additional information to the current installation.

- I'm running version 0.9.4
- Active jails are all apache jails which are watching apache logfiles 
- And the sshd jail which is using journald
- Open ports are only ssh and https
- And the distribution is opensuse 13.2

**Comment by HolgerHees** [comment] 2016-07-10 18:21
the last log entry was 5 hours ago.

python-systemd from latest git
pyinotify is 0.9.4
and gamin is 0.1.10

I will wait for the next crash to provide more informations.

In the meantime I was also doing a memory check without any errors.

**Comment by sebres** [comment] 2016-07-10 19:50
F2B written in python, so it is exactly so stable as the python self, resp. some python modules it uses...
I've still never seen a python process, that crashes kernel.
You can try to change f2b-backend for example from gamin to pyinotify or vista-versa, or rather to polling (would be then python pure).

**Comment by yarikoptic** [comment] 2016-07-20 20:15
just so we don't drag a dead horse around -- since unlikely anything we could do to "fix" whatever leads to such a grave fail, I will close it.  But by any means if you feel we need to fix something, feel welcome to reopen.
Cheers

**Closed by yarikoptic** 2016-07-20 20:15 UTC
