### ISSUE TITLE
Restart loop because of ssh command escaping error

### ISSUE THREAD

**Issue by dz0ny** [fail2ban/fail2ban#897] opened 2014-12-29 17:38 UTC
```
2014-12-29 12:56:24,276 fail2ban.server : INFO Stopping all jails
2014-12-29 12:56:24,505 fail2ban.actions: WARNING [ssh] Unban {hidden}
2014-12-29 12:56:24,513 fail2ban.actions.action: ERROR iptables -n -L INPUT | grep -q 'fail2ban-ssh[ \t]' returned 100
2014-12-29 12:56:24,514 fail2ban.actions.action: ERROR Invariant check failed. Trying to restore a sane environment
2014-12-29 12:56:24,521 fail2ban.actions.action: ERROR iptables -D INPUT -p tcp -m multiport --dports ssh -j fail2ban-ssh
iptables -F fail2ban-ssh
iptables -X fail2ban-ssh returned 100
2014-12-29 12:56:24,554 fail2ban.jail : INFO Jail 'ssh' stopped
2014-12-29 12:56:24,557 fail2ban.server : INFO Exiting Fail2ban
```

**Comment by yarikoptic** [comment] 2015-01-03 06:12
closing for now since not clear what the problem was, but feel free to follow up and reopen

**Closed by yarikoptic** 2015-01-03 06:12 UTC
Labels: moreinfo

**Comment by MT76** [comment] 2016-09-04 19:38
I landed here googling for the same error:

```
2016-09-03 21:09:00,097 fail2ban.actions.action: ERROR  iptables -D INPUT -p tcp -m multiport --dports ssh -j fail2ban-ssh
iptables -F fail2ban-ssh
iptables -X fail2ban-ssh returned 100

```

I know it's an old and closed issue, but i found a solution to this error and thought i should share.

After seeing this error in the fail2ban log, I found that the iptables rules in INPUT chain for the configured jails where not deleted completely when stopping fail2ban. Also the corresponding chains where not deleted. After some testing i found this will happen when you save iptables while fail2ban is running and then restore iptables on boot. Restoring iptables will add the fail2ban jail rules to the INPUT chain, without fail2ban knowing about it. Fail2ban will then add its rules to iptables' INPUT chain, resulting in double entries. Then, when you stop fail2ban it deletes the rules from the INPUT chain, but only the entries it added itself; so only one entry for each jail gets deleted. Then fail2ban tries to flush and delete the jail chains, resulting in this error because the jail chain is still referenced in the INPUT chain.

So to solve this error you have to stop fail2ban and then manually delete these rules from iptables' INPUT chain. To make sure they don't return, don't use iptables-save and don't restore iptables on boot. If you really need save/restore, then first stop fail2ban before saving iptables.

To devs:  Maybe fail2ban should check for existing jail rules in the INPUT chain before adding them?

-Maarten-

**Comment by yarikoptic** [comment] 2016-09-04 22:15
Thanks #MT76 . Issue shouldn't happen if init.d script states correctly to stop fail2ban before stopping iptables, which I think we did. What is your system and version of fail2ban?

**Comment by MT76** [comment] 2016-09-04 22:44
Sorry, forgot to include that info:

```
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
```
```
fail2ban:
  Installed: 0.8.6-3wheezy3build0.12.04.1
```
```
iptables:
  Installed: 1.4.12-1ubuntu5
```

**Comment by yarikoptic** [comment] 2016-09-04 23:05
Ooh that is old - earth was flat then :-) . Fwiw You could get backport of more recent one from NeuroDebian.
Most probably Thur issue was resolved since then - changelog might have a record

**Comment by MT76** [comment] 2016-09-05 00:14
Ghe. Guess it's time to upgrade this server.   =)
I will report back when it is upgraded to latest LTS.

**Comment by MT76** [comment] 2016-09-07 23:34
Well, i upgraded the system:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
```
```
fail2ban:
  Installed: 0.9.3-1
```
```
iptables:
  Installed: 1.6.0-2ubuntu3
```

Still same problem. Only different error msg.

Log snippet:
```
2016-09-07 15:42:24,001 fail2ban.action         [2274]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stdout: b''
2016-09-07 15:42:24,002 fail2ban.action         [2274]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stderr: b'iptables: Too many links.\n'
2016-09-07 15:42:24,002 fail2ban.action         [2274]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- returned 1
2016-09-07 15:42:24,002 fail2ban.actions        [2274]: ERROR   Failed to stop jail 'sshd' action 'iptables-multiport': Error stopping action
2016-09-07 15:42:24,002 fail2ban.jail           [2274]: INFO    Jail 'sshd' stopped
```

To reproduce:

```
root@websrv:~# service fail2ban start

root@websrv:~# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-postfix-rdns  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix-sasl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,imap3,imaps,pop3,pop3s
f2b-dovecot  tcp  --  anywhere             anywhere             multiport dports pop3,pop3s,imap2,imaps,submission,urd,sieve
f2b-postfix-rbl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh

root@websrv:~# iptables-save > /etc/iptables/rules.v4

root@websrv:~# service fail2ban stop

root@websrv:~# iptables-restore < /etc/iptables/rules.v4

root@websrv:~# service fail2ban start

root@websrv:~# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-postfix-rdns  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix-sasl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,imap3,imaps,pop3,pop3s
f2b-dovecot  tcp  --  anywhere             anywhere             multiport dports pop3,pop3s,imap2,imaps,submission,urd,sieve
f2b-postfix-rbl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh
f2b-postfix-rdns  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix-sasl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,imap3,imaps,pop3,pop3s
f2b-dovecot  tcp  --  anywhere             anywhere             multiport dports pop3,pop3s,imap2,imaps,submission,urd,sieve
f2b-postfix-rbl  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-postfix  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh
```

As you can see, there are duplicate entries in INPUT chain. This also happens when i save iptables, then reboot and on boot my iptables get restored by iptables-persistent.

**Comment by sebres** [comment] 2016-09-08 00:24
well, I suspect, that you can have 2 problems:
- either you have some chains, that used same naming convention as fail2ban. e.g. saving iptables during fail2ban works have few sense, at least not filtered f2b chains. So restoring it, will disturb correct work of f2b...
- or you have missconfigurred your jail.local - two jail used the same name.
To check this, please dump your fail2ban config, by exec `fail2ban-client -d` and post the output of that.

**Comment by MT76** [comment] 2016-09-08 01:56
There are no f2b-like chains in iptables, this behavior can be reproduced on a default (empty) iptables rule-set. Also, there are no duplicate jail names in my jail.local.

But you are right about little sense to manually save iptables. I tried with saving iptables with a script in /etc/network/if-post-down.d/ and then this doesn't happen. 

Still, i think it would be good practice if f2b would first check if an exact same rule for a jail exists in INPUT before trying to add it. Then f2b will never give this error on stop, not even when a user does manually save iptables.

**Comment by sebres** [comment] 2016-09-08 10:02
> check if an exact same rule for a jail exists in INPUT before trying to add it

Exactly that does it (our iptables-actions have `actioncheck` parameters that operate such handling). But I think, your manually activities (restore iptables) do not...

BTW it may be nevertheless still one signal for #980

**Comment by MT76** [comment] 2016-09-08 17:21
> Exactly that does it (our iptables-actions have actioncheck parameters that operate such handling).

Yes, indeed i see it should do that. But why doesn't it do that when i do this next steps:
(with empty iptables and modified jail.local which only loads recidive jail)
```
root@websrv:~# service fail2ban stop

root@websrv:~# sh iptables_reset.sh
iptables saves to iptables.1473353328
iptables has been reset to default

root@websrv:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

root@websrv:~# iptables -N f2b-recidive

root@websrv:~# iptables -A INPUT -p tcp -j f2b-recidive

root@websrv:~# service fail2ban start

root@websrv:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
f2b-recidive  tcp  --  anywhere             anywhere
f2b-recidive  tcp  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain f2b-recidive (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```
As you can see f2b does add the rule when it should not. This results in a duplicate entry in INPUT chain. 
This is not something you would normally do, but i'm trying to find why this is happening. 

>But I think, your manually activities (restore iptables) do not...

Manually saving iptables is the problem. Well to be honest i think the root of the problem lies with iptables happily accepting duplicate rules. IMHO it should not do that, but it does. So how can f2b counter this? I don't know. :(

**Comment by sebres** [comment] 2016-09-08 18:55
You described currently a little bit another behavior: `actioncheck` was never provided to check starting/stopping action (it is assumed, that is would be always correct).
At the moment `actioncheck` provided to check something implicit before ban/unban only, but we can indeed verify, that it can be used in start/stop also (e .g to check existence of table-chain)...
Unfortunately it is a little bit complicated, because it will be not completely backwards compatible, so usage of another parameter is desirable here, for example something like `actionstarted`, that will check the action is already available (for start - positive, for stop - negative).
Stupidly introducing of such parameter can be also evil, for example because of the following bad configuration:
```ini
[Jail-A]
action=iptables-allports[name="my-jail", chain=INPUT, ...]
[Jail-B]
action=iptables-allports[name="my-jail", chain=INPUT, ...]
```
So this definitely wrong configuration - banning in both goes in the same table/chain (my-jail/INPUT). But it will not produce an error by starting, because after start of `Jail-A` starting of `Jail-B` will determine with `actionstarted`, that is already done, and does not produce an error (so is the plain of you, resp. exactly that what you want).
The problem is, that stopping of some jail from both (e.g. Jail-A) will prevent banning in another still running jail (e.g. Jail-B).

BTW. Also after theoretically check/repair (restarting of action) it is still not good enough, because many bans are still in the list of BanManager, so fail2ban will not really ban a ticket by the new failures, it will just say "already banned", at least for the whole rest bantime, but it can be long (up to permanent) and newer version of fail2ban can self-employed increment it, also if it started with lower values...

That may be very-very annoying (regarding of backwards compatibility, upgrade to newer version, etc.)
At least a bold warning should be done there.
Would think about a little bit.

BTW. the way, that you described, imho, is comparable with example above (what I mean as Jail-A, is your manually operated iptables processing, and Jail-B would be in charge of fail2ban). As already said, imho, bad and evil.

**Comment by sebres** [comment] 2016-09-08 19:28
I've just realized, that we anyway already have another problem (regardless of new suggested parameter `actionstarted`):
- if during of executing of `actionban` or even `actionunban`, the `actioncheck` will whyever fail, the action will process situation "Invariant check failed. Trying to restore a sane environment".
- but what it really doing - stop/start, so it will theoretically remove all current bans (in this action only);
- but because the tickets are still in BanManager, in case of new failures from the same object, they will not be banned, because just "already banned" will happen (with return). So in this case, the "attack" will be some time unnoticed.

The solution would be to introduce a new ticket-flag "ticket.banned", which shows that is processed through all actions, so in case of "already banned" and `ticket.banned == True`, we should try to repeat all the actions for this ticket (at least several times, to prevent high-load in wrong environment).

**Comment by MT76** [comment] 2016-09-09 11:11
Well, you totally lost me here. Guess thats why you are a dev and im just an end-user.  :)
Still, it's good to see you are not ignoring this issue and even elaborating on it.
I wish you all the best in the continuation of f2b development. This project makes running a internet connected box much safer. Thanks a lot.
