### ISSUE TITLE
fail2ban crash with some fqdn

### ISSUE THREAD

**Issue by jas01** [fail2ban/fail2ban#1164] opened 2015-08-20 08:06 UTC
Hi,

When a attack come from a fqdn who has lot of ip-address we find fail2ban stuck. He don't really crash but until we remove the line inside the log file, fail2ban do nothing.

The fqdn is unassigned.infomir.com.ua, when you try a nslookup on this name you got...1362 ip-address.

Regards.

**Comment by sebres** [comment] 2015-09-07 23:26
Just a notice for me:
```python
set([i[4][0] for i in socket.getaddrinfo(dns, None, socket.AF_INET, 0, socket.IPPROTO_TCP)])
```

**Comment by sebres** [comment] 2015-09-08 09:35
fixed now in 0b5eacec0934238e86b88e02555f234bf932a968, as test case use following code, returns a large list of IPs...
```bash
python -c "from fail2ban.server.filter import DNSUtils; print(DNSUtils.dnsToIp('unassigned.infomir.com.ua'))"
```
@fail2ban/contributors, @fail2ban/developers if someone knows dns that resolves similar amounts of IPs, but persistent (in the long term stay so large), I will add a test case.

**Comment by sebres** [comment] 2015-09-08 18:13
PR #1184 not yet merged

**Comment by yarikoptic** [comment] 2015-09-08 18:29
@jas01 note that making fail2ban parse/react to logs with names instead of IPs is not recommended (although we still do allow it by default).  E.g. in this case -- banning 1000 of ips might be a bit too rushed and counter productive. Theoretically (didn't try to simulate attack from such a domain name) with current code (what was your version of fail2ban?)  it should simply not ban that IP since resolving it fails (at least for me) using socket.gethostbyname_ex:
```
2015-09-08 14:27:02,077 fail2ban.filter         [1498]: WARNING Unable to find a corresponding IP address for unassigned.infomir.com.ua: [Errno 1] Unknown host
```
So it would be interesting to discover what do you mean by "stuck"?  if you had fail2ban loglevel at DEBUG level -- what were the last log msgs?  was it stuck at busy 100%?  did fail2ban-client could still communicate, etc

**Comment by jas01** [comment] 2015-09-09 09:04
Le 08/09/2015 à 11:29:20-0700, Yaroslav Halchenko a écrit
> @jas01 note that making fail2ban parse/react to logs with names instead of IPs
> is not recommended (although we still do allow it by default). E.g. in this

Ok.

> case -- banning 1000 of ips might be a bit too rushed and counter productive.
> Theoretically (didn't try to simulate attack from such a domain name) with
> current code (what was your version of fail2ban?) it should simply not ban that
> IP since resolving it fails (at least for me) using socket.gethostbyname_ex:
>
> 2015-09-08 14:27:02,077 fail2ban.filter         [1498]: WARNING Unable to find a corresponding IP address for unassigned.infomir.com.ua: [Errno 1] Unknown host
>
> So it would be interesting to discover what do you mean by "stuck"? if you had
> fail2ban loglevel at DEBUG level -- what were the last log msgs? was it stuck
> at busy 100%? did fail2ban-client could still communicate, etc
>

Well, stuck mean nothing append until we get ride of the line with the
name.

The daemon still running but no rules was added anymore, no message in the
log either.

Regards.

**Comment by sebres** [comment] 2015-09-09 09:31
> The daemon still running but no rules was added anymore, no message in the log either.

All jails? or only this one?

**Comment by yarikoptic** [comment] 2015-09-09 12:14
@jas01 if it was persistent/reproducible, would you mind running
```
python -c "import socket; print(socket.gethostbyname_ex('unassigned.infomir.com.ua'))"
```
and (since we still don't know what system/fail2ban)
```
python3 -c "import socket; print(socket.gethostbyname_ex('unassigned.infomir.com.ua'))"
```
and pasting output from those two commands

**Comment by yarikoptic** [comment] 2015-09-09 12:15
most probably sebres nailed it down but would be very nice to confirm that stall happens due to gethostbyname_ex

**Closed** 2015-09-09 22:07 UTC
