### ISSUE TITLE
Regex: Condition direct behind <HOST> returns false

### ISSUE THREAD

**Issue by markierer** [fail2ban/fail2ban#1324] opened 2016-02-16 22:42 UTC
I use Ubuntu 14.04, Apache 2.4.7, Fail2Ban 0.9.3

In following case an entry with a port number behind the IP gets never detected. Because the first sign behind the HOST has to be a fixed sign and not a condition.
`_apache_error_client = \[.*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client HOST(:\d{1,5})?\]`

This works:
`[client HOST:(\d{1,5})?\]`

This is not working:
`[client HOST.*(\d{1,5})?\]`

**Comment by yarikoptic** [comment] 2016-02-16 23:42
Please give a sample log line

On February 16, 2016 5:42:47 PM EST, markierer <notifications@github.com> wrote:
> I use Ubuntu 14.04, Apache 2.4.7, Fail2Ban 0.9.3
>
>In following case an entry with a port number behind the IP gets never
>detected. Because the first sign behind the <HOST>has to be a fixed
>sign and not a condition.
>`_apache_error_client = \[.*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+
>\d+)?\])? \[client <HOST>(:\d{1,5})?\]`
>
>This works:
>`[client <HOST>:(\d{1,5})?\]`
>
>This is not working:
>`[client <HOST>.*(\d{1,5})?\]`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1324

-- 
Sent from a phone which beats iPhone.

**Comment by markierer** [comment] 2016-02-17 00:08
Sample log:

`[Mon Feb 15 21:30:46.448406 2016] [proxy_fcgi:error] [pid 8534:tid 140240894179072] [client 178.219.244.181:3125] AH01071: Got error 'Primary script unknown\n', referer: `

**Comment by markierer** [comment] 2016-02-17 00:14
I am not sure but as I can see in fail2ban.log even with the hack `[client HOST:(\d{1,5})?\]` the HOST inludes the port.

Example:
`2016-02-15 12:02:16,593 fail2ban.filter         [1220]: WARNING Unable to find a corresponding IP address for XX.XXX.XX.XXX**:60276**: [Errno -2] Name or service not known`

**Comment by sebres** [comment] 2016-02-17 09:00
The expression `\[client HOST(:\d{1,5})?\]` is alright (because whole part with port **including colon** is optional. BTW, still better would be non-capturing version `\[client <HOST>(?::\d{1,5})?\]`

Which filter you are using? Because I know no expression in any of our apache filters, that will match the sample line from your log excerpt. 
It is some own homegrown filter? Then I think you'll have a bug in your `failregex`.

To test your expression, execute:
```bash
fail2ban-regex -v  "log-line" /path/to/your/filter/apache-xxx.conf
# or
fail2ban-regex -v  "log-line" "your-failregex"
```
Using of option `-v` will allow to see the HOST was effectively matched.

If I extend apache-auth filter with an expression convenient your log-line, the host will be fine matched:
```bash
$test = "[Mon Feb 15 21:30:46.448406 2016] [proxy_fcgi:erro..."
fail2ban-regex -v "$test" ./config/filter.d/apache-auth.conf
```
Output:
```
Running tests
=============
Use   failregex filter file : apache-auth, basedir: ./config
Use      single line : [Mon Feb 15 21:30:46.448406 2016] [proxy_fcgi:erro...
Results
=======
Failregex: 1 total
|-  #) [# of hits] regular expression
......
|  14) [1] ^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(?::\d{1,5})?\] (AH01071: )?Got error '\S+ script unknown\b
|      178.219.244.181  Mon Feb 15 21:30:46 2016
......
Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
......
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

Thus I'll close the issue, reopen if I'm wrong.

**Closed by sebres** 2016-02-17 09:00 UTC

**Comment by markierer** [comment] 2016-02-17 10:20
I am absolutely sure that the original failregex is correct. That is no question. The problem is, this expression does not detect the log entry on my Ubuntu 14.04. Only if I fix the colon : , it works. 

I tested your example on my server, no success.

Here is my filter who works. You see I had to insert a dot-asteriks `^\[.*\ ]` at the beginning. With your example `^\[\]` it does not detect anything on my Ubuntu 14.04. And the second problem was the conditional expression before the HOST. I couldn't belive it myself.
`^\[.*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>\:\d{1,5}\] AH01071: Got error 'Primary script unknown\\n', referer:.*$`

Do I need a special library for regex? Is there a problem with older regex versions like in Ubuntu 14.04?

I double checked the fail2ban-regex Version : I have 0.9.3

Thanks for a hint.

**Comment by sebres** [comment] 2016-02-17 11:59
> I tested your example on my server, no success.

Output (best with `-v` argument)... "No success" is not meaningful and unproductive.

> You see I had to insert a dot-asteriks `^\[.*\ ]` at the beginning.

This suggests, that the fail2ban has not found a date-pattern or part of it (possibly for example the milliseconds) for this log-string. To test it you can specify a date-pattern argument `-d` by test:
`fail2ban-regex -d "(?:%a )?%b %d %H:%M:%S(?:\.%f)?(?: %Y)?" ...`
By the way, the template  "(?:%a )?%b %d %H:%M:%S(?:\.%f)?(?: %Y)?" is a default template of fail2ban (since 2014).

> Do I need a special library for regex? Is there a problem with older regex versions like in Ubuntu 14.04?

No. And I've already test different f2b-versions on several debians, including the ubuntu 14.04.

> I double checked the fail2ban-regex Version : I have 0.9.3

Are you sure, that the config (inside /etc/fail2ban) also 0.9.3 is?
You can download (or git checkout) current master from here and compare its `config` directory with yours. Or test with `fail2ban-regex` using this config path as prefix-path for the filter filename...

**Comment by markierer** [comment] 2016-02-17 12:25
Sorry, here is the call:
`master@server:~$ sudo fail2ban-regex -d "(?:%a )?%b %d %H:%M:%S(?:\.%f)?(?: %Y)?" ~/output /etc/fail2ban/filter.d/apache-proxy-fcgi.conf -v

Running tests
=============

Use      datepattern : (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
Use   failregex filter file : apache-proxy-fcgi, basedir: /etc/fail2ban
Use         log file : /home/administrator/output
Use         encoding : UTF-8


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] AH01071: Got error 'Primary script unknown\\n', referer:.*$
-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [4] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
-

Lines: 4 lines, 0 ignored, 0 matched, 4 missed [processed in 0.00 sec]
|- Missed line(s):
|  [Mon Feb 15 21:30:46.448406 2016] [proxy_fcgi:error] [pid 8534:tid 140240894179072] [client 178.219.244.181:3125] AH01071: Got error 'Primary script unknown\n', referer:
-
`

And here the file content of "output"
`[Mon Feb 15 12:02:13.022978 2016] [:error] [pid 6432:tid 140240910964480] [client XX.XXX.XX.XXX] ModSecurity: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/usr/share/modsecurity-crs/activated_r$
[Mon Feb 15 12:02:16.010478 2016] [test:error] [pid 6432:tid 140240798865152] [client XX.XXX.XX.XXX:999] client denied by server configuration: 
[Mon Feb 15 12:02:16.010478 2016] [test:error] [pid 6432:tid 140240798865152] [client XX.XXX.XX.XXX] AH01617: user john authentication failure for "hhh": Password Mismatch
[Mon Feb 15 21:30:46.448406 2016] [proxy_fcgi:error] [pid 8534:tid 140240894179072] [client 178.219.244.181:3125] AH01071: Got error 'Primary script unknown\n', referer:`

**Comment by markierer** [comment] 2016-02-17 12:34
The filter looks like that:

```
# Fail2Ban apache-proxy-fcgi.conf

[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# apache-common.local
before = apache-common.conf

[Definition]
failregex = ^%(_apache_error_client)s AH01071: Got error 'Primary script unknown\\n', referer:.*$
ignoreregex =
```

**Comment by markierer** [comment] 2016-02-17 16:00
Here is a complete test:

First step
`sudo fail2ban-regex ~/output /etc/fail2ban/filter.d/apache-test.conf -v --print-all-matched`

The filter apache-test.conf has following failregex:
`failregex = ^%(_apache_error_client)s.*$`

Output

```
Running tests
Use   failregex filter file : apache-test, basedir: /etc/fail2ban
Use         log file : /home/master/output
Use         encoding : UTF-8

Results
Failregex: 3 total
|-  #) [# of hits] regular expression
|   1) [3] ^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\].*$
|      82.220.39.209  Mon Feb 15 12:02:13 2016
|      82.220.39.209  Mon Feb 15 12:02:16 2016
|      1.2.3.4  Sat Jun 01 11:23:08 2013
Ignoreregex: 0 total
```

As you can see, the date is not the problem (6 hits). It was always the `<HOST>`.

```
Date template hits:
|- [# of hits] date format
|  [6] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
|  [0] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:Year|Year2) 24hour:Minute:Second
|  [0] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] Month/Day/Year:24hour:Minute:Second
|  [0] Month-Day-Year 24hour:Minute:Second\.Microseconds
|  [0] TAI64N
|  [0] Epoch
|  [0] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
|  [0] ^24hour:Minute:Second
|  [0] ^<Month/Day/Year2@24hour:Minute:Second>
|  [0] ^Year2MonthDay  ?24hour:Minute:Second
|  [0] MON Day, Year 12hour:Minute:Second AMPM
|  [0] ^MON-Day-Year2 24hour:Minute:Second
```

All lines without port are ok

```
Lines: 6 lines, 0 ignored, 3 matched, 3 missed [processed in 0.00 sec]
|- Matched line(s):
|  [Mon Feb 15 12:02:13.022978 2016] [test1:error] [pid 6432:tid 140240910964480] [client 82.220.39.209] sdssdsdsdsd
|  [Mon Feb 15 12:02:16.010478 2016] [test3:error] [pid 6432:tid 140240798865152] [client 82.220.39.209] sdsd
|  [Sat Jun 01 11:23:08 2013] [test5:error] [client 1.2.3.4] sd
```

All lines with a port are not ok

```
|- Missed line(s):
|  [Mon Feb 15 12:02:16.010478 2016] [test2:error] [pid 6432:tid 140240798865152] [client 82.220.39.209:999] sdsdsd
|  [Mon Feb 15 21:30:46.448406 2016] [test3:error] [pid 8534:tid 140240894179072] [client 178.219.244.181:3125] sds
|  [Mon Dec 23 07:49:01.981912 2013] [test6:error] [pid 3790] [client 204.232.202.107:46301] s
```

**Comment by sebres** [comment] 2016-02-17 16:16
Hm, very very strange...
BTW, expression `.*$` makes no sense (and can be removed)

Did you check your config (/etc/fail2ban)? I mean:
> Are you sure, that the config (inside /etc/fail2ban) also 0.9.3 is?
You can download (or git checkout) current master from here and compare its config directory with yours. 
Or just test with fail2ban-regex using this config path as prefix-path for the filter filename...

For example:
```
mkdir test & cd test
wget ...fail2ban-master.zip + unzip ... / or / git clone ...
cp /etc/fail2ban/filter.d/apache-test.conf ./config/filter.d/
fail2ban-regex ... ./config/filter.d/apache-test.conf
```

**Comment by markierer** [comment] 2016-02-17 16:24
MY FAULT:
I use the IPv6 patch... the colon gets filtered.
`regex = regex.replace("<HOST>", "(?:::f{4,6}:)?(?P<host>[\w\-.^_:]*\w)")`

Ok, maybe this case is important information for all with the IPv6 patch.

**Comment by yarikoptic** [comment] 2016-02-17 16:29
There is no official ipv6 patch so the issue is out of scope here I guess
