### ISSUE TITLE
actioncheck error stdout: b''

### ISSUE THREAD

**Issue by yodog** [fail2ban/fail2ban#1914] opened 2017-10-11 19:06 UTC
fail2ban version 0.9.7-1~nd16.04+1

new action with empty `actioncheck` works but

`actioncheck = <iptables> -n -L PREROUTING -t nat | grep -q '<ip>'`

fails with error

> 2017-10-11 15:41:50,533 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- stdout: b''
> 2017-10-11 15:41:50,533 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- stderr: b''
> 2017-10-11 15:41:50,533 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- returned 1
> 2017-10-11 15:41:50,533 fail2ban.CommandAction  [458]: ERROR   Invariant check failed. Trying to restore a sane environment
> 2017-10-11 15:41:50,742 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- stdout: b''
> 2017-10-11 15:41:50,743 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- stderr: b''
> 2017-10-11 15:41:50,743 fail2ban.action         [458]: ERROR   iptables -n -L PREROUTING -t nat | grep -q '<ip>' -- returned 1
> 2017-10-11 15:41:50,743 fail2ban.CommandAction  [458]: CRITICAL Unable to restore environment
> 

- below are the only 2 files created.
- all other files remain intact.
- had to add spaces in `< iptables>` and `< ip>` to post the code here, but there isn't any in my local file.

**/etc/fail2ban/action.d/iptables-loop.conf**

> [INCLUDES]
> before = iptables-common.conf
> 
> [Definition]
> actionstart =
> actionstop = < iptables> -F -t nat
> actioncheck = < iptables> -n -L PREROUTING -t nat | grep -q '< ip>'
> actionban = < iptables> -t nat -A PREROUTING -s <ip> -j DNAT --to-destination < ip>
> actionunban = < iptables> -t nat -D PREROUTING -s <ip> -j DNAT --to-destination < ip>
> 
> [Init]
> #empty section
> 

**/etc/fail2ban/jail.d/rasg.conf**

> [DEFAULT]
> banaction = iptables-loop
> bantime   = 600
> findtime  = 300
> maxretry  = 3
> ignoreip  = 127.0.0.1/8 192.168.25.0/24
> 
> [monit]
> enabled = true
> logpath = /var/log/monit.log
> 
> [nginx-http-auth]
> enabled = true
> 
> [nginx-botsearch]
> enabled = true
> 
> [sshd]
> enabled = true
> 
> 
> [vsftpd]
> enabled = true
>

**Comment by sebres** [comment] 2017-10-11 19:16
This is not a bug, rather a mistake in you configuration...
Closed as duplicate of  #1907, see this issue for possible solution...

**Closed by sebres** 2017-10-11 19:16 UTC

**Comment by yodog** [comment] 2017-10-11 20:17
alright, but why does it interpolate variables like `<iptables>`, `<chain>` and `<name>` ?

**/etc/fail2ban/action.d/iptables-multiport.conf**
`actioncheck = <iptables> -n -L <chain> | grep -q 'f2b-<name>[ \t]'`

**Comment by sebres** [comment] 2017-10-11 20:51
> alright, but why does it interpolate variables like `<iptables>`, `<chain>` and `<name>`?

For the same reason, that it does the `actionstart`...
Because they all are not ticket-related (like `<ip>`) but jail-related (resp. config-related) interpolations...

To cut a long story short - the sense of the `actioncheck` is to check the sane environment (and with not zero exit-code to try to restore it if expected). 
What the interpolation of `ip` should cause with `actioncheck`? If IP already banned? This would be a wrong case... And anyway not designed for such purposes (normally the IP should not be in the jail/chain/etc if it is not banned, and vice versa already in this "list" if already resp. still banned).

As already written in #1907 if nonetheless your action needs to check something IP-related - just do it directly in `actionban` as multi-line script (and do exit if ban not needed or just enclose ban process in `if ... fi` scope).
