### ISSUE TITLE
More meaningful/descriptive error messages when fail2ban fails to start.

### ISSUE THREAD

**Issue by klonos** [fail2ban/fail2ban#1246] opened 2015-11-05 22:59 UTC
I hope that this request is not a duplicate. I did search the issue queue for similar issues before filing this one.

So, here goes... I realize that fail2ban fails to start if a certain jail is enabled but the respective log(s) are not on the system, but I think that this is not ideal or graceful enough. Here's why... I started enabling jails for some of the services already running on my setup as well as some that I intended to setup soon(ish). This is the error I received when trying to restart fail2ban (Ubuntu - not super-guru myself mind you):

```
Job for fail2ban.service failed because the control process exited with error code.
See "systemctl status fail2ban.service" and "journalctl -xe" for details.
```

I had to revert my custom edits (just enabling certain jails - no other settings) in `/etc/fail2ban/jail.local` and restart to verify that the issue was with my edits. Then I had to loop between re-editing `jail.local`, enabling **one jail at a time** and restarting fail2ban service just to see if it would complain or not. Then move to enabling the next jail. This is a very tedious process as you understand.
1. Can we have a global switch or config option that ignores missing log files (jails for services intended to be installed at a later point) and allows fail2ban to start with perhaps warning messages in `fail2ban.log` instead of failing?
2. If not allowing jails for future services to be enabled, can we at least have it so that fail2ban tells us in its "failure to start" message the reason why? Something along the lines of:

`Job for fail2ban.service failed because the following jail configurations had issues:`
`- [jail1]: [jail1_logfile.log] logfile not found`
`- [jail2]: [jail2_logfile.log] logfile not found`
`- [jail2]: "enabled=ture" Not recognized. Misspell?`

Thank you for considering this.

**Comment by AlexisWilke** [comment] 2016-10-31 17:15
Did you try to check out the journal for the error(s)?

    journalctl -a -u fail2ban

Because it seems that the errors are okay in there... that is, at least it tells you where the error is.

**Comment by sebres** [comment] 2016-10-31 18:20
Just as link to #1379

**Comment by sebres** [comment] 2017-07-03 09:55
1. duplicate of #55
2. 0.10th version of fail2ban provides an error messages of each broken jail by starting.

**Closed by sebres** 2017-07-03 09:55 UTC
