### ISSUE TITLE
nftables set get deleted when restarting nftables

### ISSUE THREAD

**Issue by phonon112358** [fail2ban/fail2ban#2480] opened 2019-07-26 19:41 UTC
Hi,

I am currently using fail2ban 0.10.2 on Debian 10 (buster). A few days ago, I configured nftables (version 0.9.0-2) for the first time. 
The nftables action of Fail2ban works fine. However, when I restart nftables (via `systemctl restart nftables`, the f2b set is gone... 
Only a restart of Fail2ban afterwards recovers it.
The reason apparently is that nftables loads its rules from the `/etc/nftables.conf`. 
Is there any chance that one can configure the fail2ban action `nftables` in such a way that the set persists restarts of nftables service? (I was already thinking about something with `nft list ruleset > /etc/nftables.conf`, however this could cause issues regarding unban...)

**Comment by sebres** [comment] 2019-07-29 10:02
_Duplicate of #2313_

Well there are only three options:
- either you'd extend a dependency of fail2ban (to nftables), so a restart of nftables would cause a restart of fail2ban too (basically this is already fixed in 67247999ff9aeb38ef376f53faffcc4c74a0919f).
- or you'd make rules of nftables-action persistent (although I don't like it, but we can provide this like a some new action or controlling the persistence via some parameters);
- or you'd save all chains prefixed with f2b-* before a restart and restore those hereafter;

If I get close #980 the ban of already banned ticket can be repeated (so each action should be able to detect missing ban and then reban a flushed ticket).

**Closed by sebres** 2019-07-29 10:02 UTC

**Comment by phonon112358** [comment] 2019-07-29 10:59
Thanks a lot! 
I haven't seen https://github.com/fail2ban/fail2ban/issues/2313 before... sorry for the duplicate!
Your solution in https://github.com/fail2ban/fail2ban/commit/67247999ff9aeb38ef376f53faffcc4c74a0919f works very fine!
