### ISSUE TITLE
[FR]: sshd kex_exchange_identification: banner line too long

### ISSUE THREAD

**Issue by Daniel15** [fail2ban/fail2ban#3169] opened 2021-12-02 03:31 UTC
- Fail2Ban version:  0.11.2-2
- OS, including release name/version :  Debian Bullseye
- Filter: sshd
- OpenSSH version: OpenSSH_8.4p1 Debian-5

I recently experienced a DDoS attack to the SSH port on one of my servers, and the logs looked like this:

```
Dec  1 18:59:33 hostname sshd[1189573]: banner exchange: Connection from 59.91.122.57 port 34388: invalid format
Dec  1 18:59:33 hostname sshd[1189575]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189575]: banner exchange: Connection from 103.81.114.182 port 44105: invalid format
Dec  1 18:59:33 hostname sshd[1189580]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189580]: banner exchange: Connection from 103.88.221.194 port 45164: invalid format
Dec  1 18:59:33 hostname sshd[1189581]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189581]: banner exchange: Connection from 37.17.9.140 port 37374: invalid format
Dec  1 18:59:33 hostname sshd[1189582]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189582]: banner exchange: Connection from 46.109.118.225 port 44400: invalid format
Dec  1 18:59:33 hostname sshd[1189578]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189578]: banner exchange: Connection from 177.184.64.2 port 54840: invalid format
Dec  1 18:59:33 hostname sshd[1189583]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189583]: banner exchange: Connection from 90.162.115.178 port 58531: invalid format
Dec  1 18:59:33 hostname sshd[1189585]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:33 hostname sshd[1189585]: banner exchange: Connection from 85.29.129.140 port 43044: invalid format
Dec  1 18:59:34 hostname sshd[1189589]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189589]: banner exchange: Connection from 92.47.62.133 port 59435: invalid format
Dec  1 18:59:34 hostname sshd[1189584]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189584]: banner exchange: Connection from 129.18.180.224 port 32881: invalid format
Dec  1 18:59:34 hostname sshd[1189586]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189586]: banner exchange: Connection from 103.131.97.146 port 38587: invalid format
Dec  1 18:59:34 hostname sshd[1189588]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189588]: banner exchange: Connection from 37.191.94.56 port 46876: invalid format
Dec  1 18:59:34 hostname sshd[1189587]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189587]: banner exchange: Connection from 1.179.183.73 port 60945: invalid format
Dec  1 18:59:34 hostname sshd[1189590]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189590]: banner exchange: Connection from 60.217.64.237 port 41351: invalid format
Dec  1 18:59:34 hostname sshd[1189591]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 hostname sshd[1189591]: banner exchange: Connection from 103.221.254.12 port 47642: invalid format
```

fail2ban doesn't seem to catch these. It looks like it handles some `kex_exchange_identification` messages (eg. see 02525d7b6f96c2841c24c4dbfcfe14e4a3d1ef63 by @sebres) but not "banner line too long".

The combination of "kex_exchange_identification: banner line too long" followed by "Connection from xxx.xxx.xxx.xxx port xxxx: invalid format" should be sufficient to block these attempts. The regexes in `sshd.conf` are a bit scary to me though 😅

It looks like they were just sending junk data to the SSH port then keeping the connection open, so the disconnection didn't happen until later.

**Comment by sebres** [comment] 2021-12-02 16:09
Are there some other messages for the same ID (e. g. `sshd[1189591]`)? With other words if you filtered the excerpt by words like "banner", please provide the excerpt with ALL messages of the session.
Because I'm still unsure whether the issues on banner exchange stage can be considered as a failure even in ddos or aggressive mode.

In between you can simply extend your jail to consider them as a failure specifying your own regex:
```ini
[sshd]
failregex = %(known/failregex)s
            ^banner exchange: Connection from <ADDR><__on_port_opt>: invalid format
enabled = true
```

To test it with fail2ban-regex you can try:
```bash
fail2ban-regex /var/log/auth.log 'sshd[failregex="^banner exchange: Connection from <ADDR><__on_port_opt>: invalid format"]'
```

> The combination of "kex_exchange_identification: banner line too long" followed by "Connection from xxx.xxx.xxx.xxx port xxxx: invalid format" should be sufficient to block these attempts.

Related to source code they can be "banner line too long", "banner line contains invalid characters", etc. I guess in all that cases it can simply react on 2nd message with "invalid format".

**Comment by Daniel15** [comment] 2021-12-02 19:46
> Are there some other messages for the same ID (e. g. sshd[1189591])?

Nope. The log snippet I posted above was all of the lines in the log at the time. I just double-checked for `1189591`:
```
daniel@lux01:~$ sudo grep "1189591" /var/log/auth.log
Dec  1 18:59:34 lux01 sshd[1189591]: error: kex_exchange_identification: banner line too long
Dec  1 18:59:34 lux01 sshd[1189591]: banner exchange: Connection from 103.221.254.12 port 47642: invalid format
```

The regex you provided seems to work great. Thanks!

**Comment by Daniel15** [comment] 2021-12-07 02:17
@sebres So the regex you provided worked great when testing it with `fail2ban-regex`, but it didn't actually block another attack today.

Here's an example log snippet:
```
Dec  6 17:58:39 lux01 sshd[1707522]: banner exchange: Connection from 218.24.16.198 port 33323: invalid format
Dec  6 17:58:39 lux01 sshd[1707524]: banner exchange: Connection from 45.118.112.78 port 32959: invalid format
Dec  6 17:58:39 lux01 sshd[1707532]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707530]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707530]: banner exchange: Connection from 213.32.252.134 port 51935: invalid format
Dec  6 17:58:39 lux01 sshd[1707532]: banner exchange: Connection from 88.198.189.60 port 58413: invalid format
Dec  6 17:58:39 lux01 sshd[1707531]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707531]: banner exchange: Connection from 82.207.20.247 port 39410: invalid format
Dec  6 17:58:39 lux01 sshd[1707525]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707525]: banner exchange: Connection from 103.15.245.18 port 52213: invalid format
Dec  6 17:58:39 lux01 sshd[1707461]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707461]: banner exchange: Connection from 117.242.39.208 port 59736: invalid format
Dec  6 17:58:39 lux01 sshd[1707523]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707536]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:39 lux01 sshd[1707523]: banner exchange: Connection from 202.40.177.94 port 39965: invalid format
Dec  6 17:58:39 lux01 sshd[1707536]: banner exchange: Connection from 188.112.39.231 port 48883: invalid format
Dec  6 17:58:39 lux01 sshd[1707534]: error: kex_exchange_identification: read: Connection reset by peer
Dec  6 17:58:39 lux01 sshd[1707534]: Connection reset by 82.200.55.38 port 33856
Dec  6 17:58:40 lux01 sshd[1707541]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707541]: banner exchange: Connection from 213.240.224.24 port 34640: invalid format
Dec  6 17:58:40 lux01 sshd[1707540]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:40 lux01 sshd[1707540]: Connection closed by 188.166.104.152 port 41093
Dec  6 17:58:40 lux01 sshd[1707544]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707544]: banner exchange: Connection from 194.44.38.111 port 54806: invalid format
Dec  6 17:58:40 lux01 sshd[1707533]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707533]: banner exchange: Connection from 168.232.60.242 port 46116: invalid format
Dec  6 17:58:40 lux01 sshd[1707538]: error: kex_exchange_identification: read: Connection reset by peer
Dec  6 17:58:40 lux01 sshd[1707538]: Connection reset by 197.248.249.147 port 57218
Dec  6 17:58:40 lux01 sshd[1707553]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707553]: banner exchange: Connection from 109.198.1.197 port 50606: invalid format
Dec  6 17:58:40 lux01 sshd[1707537]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707537]: banner exchange: Connection from 131.161.177.62 port 33345: invalid format
Dec  6 17:58:40 lux01 sshd[1707557]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707557]: banner exchange: Connection from 83.44.73.57 port 39848: invalid format
Dec  6 17:58:40 lux01 sshd[1707555]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707555]: banner exchange: Connection from 94.158.53.197 port 47249: invalid format
Dec  6 17:58:40 lux01 sshd[1707543]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707543]: banner exchange: Connection from 103.251.225.16 port 50448: invalid format
Dec  6 17:58:40 lux01 sshd[1707539]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707539]: banner exchange: Connection from 218.24.16.198 port 33190: invalid format
Dec  6 17:58:40 lux01 sshd[1707556]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707556]: banner exchange: Connection from 103.88.221.194 port 38805: invalid format
Dec  6 17:58:40 lux01 sshd[1707554]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707554]: banner exchange: Connection from 36.37.71.84 port 46766: invalid format
Dec  6 17:58:40 lux01 sshd[1707542]: error: kex_exchange_identification: banner line too long
Dec  6 17:58:40 lux01 sshd[1707542]: banner exchange: Connection from 90.150.172.238 port 42206: invalid format
Dec  6 17:58:40 lux01 sshd[1707559]: error: kex_exchange_identification: read: Connection reset by peer
Dec  6 17:58:40 lux01 sshd[1707559]: Connection reset by 85.217.192.39 port 52144
Dec  6 17:58:40 lux01 sshd[1707563]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:40 lux01 sshd[1707562]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:40 lux01 sshd[1707563]: Connection closed by 192.236.192.65 port 41115
Dec  6 17:58:40 lux01 sshd[1707562]: Connection closed by 192.236.192.65 port 42221
Dec  6 17:58:40 lux01 sshd[1707560]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:40 lux01 sshd[1707560]: Connection closed by 103.174.40.123 port 38460
Dec  6 17:58:40 lux01 sshd[1707561]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:40 lux01 sshd[1707561]: Connection closed by 103.174.40.125 port 53521
Dec  6 17:58:41 lux01 sshd[1707565]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:41 lux01 sshd[1707565]: Connection closed by 103.174.40.121 port 40748
Dec  6 17:58:41 lux01 sshd[1707567]: error: kex_exchange_identification: Connection closed by remote host
Dec  6 17:58:41 lux01 sshd[1707567]: Connection closed by 103.174.40.124 port 46145
```

Some users were banned, but the ones with "banner line too long" didn't seem to be.
```
daniel@lux01:~$ sudo cat /var/log/fail2ban.log | grep 194.44.38.111
daniel@lux01:~$
```

This is my config in `/etc/fail2ban/jail.d/ssh.local`:
```
[sshd]
mode = aggressive
failregex = %(known/failregex)s
            ^banner exchange: Connection from <ADDR><__on_port_opt>: invalid format
banaction = %(banaction_allports)s
maxretry = 5
bantime = 14400
findtime = 14400
```

fail2ban *seems* to be reading the config, as the bantime and findtime match in the startup log:
```
2021-12-06 18:14:12,080 fail2ban.server         [1708779]: INFO    Starting Fail2ban v0.11.2
2021-12-06 18:14:12,080 fail2ban.observer       [1708779]: INFO    Observer start...
2021-12-06 18:14:12,084 fail2ban.database       [1708779]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2021-12-06 18:14:12,086 fail2ban.jail           [1708779]: INFO    Creating new jail 'sshd'
2021-12-06 18:14:12,105 fail2ban.jail           [1708779]: INFO    Jail 'sshd' uses pyinotify {}
2021-12-06 18:14:12,108 fail2ban.jail           [1708779]: INFO    Initiated 'pyinotify' backend
2021-12-06 18:14:12,110 fail2ban.filter         [1708779]: INFO      maxLines: 1
2021-12-06 18:14:12,132 fail2ban.filter         [1708779]: INFO      maxRetry: 5
2021-12-06 18:14:12,132 fail2ban.filter         [1708779]: INFO      findtime: 14400
2021-12-06 18:14:12,132 fail2ban.actions        [1708779]: INFO      banTime: 14400
2021-12-06 18:14:12,132 fail2ban.filter         [1708779]: INFO      encoding: UTF-8
2021-12-06 18:14:12,133 fail2ban.filter         [1708779]: INFO    Added logfile: '/var/log/auth.log' (pos = 1216172, hash = f24465b4556894861f072f293673cac5ae092691)
2021-12-06 18:14:12,144 fail2ban.jail           [1708779]: INFO    Jail 'sshd' started
```

Any ideas?

**Comment by sebres** [comment] 2021-12-07 09:56
After restart (why? you could simply reload the config with `fail2ban-client reload`) fail2ban continues from last known log position, so it would not "rescan" the old (already processed) entries.
May be this is the reason (since restarted at 18:14, but you show the log excerpt from 17:58).

Oh wait, it can be my fault, I didn't think about interpolation of `<__on_port_opt>` - it is a parameter of filter and substitution  wouldn't work in jail (only in filter.d/sshd.local or if one supply failregex as parameter to the filter). So I corrected my answer above (`<__on_port_opt>` is replaced by its substitution `(?: (?:port \d+|on \S+)){0,2}`).
Sorry for confusion.

**Comment by Daniel15** [comment] 2021-12-08 19:06
> . So I corrected my answer above (<__on_port_opt> is replaced by its substitution (?: (?:port \d+|on \S+)){0,2}).

Thanks. This seems to be working :)

**Comment by sebres** [comment] 2022-01-18 15:22
fixed in 8bf15db688ac0f95f6f1489947ee00825340b23e for 0.10, will be merged in 0.11 and 1.0

**Closed** 2022-01-18 15:23 UTC
Labels: filter-request

**Comment by SomePersonSomeWhereInTheWorld** [comment] 2024-04-04 13:39
Can the reg ex be expanded to include these?
```
Mar 31 00:36:17 ourserver sshd[3169786]: error: kex_exchange_identification: client sent invalid protocol identifier "MGLNDD_128.59.124.103_22"
Mar 31 00:36:17 ourserver sshd[3169786]: banner exchange: Connection from 198.199.117.134 port 32944: invalid format
```

Notice `MGLNDD`. There is a [thread over as SANS](https://isc.sans.edu/diary/MGLNDD+Scans/28458) that discusses this as a scan from Stretchoid [as well as that](https://isc.sans.edu/diary/Update+MGLNDD+Scans/30686)  "RIPE Atlas employs a global network of probes that measure Internet connectivity and reachability." A user is maintaining an IP list [here](https://github.com/datacenters-network/security/blob/main/stretchoid.txt).

**Comment by Daniel15** [comment] 2024-04-04 15:21
@SomePersonSomeWhereInTheWorld Please open a new issue instead of commenting on an old one.

**Comment by sebres** [comment] 2024-04-04 16:11
@SomePersonSomeWhereInTheWorld, [current stock sshd-filter](https://github.com/fail2ban/fail2ban/blob/921d9a5a405d4cedc0f266b51a4ac133b72b6552/config/filter.d/sshd.conf#L74) will match both messages in `ddos` or `aggressive` mode. (Mode `aggressive` is for everything what doesn't belong to authentication concerns).
If you use new filter, just set `mode = aggressive` in sshd jail, otherwise simply update it (if fail2ban version >= 0.11.2/0.10.6, otherwise patch your filter manually or add the REs to the jail)...
See ab3a7fc6d2ea01cd4a17607398d151bb5fe2e63b, bf689c27b833d4cafc6ce34ada214cd4df2d7d86 and 4f679a56e0d564bafa7781938f8d28bb69fd96af
To check whether they match, use `fail2ban-regex ... 'sshd[mode=aggressive]'`

@Daniel15 
> Please open a new issue instead of commenting on an old one.

Why? The issue is almost about the same thing... and for us it doesn't matter old or not, since it'd appear in GH-notifications.
If you want no notifications about this issue anymore, just unsubscribe it (large button in right issue-area).

**Comment by SomePersonSomeWhereInTheWorld** [comment] 2024-04-04 17:23
> @SomePersonSomeWhereInTheWorld, [current stock sshd-filter](https://github.com/fail2ban/fail2ban/blob/921d9a5a405d4cedc0f266b51a4ac133b72b6552/config/filter.d/sshd.conf#L74) will match both messages in `ddos` or `aggressive` mode. (Mode `aggressive` is for everything what doesn't belong to authentication concerns only).

Thanks I can confirm  `mode=aggressive` works.
