### ISSUE TITLE
Option to reset banned IP on reload

### ISSUE THREAD

**Issue by basti12203** [fail2ban/fail2ban#2459] opened 2019-07-04 20:24 UTC
I use fail2ban in combination with ferm. As I can see fail2ban reset banned ip's only (?) on restart.
At the moment i have a "race condition". I restart fail2ban before I reload or restart ferm, this is done by ferm with a pre hook to inform fail2ban to iptables changes. With ferm i do some manually inserts in the fail2ban chain (f2b-sshd for example).
When I restart fail2ban as post hook my manually inserts are lost.

So it would be nice to add an option to fail2ban to reload already banned ips into the chains without restarting (fail2ban reload --all-ip)
So I can:
pre hook -> restart fail2ban
restart ferm
post hook -> load banned ips into chains

Best Regards

**Comment by sebres** [comment] 2019-07-08 10:57
> So it would be nice to add an option to fail2ban to reload already banned ips into the chains without restarting

Which primary goal is to do that?
- if it is just a possibility to reban all IPs, this is a duplicate of #1680;
- if you need just a restore all active bans after restart of fail2ban - then it is already the case (>= v.0.9), if database is not disabled;
- if you're looking for reload option (e. g. reload configuration without restart), there is already such option of `fail2ban-client` since v.0.10;
- if you need to restore your manually (via ferm) inserted rules to fail2ban chains, then it is impossible, because this tickets are not under fail2ban control. Furthermore since 0.10 some actions create the chains on demand (by first ban), so if no IPs get restored after restart, no ...

Instead of manual changes of fail2ban chains, rather use something like that to force fail2ban add or remove IP to fail2ban chains.
```bash
fail2ban-client set sshd banip <ip>
fail2ban-client set sshd unbanip <ip>
```

**Closed by sebres** 2019-07-08 10:57 UTC
Labels: closed-as-duplicate

**Comment by basti122303** [comment] 2019-07-08 11:12
I'm looking for an option to restore all active bans after reload of fail2ban.

**Comment by sebres** [comment] 2019-07-08 11:18
But it happens automatically if fail2ban gots restarted.
And if you use reload instead of restart - the IPs are still banned, so you don't need to restore it.
