### ISSUE TITLE
Listen on a network port and accept command from remote client

### ISSUE THREAD

**Issue by iredmail** [fail2ban/fail2ban#1957] opened 2017-11-04 14:20 UTC
Dear developers,

We run Fail2ban behind HAProxy in mail server cluster, the situation is the backend cluster nodes successfully bans bad clients locally, but banned IP was not sent to Fail2ban on HAProxy servers.

It will be very helpful if Fail2ban can listen on a network port and accept commands (at least `banip` and `unbanip`) from remote client, either RESTful API or a custom socket-based protocol is ok.

Currently we have a simple Python RESTful API server (with custom action to run `curl` and post banned/unbanned ip to API server) to handle this, although it works fine, but it will be the best solution to make Fail2ban listening on a network port and access commands from remote clients directly, or even able to sync ban/unban status with other servers.

**Comment by sebres** [comment] 2017-11-05 18:41
duplicate of #881

**Closed by sebres** 2017-11-05 18:41 UTC
Labels: closed-as-duplicate
