### ISSUE TITLE
Can anyone share working snippet of jail.local and apache log format 

### ISSUE THREAD

**Issue by Akshay-Hegde** [fail2ban/fail2ban#2414] opened 2019-05-04 19:53 UTC
I am using Centos 7, apache 2.4.6 I installed fail2ban successfully, unfortunately I am missing something because of which fail2ban not blocking even when there is genuine attack 

I suspect logformat of apache probably the case. Can someone here share standard log format required by the fail2ban to match regex in base filters.d folder. Also if possible one example. (Jail, filter.conf and logformat)

Rest of all seems like OK, including iptable rules, and ipset list also listing jails configured

**Comment by sebres** [comment] 2019-05-05 10:32
Looks like a duplicate of #2378.
Please note this is not a place for howto's (this is actually a developer repository).

**Closed by sebres** 2019-05-05 10:32 UTC
Labels: closed-as-duplicate
