### ISSUE TITLE
With UFW >= 0.36 the 'insert' should better be a 'prepend' 

### ISSUE THREAD

**Issue by mdavids** [fail2ban/fail2ban#2364] opened 2019-03-03 10:56 UTC
With regard to:
https://github.com/fail2ban/fail2ban/blob/324f0ed7cc9233c992313586d475cfa9fa52df47/config/action.d/ufw.conf#L17

Please see: https://bugs.launchpad.net/ubuntu/+source/ufw/+bug/1368411
Inserting an IPv6 rule failed and the solution is a new UFW feature named 'prepend' in UFW 0.36.

May I also suggest to extend the UFW command with a comment? Something like 'added by fai2ban'

Speaking of IPv6; it would also be great to have some kind of a configurable option that blocks an entire IPv6 subnet, like a /48, /56 or /64 (this per default?) instead of the current default /128.

**Comment by sebres** [comment] 2019-03-04 10:36
closed as duplicate of #2331

**Closed by sebres** 2019-03-04 10:36 UTC
Labels: closed-as-duplicate
