### ISSUE TITLE
actionstart_on_demand = false no longer working for IPv6

### ISSUE THREAD

**Issue by KimBrodowski** [fail2ban/fail2ban#2804] opened 2020-08-11 09:21 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.11.1
- OS, including release name/version: Debian 11 (Bullseye)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

It looks like actionstart_on_demand is no longer working for IPv6. On Debian 10 (Buster) running Fail2Ban v0.10.2 the same configuration appears to work correctly.

```
bullseye # ipset list | grep -E 'f2b-ssh6?$'
Name: f2b-ssh
```

```
buster # ipset list | grep -E 'f2b-ssh6?$'
Name: f2b-ssh
Name: f2b-ssh6
```

#### Steps to reproduce

1. Apply configuration changes that make use of actionstart_on_demand and support IPv6 (examples see below, we use ipsets here)
2. Start the fail2ban service.
3. Dump ipsets / iptables chains.

#### Expected behavior

Both IPv4 and IPv6 ipsets are created.

#### Observed behavior

IPv6 ipsets are not created.

### Configuration, dump and another helpful excerpts

/etc/fail2ban/action.d/iserv-ipset.conf:
```
[INCLUDES]

before = iptables-common.conf

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = ipset create <ipmset> hash:ip timeout <default-timeout><familyopt> -exist
actionstart_on_demand = false

# Option:  actionflush
# Notes.:  command executed once to flush IPS, by shutdown (resp. by stop of the jail or this action)
# Values:  CMD
#
actionflush = ipset flush <ipmset>

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop = ipset flush <ipmset>


# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = ipset add <ipmset> <ip> timeout <bantime> -exist

actionprolong = %(actionban)s

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = ipset del <ipmset> <ip> -exist

[Init]

# Option: default-timeout
# Notes:  specifies default timeout in seconds (handled default ipset timeout only)
# Values:  [ NUM ]  Default: 600

default-timeout = 600

ipmset = f2b-<name>
familyopt =

[Init?family=inet6]

ipmset = f2b-<name>6
familyopt = <sp>family inet6
```

#### Any customizations done to /etc/fail2ban/ configuration

Relevant section of /etc/fail2ban/jail.conf
```
[DEFAULT]
ignoreip = 127.0.0.1
bantime  = 600
findtime = 600
backend  = auto
enabled  = true
usedns   = no

#
# Block hackers for 10 minutes if they exceed 10 login attempts in 10 minutes
#
[ssh]
logpath  = /var/log/auth.log
filter   = sshd
action   = iserv-ipset[name=ssh, bantime=600]
maxretry = 10
```

The SSH jail is enabled.

**Comment by sebres** [comment] 2020-08-11 10:07
Seems to be fixed in current 0.10/0.11 branch - I cannot reproduce it anymore...

```ini
[sshd]
enabled = true
banaction = iptables-ipset-proto6[actionstart_on_demand=false]
```
```bash
# fail2ban-client start
Server ready
# ipset list | grep -E 'f2b-sshd6?$'
Name: f2b-sshd
Name: f2b-sshd6
```

**Comment by KimBrodowski** [comment] 2020-08-11 12:58
I've installed Fail2Ban v1.0.1.dev1 and this is still broken for me. The IPv6 ipsets did eventually appear (despite no bans being placed). I don't know why or how. After the system initially boots this is broken for me though, which causes firewall rules not to be applied. Restarting the daemon doesn't fix it for me.

**Comment by KimBrodowski** [comment] 2020-08-11 13:02
Mhh. Seems to be that setting `banaction` instead of `action` seems to make a difference.

**Comment by sebres** [comment] 2020-08-11 14:19
>  Seems like setting banaction instead of action makes a difference somehow.

Well default `action` interpolates `action_`, so would substitute `banaction` with several parameters needed by default actions (like name, port, protocol, chain, etc), see 
https://github.com/fail2ban/fail2ban/blob/15882002749f1811820d638a1178fd267f7272a2/config/jail.conf#L212

If you overwrite `action`, you've to supply all the parameters by yourself. 
Anyway you can check in the dump of `fail2ban-client -d | grep ssh` whereas all parameters required by your action are set or interpolated properly.

> O.K. no idea what is going on here. I can't see any pattern.

But is it still wrong? Or self repaired? :)

Also note that after restart the jail would restore active (banned) IPs. so also if action started on demand. it can start it for both families if active bans for IPv4 and IPv6 are available after restart.

**Comment by KimBrodowski** [comment] 2020-08-14 06:43
> But is it still wrong? Or self repaired? :)

This is still broken for me. Right now I don't have time to look into this a lot further, since Debian Bullseye isn't a priority for us right now and the Coronavirus pandemic has delayed other important things.

My test system is on an isolated network and shouldn't have any bans whatsoever.

I can provide you with my full configuration if you want to give it a shot. IPv4 works as expected, IPv6 only on Fail2Ban v0.10.2 (Debian Buster).

**Comment by KimBrodowski** [comment] 2020-08-14 07:19
What worked for me is starting the system, leaving it as is for a while and then restarting fail2ban. This is really odd. Not really reproducible either. I wondered if it just takes a while for the IPv6 ipsets to show up, but I don't think I've ever seen them appear without the f2b service being restarted.

I also wondered if it had anything to do with kernel modules not being loaded, but there are no error messages etc. and manually creating IPv6 ipsets earlier doesn't seem to solve it.

**Comment by sebres** [comment] 2020-08-17 09:50
> I can provide you with my full configuration if you want to give it a shot.

You can try to start it with some single jail (e. g. like sshd in https://github.com/fail2ban/fail2ban/issues/2804#issuecomment-671856008) and loglevel DEBUG (in fail2ban.local) and provide a fail2ban.log excerpt with start commands.
Normally you'd see there 2 blocks with commands executed on start (once for IPv4 and IPv6).

**Comment by KimBrodowski** [comment] 2021-01-18 20:53
I had some time to look into this now. The issue is https://github.com/fail2ban/fail2ban/blob/960e30cfcdae7e2c81f74046efdbff1606f9774e/fail2ban/server/ipdns.py#L208.

Since fail2ban is part of our firewall it is started before networking, meaning no IPv6 address is assigned to any interface. This is also why later restarts fix the issue.

IMHO checking for IPv6 addresses on interfaces to determine whether to setup jails doesn't make much sense to me. Hardcoding the return value of `IPv6IsAllowed()` to `True` fixes the bug for us.

At the very least this should be configurable behaviour.

**Comment by sebres** [comment] 2021-01-18 21:11
> Since fail2ban is part of our firewall it is started before networking

Hmm... I'm still not convinced it is the right way - for instance how it should do things like DNS lookup (ignoreip, etc) or similar IP/network related stuff without the interfaces (so I mean before they are initialized)?

> At the very least this should be configurable behaviour.

Well, it is possible (conditionally, because some things are called before config is fully loaded or substituted)... 
But everything else what would need a current IP, hostname etc on init/load phase too?..

Anyway if you can provide a PR, I'm curious how it looks.

**Comment by KimBrodowski** [comment] 2021-01-26 17:18
> Anyway if you can provide a PR, I'm curious how it looks.

I don't actually "speak" Python. Syntax is of course similar enough to read and understand, modifying a line here and there doesn't do much harm, but I'm not sure I'm the right person to file PRs without ever having written even the most simple Python application.

> [...] how it should do things like DNS lookup (ignoreip, etc) or similar IP/network related stuff without the interfaces (so I mean before they are initialized)?

Local name resolution etc. works at that point. Of course not every feature can. However why would that be any different for IPv4? IPv4 appears to work just fine pre network-online.target. Why add special handling for IPv6 in the first place?

This will lead to situations where servers are unprotected if IPv6 networking comes online later, for example due to late configuration. We have setups like that on dial-in lines. fail2ban will of course kick in eventually once the first ban is due, but existing bans will not be applied. This also make setting `actionstart_on_demand = false` rather pointless.

Since I personally consider fail2ban more of a mechanism to keep log files clean than actually improving security significantly I don't believe this is a show stopper, but at least it's somewhat odd.

**Comment by sebres** [comment] 2021-01-26 18:40
> However why would that be any different for IPv4?
> Why add special handling for IPv6 in the first place?

IPv4 was from scratch a part of fail2ban handling.
And this is nothing about first place, there are just (historical or probably active) systems without IPv6, so this check is implemented to don't bother such systems at all.

And it is not configurable at the moment, because partially fail2ban-client reading such a configuration must already know whether it has IPv6 or not (e. g. `ignoreself` option can obtain new own addresses of IPv6 family).

> This will lead to situations where servers are unprotected if IPv6 networking comes online later, for example due to late configuration.

I'm interesting to listen, how it is intended to work for such a systems? Let say you have some host/container without IPv6 now. Before you enable IPv6, you must don't forget to edit fail2ban-configuration in order to enable IPv6 there, and hereafter must reload fail2ban anyway (changes on fail2ban configuration expecting at least a reload).
I don't yet convinced that put such a mark to configuration is a proper way.

And if you have hard coded IPv6IsAllowed to always return True, how it works on systems where IPv6 is not yet enabled, since you said it comes later? Does not this cause a boom :boom:?

What we can do probably, is to recognize that if fail2ban gets (re)loaded, so it would reset `IPv6IsAllowed()` on reload too.
Normally one is expecting to install certain stuff like net-filter (ip6tables etc) after one enabled IPv6, so I think one should notify fail2ban that IPv6 got enabled now, no matter via config (then reload is needed) or via `fail2ban-client` (no idea at the moment whether some info must be invalidated in fail2ban internals).
If you mean a reload (not restart) would be enough, then it is simply to implement.

**Comment by sebres** [comment] 2021-01-26 19:38
As I made a review, I noticed that current implementation of IPv6IsAllowed simply retards the proper recognition up to 5 minutes (due to internal caches of DNSUtils).
I think 3700a9e5230822d33b2377afed9b6de38676e564 will fix this behavior now - it implements invalidation of caches by reload (`fail2ban-client reload`), so should affect IPv6IsAllowed immediately.
Would it be enough for you and if so, can you please test this patch?

**Comment by KimBrodowski** [comment] 2021-01-26 21:43
I'm not sure how this is supposed to help in our case. There is no IPv6 address when fail2ban is started. There is no IPv4 address either for that matter.

We start fail2ban BEFORE network-online.target.

If it rains outside I open the umbrella BEFORE I step into the rain, not afterwards.

This is not the default setup, I'm still very much aware of that. fail2ban doesn't need any networking to do its job in our setup. It is just supposed to create ipsets and fill them with banned IPs. Because it fails to do so other services that rely on fail2ban creating ipsets fail. This is exclusively a problem with IPv6, because for some reason a check is in place to make sure at least one IPv6 address is assigned. The same check doesn't appear to be present for IPv4.

> And if you have hard coded IPv6IsAllowed to always return True, how it works on systems where IPv6 is not yet enabled, since you said it comes later? Does not this cause a boom boom?

No. Why would it? What's supposed to go wrong? Putting IPs into ipsets doesn't require any kind of external connection. It's not like the system doesn't support IPv6, it just hasn't been assigned an address yet.

> Before you enable IPv6, you must don't forget to edit fail2ban-configuration in order to enable IPv6 there, and hereafter must reload fail2ban anyway

IPv6 is enabled and configured, both in e.g. /etc/network/interfaces and fail2ban. The system simply hasn't been assigned any addresses yet. That happens a few moments later, once the firewall - which relies on fail2ban ipsets - has been started.

It is correct that in such a scenario exceptions for the system's own IP addresses wouldn't be applied. In order to make that happen you'd need to reload or restart fail2ban once the network interfaces are fully up and ready.

**Comment by sebres** [comment] 2021-01-27 10:29
Understood (missed the point with start before network resp. assumed only the case enable IPv6 later).
OK, I'll try to implement such an option for fail2ban.conf.

**Comment by KimBrodowski** [comment] 2021-01-27 15:46
Thank you very much for your work and patience!

**Comment by sebres** [comment] 2021-01-27 16:11
You are welcome...
So c75748c5d3b4de1e51318e1db4a5b72519c47c1f provides new option `allowipv6` which can be set in `/etc/fail2ban/fail2ban.local` (or `fail2ban.conf`) in default or definition sections:
```ini
[Definition]
# set it to yes, on, true of 1 to force fail2ban to acknowledge IPv6 is present:
allowipv6 = yes
```

**Closed** 2021-02-03 13:59 UTC
Labels: implemented-in-newer-version

**Comment by sebres** [comment] 2021-02-03 14:03
c75748c5d3b4de1e51318e1db4a5b72519c47c1f (and 3700a9e5230822d33b2377afed9b6de38676e564) are merged now in all major branches.
