### ISSUE TITLE
email announcing rule is up is not working properly

### ISSUE THREAD

**Issue by treveradams** [fail2ban/fail2ban#1898] opened 2017-09-22 17:57 UTC
Emails saying the rules are up are having problems in the subject `[Fail2Ban] prosody: started  on <fq-hostname>` (yes, the prosody rule is mine, but it is happening on all rules, not sure why yet). With 0.9x it works. It is from the actionstart line in actions.d/mail.conf. Why it doesn't work, I am not sure.

**Comment by sebres** [comment] 2017-09-29 19:23
Can you provide more info as just "does not work"? 
Can you provide which version exactly used?
Please, take a look at our issue-template...

Closed as long as no further info provided...

**Closed by sebres** 2017-09-29 19:23 UTC

**Comment by treveradams** [comment] 2017-09-29 23:01
[Fail2Ban] prosody: started on <fq-hostname> should not be "<fq-hostname>", it should have the host name.

/etc/fail2ban/action.d/etc/fail2ban/action.d/mail.conf is the place that this comes from in actionstart.

fail2ban-0.10.0-1.fc27.noarch
fail2ban-firewalld-0.10.0-1.fc27.noarch
fail2ban-sendmail-0.10.0-1.fc27.noarch
fail2ban-server-0.10.0-1.fc27.noarch
fail2ban-systemd-0.10.0-1.fc27.noarch

**Comment by sebres** [comment] 2017-10-02 08:40
duplicate of #1859
Already fixed in d1de20dd4181c9506c29d218c20b16fc7239cf38.
