### ISSUE TITLE
fail2ban with systemd backend may fill FS / hang system after reload

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#991] opened 2015-03-18 04:26 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1202979

Description of problem:
After automatic "systemctl reload fail2ban" the fail2ban logfile sometines
grows and fills the FS. The logfile only contains:

2015-03-16 23:01:25,159 fail2ban.server.asyncserver[879]: WARNING Socket error
2015-03-16 23:01:25,159 fail2ban.server.asyncserver[879]: WARNING Socket error
2015-03-16 23:01:25,159 fail2ban.server.asyncserver[879]: WARNING Socket error
2015-03-16 23:01:25,159 fail2ban.server.asyncserver[879]: WARNING Socket error
2015-03-16 23:01:25,159 fail2ban.server.asyncserver[879]: WARNING Socket error

etc. etc.

Version-Release number of selected component (if applicable):
fail2ban-0.9-2.fc20.noarch

How reproducible:
Seems to take time, or specific systems. The cause is clear though, see below.

Steps to Reproduce:
1. enable en start fail2ban
2. do a nightly (cron?) "systemctl reload fail2ban"
3. And wait...

Actual results:
FS full, system probably needs a reboot to make it responsive.

Expected results:
Happy systemn, no impact at all.

Additional info:
The probable cause is this:
- fail2ban opens all journal files in /var/log/journal for each jail.
- the number of log files in /var/log/journal grows over time (depending on
  settings)
- fail2ban has a (soft) ulimit of 1024 open files
- at a certain point (during reload?) fail2ban hits the ulimit
- and starts flooding its log file

**Comment by sebres** [comment] 2015-03-18 07:56
Nice one :)

**Comment by yarikoptic** [comment] 2015-03-21 17:22
so the summary is that it leaks file descriptors somewhere.  We do not deal with journal files directly -- and just use systemd Python module.  My bet, is that it there somewhere them not closing some files upon destruction of e.g. journal.Reader

what does systemctl reload  does on centos -- calls fail2ban-client reload? (just to make sure)

**Comment by opoplawski** [comment] 2015-03-28 04:17
Well, it's Fedora, not centos (7), but in either case It's the upstream .service file:
[Service]
Type=forking
ExecStart=/usr/bin/fail2ban-client -x start
ExecStop=/usr/bin/fail2ban-client stop
ExecReload=/usr/bin/fail2ban-client reload

But yeah, I suspect you'll want to report this against systemd's python interface to the journal.

**Comment by keszybz** [comment] 2015-04-10 14:13
OK, it seems to be a bug in systemd python wrappers. I'll push a fix shortly.

**Comment by keszybz** [comment] 2015-04-12 20:57
Hm, I *thought* that this is a problem with systemd python wrappers, but this doesn't seem to be true. (I thought the object is not destroyed properly, but that was simply because a reference was kept in sys.exc_info. As soon as the exception was cleared, all file descriptors were closed properly). I made a bunch of tests, and systemd.journal.Reader seems to free all resources properly upon destruction.

**Comment by goeranu** [comment] 2015-12-28 15:09
Isn't the ulimit of 1024 file descriptors the issue here?  Where exactly is it set?  I tried to raise the limit in my systemd configuration, but looking at /proc/*pid*/limit it seems only the hard limit is raised.  The soft remains at 1024.  From what I understand it is being explicitly lowered by the fail2ban server, but some grep:ing has failed to point out where.

Maybe I'm restating the obvious, but let me note down my observations in case they might be of some help.

My system has almost 400 files in /var/log/journal/*big-hash*.  It seems each one is opened by each jail.  (With one jail, it had just over 400 files open, with two, just over 800.)  So the limit of 1024 file descriptors is reached if I enable a third jail.  The fail2ban server then runs with all file descriptors used up.  What then happens is for example that logrotate comes along and after rotating issues a `fail2ban-client flushlogs`.  The server tries to read the command over the socket, but because it has no free file descriptors, it spins in this infinite loop:
```
poll([{fd=3, events=POLLIN|POLLPRI|POLLERR|POLLHUP|POLLNVAL}], 1, 30000) = 1 ([{fd=3, revents=POLLIN}])
accept(3, 0x7fff582faca0, [110])        = -1 EMFILE (Too many open files)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=1892, ...}) = 0
write(5, "2015-12-28 15:14:44,474 fail2ban"..., 78) = 78
```
I usually notice it by the load on the server before the file system fills up.

**Comment by sebres** [comment] 2015-12-28 17:15
The hard/soft user level limits may be specified in `/etc/security/limits.conf` or in `/etc/security/limits.d/*.conf`.
So if your fail2ban runs as root, please increase `nofile` values there, like:
```
root soft nofile 4096
root hard nofile 10240
```

Use `man limits.conf` to read about limits or look at nice article about - <a href = "http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/">Linux Increase The Maximum Number Of Open Files / File Descriptors (FD)</a>

I tend to close this issue, because it could be imho a common linux issue called "I run *nux daemon within few resources environment". I don't see it would be really an issue of fail2ban (or even python).

One idea by the way: I have rewritten asyncserver module in my feature branch, so I can respond to error `EMFILE` (see https://github.com/sebres/fail2ban/blob/f2b-perfom-prepare-716/fail2ban/server/asyncserver.py#L111) and it would be possible to reload fail2ban-server if that occur.
But, I don't know whether it would be good, and as already said, I don't think it is an issue of f2b.

**Comment by goeranu** [comment] 2015-12-28 17:31
I do not think so.

AFAIK `limits.conf` is not involved when starting systemd services in general.  It is something used by *pam* modules when starting a session.  But when simply starting a process, systemd doesn't look at it.

To verify I created a simple process with just the settings
```
[Service]
Type=simple
ExecStart=/usr/bin/sleep 24h
LimitNOFILE=9999
```
Checking `/proc/*pid*/limits` again, this process has **both** soft and hard limit set to 9999.

So I still believe the lowering of the soft limit is something fail2ban does.

My `limits.conf` is empty by the way, except for comments.

**Comment by sebres** [comment] 2015-12-28 18:09
> the lowering of the soft limit is something fail2ban does

Definitely no. 

But, if you are sure, you should consult a support resp. contact the maintainers of your *nux distribution.

**Comment by goeranu** [comment] 2015-12-28 19:10
I didn't say I'm *sure*.  I said I *believe*.  But if you are so sure fail2ban is not doing it, I'll investigate further.

**Comment by goeranu** [comment] 2015-12-28 19:41
If the start command is `/usr/bin/fail2ban-client -x start`, then the soft limit is lowered to 1024.  But if I change that to `/usr/bin/env /usr/bin/fail2ban-client -x start`, then the limit remains at 8192.

Interesting!

**Comment by sebres** [comment] 2015-12-28 20:42
I'm telling you :)
I had checked it on several servers (diverse f2b versions and different debians) - the f2b process has always the value of "max open files" equal system configured.

**Comment by sebres** [comment] 2016-11-22 10:21
Should we add an option `LimitNOFILE = 10000` to https://github.com/fail2ban/fail2ban/blob/master/files/fail2ban.service ?
Another way would be to create `fail2ban.service.d/limits.conf` like below:
```
$ cat /etc/systemd/system/fail2ban.service.d/limits.conf
[Service]
LimitNOFILE=10000
```

Additionaly I've made a PR #1618, you can check that may help here (in relation to limits resp. stop continuously restarting on such errors).

**Comment by sebres** [comment] 2016-12-13 12:30
> Funny this comes up now ... messing around with our disk space ...

What you want say us?! Please be a little bit more concrete... (BTW fail2ban version is more interested as OS)

> Once more and I'll have to disable fail2ban (production web server)...

Well, it's your decision to have or not to have... But such statements bring no useful sense here.

**Comment by boindil** [comment] 2016-12-13 13:22
> > Funny this comes up now ... messing around with our disk space ...

> What you want say us?! Please be a little bit more concrete... (BTW fail2ban version is more interested as OS)

I meant the fact, that this issue had no comment since late 2015 and now again the problem seems to rise again. That said there must have been some change in fail2ban (that combined with the comments on here some dependency probably changed something). The installed fail2ban is version 0.9.2 (standard on CentOS 7).

**Comment by Thermi** [comment] 2017-05-18 23:34
This still happens with 0.9.6!

**Comment by sebres** [comment] 2017-05-19 12:21
@Thermi 
- How many jails did you've (using systemd-backend)?
```bash
?sudo? fail2ban-client -d | grep -c -E "^\\['add',.*, 'systemd"
```
- How many journal files are there?
```bash
# note the correct path for your systemd journal root:
?sudo? find /var/log/journal -type f | wc -l
?sudo? find /run/log/journal -type f | wc -l
```

**Comment by Thermi** [comment] 2017-05-19 12:24
python-systemd version is 233. fail2ban-daemon ran out of file descriptors
after a couple of reloads, so old ones are probably not closed. It might
be a problem in the underlying library.

On 19.05.2017 14:21, Serg G. Brester wrote:
> @Thermi <https://github.com/thermi>
> 
>   * How many jails did you've (using systemd-backend)?
> 
> ?sudo? fail2ban-client -d | grep -c -E "^\\['add',.*, 'systemd"

5

> 
>   * How many journal files are there?
> 
> # note the correct path for your systemd journal root:
> ?sudo? find /var/log/journal -type f | wc -l

54

> ?sudo? find /run/log/journal -type f | wc -l

Doesn't exist.

-- 
GPG Key ID: 0x63EC6658
Fingerprint: 23CA BB60 2146 05E7 7278 6592 3839 298F 63EC 6658

**Comment by sebres** [comment] 2017-05-19 12:45
> fail2ban-daemon ran out of file descriptors after a couple of reloads

But 0.9 version has not the reload functionality at all (the service/init.d will just map it to `fail2ban-client restart`, which in reality simply restarts a daemon, so the process should really going down, new process up).

The new **reload** functionality (`fail2ban-client reload`) was introduced firstly in v. 0.10.

So could you please check the PID of the fail2ban process was changed in the log-file (by thing you meant as "couple of reloads").

> so old descriptors are probably not closed

I believe it is impossible using restart.

BTW. Is recidive jail on? If yes, does it have used the systemd backend?
```
?sudo? fail2ban-client -d | grep -E "^\\['add', 'recidive'|'recidive'.*logpath"
```

**Comment by sebres** [comment] 2017-05-19 13:08
> fail2ban-client reload was introduced firstly in v. 0.10

Sorry, my bad... fail2ban-client of 0.9 seems to have "reload" command also, but this "reloading" in the manner to stop/start all the jails only (but indeed the same process).
I'll analyze it further...

**Comment by sebres** [comment] 2017-05-19 13:42
I could not comprehend because of my mistake with 0.9 reload/restart and because it was never reproducible on 0.10 (where it was already fixed long time).

So what, admittedly I had no interest for 0.9-branch, but (as pardon for long time) I've nevertheless fixed (back-ported) this very annoying bug in v.0.9 now.
See c7ddf1f940aa30f7d31dc1bf6e4d895713a6e38b.

Thus close the issue. Thank you all for testing and analysis.

**Comment by jkempinger-dv** [comment] 2017-12-11 15:30
I'm running v0.10.1.dev1 on a CentOS server using systemd as the backend.  Just had the server freeze up last night due to what I believe is this same issue.  There's a flood of `[3596]: WARNING Socket error` in the log file (which completely filled the disk) and there's a python process running fail2ban-server that's using up 98–99% of the processor percentage.

I killed the process and deleted the log file, so the server is working.  There's nothing in the log file before the socket error other than the expected `[3596]: INFO    rollover performed on /var/log/fail2ban.log`.  This is the third time I've seen this with fail2ban -- the first two times on 0.9 and this time on 0.10.1 -- but the issue is very sporadic.  If there's any debugging I can do, please let me know!

**Comment by sebres** [comment] 2017-12-11 16:01
Thus it looks like the evil-doers was not the systemd-backend alone...
Something still leaks the file descriptors... :(

Arrangements we can do in this direction:
- try to find the leakage;
- we need test-cases to cover/simulate out of file handle situation;
- (if possible) hard restart of fail2ban (or something similar) by first sign of "limits exceeded", in order to avoid endless flooding in the log file;

Arrangements you can do:
- if you get it again, try to find which files descriptors are open;
- increase max files limits, see https://github.com/fail2ban/fail2ban/issues/991#issuecomment-262202332

**Comment by jkempinger-dv** [comment] 2017-12-11 16:23
@sebres Thanks for the response!  Currently (on the recently rebooted server), lsof lists fail2ban as using 235 files.  The system limit is set to 203,572.  It appears that most of the files are system.journal files and inotify.  The issue comes seems to come up only every few months (all three times it's been in the middle of the night on a weekend when the server was likely not getting much use), so I'm not sure when/if it will happen again, but if it happens again I'll check!

**Comment by sebres** [comment] 2017-12-11 16:27
> The system limit is set to 203,572

Can you verify, whether the fail2ban-process has currently the same limits?

**Comment by jkempinger-dv** [comment] 2017-12-11 16:34
This is what `cat /proc/$PID/limits` gave for fail2ban-server:

```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7973                 7973                 processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7973                 7973                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

**Closed** 2018-03-02 16:35 UTC
