### ISSUE TITLE
New test failures with 0.10.5

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#2596] opened 2020-01-11 23:31 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.5

### The issue:

I'm looking to update the fail2ban package in Fedora to 0.10.5 and am getting the following test failures:
```
FAIL: testIPAddr_CompareDNS (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 2068, in testIPAddr_CompareDNS
    self.assertTrue(IPAddr("93.184.216.34").isInNet(ips))
AssertionError: False is not true
======================================================================
FAIL: testSampleRegexsSSHD (fail2ban.tests.samplestestcase.FilterSamplesRegex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/samplestestcase.py", line 239, in testFilter
    self.assertFalse(faildata.get('match', True),
AssertionError: True is not false : Line not matched when should have
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./fail2ban/tests/samplestestcase.py", line 291, in testFilter
    raise AssertionError("%s: %s on: %s:%i, line:\n %sregex (%s):\n %s\n"
AssertionError: sshd: True is not false : Line not matched when should have on: ./fail2ban/tests/files/logs/sshd:61, line:
 Mar 29 05:59:23 dusky sshd[20878]: [ID 800047 auth.info] Failed keyboard-interactive for <invalid username> from 205.186.180.55 port 42742 ssh2
regex (-1):
 None
faildata: {'host': '205.186.180.55', 'match': True, 'time': '2005-03-29T05:59:23'}
fail: {}
======================================================================
FAIL: testServerActions_NginxBlockMap (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/utils.py", line 219, in wrapper
    return f(self, *args, **kwargs)
  File "./fail2ban/tests/utils.py", line 243, in wrapper
    return f(self, tmp, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 338, in wrapper
    return f(self, tmp, startparams, *args, **kwargs)
  File "./fail2ban/tests/fail2banclienttestcase.py", line 1284, in testServerActions_NginxBlockMap
    self.assertNotIn('\\125-000-001 1;\n', mp)
  File "./fail2ban/tests/utils.py", line 631, in assertNotIn
    self.fail(msg)
AssertionError: '\\125-000-001 1;\n' unexpectedly found in '\\\\125-000-001 1;\n\\\\125-000-002 1;\n\\\\125-000-003 1;\n\\\\125-000-004 1;\n\\\\125-000-005 1;\n'
```
Full log attached.
[build.log](https://github.com/fail2ban/fail2ban/files/4050049/build.log)

I don't see the testIPAddr_CompareDNS failure building locally, so it may be a test that requires network access and so should be skipped with --no-network.  The other two are reproduced locally.

**Comment by andypost** [comment] 2020-01-12 23:43
Getting only one test failure on 0.11.1
```
======================================================================
FAIL: testServerActions_NginxBlockMap (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/andypost/aports/main/fail2ban/src/fail2ban-0.11.1/fail2ban/tests/utils.py", line 219, in wrapper
    return f(self, *args, **kwargs)
  File "/builds/andypost/aports/main/fail2ban/src/fail2ban-0.11.1/fail2ban/tests/utils.py", line 243, in wrapper
    return f(self, tmp, *args, **kwargs)
  File "/builds/andypost/aports/main/fail2ban/src/fail2ban-0.11.1/fail2ban/tests/fail2banclienttestcase.py", line 367, in wrapper
    return f(self, tmp, startparams, *args, **kwargs)
  File "/builds/andypost/aports/main/fail2ban/src/fail2ban-0.11.1/fail2ban/tests/fail2banclienttestcase.py", line 1328, in testServerActions_NginxBlockMap
    self.assertNotIn('\\125-000-001 1;\n', mp)
  File "/builds/andypost/aports/main/fail2ban/src/fail2ban-0.11.1/fail2ban/tests/utils.py", line 635, in assertNotIn
    self.fail(msg)
AssertionError: '\\125-000-001 1;\n' unexpectedly found in '\\\\125-000-001 1;\n\\\\125-000-002 1;\n\\\\125-000-003 1;\n\\\\125-000-004 1;\n\\\\125-000-005 1;\n'

----------------------------------------------------------------------
Ran 473 tests in 90.140s
```

**Comment by sebres** [comment] 2020-01-13 11:22
Hmm...
First test seems to don't have a network constraint (so ignores `--no-network` parameter), but why two other tests are failing?... Weird.

- testSampleRegexsSSHD : are there some changes during a refactoring process on `sshd.conf` or `logs/sshd` test file?

Can you start this tests with more heavy debugging, Orion?
```
cd ...; 2to3;
PYTHONPATH=. bin/fail2ban-testcases --no-network -l 5 'testSampleRegexsSSHD |testServerActions_NginxBlockMap'
```

**Comment by opoplawski** [comment] 2020-01-14 05:16
Here are some test runs with that (look for the start of the %check section):
https://kojipkgs.fedoraproject.org//work/tasks/6947/40506947/build.log
https://kojipkgs.fedoraproject.org//work/tasks/6980/40506980/build.log

**Comment by sebres** [comment] 2020-01-14 09:37
Hmm... both attempts don't show the failure in testSampleRegexsSSHD.
Worse if that is either sporadic (or depending on some previous tests).

**Comment by sebres** [comment] 2020-01-14 10:25
Other failure (NginxBlockMap) looks like a bug (shell dependency) and going to different echo behavior with backslash in default shell's fail2ban is running:
```
$ bash -c 'echo "\\test"'
\test
$ sh -c 'echo "\\test"'
        est
```

**Comment by sebres** [comment] 2020-01-14 11:29
All things (excepting inexplicable testSampleRegexsSSHD) should be fixed now.
As for testSampleRegexsSSHD, I don't know what exactly happens here. 
One (and perhaps sole) possibility were either different (patched) common-include or sshd-filter.
A sporadic (timing) issue is hardly imaginable here, let alone I never saw this (or some similar thing) in Travis CI.

**Comment by andypost** [comment] 2020-01-15 00:21
Commit ec37b1942c4da76f7a0f71efe81bea6835466648 fixed tests for me, thank you a lot!

**Comment by jasontibbitts** [comment] 2020-01-15 00:22
I was updating my local fork of the Fedora package to 0.11.1 and got the same three failures (when running the test suite with --no-network).  I can confirm that two failures are fixed with the recent patches but testSampleRegexsSSHD remains.  For me this is quite reproducible; I did a number of builds and all failed identically.

I run the tests with `./fail2ban-testcases-all-python3 --no-network`.  I added `-l 5` and there is a huge spew of information.  To narrow it down I added `test SampleRegexSSHD` (to, I presume, just run that one test) and... it doesn't fail.

So I wonder if one of the other tests does something to which causes testSampleRegexSSHD to fail.  Is there a way I might, say, exclude a bunch of tests, so that I could try a binary search?

**Comment by sebres** [comment] 2020-01-15 11:29
Hmm... weird.
Binary search is to heavy here (it expects regexp's as positive and negative filter), but...

> and there is a huge spew of information. 

But if it failed under heavydebug (`-l 5`) too, it could be a bit simple firstly to redirect the output into some file and hereafter search and cut a part between SSHD and next test:
```
========== fail2ban.tests.samplestestcase.FilterSamplesRegex.testSampleRegexsSSHD ====================
...
========== fail2ban.tests.samplestestcase.FilterSamplesRegex. ....
```
Maybe I'll get to see some evil thing there.

BTW. in case of redirect still one case could fail (due to redirection) but it does no matter.

**Comment by jasontibbitts** [comment] 2020-01-15 16:34
Fortunately it's all captured in the build log; I just wasn't sure what to look for since there's so much output.  Here I've snipped everything up to the first occurrence of testSampleRegexsSSHD and everything after what looked like the first line of the following test.  I left in the failure output at the end just in case.  I hope this helps.

[build-log-exerpt.txt](https://github.com/fail2ban/fail2ban/files/4066039/build-log-exerpt.txt)

**Comment by sebres** [comment] 2020-01-15 17:22
> ... I hope this helps.

Thank you! Indeed, the "failure" is obvious now:
```diff
--- "a/build-log-exerpt.txt"
+++ "b/build-log-exerpt-working.txt"
@@ -4,13 +4,10 @@
  #06-L |    datedetector-6 : matchTime            |   matched last time template #00
  #06-L |    datedetector-6 : getTime              |   got time 1112068763.000000 for 'Mar 29 05:59:23' using template {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
  HEAVY |          filter-5 : findFailure          | Looking for match of [('', 'Mar 29 05:59:23', ' dusky sshd[20878]: [ID 800047 auth.info] Failed keyboard-interactive for <invalid username> from 205.186.180.55 port 42742 ssh2')]
- HEAVY |          filter-5 : findFailure          |   Looking for prefregex '^(?P<mlfid>\\s*(?:\\S+\\s+)?(?:sshd(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?)(?:(?:error|fatal): (?:PAM: )?)?(?P<content>.+)$'
+ HEAVY |          filter-5 : findFailure          |   Looking for prefregex '^(?P<mlfid>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?)(?:(?:error|fatal): (?:PAM: )?)?(?P<content>.+)$'
- TRACE |          filter-7 : findFailure          |   Pre-filter matched {'mlfid': ' dusky sshd[20878]: ', 'content': '[ID 800047 auth.info] Failed keyboard-interactive for <invalid username> from 205.186.180.55 port 42742 ssh2'}
+ TRACE |          filter-7 : findFailure          |   Pre-filter matched {'mlfid': ' dusky sshd[20878]: [ID 800047 auth.info] ', 'content': 'Failed keyboard-interactive for <invalid username> from 205.186.180.55 port 42742 ssh2'}
  HEAVY |          filter-5 : findFailure          |   Looking for failregex 0 - '^[aA]uthentication (?:failure|error|failed) for (?P<user>.*) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))( via \\S+)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$'
  HEAVY |          filter-5 : findFailure          |   Looking for failregex 1 - '^User not known to the underlying authentication module for (?P<user>.*) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$'
  HEAVY |          filter-5 : findFailure          |   Looking for failregex 2 - '^Failed publickey for invalid user (?P<user>(?P<cond_user>\\S+)|(?:(?! from ).)*?) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)'
  HEAVY |          filter-5 : findFailure          |   Looking for failregex 3 - '^Failed \\b(?!publickey)\\S+ for (?P<cond_inv>invalid user )?(?P<user>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)'
- HEAVY |          filter-5 : findFailure          |   Looking for failregex 4 - '^(?P<user>ROOT) LOGIN REFUSED FROM (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))'
- HEAVY |          filter-5 : findFailure          |   Looking for failregex 5 - '^[iI](?:llegal|nvalid) user (?P<user>.*?) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w))(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$'
- HEAVY |          filter-5 : findFailure          |   Looking for failregex 6 - '^User (?P<user>.+) from (?:\\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?|(?P<dns>[\\w\\-.^_]*\\w)) not allowed because not listed in AllowUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$'
- ...
+ TRACE |          filter-7 : findFailure          |   Matched failregex 3: {'ip4': '205.186.180.55', 'cond_user': None, 'ip6': None, 'user': '<invalid username>', 'dns': None, 'cond_inv': None}
```
The issue happens because the `prefregex` (and probably `__prefix_line` from common) in build is totally different, so it results in other content (and different `mlfid`), which cannot be matched hereafter by `failregex` (whereas working variant find a match by 3rd regex).

So [__prefix_line](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/common.conf#L72) from common for a `file` type should contain `%(__date_ambit)s?`, which interpolating into `(?:\[\])?`, that is well available in working variant (`^(?P<mlfid>(?:\\[\\])?...`), but not available in `prefregex` of failed build.

Why it is happening (or else why together in combination with other tests only) is still unclear to me.
I can only imagine that:
- either some (custom) tests cause loading of different common (or other include), and because the configs are cached (also in test cases) it remains "invalid" by testing sshd in sample regex factory;
- or factory (or testSampleRegexsSSHD) will be executed several times, once with stock config and other time with some custom config (but it should even produce then error in filtered run also).
- or it occurs because of the extended tests of `journal` type (#2387), e. g. if the sequence of the tests is different for some reasons - this would point to "broken" config-caching mechanism (at least in test-cases).

I must investigate more.

**Comment by jasontibbitts** [comment] 2020-01-15 17:28
I'm certainly willing to test anything you might suggest.  I do know that I was building 0.11 snapshots for a while and did not have this problem.  However, the last snapshot I built was from March of last year (7f0bba9) so that's probably not recent enough to be all that helpful  But I can try to bisect from there.

**Comment by sebres** [comment] 2020-01-15 17:36
Well, one thing is really interesting now: 
Do you testing the build with a **stock config folder** or are there some (local) modifications (e. g. [include](https://github.com/fail2ban/fail2ban/blob/67fd75c88e939c0e09ce203f18f50fe460ada84f/config/jail.conf#L36) is changed to `paths-fedora` and/or `backend` for `sshd` is switched to `systemd`)?

Because now fail2ban choose the common prefix line (depending on used backend or specified filter options).

**Comment by sebres** [comment] 2020-01-15 17:51
This not an assumption anymore. :)
I can pretty well reproduce the issue if I add `sshd_backend = systemd` to the config.
And then it is also clear why it fails - once read with modified config, ("cached") filter `sshd` can not match non journal sshd.log anymore.

Either we have to change caching mechanism, or must clear the cache in testSampleRegexsFactory before it processing test logs.

**Comment by jasontibbitts** [comment] 2020-01-15 17:55
Just saw your response while I was typing this, but I figured I'd submit it anyway.  It appears to me that the first bad commit is cd32f4a13297678bdefcd19901f60aba7bdd56e4.  c47bb523b76e2bb6efe6f447848ae11e3010a155 was good.

Fedora does tweak config/jail.conf to add paths-fedora, and it changes shebang lines to reference python3.  Here's what we do:

* Install minimal OS and build dependencies into a chroot.
* Unpack the tarball and cd to the directory it creates.
* Run the following two commands:
** `sed -i -e 's/^before = paths-.*/before = paths-fedora.conf/' config/jail.conf`
** `find -type f -exec sed -i -e '1s,^#!/usr/bin/python *,#!/usr/bin/python%{python3_version},' {} +`
* Then run 2to3 and `/usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'`

**Comment by sebres** [comment] 2020-01-15 18:00
:) And it surely contains https://github.com/fail2ban/fail2ban/blob/67fd75c88e939c0e09ce203f18f50fe460ada84f/config/paths-fedora.conf#L36 

It's definitely cache, so basically this test attempt (with 2 tests) fails with guaranty:
```
fail2ban-testcases -fn 'testReadStockJailConfForceEnabled|testSampleRegexsSSHD'
```
because firstly it reads whole config (and uses journal as type) and cache it "wrong", so unable process second test.

**Comment by jasontibbitts** [comment] 2020-01-15 18:45
I can confirm that the patch fixes the issue; I'm able to build 0.11.1 (plus the three patches mentioned in this ticket) without testsuite failures.  Thanks for the help.

**Comment by sebres** [comment] 2020-01-15 20:47
you were to fast :)
unfortunately this mini-patch was a first shot and does not fix all cases (e. g. `fail2ban-regex`), as well as doesn't consider replacement of `logtype` in definition section of (local) filter version.
I'm preparing a bit longest replacement fix for that (with code coverage for the future, etc)

**Comment by sebres** [comment] 2020-01-15 20:53
So it should be ultimately fixed in 8dc6f30cdd855c41b80ebdde3fe2bc91cc94e594  (I amended it to 5630009ed5a8af3cb343c2cf400e80629d4fa0d6, so it replaces that).
I'll merge it to 0.11 also if all test cases pass.

**Comment by sebres** [comment] 2020-01-15 21:16
Thx for test and help! Thus close as fixed.

@fail2ban/maintainers do we need new releases for 0.10/0.11 after this "minor" fixes, or can current state of both actions be considered as a patch?

**Closed by sebres** 2020-01-15 21:16 UTC

**Comment by opoplawski** [comment] 2020-01-16 02:44
I'm fine with patching.  Thanks for the prompt attention!
