### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by JKBert** [fail2ban/fail2ban#2707] opened 2020-05-01 19:02 UTC
Hello,

I'm trying to write a regex to block connections that give in syslog following error message:
```
 May  1 20:57:29 rayleigh pop3d-ssl: Connection, ip=[::ffff:213.217.0.213]
May  1 20:57:29 rayleigh pop3d-ssl: ip=[::ffff:213.217.0.213], An unexpected TLS packet was received.
May  1 20:57:29 rayleigh pop3d-ssl: Disconnected, ip=[::ffff:213.217.0.213]
May  1 20:57:29 rayleigh pop3d-ssl: ip=[::ffff:213.217.0.213], An unexpected TLS packet was received.
May  1 20:57:29 rayleigh pop3d-ssl: Disconnected, ip=[::ffff:213.217.0.213]
May  1 20:57:40 rayleigh pop3d-ssl: Connection, ip=[::ffff:213.217.0.213]
May  1 20:57:40 rayleigh pop3d-ssl: Connection, ip=[::ffff:213.217.0.213]
May  1 20:57:40 rayleigh pop3d-ssl: ip=[::ffff:213.217.0.213], An unexpected TLS packet was received.
May  1 20:57:40 rayleigh pop3d-ssl: Disconnected, ip=[::ffff:213.217.0.213]
May  1 20:57:40 rayleigh pop3d-ssl: ip=[::ffff:213.217.0.213], An unexpected TLS packet was received.
```
Please note that incoming connection are real IPv4 and not IPv4 mapped in IPv6.

I have tried to add a new filter without any success:
```
[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[Definition]

#_daemon = (?:courier)?(?:imapd?|pop3d?)-ssl?

#failregex = ^%(__prefix_line)s.*ip=\[<HOST>\], An unexpected TLS packet was received.$
failregex = ip=\[<HOST>\], An unexpected TLS packet was received.$

ignoreregex =

datepattern = {^LN-BEG}
```
If I test regex with fail2ban-regex, a lot of lines match. I don't understand my mistake.

Fail2ban version is 0.11.1-2 (Debian package) and runs on a Linux Debian server (amd64).
Best regards,

JB

**Comment by sebres** [comment] 2020-05-04 11:31
> I have tried to add a new filter without any success

What do you mean exactly? Error? No findings?

> If I test regex with fail2ban-regex, a lot of lines match. I don't understand my mistake.

So if it matches, what is then your issue?

The filter is not really needed for this simple log, and a jail is enough:
```ini
[jail]
filter =
failregex = ^\s*\S+\s+(?:(?:courier)?(?:imapd?|pop3d?)-ssl)?: ip=\[<ADDR>\], An unexpected TLS packet was received\.
logpath = /path/to/your/log
...
enabled = true
```

> Please note that incoming connection are real IPv4 and not IPv4 mapped in IPv6.

Fail2ban correct recognize such IPs with `<HOST>` or `<ADDR>` tags:
```
$ msg='May  1 20:57:29 rayleigh pop3d-ssl: ip=[::ffff:213.217.0.213], An unexpected TLS packet was received.'
$ fail2ban-regex -o row "$msg" '^\s*\S+\s+(?:(?:courier)?(?:imapd?|pop3d?)-ssl)?: ip=\[<ADDR>\], An unexpected TLS packet was received\.'
['213.217.0.213',       1588359449.0,   {'ip6': None, 'ip4': '213.217.0.213'}],
```

I'll close this unless it is not clear what the issue is exactly.

**Closed by sebres** 2020-05-04 11:31 UTC
Labels: moreinfo
