### ISSUE TITLE
sshd filter registers fail in pam_unix even though login is successful

### ISSUE THREAD

**Issue by Debilski** [fail2ban/fail2ban#2157] opened 2018-06-18 21:34 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2
- OS, including release name/version: Debian jessie (backported fail2ban)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

sshd logs an unauthorised login attempt in the `pam_unix(sshd:auth)` which is seen by the fail2ban filter. However, as the login is handled in `pam_sss(sshd:auth)`, this should not count as a failed login attempt.

#### Steps to reproduce

ssh to the server and give the correct password. Log out again. Repeat three times.

#### Expected behavior

IP address should not be blocked.

#### Observed behavior

No connection to server. IP is blocked.

#### Any additional information

The bug has been reported in #106 (and fixed in #107) but seems to have been re-introduced in https://github.com/fail2ban/fail2ban/commit/8825a5f31b984fe52f705df6cec4720c9c1f0beb 

#### Relevant lines from monitored log files in question:

    $ journalctl -f -u ssh -u fail2ban
    -- Logs begin at Fri 2016-12-23 11:15:47 CET. --
    Jun 18 23:19:43 itbssh sshd[31758]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=host.name  user=ppy
    Jun 18 23:19:43 itbssh fail2ban-server[23423]: fail2ban.ipdns          [23423]: WARNING Determined IP using DNS Lookup: host.name = ['X.X.X.X']
    Jun 18 23:19:43 itbssh fail2ban-server[23423]: fail2ban.filter         [23423]: INFO    [sshd] Found X.X.X.X - 2018-06-18 23:19:43
    Jun 18 23:19:43 itbssh sshd[31758]: pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=host.name user=ppy
    Jun 18 23:19:43 itbssh sshd[31758]: Accepted password for ppy from X.X.X.X port 59904 ssh2
    Jun 18 23:19:43 itbssh sshd[31758]: pam_unix(sshd:session): session opened for user ppy by (uid=0)

```
```

**Comment by sebres** [comment] 2018-06-19 08:19
This was already "fixed" in 0.10.3 (closed in #2090).
Indirectly this is not a bug (but feature), which avoids brute-force of password of some account if another (valid) account exists. 
If you don't want this, as long as still not updated to 0.10.3, you could either add this regexp to ignoreregex or increase `maxretry`...

**Closed by sebres** 2018-06-19 08:19 UTC

**Comment by Debilski** [comment] 2018-06-19 09:29
On 19.06.2018 10:19, Sergey G. Brester wrote:
> This was already "fixed" in 0.10.3 (closed in #2090 
> <https://github.com/fail2ban/fail2ban/pull/2090>).
> Indirectly this is not a bug (but feature), which avoids brute-force of 
> password of some account if another (valid) account exists.
> If you don't want this, as long as still not updated to 0.10.3, you 
> could either add this regexp to ignoreregex or increase |maxretry|...

Yeah, I’ve increased the maxretry for now but of course the limit is 
still reached pretty quickly if you do a bunch of `scp`s and don’t have 
a ssh key to log in. But we can live with that until the new version 
arrives in debian. Thanks.
