### ISSUE TITLE
<Name> not working in emails

### ISSUE THREAD

**Issue by paulb057** [fail2ban/fail2ban#1677] opened 2017-01-20 23:06 UTC
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.9.3
- OS, including release name/version: Ubuntu 5.4.0-6ubuntu1~16.04.4
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I just did an install on a new machine and am having a problem with the email not giving me the correct information.  <name> and  <logpath> (maybe more) do not have the right values. When every <name> it says "default" rather then the jail and the <logpath> says /dev/null.  

If I look in the Fail2Ban logs it has the correct information.

/var/log/fail2ban.log
2017-01-20 17:25:18,507 fail2ban.filter         [1449]: INFO    [hack-admin] Found 105.101.139.39
2017-01-20 17:25:18,966 fail2ban.actions        [1449]: NOTICE  [hack-admin] Ban 105.101.139.39

#### Expected behavior

Subject: [Fail2Ban] hack-admin: banned 105.101.139.39 from my-machine-07
In body of email: The IP 105.101.139.39 has just been banned by Fail2Ban after
1 attempts against hack-admin.

Lines containing IP:105.101.139.39 in /var/www/log/mysite-access.log

105.101.139.39 - - [20/Jan/2017:17:25:18 -0500] "GET /wp-login.php HTTP/1.1" 302 557 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1"

#### Observed behavior

Email Message

Subject: [Fail2Ban] default: banned 105.101.139.39 from my-machine-07
In body of email: The IP 105.101.139.39 has just been banned by Fail2Ban after
1 attempts against default.

Lines containing IP:105.101.139.39 in /dev/null

### Configuration, dump and another helpful excerpts

['add', 'hack-admin', 'auto']
['set', 'hack-admin', 'ignorecommand', '']
['set', 'hack-admin', 'usedns', 'warn']
['set', 'hack-admin', 'bantime', -1]
['set', 'hack-admin', 'findtime', 600]
['set', 'hack-admin', 'addlogpath', '/var/www/logs/mysite-access.log', 'head']
['set', 'hack-admin', 'logencoding', 'auto']
['set', 'hack-admin', 'addignoreip', '127.0.0.1/8']
['set', 'hack-admin', 'maxretry', 0]
['set', 'hack-admin', 'addfailregex', '<HOST>.*"[A-Z]* /(cms|user|muieblackcat|db|cpcommerce|wp-login|joomla|awstatstotals|wp-content|wp-includes|pma|phpmyadmin|myadmin|mysql|mysqladmin|sqladmin|mypma|xampp|mysqldb|pmadb|phpmyadmin1|phpmyadmin2).*"']
['set', 'hack-admin', 'addignoreregex', '.*\\"GET \\/(press|mailto|domestic|word).*']
['set', 'hack-admin', 'addaction', 'sendmail-geoip-lines']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'actioncheck', '']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'actionstart', 'printf %b "Subject: [Fail2Ban] <name>: started on `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: <sendername> <<sender>>\nTo: <dest>\\n\nHi,\\n\nThe jail <name> has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f <sender> <dest>']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'actionunban', '']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'actionstop', 'printf %b "Subject: [Fail2Ban] <name>: stopped on `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: <sendername> <<sender>>\nTo: <dest>\\n\nHi,\\n\nThe jail <name> has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f <sender> <dest>']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'actionban', 'printf %b "Subject: [Fail2Ban] <name>: banned <ip> from `uname -n`\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: <sendername> <<sender>>\nTo: <dest>\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against <name>.\\n\\n\nHere is more information about <ip> :\\n\nhttp://bgp.he.net/ip/<ip>\nhttp://www.projecthoneypot.org/ip_<ip>\nhttp://whois.domaintools.com/<ip>\\n\\n\nCountry:`geoiplookup -f /usr/share/GeoIP/GeoIP.dat "<ip>" | cut -d\':\' -f2-`\nAS:`geoiplookup -f /usr/share/GeoIP/GeoIPASNum.dat "<ip>" | cut -d\':\' -f2-`\nhostname: `host -t A <ip> 2>&1`\\n\\n\nLines containing IP:<ip> in <logpath>\\n\n`grep -E <grepopts> \'(^|[^0-9])<ip>([^0-9]|$)\' <logpath>`\\n\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f <sender> <dest>']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'known/dest', 'root']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'dest', 'root']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'sendername', 'Fail2Ban']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'known/sender', 'fail2ban']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'name', 'default']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'sender', 'fail2ban']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'grepopts', '-m 1000']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'known/sendername', 'Fail2Ban']
['set', 'hack-admin', 'action', 'sendmail-geoip-lines', 'logpath', '/dev/null']

**Comment by sebres** [comment] 2017-01-21 13:27
Short, the correct parameters should be specified in your jail.local, like in this example:
```
[DEFAULT]
my_geoip_action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             sendmail-geoip-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s", chain="%(chain)s"]

[sshd]
enabled = true
action = %(my_geoip_action)s
```

BTW. in v.0.9 it does currently work for jails with exact one logpath only. 
v.0.10 can grep from multiple logs.

Closed as invalid.

**Closed by sebres** 2017-01-21 13:27 UTC

**Comment by paulb057** [comment] 2017-01-21 19:24
Thanks for the help and getting back to me.

 

I have done as you said and there was no change when I restart fail2ban I am getting the same result, the email coming as “default”.  All the other parameters that are used in the email (<sendername>, <<sender>>, <dest>,<ip>, <failures>)  are working and getting replaced properly before and after this change.  Also start and stop emails that are the default it is not working as well (The jail default has been started successfully).  As both those two things are part of the basic install should they not work with out any other changes?  I understand the grep does will not work as I have multiple log files unless I upgrade.

 

[DEFAULT]

apache_error_log = /var/www/logs/*error.log

apache_access_log = /var/www/logs/*access.log

loglevel = 4

my_geoip_action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]

             sendmail-geoip-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s", chain="%(chain)s"]

 

[hack-admin]

enabled  = true

filter   = hackadmin

action   = %(my_geoip_action)s

logpath = %(apache_access_log)s

 

 

 


Paul Barbeau CEH, CHFI, CCFE, CPT, CDRP
President & Chief Technology Officer
hyperNET

**Comment by sebres** [comment] 2017-01-21 22:40
I cannot reproduce what you say neither with current 0.9 nor with 0.10 (don't known what exactly 0.9.3 does wrong). If I check it with `fail2ban-client -d | grep sshd`, then both parameters `logpath` and `name` (and `actname`) are correctly set to expected values.

I see that `apache_access_log` uses wildcard, possible you have more as one file. As already said, in v.0.9 multiple logfiles cannot be used in such actions.

BTW. Be sure that the multiple actions in failregex separated exactly with one newline.
So valid:
```
failregex = action 1
            action 2
```
Not valid:
```
failregex = action 1

            action 2
```
