### ISSUE TITLE
[sogo-auth] jail does not work (no banning despite successful detection within filter/failregex)

### ISSUE THREAD

**Issue by chc-pr** [fail2ban/fail2ban#1804] opened 2017-06-15 08:33 UTC
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: Ubuntu 16.04.02 LTS
- [ ] Fail2Ban installed via OS/distribution mechanisms - using iRedmail installer on a clean 16.04.02 server with only ssh 
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

On testing my new mailserver prior to installation I found that fail2ban was never baning any logon fails from sogo. I have tried several installation attempts spinning up various VMs with various options selected using the iRedMail installer - with Apache, with Nginx etc and they all failed to ban sogo logons

#### Steps to reproduce
see above

#### Expected behavior
IP address from failed logon attempts to be baned for the ban time

#### Observed behavior
No actions taken at all. No logs record any events other than a failed logon which (mostly) matches the regex entry in sogo-auth. See next entry for more details.

#### Any additional information
On investigation, it appears that the regex entry in sogo-auth.conf is not triggering. Using a regex tester, it appears that the regex pattern has some errors. Specifically, adding \w{3} \d{2} \d{2}:\d{2}:\d{2} immediately after the start ^ produces a pattern match when the '<HOST>' entry is replaced with \d+.\d+.\d+.\d+

I assume that <HOST> is a fail2ban specific variable as it is not on the regex list of variables I have seen. Obviously, <HOST> has to be retained or the jail will not load.

With the above insertion after the ^, the jail loads but still does not ban anything. Below is the modified regex pattern which does apparently match and a sample log entry
failregex = ^\w{3} \d{2} \d{2}:\d{2}:\d{2} sogod \[\d+\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
/var/log/sogo/sogo.log entry which should have been banned.
Jun 15 04:25:49 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0

subsequent iptables -L -n output (sogo part only)

Chain f2b-sogo (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

#### Any customizations done to /etc/fail2ban/ configuration
```
The following changes were made to the jail.local file to facilitate testing
findtime = 300
bantime = 300
maxretry = 3
ignoreip = 127.0.0.1 127.0.0.0/8 172.16.1.124

The last entry in ignoreip was set as an antilockout to allow testing from all other i addresses on the subnet

No other changes were made
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
fail2ban reset to DEBUG, /var/log/fail2ban.log remains empty.
```

#### Relevant lines from monitored log files in question:

```
Jun 15 04:24:55 sogod [25584]: 172.16.1.232 "GET /SOGo/ HTTP/1.1" 200 6984/0 0.011 26017 73% 0
Jun 15 04:25:12 sogod [25584]: SOGoRootPage successful login from '172.16.1.232' for user 'sogotest@pchmt.net' - expire = -1  grace = -1
Jun 15 04:25:12 sogod [25584]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 200 50/91 0.017 - - 0
Jun 15 04:25:13 sogod [25584]: 172.16.1.232 "GET /SOGo//sogotest@pchmt.net HTTP/1.1" 302 0/0 0.002 - - 0
Jun 15 04:25:13 sogod [25584]: 172.16.1.232 "GET /SOGo//sogotest@pchmt.net/view HTTP/1.1" 302 0/0 0.002 - - 0
Jun 15 04:25:13 sogod [25584]: 172.16.1.232 "GET /SOGo/so/sogotest@pchmt.net/Mail HTTP/1.1" 302 0/0 0.002 - - 0
Jun 15 04:25:13 sogod [25584]: 172.16.1.232 "GET /SOGo/so/sogotest@pchmt.net/Mail/view HTTP/1.1" 200 17258/0 0.021 73446 76% 0
Jun 15 04:25:14 sogod [25584]: 172.16.1.232 "GET /SOGo/so/sogotest@pchmt.net/Calendar/alarmslist?browserTime=1497515113 HTTP/1.1" 200 63/0 0.005 - - 0
Jun 15 04:25:14 sogod [25584]: 172.16.1.232 "GET /SOGo/so/sogotest@pchmt.net/Mail/0/view HTTP/1.1" 200 63020/0 0.325 - - 1M
Jun 15 04:25:15 sogod [25584]: 172.16.1.232 "POST /SOGo/so/sogotest@pchmt.net/Mail/0/folderINBOX/view HTTP/1.1" 200 1457/48 0.336 - - -1832K
Jun 15 04:25:18 sogod [25584]: 172.16.1.232 "POST /SOGo/so/sogotest@pchmt.net/Mail/unseenCount HTTP/1.1" 200 21/31 0.255 - - 0
Jun 15 04:25:20 sogod [25584]: SOGoUserHomePage user 'sogotest@pchmt.net' logged off
Jun 15 04:25:20 sogod [25589]: <0x0x5630def59d50[SOGoCache]> Cache cleanup interval set every 300.000000 seconds
Jun 15 04:25:20 sogod [25589]: <0x0x5630def59d50[SOGoCache]> Using host(s) '127.0.0.1' as server(s)
Jun 15 04:25:20 sogod [25584]: 172.16.1.232 "GET /SOGo/so/sogotest@pchmt.net/logoff HTTP/1.1" 302 0/0 0.042 - - 0
Jun 15 04:25:20 sogod [25584]: 172.16.1.232 "GET /SOGo/so/ HTTP/1.1" 200 6985/0 0.009 26023 73% 0
Jun 15 04:25:20 sogod [25589]: 172.16.1.232 "POST /SOGo/so/sogotest@pchmt.net/Mail/0/folderINBOX/expunge HTTP/1.1" 500 36/0 0.176 - - 2M
Jun 15 04:25:29 sogod [25589]: [WARN] <0x0x7fd4397bbcc0[WOxElemBuilder]> could not locate builders: WOxExtElemBuilder,WOxExtElemBuilder
Jun 15 04:25:29 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:25:29 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/84 0.238 - - 2M
Jun 15 04:25:34 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:25:34 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/85 0.003 - - 0
Jun 15 04:25:40 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:25:40 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/86 0.002 - - 0
Jun 15 04:25:45 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:25:45 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/87 0.002 - - 0
Jun 15 04:25:49 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:25:49 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
Jun 15 04:29:46 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:29:46 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.011 - - 0
Jun 15 04:29:51 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:29:51 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.004 - - 0
Jun 15 04:29:54 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:29:54 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
Jun 15 04:29:56 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:29:56 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
Jun 15 04:29:59 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:29:59 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
Jun 15 04:30:01 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
Jun 15 04:30:01 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
```

**Comment by sebres** [comment] 2017-06-15 08:56
If I test your log-excerpt with sogo-auth filter, it works as expected...
```bash
$ fail2ban-regex --print-all-matched --print-all-missed /tmp/test-sogo-auth.log /etc/fail2ban/filter.d/sogo-auth.conf
...
Lines: 40 lines, 0 ignored, 11 matched, 29 missed
[processed in 0.01 sec]

|- Matched line(s):
|  Jun 15 04:25:29 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
| ...
|  Jun 15 04:30:01 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
`-
|- Missed line(s):
|  Jun 15 04:24:55 sogod [25584]: 172.16.1.232 "GET /SOGo/ HTTP/1.1" 200 6984/0 0.011 26017 73% 0
| ...
|  Jun 15 04:30:01 sogod [25589]: 172.16.1.232 "POST /SOGo/connect HTTP/1.1" 403 34/88 0.002 - - 0
`-
```
All 11 entries with `might not have worked - password policy` are matched.
At least with current 0.10/0.9 versions, but I don't see ATM any relevant change compared to 0.9.3.

So because the failregex seems to work, I would like to know what other is wrong on your system/configuration...
Have you already tried to execute `fail2ban-regex` over your sogo log-file?

BTW. I hope, you've enabled jail `sogo-auth` in your `jail.local`? Just to be sure...
```
[sogo-auth]
enabled = true
```

**Comment by chc-pr** [comment] 2017-06-15 09:18
Full entry in jail.local
[sogo-iredmail]
enabled     = true
filter      = sogo-auth
action      = iptables-multiport[name=sogo, port="http,https,smtp,submission,pop3,pop3s,imap,imaps,sieve", protocol=tcp]
logpath     = /var/log/sogo/sogo.log

/usr/bin/fail2ban-regex -v /var/log/sogo/sogo.log /etc/fail2ban/filter.d/sogo-auth.conf produces 

Running tests
=============

Use   failregex filter file : sogo-auth, basedir: /etc/fail2ban
Use         log file : /var/log/sogo/sogo.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^\w{3} \d{2} \d{2}:\d{2}:\d{2} sogod \[\d+\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [51] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
|  [0] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:Year|Year2) 24hour:Minute:Second
|  [0] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] Month/Day/Year:24hour:Minute:Second
|  [0] Month-Day-Year 24hour:Minute:Second\.Microseconds
|  [0] TAI64N
|  [0] Epoch
|  [0] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
|  [0] ^24hour:Minute:Second
|  [0] ^<Month/Day/Year2@24hour:Minute:Second>
|  [0] ^Year2MonthDay  ?24hour:Minute:Second
|  [0] MON Day, Year 12hour:Minute:Second AMPM
|  [0] ^MON-Day-Year2 24hour:Minute:Second
`-

Lines: 51 lines, 0 ignored, 0 matched, 51 missed [processed in 0.00 sec]
Missed line(s): too many to print.  Use --print-all-missed to print all 51 lines

**Comment by sebres** [comment] 2017-06-15 09:35
It looks like modified sogo-auth (do you have `sogo-auth.local`, resp. made some changes in `sogo-auth.conf`?)... If not, then it may be your maintainers (questionable why they should do this).
```diff
- # original
- ^ sogod \[\d+\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
+ # your version
+ ^\w{3} \d{2} \d{2}:\d{2}:\d{2} sogod \[\d+\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
```
Take a look at original [sogo-auth.conf](https://github.com/fail2ban/fail2ban/blame/master/config/filter.d/sogo-auth.conf), I'll see that was changed the last-time 4 years ago.

Thus I close the issue as incorrect.

**Comment by sebres** [comment] 2017-06-15 09:39
BTW. Someone, that has built it, seems to be not understood how fail2ban works:
because the date-format could be different from system to system, the **matched date-pattern string will be cutted out from the log-line**, before fail2ban begins to parse `failregex`.

**Comment by chc-pr** [comment] 2017-06-15 10:01
Please do not close this.  The modified date entry I added to the entry as per your original below because it was not baning.  The data modifier was for from my own tests using a regex tester as the ^ sogod ... style was not matching on that tester.
The issue remains - sogo is NOT baning whichever version below of the regex is used. 
On Thu, Jun 15, 2017 at 10:35, Serg G. Brester  wrote:
 It looks like modified sogo-auth (do you have sogo-auth.local, resp. made some changes in sogo-auth.conf?)... If not, then it may be your maintainers (questionable why they should do this).
	- # original - ^ sogod [d+]: SOGoRootPage Login from '' for user '.*' might not have worked( - password policy: d* grace: -?d* expire: -?d* bound: -?d*)?s*$ + # your version + ^w{3} d{2} d{2}:d{2}:d{2} sogod [d+]: SOGoRootPage Login from '' for user '.*' might not have worked( - password policy: d* grace: -?d* expire: -?d* bound: -?d*)?s*$ Take a look at original sogo-auth.conf (https://github.com/fail2ban/fail2ban/blame/master/config/filter.d/sogo-auth.conf), I'll see that was changed the last-time 4 years ago.
 Thus I close the issue as incorrect.

**Comment by sebres** [comment] 2017-06-15 10:10
Please provide output of fail2ban-regex without any modification on filter...

As I already wrote, this is not reproducible at all, neither on current 0.9 (nor with 0.10).
Not interested to test it with 0.9.3, because too old and I guess it will work nevertheless.

**Comment by chc-pr** [comment] 2017-06-15 10:13
Here is the regex test using the original regex.  I do see what you mean about picking up the entries this time, but fail2ban is still not baning sogo.  It bans sshd and roundcube fine, but not sogo (and I think it is not baning IMAP and SMTP either, but I have not properly checked that yet. Clearly something is not right and I have been working on thsi problem for nearly a month now on and off, so it is quite possible I am missing something really obvious. It is also why I have tried several fresh VM builds (in case I messed with something I forgot) but ALL the installs (5 now) are exhibiting the same behaviour.

Running tests
=============

Use   failregex filter file : sogo-auth, basedir: /etc/fail2ban
Use         log file : /var/log/sogo/sogo.log
Use         encoding : UTF-8


Results
=======

Failregex: 16 total
|-  #) [# of hits] regular expression
|   1) [16] ^ sogod \[\d+\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
|      172.16.1.232  Thu Jun 15 04:25:29 2017
|      172.16.1.232  Thu Jun 15 04:25:34 2017
|      172.16.1.232  Thu Jun 15 04:25:40 2017
|      172.16.1.232  Thu Jun 15 04:25:45 2017
|      172.16.1.232  Thu Jun 15 04:25:49 2017
|      172.16.1.232  Thu Jun 15 04:29:46 2017
|      172.16.1.232  Thu Jun 15 04:29:51 2017
|      172.16.1.232  Thu Jun 15 04:29:54 2017
|      172.16.1.232  Thu Jun 15 04:29:56 2017
|      172.16.1.232  Thu Jun 15 04:29:59 2017
|      172.16.1.232  Thu Jun 15 04:30:01 2017
|      172.16.1.232  Thu Jun 15 05:14:54 2017
|      172.16.1.232  Thu Jun 15 05:15:01 2017
|      172.16.1.232  Thu Jun 15 05:15:05 2017
|      172.16.1.232  Thu Jun 15 05:15:10 2017
|      172.16.1.232  Thu Jun 15 05:15:14 2017
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [51] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
|  [0] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:Year|Year2) 24hour:Minute:Second
|  [0] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] Month/Day/Year:24hour:Minute:Second
|  [0] Month-Day-Year 24hour:Minute:Second\.Microseconds
|  [0] TAI64N
|  [0] Epoch
|  [0] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
|  [0] ^24hour:Minute:Second
|  [0] ^<Month/Day/Year2@24hour:Minute:Second>
|  [0] ^Year2MonthDay  ?24hour:Minute:Second
|  [0] MON Day, Year 12hour:Minute:Second AMPM
|  [0] ^MON-Day-Year2 24hour:Minute:Second
`-

Lines: 51 lines, 0 ignored, 16 matched, 35 missed [processed in 0.00 sec]
Missed line(s): too many to print.  Use --print-all-missed to print all 35 lines

**Comment by chc-pr** [comment] 2017-06-15 10:16
Our messages crossed. I am surprised that fail2ban as installed is so out of date. I am thinking I might give up on iRedMail and just try to build the mailserver components myself. You certainly cannot fix an unreproducable error. I appreciate yoru help thus far. If this is where we have to leave it I understand.

**Comment by chc-pr** [comment] 2017-06-15 10:26
I have just noticed something ... the time stamp is does not match the real time. I know it was set to GMT during install ... could this be the source of the problem?

**Comment by sebres** [comment] 2017-06-15 10:33
> the time stamp is does not match the real time

Example? I saw (from your excerpt):
```
Jun 15 04:25:29 sogod [25589]: SOGoRootPage Login from '172.16.1.232' for user 'sogotest@pchmt.net' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0
```
and it was pretty found (according fail2ban-regex above) as:
```
172.16.1.232  Thu Jun 15 04:25:29 2017
```
Which time zone is active?

If it is not a TZ-issue...
Please take a look in fail2ban.log, whether you'll see something conspicuous round about sogo jail.
Additionally note that fail2ban will ban an IP **only** if it makes 3 attempts in the last 5 minutes (corresponding yours maxretry/findtime).
Please provide the output of `?sudo? fail2ban-client -d | grep sogo-iredmail`

**Comment by chc-pr** [comment] 2017-06-15 10:40
I am aware of the ban time/span/attempts requirements. I am testing by making five or six attempts to logon using an invalid username and/or password from the sogo logon within about 1 minute I guess - certainly less than the 5 minutes I have set. Using exactly the same approach with both ssd (putty) and Roundcube both successfully ban the ip.

**Comment by chc-pr** [comment] 2017-06-15 10:42
I have now modified my system prompt to display the system time which shows the correct local time (GMT). So, the system time and the times tamp for the entries appear to be out of alignment by about 5 hours. I have no idea why that would be or where to look to check.

**Comment by chc-pr** [comment] 2017-06-15 10:49
Date and time seems to be OK, but the time showing in the log files is 5 hours behind ... ???

11:44:44 root@mail2:~# timedatectl
      Local time: Thu 2017-06-15 11:45:31 BST
  Universal time: Thu 2017-06-15 10:45:31 UTC
        RTC time: Thu 2017-06-15 10:45:31
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by chc-pr** [comment] 2017-06-15 10:51
As requested re  fail2ban-client -d | grep sogo-iredmail

['add', 'sogo-iredmail', 'auto']
['set', 'sogo-iredmail', 'bantime', 300]
['set', 'sogo-iredmail', 'maxretry', 3]
['set', 'sogo-iredmail', 'usedns', 'warn']
['set', 'sogo-iredmail', 'addlogpath', '/var/log/sogo/sogo.log', 'head']
['set', 'sogo-iredmail', 'logencoding', 'auto']
['set', 'sogo-iredmail', 'ignorecommand', '']
['set', 'sogo-iredmail', 'addignoreip', '127.0.0.1']
['set', 'sogo-iredmail', 'addignoreip', '127.0.0.0/8']
['set', 'sogo-iredmail', 'addignoreip', '172.16.1.124']
['set', 'sogo-iredmail', 'findtime', 300]
['set', 'sogo-iredmail', 'addfailregex', "^ sogod \\[\\d+\\]: SOGoRootPage Login from '<HOST>' for user '.*' might not have worked( - password policy: \\d*  grace: -?\\d*  expire: -?\\d*  bound: -?\\d*)?\\s*$"]
['set', 'sogo-iredmail', 'addaction', 'iptables-multiport']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'actionstart', '<iptables> -N f2b-<name>\n<iptables> -A f2b-<name> -j <returntype>\n<iptables> -I <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'actionban', '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'actionstop', '<iptables> -D <chain> -p <protocol> -m multiport --dports <port> -j f2b-<name>\n<iptables> -F f2b-<name>\n<iptables> -X f2b-<name>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'actioncheck', "<iptables> -n -L <chain> | grep -q 'f2b-<name>[ \\t]'"]
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'actionunban', '<iptables> -D f2b-<name> -s <ip> -j <blocktype>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'iptables', 'iptables <lockingopt>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'chain', 'INPUT']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'lockingopt', '-w']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/chain', 'INPUT']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'protocol', 'tcp']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/port', 'ssh']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/returntype', 'RETURN']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/name', 'default']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'port', 'http,https,smtp,submission,pop3,pop3s,imap,imaps,sieve']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'name', 'sogo']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'returntype', 'RETURN']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/protocol', 'tcp']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/iptables', 'iptables <lockingopt>']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sogo-iredmail', 'action', 'iptables-multiport', 'known/lockingopt', '-w']
['start', 'sogo-iredmail']

**Comment by chc-pr** [comment] 2017-06-15 10:54
var/log/fail2ban.log is empty.

**Comment by sebres** [comment] 2017-06-15 10:55
Understood. Indeed it seems to be an issue "wrong time zone in the sogo-log".

So you've currently two options:
- either you bring your sogo-service to write the log-entries in the same TZ, where fail2ban works also (normally it is system-TZ, not UTC).
- or (if you can't), then you can try to use our latest version (v. 0.10), where you've a new option, that could be used for this jail:
```
[sogo-iredmail]
logtimezone = UTC+0500
# or BST zone
# logtimezone = BST
...
```
Thus closed.

**Closed by sebres** 2017-06-15 10:55 UTC
