### ISSUE TITLE
fail2ban-client unban --all fails with NOK: ("unsupported operand type(s) for +: 'float' and 'str'",) unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by a-schaefers** [fail2ban/fail2ban#2914] opened 2021-01-19 03:08 UTC
### Environment:

Fail2Ban v0.10.2

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

#### Steps to reproduce

fail2ban-client unban --all

#### Expected behavior

unban all

#### Observed behavior

jails still contain bans

#### Any additional information

output:

 NOK: ("unsupported operand type(s) for +: 'float' and 'str'",)
unsupported operand type(s) for +: 'float' and 'str'

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment] 2021-01-19 12:41
I assume it is a duplicate of #2241 (see also https://github.com/fail2ban/fail2ban/issues/2241#issuecomment-425037901 and below), so fixed in 6067579464f32e81f4810692cf465219ae6b2537 (0.10.4 and 0.11.2).
Thus closed... Don't hesitate to ping me (or reopen it) if the issue still presents after an upgrade.

**Closed by sebres** 2021-01-19 12:41 UTC
Labels: closed-as-duplicate, implemented-in-newer-version
