### ISSUE TITLE
[BR]: fail2ban leaks idle server processes

### ISSUE THREAD

**Issue by yogo1212** [fail2ban/fail2ban#3358] opened 2022-09-22 07:13 UTC
### Environment:

- Fail2Ban version: 0.11.2-2 
- OS: Debian 11 (VM) / Rocky Linux 9 (Host)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [~] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban is started by supervisord inside a `docker-mailserver` VM.
It spawns one `fail2ban-server` process, fails to communicate with it, and restarts - leaving behind the idle process.
I've initially created an [issue](https://github.com/docker-mailserver/docker-mailserver/issues/2781) over at docker-mailserver with some more details about the environment.

Regardless, I think I've managed to isolate the problem.
Here's the command line of one of the processes:
```
/usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtarget /var/log/fail2ban.log --syslogsocket auto
```
It also doesn't work if run manually (great for testing).

No files are created, no log is written - no anything, basically.

The error happens here:

```
        with open("/tmp/test.log", "a") as f:
            f.write("pre close fd\n") # this gets written
        print("moo") # this is printed

        # urandom should not be closed in Python 3.4.0. Fixed in 3.4.1
        # http://bugs.python.org/issue21207
        if sys.version_info[0:3] == (3, 4, 0): # pragma: no cover
            urandom_fd = os.open("/dev/urandom", os.O_RDONLY)
            for fd in range(0, maxfd):
                try:
                    if not os.path.sameopenfile(urandom_fd, fd):
                        os.close(fd)
                except OSError:   # ERROR (ignore)
                    pass
            os.close(urandom_fd)
        else:
            os.closerange(0, maxfd)

        with open("/tmp/test.log", "a") as f:
            f.write("pre redir\n") # this isn't printed
```

I assume that an important file descriptor - maybe one keeping open a namespace? - is closed.
Maybe I'll find time to continue the investigation on the weekend.

#### Steps to reproduce

Spawn a docker-mailserver instance with fail2ban enabled in mailserver.env on Rocky Linux 9.

#### Expected behavior
Fail2ban runs silently in the background, doing it's thing.

#### Observed behavior
Fail2ban becomes aware of it's perception and it's effectuality being manifest in numbered channels and digresses - comfortably - into solipsism, severing these ties to the outside world.
It ponders silently about its existence, just _being_ - doing nothing in the eyes of an observer.

Just trying to deal positively with the template..

#### Any customizations done to /etc/fail2ban/ configuration
None of my doing (provided by docker-mailserver). Will provide on request.
I don't think any configuration files are used by the call in the description.

#### Relevant parts of /var/log/fail2ban.log file:
Empty, as per the description.

#### Relevant lines from monitored log files:

```
pre close fd
pre close fd
pre close fd
pre close fd
```

**Comment by yogo1212** [comment] 2022-09-22 07:32
damn. can't concentrate on work..

files in `/proc/$pid/ns` are identical for the shell and the daemonised fail2ban process.

**Comment by yogo1212** [comment] 2022-09-22 07:36
also, print after closing doesn't work even if i change the first parameter to `closerange` to 3.
maybe it's really just hanging?

**Comment by sebres** [comment] 2022-09-22 15:41
Duplicate of #3334 ?

Fact is: under docker the `nofile` limit may be toooooo high set (I don't know why), so the fork process (close of all descriptors in parent may be too slow - several minutes).
If so this was fixed in 535a982dccfb5e05f8fa0f3965e5bf454716179d and merged in all major branches (and seems to work well - see https://github.com/fail2ban/fail2ban/issues/3334#issuecomment-1219098856).

You can try the fix (or to reduce nofile limit or use `-f` to start it in foreground instead) and test it, I assume it would work fine (otherwise you can ping me here).

But...

I wonder also why do you start `fail2ban-server` with `--async -b` parameters? Parameter `--async` is still internal parameter and not really documented, it is used in internal communication to signal fork, it should not read any config by itself, which the fork would obtain from parent process. In that case the fail2ban may really don't do anything, just wait for the config stream supplied from outside. 
Please don't use `--async` by start (I must find better suitable name for that parameter to avoid confusion with asynchronous handling)... To start fail2ban:
- either use `fail2ban-server -f ...` to start it in foreground, like it happens in our default systemd unit: https://github.com/fail2ban/fail2ban/blob/2df58c5281facd73e73778a734a90f7d4fe95468/files/fail2ban.service.in#L11
- or use `fail2ban-(server|client) -b ...` to start it in background (with fork), but without async parameter.

**Closed by sebres** 2022-09-22 15:41 UTC
Labels: closed-as-incorrect, closed-as-duplicate, bug

**Comment by yogo1212** [comment] 2022-09-23 03:55
@sebres 
that's it! who'd have thought - `SC_OPEN_MAX` is 1073741816 oO.
i know `-f` worked already through testing - but `nofile` seems like the better option.

thanks!

**Comment by yogo1212** [comment] 2022-09-23 05:39
> I wonder also why do you start fail2ban-server with --async -b parameters?

That is is process line created by `fail2ban-client start`.
Because the pid file is not written (timely) and the process is daemonised, supervisord or system won't see it.
The process isn't cleaned up between restarts which means that (in my case) supervisord was spawning those processes every ~40 seconds and only seven days (extrapolating from my observations) later would the first server be done closing its fds and create the pid file. Assuming oom-killer doesn't kill it first.

**Comment by sebres** [comment] 2022-09-23 12:52
> that's it!... thanks!

YW

> That is is process line created by fail2ban-client start.

I know, I was just explaining the process of f2b-start in both modes.

> Because the pid file is not written (timely) and the process is daemonised, supervisord or system won't see it.
(Ideally, fail2ban would take it down when it exits..)

No. One simply doesn't need to daemonize it and provide a pid-file if it's running as systemd unit (therefore it is started with `-f` in stock [systemd-service file](https://github.com/fail2ban/fail2ban/blob/2df58c5281facd73e73778a734a90f7d4fe95468/files/fail2ban.service.in#L11)). Forking + daemonization (start with `-b`) was intended for init.d, rc.d and other script based init-daemons.

Anyway the basic error has noting with that (let alone fixed already), so I don't see why we still need to do something here.

**Comment by yogo1212** [comment] 2022-09-23 15:19
> No. One simply doesn't need to daemonize it and provide a pid-file if it's running as systemd unit (therefore it is started with `-f` in stock [systemd-service file](https://github.com/fail2ban/fail2ban/blob/2df58c5281facd73e73778a734a90f7d4fe95468/files/fail2ban.service.in#L11)). Forking + daemonization (start with `-b`) was intended for init.d, rc.d and other script based init-daemons.

> Anyway the basic error has noting with that (let alone fixed already), so I don't see why we still need to do something here.

Oops! That was not my intention!
Sorry for the confusion.. `-f` and unit type "simple" are just to my liking!

Sadly, I'm stuck with supervisord in `docker-mailserver` but the `nofile` option is more than enough until the `/proc/self/fd` fix reaches debian-11/docker-mailserver :-)
(here's what I proposed over there: https://github.com/docker-mailserver/docker-mailserver/pull/2792).

:waffle: :cherries: :beers:

**Comment by polarathene** [comment] 2022-09-25 22:09
[Cross-posting from `docker-mailserver` end](https://github.com/docker-mailserver/docker-mailserver/pull/2792#issuecomment-1257286725
).

The advice is not to set `ulimit` within the container scripts, but use the official `ulimit` config support from running Docker containers itself, doing it within a running container in my experience is not reliable (_for example, try adjusting `ulimit` twice in a container shell, and it'll probably fail the 2nd time_).

**[`docker run` CLI](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit):**

```bash
--ulimit nofile="$(ulimit -Sn):$(ulimit -Sn)"
```

**[`docker-compose.yml`](https://docs.docker.com/compose/compose-file/#ulimits):**
```yml
ulimits:
  nofile:
    soft: $(ulimit -Sn)
    hard: $(ulimit -Hn)
```

With the `docker-compose.yml` I don't think it supports applying the values this way (_although I believe you can use `${SOME_ENV}` instead if you set the ulimit values in your environment or when calling the `docker-compose` command_).

For reference, most modern linux hosts should have a default hard limit of 512k that is set by systemd, and a soft limit of `1024` which is for compatibility / legacy support, software that needs to raise the limit will request so from the system and if it doesn't cause the hard limit to be exceeded it should be granted AFAIK.

When we previously discussed this issue in f2b repo and elsewhere, a million FD is still very quick, but a billion being 1000x more was notably slower. The defaults from systemd that your Docker host should have set will be fine for the docker daemon.
