### ISSUE TITLE
[BR]: problem with blocklist_de

### ISSUE THREAD

**Issue by nazcar4** [fail2ban/fail2ban#2994] opened 2021-04-06 21:24 UTC
I've been applying the fixes mentioned here with that action, but it always gives error 400:
```
[894021]: ERROR 7f33c07c3c08 - exec: ['f2bV_matches = $ 0 \ ncurl --fail --data-urlencode "server=fail2ban2@almogavers.net" --data "apikey = xxxx" --data "service = <service > "--data" ip = 150.158.153.78 "--data-urlencode" logs = $ f2bV_matches "--data \ 'format = text \' --user-agent" fail2ban v0.8.11 "" https: // www .blocklist.de / en / httpreports.html "',' Apr 6 22:42:49 web2 sshd [913015]: pam_unix (sshd: auth): authentication failure; logname = uid = 0 euid = 0 tty = ssh ruser = rhost = 150.158.153.78 \ nApr 6 22:42:52 web2 sshd [913015]: Failed password for invalid user np from 150.158.153.78 port 45226 ssh2 \ nApr 6 22: 48:59 web2 sshd [915578]: Invalid user gabriel from 150.158.153.78 port 45554 ']
2021-04-06 22: 48: 59,828 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: '% Total% Received% Xferd Average Speed ​​Time Time Time Current'
2021-04-06 22: 48: 59,828 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: 'Dload Upload Total Spent Left Speed'
2021-04-06 22: 48: 59,828 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: ''
2021-04-06 22: 48: 59,829 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: '0 0 0 0 0 0 0 0 -: -: - -: -: - - : -: - 0 '
2021-04-06 22: 48: 59,829 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: '100 579 0 0 100 579 0 2631 -: -: - -: -: - - : -: - 2631 '
2021-04-06 22: 48: 59,829 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - stderr: 'curl: (22) The requested URL returned error: 400 Bad Request'
2021-04-06 22: 48: 59,829 fail2ban.utils [894021]: ERROR 7f33c07c3c08 - returned 22
```
I have the action like this:
```ini
# Option: actionban
# Notes .: command executed when banning an IP. Take care that the
# command is executed with Fail2Ban user rights.
# Tags: See jail.conf (5) man page
# Values: CMD
#
actionban = curl --fail --data-urlencode "server = <email>" --data "apikey = <apikey>" --data "service = <service>" --data "ip = <ip>" - data-urlencode "logs = <matches>" --data 'format = text' --user-agent "fail2ban v0.8.11" "https://www.blocklist.de/en/httpreports.html"

# Option: actionunban
```
when I try to pass the line by hand:
```
curl --fail --data-urlencode "server=fail2ban2@almogavers.net" --data "apikey = xxxxx" --data "service = <service>" --data "ip = 148.72.22.191" --data- urlencode "logs = $ f2bV_matches" --data \ 'format = text \' --user-agent "fail2ban v0.8.11" "https://www.blocklist.de/en/httpreports.html" ',' Apr 6 22:50:41 web2 sshd [915643]: pam_unix (sshd: auth): authentication failure; logname = uid = 0 euid = 0 tty = ssh ruser = rhost = 148.72.22.191 \ nApr 6 22:50:42 web2 sshd [915643]: Failed password for invalid user ubuntu from 148.72.22.191 port 38650 ssh2 \ nApr 6 22: 54:12 web2 sshd [917873]: Invalid user bingo from 148.72.22.191 port 50100 ']
```
I see that instead of the url of blocklist.de it tries to pass the data to my own ip, I do not know if it is an error in the action or is that the data was wrong by hand

**Comment by sebres** [comment] 2021-04-07 09:19
See my answer https://github.com/fail2ban/fail2ban/issues/2993#issuecomment-814365639 to same issue.

If you want to try it by hand, either you need to use python interface (and supply an array like descried in my answer above), or you must rewrite it like here:
```diff
- curl --fail --data-urlencode "server=fail2ban2@almogavers.net" --data "apikey = xxxxx" --data "service = <service>" --data "ip = 148.72.22.191" --data- urlencode "logs = $ f2bV_matches" --data \ 'format = text \' --user-agent "fail2ban v0.8.11" "https://www.blocklist.de/en/httpreports.html" ',' Apr 6 22:50:41 web2 sshd [915643]: pam_unix (sshd: auth): authentication failure; logname = uid = 0 euid = 0 tty = ssh ruser = rhost = 148.72.22.191 \ nApr 6 22:50:42 web2 sshd [915643]: Failed password for invalid user ubuntu from 148.72.22.191 port 38650 ssh2 \ nApr 6 22: 54:12 web2 sshd [917873]: Invalid user bingo from 148.72.22.191 port 50100 ']
+ f2bV_matches=' Apr 6 22:50:41 web2 sshd [915643]: pam_unix (sshd: auth): authentication failure; logname = uid = 0 euid = 0 tty = ssh ruser = rhost = 148.72.22.191 \ nApr 6 22:50:42 web2 sshd [915643]: Failed password for invalid user ubuntu from 148.72.22.191 port 38650 ssh2 \ nApr 6 22: 54:12 web2 sshd [917873]: Invalid user bingo from 148.72.22.191 port 50100 '
+ curl --fail --data-urlencode "server=fail2ban2@almogavers.net" --data "apikey = xxxxx" --data "service = <service>" --data "ip = 148.72.22.191" --data- urlencode "logs = $f2bV_matches" --data \ 'format = text \' --user-agent "fail2ban v0.8.11" "https://www.blocklist.de/en/httpreports.html"
```

> `fail2ban v0.8.11`

Not all actions are compatible to v0.8.11 (why do you still use this old version?).
But I'm unsure it has something with the version, because as you can see it seems to fail with newer version too. 
I don't use blocklist.de, so I cannot check what is wrong here.

**Comment by nazcar4** [comment] 2021-04-07 09:53
It is not an old version:
fail2ban-client -V 1.0.1.1
I just put the version by hand because I don't take it automatically.
As for the rest, I do not fully understand it, I am a newbie, but I will get to it.Thank you very much for the answer

**Comment by nazcar4** [comment] 2021-04-07 11:21
With the latest version installed it gives me this error, it is as if some component was not being executed.

13:17:36,184 fail2ban.utils          [3707051]: ERROR   ['f2bV_matches=$0 \ncurl --fail --data-urlencode "server=fail2ban@blocklist.de" --data "apikey=xxxxxx" --data "service=<service>" --data "ip=193.56.29.29" --data-urlencode "logs=$f2bV_matches\n" --data \'format=text\' --user-agent "<agent>" "https://www.blocklist.de/en/httpreports.html"', 'Apr  6 09:30:58 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<mnOiy0i/EuzBOB0d>\nApr  6 09:30:58 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<IjKmy0i/FOzBOB0d>\nApr  6 09:30:59 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<AaKsy0i/FezBOB0d>'] -- failed with [Errno 3] No such process
2021-04-07 13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current'
2021-04-07 13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '                                 Dload  Upload   Total   Spent    Left  Speed'
2021-04-07 13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: ''
2021-04-07 13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0'
2021-04-07 13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    636  0:00:01  0:00:01 --:--:--   636'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    361  0:00:02  0:00:02 --:--:--   361'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    252  0:00:03  0:00:03 --:--:--   252'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    193  0:00:04  0:00:04 --:--:--   193'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    157  0:00:05  0:00:05 --:--:--   157'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    132  0:00:06  0:00:06 --:--:--     0'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    114  0:00:07  0:00:07 --:--:--     0'
2021-04-07 13:17:36,186 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    100  0:00:08  0:00:08 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     89  0:00:09  0:00:09 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     81  0:00:10  0:00:10 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     73  0:00:11  0:00:11 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     67  0:00:12  0:00:12 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     62  0:00:13  0:00:13 --:--:--     0'
2021-04-07 13:17:36,187 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     58  0:00:14  0:00:14 --:--:--     0'
2021-04-07 13:17:36,188 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     54  0:00:15  0:00:15 --:--:--     0'
2021-04-07 13:17:36,188 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     51  0:00:16  0:00:16 --:--:--     0'
2021-04-07 13:17:36,188 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     48  0:00:17  0:00:17 --:--:--     0'
.........
2021-04-07 13:17:36,194 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     14  0:00:59  0:00:59 --:--:--     0'
2021-04-07 13:17:36,194 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- killed with SIGTERM (return code: -15)
2021-04-07 13:17:36,194 fail2ban.actions        [3707051]: ERROR   Failed to execute ban jail 'dovecot' action 'blocklist_de' info 'ActionInfo({'ip': '193.56.29.29', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f40ad81e700>, 'matches': 'Apr  6 09:30:58 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<mnOiy0i/EuzBOB0d>\nApr  6 09:30:58 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<IjKmy0i/FOzBOB0d>\nApr  6 09:30:59 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<AaKsy0i/FezBOB0d>', 'F-*': {'matches': [['', 'Apr  6 09:30:58', ' ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<mnOiy0i/EuzBOB0d>'], 'Apr  6 09:30:58 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<IjKmy0i/FOzBOB0d>', 'Apr  6 09:30:59 ns dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 0 secs): user=<user>, rip=193.56.29.29, lip=192.168.0.2, session=<AaKsy0i/FezBOB0d>'], 'failures': 3, 'user': 'user', 'ip4': '193.56.29.29'}, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f40ad81edc0>})': Error banning 193.56.29.29


ns:~#ps aux | grep fail2ban
root     3707051  0.7  0.1 991056 28524 ?        Ssl  13:16   0:02 /usr/bin/python3 /usr/bin/fail2ban-server -xf start
root     3714223  0.0  0.0   2420   588 ?        Ss   13:21   0:00 /bin/sh -c /etc/fail2ban/filter.d/ignorecommands/ignorehost 45.133.1.221
root     3714225  6.0  0.0  43184 14056 ?        S    13:21   0:00 fail2ban-python /etc/fail2ban/filter.d/ignorecommands/ignorehost 45.133.1.221

**Comment by dhacker29** [comment] 2021-04-07 12:34
The manual reporting procedure is listed here [https://www.blocklist.de/en/httpreports.html?help](url) is it possible that --data 'format=text' might need to be --data 'format=php'?

**Comment by sebres** [comment] 2021-04-07 13:05
> might need to be --data 'format=php'?

I don't use it, so you can try (from shell) to supply it this way.

**Comment by nazcar4** [comment] 2021-04-07 13:14
Format of the return (error messages, OK message ...) = xml, text, php, json 
This is what it says in that help, seen in its forum it seems that the 400 error is given among other cases by few entries in the logs that are sent. I will try uploading the maxretry and I will tell you

**Comment by sebres** [comment] 2021-04-07 16:13
As for your attempts from above:

> `curl: option --data-: is ambiguous`

This is because your format of command seems to be completely invalid (have many spaces): e. g. `--data- urlencode` contains an unexpected space.

> it is as if some component was not being executed ...
```
13:17:36,184 fail2ban.utils          [3707051]: ERROR ... failed with [Errno 3] No such process`
13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0'
13:17:36,185 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0    636  0:00:01  0:00:01 --:--:--   636'
.........
13:17:36,194 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- stderr: '100   838    0     0  100   838      0     14  0:00:59  0:00:59 --:--:--     0'
13:17:36,194 fail2ban.utils          [3707051]: ERROR   7f40ac15a7c0 -- killed with SIGTERM (return code: -15)
```

No, it looks either like some after effect to me, e. g. kill by timeout (default action timeout is 60 seconds)... 
Because curl seems to output `0:00:01 ... 0:00:59`.
May be the server(s) of them are simply overloaded (or even under some DDoS attack), so cannot answer in this time.

**Comment by sebres** [comment] 2021-04-15 22:45
any new findings here?

**Comment by nazcar4** [comment] 2021-04-15 23:10
I still have the same, same error: ERROR 7f04d4674400 - stderr: 'curl: (22) The requested URL returned error: 400 Bad Request'
I no longer know where to look or where to ask

**Comment by sebres** [comment] 2021-04-16 09:34
what exactly did you try to adjust?

**Comment by nazcar4** [comment] 2021-04-16 09:50
Well, it is currently configured that on 5 both ssh postfix postfix-sasl fail to notify blocklist.de, but I see the aforementioned error in the fail2ban logs.I am trying to write in the blocklist.de forum but it gives an error when recovering the password and before a new registration it is necessary approval from some admin, so that path I have closed

**Comment by sebres** [comment] 2021-04-16 10:25
I mean that because neither I have blocklist.de access (apikey), nor the time to test it, I am reliant on community or some contributors which could find out what is wrong there and also test different variants from console.
One can't make something out of nothing.

From other side there is a help page describing a report request - https://www.blocklist.de/en/httpreports.html?help
If I interpret this info correctly, fail2ban action works as it is described. You can also test it directly from shell (adjust server and apikey before you try it):
```
server=fail2ban@blocklist.de
apikey=xxxxxx
curl --fail --data-urlencode \
  "server=$server" --data "apikey=$apikey" \
   --data "service=sshd" --data "ip=192.0.2.1" --data-urlencode "logs=availability test" --data 'format=text' 
   --user-agent "fail2ban" "https://www.blocklist.de/en/httpreports.html"
```

By the way looking again at https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/action.d/blocklist_de.conf#L57
I found that in your [example above](https://github.com/fail2ban/fail2ban/issues/2994#issuecomment-814830700) the values of `<service>` and `<agent>` are not interpolated.
This can mean that you did not supply it to the action. Correct example for the action parameters can be found here:
https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/jail.conf#L252

**Comment by nazcar4** [comment] 2021-04-16 10:27
after set timeout = 600 in jail.local [DEFAULT] and level set to debug i see this in logs

ActionInfo.<lambda> at 0x7fdd01cb47b8>, 'matches': 'Apr 11 22:00:02 web2 sshd[54293]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=159.75.91.163  user=root\nApr 11 22:00:03 web2 sshd[54293]: Failed password for root from 159.75.91.163 port 38510 ssh2\nApr 11 22:02:31 web2 sshd[57498]: Invalid user josip from 159.75.91.163 port 48026', 'F-*': {'matches': ['Apr 11 22:00:02 web2 sshd[54293]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=159.75.91.163  user=root', 'Apr 11 22:00:03 web2 sshd[54293]: Failed password for root from 159.75.91.163 port 38510 ssh2', 'Apr 11 22:02:31 web2 sshd[57498]: Invalid user josip from 159.75.91.163 port 48026'], 'failures': 3, 'mlfid': ' web2 sshd[49825]: ', 'alt_user': '', 'ip4': '159.75.91.163', 'user': 'root', 'users': "['root']"}, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7fdd01cb4e18>})': Error banning 159.75.91.163
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/fail2ban/server/actions.py", line 518, in __checkBan
    action.ban(aInfo)
  File "/usr/local/lib/python3.7/dist-packages/fail2ban/server/action.py", line 568, in ban
    raise RuntimeError("Error banning %(ip)s" % aInfo)
RuntimeError: Error banning 159.75.91.163

is it a bug in python or does it directly indicate error 400 in curl?

**Comment by nazcar4** [comment] 2021-04-16 10:35
> I mean that because neither I have blocklist.de access (apikey), nor the time to test it, I am reliant on community or some contributors which could find out what is wrong there and also test different variants from console.
> One can't make something out of nothing.
> 
> From other side there is a help page describing a report request - https://www.blocklist.de/en/httpreports.html?help
> If I interpret this info correctly, fail2ban action works as it is described. You can also test it directly from shell (adjust server and apikey before you try it):
> 
> ```
> server=fail2ban@blocklist.de
> apikey=xxxxxx
> curl --fail --data-urlencode \
>   "server=$server" --data "apikey=$apikey" \
>    --data "service=sshd" --data "ip=192.0.2.1" --data-urlencode "logs=availability test" --data 'format=text' 
>    --user-agent "fail2ban" "https://www.blocklist.de/en/httpreports.html"
> ```
> 
> By the way looking again at
> 
> https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/action.d/blocklist_de.conf#L57
> 
> 
> I found that in your [example above](https://github.com/fail2ban/fail2ban/issues/2994#issuecomment-814830700) the values of `<service>` and `<agent>` are not interpolated.
> This can mean that you did not supply it to the action. Correct example for the action parameters can be found here:
> https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/jail.conf#L252

Everything revised again with the examples that you have given me and the happy error 400 in the curl is still there

**Comment by sebres** [comment] 2021-04-16 10:46
> is it a bug in python or does it directly indicate error 400 in curl?

Neither it is a bug, nor it is something unexpected - if action fails, in debug mode fail2ban will show a traceback info (with callstack to be able to recognize the issue if it is something caused by fail2ban).
Here it is definitely not an error of fail2ban (or its action).

> Everything revised again with the examples that you have given me and the happy error 400 in the curl is still there

Then unfortunately we cannot do here something... and I can only suggest - don't use this service.

**Comment by nazcar4** [comment] 2021-04-16 10:51
I think that effectively in the end I will stop using blocklist.de, thank you very much for everything

**Comment by sebres** [comment] 2021-04-16 10:56
Then lets close it as 3rd party issue, unless some new findings are there.

**Closed by sebres** 2021-04-16 10:56 UTC
Labels: 3rd party  issue, moreinfo

**Comment by nazcar4** [comment] 2021-04-17 21:41
solved adding to each jail the following line

         sendmail-whois-lines [name = dovecot, dest=fail2ban@blocklist.de, sender=fail2ban@xxxxxx]

**Comment by sebres** [comment] 2021-04-20 15:01
> solved adding to each jail the following line
> `sendmail-whois-lines ...`

Nope. This is definitely not a solution.
Adding a second (or third) action can not and does not solve any issue with another action.
As already said it looks rather like a timing problem (especially because several things like timeout etc indicating that).

If it is not solved by service blocklist.de and it is really something like a certain delay (caused by an additional action), then almost the same workaround would be to add something like `sleep 1` in `actionban` of blocklist_de.
But neither it is a "solution", nor it is advisable configuration (it's like throttle the driving speed using continuously applied handbrake).

**Comment by nazcar4** [comment] 2021-04-20 15:06
227 / 5000
Resultados de traducción
Adding this option the error in curl has disappeared, and the data is being sent, by mail, to blocklist.de
I understand that it is another option totally different to sending by curl, but even so, now the data is being sent.

**Comment by nazcar4** [comment] 2021-04-20 15:06
Adding this option the error in curl has disappeared, and the data is being sent, by mail, to blocklist.de
I understand that it is another option totally different to sending by curl, but even so, now the data is being sent.
