### ISSUE TITLE
Fails to output <matches> for sendmail filters?

### ISSUE THREAD

**Issue by Jas0n99** [fail2ban/fail2ban#2493] opened 2019-08-05 13:43 UTC
I was doing a little testing and for some odd reason both the **sendmail-auth** & **sendmail-reject** filters fail to output `<matches>` data. It catches & bans properly, just no matches output. At first I thought this was a fluke in my script, but I also checked the sqlite DB and the matches were empty there too...

CentOS 6, Running F2B 0.11

Only .local customization to those files was having to adjust the '_daemon' variable. Otherwise it's stock filter code.

No issues with other filters or fields... very strange! FYI, I was testing output of:

ip, family, ip-rev, ip-host, bancount, name, failures, ipfailures, ipjailfailures, matches

Is there any way I can debug this further to see what's going on (or not going on)?

**Comment by sebres** [comment] 2019-08-19 10:35
> Fails to output <matches> for sendmail filters?

What exactly "fails to output" means? Do you see an error or it is simply empty?

> I was doing a little testing and for some odd reason both the sendmail-auth & sendmail-reject filters fail to output `<matches>` data. It catches & bans properly, just no matches output.

Filters don't output anything. But actions doing that.

1. So which action do you use to do "output" `<matches>`? If it is your own or custom action using `<matches>` please provide the config or parameters dump like result of `fail2ban-client -d | grep sendmail`

2. Which backend is used for this jails - file-related (`pyinotify`/`polling`) or journal (`systemd`)? Take a look at start of fail2ban.log for message `Jail 'sendmail-auth' uses`...

Also note similar issues, like https://github.com/fail2ban/fail2ban/issues/2310#issuecomment-448943726, #2488 etc.

**Comment by Jas0n99** [comment] 2019-08-19 17:36
No errors (My usual loglevel is set to NOTICE)...  I can bump it up if need be.

All jails use pyinotify. I actually set `journalmatch =` in several of my .local files just to avoid the annoying line in the logfile (I forgot what it said exactly) for filters that had it configured.

I first noticed it when using the "abuseipdb" action. Only thing I did was create a .local to add my key (Well, technically and to update the action to AIPDB's API v2 format that has a couple minor changes, and add `norestored = 1`). That's when I noticed that <matches> would be empty from the abuseipdb action for new bans triggered by the **sendmail-reject** filter, but was correctly populated for other filters (like the apache ones, both stock & custom). 

I know I said **sendmail-auth** also previously, but I just checked the DB and there aren't any bans from that filter so I can't confirm anything about it (sorry).

Anyhow, I checked the **fail2ban.sqlite3** database and likewise noticed the "matches" data was missing from there too. A couple examples from **sendmail-reject**:
`{"matches": [], "failures": 1, "mlfid": " master mimedefang.pl[20559]: x7ICuRRt031173: ", "ip4": "121.144.226.108"}`
`{"matches": [], "failures": 1, "mlfid": " master sendmail[9546]: x7J0r0AM009546: ", "ip4": "23.247.75.250", "email": "<info@simpcomputer.pw>"}`

Whereas with other filters, for example **apache-fakegooglebot**, matches is populated correctly:
`{"matches": [["95.216.249.71 - - [", "19/Aug/2019:01:06:27 -0500", "] \"GET [MUNGED] HTTP/1.0\" 426 110 \"-\" \"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)\""]], "failures": 1, "ip4": "95.216.249.71"}`

Or even **dovecot**:
`{"matches": [["", "Aug 13 06:13:08", " master dovecot-auth: pam_unix(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser= rhost=35.163.31.145 "]], "failures": 1, "ip4": "35.163.31.145"}`

So that's when I created a quick & simple little test action that output all the variables to a file so I could see what was going on. I appended it to my list of **banaction=** for each filter. (Which I have actions for ipset, abuseipdb, and badips.)

```
[Definition]
norestored = 1
actionstart =
actionflush =
actionstop =
actioncheck =
actionban = printf %%b "IP:<ip> | Family: <family> | IPRev: <ip-rev> | Hostname: <ip-host> | Bancount: <bancount>\n" <to_target>
            printf %%b "Name: <name> | Failures: <failures> | IPFailures: <ipfailures> | IPJailFailures: <ipjailfailures>\n" <to_target>
            printf %%b "Matches:\n" <to_target>
            printf %%b "<matches>" <to_target>
            printf %%b "\n\n" <to_target>
actionunban =
[Init]
target = /var/log/fail2ban/debug.log
to_target = >> <target>
```
Everything gets populated / written to the file correctly, except when it comes to actions under the **sendmail-reject** filter... The <matches> are always empty.

**Comment by sebres** [comment] 2019-08-20 08:42
Weird... I'll take a closer look here. 
Thanks.

**Comment by sebres** [comment] 2019-08-22 19:54
Hmm... Still don't follow what is wrong there.
**I cannot reproduce this at all** neither with `sendmail-auth` nor with `sendmail-reject` (tested also with current 0.10 and 0.11).
Also I wrote special test `testServerJails_Sendmail` in e547927075eee62ab087899ebcc6790bd08f685e testing this jails, and applied it against both major branches... Nothing - it works on my side as expected.

Remembering an RFE #2402, which could restrict the `matches`, I have only one idea...
I could imagine your situation if you would configure for both jails `maxmatches = 0` (or even `maxretry = 0` which used per default as `maxmatches` after this PR got merged).

So can you check `grep -R maxmatches /etc/fail2ban/`?
And even if it is still default (`maxmatches = %(maxretry)s`), what do you have configured as `maxretry` for this jails.
Or better provide output of `fail2ban-client -d | grep sendmail` (as I already asked you above).

**Comment by sebres** [comment] 2019-08-22 19:56
Also in travis the test is succeeded (e. g. https://travis-ci.org/sebres/fail2ban/jobs/575501482#L1025)

**Comment by Jas0n99** [comment] 2019-08-22 20:23
`grep -R maxmatches /etc/fail2ban/` doesn't find anything.

I have them set to `maxretry = 1` for both jails.

Here's the output from `fail2ban-client -d | grep sendmail` (I removed a couple bits of personally identifiable info):
> ['add', 'sendmail-reject', 'pyinotify']
> ['set', 'sendmail-reject', 'prefregex', '^<F-MLFID>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?(?:(sendmail|mimedefang(\\.pl)?))(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?(?:(sendmail|mimedefang(\\.pl)?))(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:\\w{14}: )?</F-MLFID><F-CONTENT>.+</F-CONTENT>$']
> ['multi-set', 'sendmail-reject', 'addfailregex', ['^ruleset=check_(rcpt|mail), arg1=(?P<email><\\S+@\\S+>), relay=(\\S+ )?\\[<HOST>\\](?: \\(may be forged\\))?, reject=(550 5\\.7\\.1 (?P=email)\\.\\.\\. Relaying denied\\. (IP name possibly forged \\[(\\d+\\.){3}\\d+\\]|Proper authentication required\\.|IP name lookup failed \\[(\\d+\\.){3}\\d+\\])|553 5\\.1\\.8 (?P=email)\\.\\.\\. Domain of sender address \\S+ does not exist|550 5\\.[71]\\.1 (?P=email)\\.\\.\\. (Rejected: .*|User unknown))$', '^ruleset=check_relay, arg1=(?P<dom>\\S+), arg2=<HOST>, relay=((?P=dom) )?\\[(\\d+\\.){3}\\d+\\](?: \\(may be forged\\))?, reject=421 4\\.3\\.2 (Connection rate limit exceeded\\.|Too many open connections\\.)$', '^rejecting commands from (\\S* )?\\[<HOST>\\] due to pre-greeting traffic( after \\d+ seconds)?$', '^(?:\\S+ )?\\[<HOST>\\]: (?:(?i)expn|vrfy) \\S+ \\[rejected\\]$', '^<[^@]+@[^>]+>\\.\\.\\. No such user here$', '^<F-NOFAIL>from=<[^@]+@[^>]+></F-NOFAIL>, size=\\d+, class=\\d+, nrcpts=\\d+, bodytype=\\w+, proto=E?SMTP, daemon=MTA, relay=\\S+ \\[<HOST>\\]$', '^Rejecting for no reverse DNS <HOST>$', '^Blocking dynamic looking host \\S+ from <HOST>$', '^(?:\\S+ )?\\[<HOST>\\](?: \\(may be forged\\))? did not issue MAIL/EXPN/VRFY/ETRN during connection to (?:TLS)?(MTA|MSA)$', '^lost input channel from (?:\\S+ )?\\[<HOST>\\](?: \\(may be forged\\))? to (?:TLS)?MTA after data$', '^(?:\\S+ )?\\[<HOST>\\](?: \\(may be forged\\))? did not issue (?:[A-Z]{4}[/ ]?)+during connection to M(?:TA|SP)(?:-\\w+)?$']]
> ['set', 'sendmail-reject', 'datepattern', '{^LN-BEG}']
> ['set', 'sendmail-reject', 'bantime.overalljails', True]
> ['set', 'sendmail-reject', 'bantime.increment', True]
> ['set', 'sendmail-reject', 'addlogpath', '/var/log/maillog', 'head']
> ['set', 'sendmail-reject', 'maxretry', 1]
> ['set', 'sendmail-reject', 'addignoreip', '127.0.0.1/8']
> ['set', 'sendmail-reject', 'bantime.maxtime', '90d']
> ['set', 'sendmail-reject', 'usedns', 'warn']
> ['set', 'sendmail-reject', 'logencoding', 'auto']
> ['set', 'sendmail-reject', 'bantime', '5d']
> ['set', 'sendmail-reject', 'ignorecommand', '']
> ['set', 'sendmail-reject', 'findtime', '30m']
> ['set', 'sendmail-reject', 'addaction', 'iptables-ipset-proto4']
> ['multi-set', 'sendmail-reject', 'action', 'iptables-ipset-proto4', [['actionunban', 'if ipset --quiet --test FAIL2BAN <ip>; then ipset --quiet --del FAIL2BAN <ip>; fi'], ['actionflush', 'ipset --quiet --flush FAIL2BAN'], ['actionban', 'if ! ipset --quiet --test FAIL2BAN <ip>; then ipset --quiet --add FAIL2BAN <ip>; fi'], ['actionstart', ''], ['actionstop', ''], ['iptables', 'iptables <lockingopt>'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'sendmail-reject'], ['chain', 'INPUT'], ['port', 'ssh'], ['lockingopt', ''], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['actname', 'iptables-ipset-proto4']]]
> ['set', 'sendmail-reject', 'addaction', 'badips']
> ['multi-set', 'sendmail-reject', 'action', 'badips', [['norestored', True], ['actionban', "/etc/fail2ban/action.d/wrapper_submit_abuse 'badips' '<ip>' 'spam'"], ['category', 'spam'], ['actname', 'badips'], ['name', 'sendmail-reject']]]
> ['set', 'sendmail-reject', 'addaction', 'abuseipdb']
> ['multi-set', 'sendmail-reject', 'action', 'abuseipdb', [['actionunban', ''], ['norestored', True], ['actionstop', ''], ['actionstart', ''], ['actionban', '/etc/fail2ban/action.d/wrapper_submit_abuse \'abuseipdb\' \'<ip>\' \'11,18\' "Fail2Ban Ban Triggered\\nSMTP Abuse Attempt"'], ['actioncheck', ''], ['category', '11,18'], ['apikey', ''], ['protocol', 'tcp'], ['name', 'sendmail-reject'], ['chain', 'INPUT'], ['reason', 'SMTP Abuse Attempt'], ['actname', 'abuseipdb'], ['abuseipdb_apikey', ''], ['port', 'smtp,465,submission']]]
> ['add', 'sendmail-auth', 'pyinotify']
> ['set', 'sendmail-auth', 'addfailregex', '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?(?:sendmail)(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?(?:sendmail)(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?\\w{14}: (\\S+ )?\\[<HOST>\\]( \\(may be forged\\))?: possible SMTP attack: command=AUTH, count=\\d+$']
> ['set', 'sendmail-auth', 'datepattern', '{^LN-BEG}']
> ['set', 'sendmail-auth', 'bantime.overalljails', True]
> ['set', 'sendmail-auth', 'bantime.increment', True]
> ['set', 'sendmail-auth', 'addlogpath', '/var/log/maillog', 'head']
> ['set', 'sendmail-auth', 'maxretry', 1]
> ['set', 'sendmail-auth', 'addignoreip', '127.0.0.1/8']
> ['set', 'sendmail-auth', 'bantime.maxtime', '90d']
> ['set', 'sendmail-auth', 'usedns', 'warn']
> ['set', 'sendmail-auth', 'logencoding', 'auto']
> ['set', 'sendmail-auth', 'bantime', '5d']
> ['set', 'sendmail-auth', 'ignorecommand', '']
> ['set', 'sendmail-auth', 'findtime', '30m']
> ['set', 'sendmail-auth', 'addaction', 'iptables-ipset-proto4']
> ['multi-set', 'sendmail-auth', 'action', 'iptables-ipset-proto4', [['actionunban', 'if ipset --quiet --test FAIL2BAN <ip>; then ipset --quiet --del FAIL2BAN <ip>; fi'], ['actionflush', 'ipset --quiet --flush FAIL2BAN'], ['actionban', 'if ! ipset --quiet --test FAIL2BAN <ip>; then ipset --quiet --add FAIL2BAN <ip>; fi'], ['actionstart', ''], ['actionstop', ''], ['iptables', 'iptables <lockingopt>'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'sendmail-auth'], ['chain', 'INPUT'], ['port', 'ssh'], ['lockingopt', ''], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['actname', 'iptables-ipset-proto4']]]
> ['set', 'sendmail-auth', 'addaction', 'badips']
> ['multi-set', 'sendmail-auth', 'action', 'badips', [['norestored', True], ['actionban', "/etc/fail2ban/action.d/wrapper_submit_abuse 'badips' '<ip>' 'cyrusauth'"], ['category', 'cyrusauth'], ['actname', 'badips'], ['name', 'sendmail-auth']]]
> ['set', 'sendmail-auth', 'addaction', 'abuseipdb']
> ['multi-set', 'sendmail-auth', 'action', 'abuseipdb', [['actionunban', ''], ['norestored', True], ['actionstop', ''], ['actionstart', ''], ['actionban', '/etc/fail2ban/action.d/wrapper_submit_abuse \'abuseipdb\' \'<ip>\' \'11,18\' "Fail2Ban Ban Triggered\\nSMTP Bruteforce Attempt"'], ['actioncheck', ''], ['category', '11,18'], ['apikey', ''], ['protocol', 'tcp'], ['name', 'sendmail-auth'], ['chain', 'INPUT'], ['reason', 'SMTP Bruteforce Attempt'], ['actname', 'abuseipdb'], ['abuseipdb_apikey', ''], ['port', 'submission,465,smtp']]]
> ['start', 'sendmail-reject']
> ['start', 'sendmail-auth']

**Comment by sebres** [comment] 2019-08-23 07:24
OK, I don't see it also with your configuration  (`maxretry = 1`, incremental etc) - in this case I see exactly 1 match in the banned ticket (and in action output stdout/file as well as in the database).

So I'd suggest to update your fail2ban version.

**Comment by Jas0n99** [comment] 2019-08-23 12:42
Okay, I'll try to pull the latest .11 from git this weekend and see if there is any difference. I'll let you know the outcome.

**Comment by Jas0n99** [comment] 2019-09-02 01:44
Okay, finally got a chance to update, I lost my custom src rpm so I had to re-create everything. I was running a .11 build from 2017 (didn't think it was that long ago but the rpm -qi doesn't lie)!

First, I did end up with a hit on 'sendmail-auth' before updating and it had contents for <matches>, yay!

Anyhow, after updating, got a hit on the sendmail-reject filter, and it works now! I checked the sqlite db and it has the "matches" data populated! :)

I feel like such an idiot. Thanks for all your hard work and putting up with me! Next time if I run into an issue I'll be sure to pull a current build and update first!

One last question, I searched all over and before I go diving into the code, would you mind telling me what the difference is between the "bans" and "bips" tables are in the sqlite database?

**Comment by sebres** [comment] 2019-09-02 09:32
Glad it works... Thus close.

> the difference is between the "bans" and "bips" tables are in the sqlite database?

Table `bans` contains all banned tickets of jail/IP, table `bips` contains only bad IPs and only a last banned ticket per jail.
Additionally purge of tables is different. Table `bans` is affected by `purgertime` directly, where entry from `bips` get removed after 3x `purgertime` only.

**Closed by sebres** 2019-09-02 09:32 UTC
