### ISSUE TITLE
[BR]: Unexpected log message

### ISSUE THREAD

**Issue by bgamrat** [fail2ban/fail2ban#3626] opened 2023-11-12 23:50 UTC
### Environment:

- Fail2Ban version  : Fail2Ban v0.11.2
- OS, including release name/version : 
CentOS Linux release 7.9.2009 (Core)
Derived from Red Hat Enterprise Linux 7.9 (Source)
Linux 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Unexpected log message

#### Steps to reproduce

This was found while checking log files to create slides for a LInux class

#### Expected behavior

No 'Failed to execute' message

#### Observed behavior

Unusually message in log file - 'Failed to execute'

#### Any additional information

Ban succeeded

### Configuration, dump and another helpful excerpts

None 

#### Any customizations done to /etc/fail2ban/ configuration

```
[DEFAULT]
banaction = firewallcmd-rich-rules[actiontype=<multiport>]
banaction_allports = firewallcmd-rich-rules[actiontype=<allports>]

more sshd.local
[sshd]
enabled = true
port = ssh
#action = firewallcmd-ipset
logpath = %(sshd_log)s
findtime = 7200
maxretry = 3 
bantime = 86400
#filter   = sshd-root
```

#### Relevant parts of /var/log/fail2ban.log file:

```
[fail2ban]$ sudo grep '134.17.94.229' /var/log/fail2ban.log
2023-11-12 17:32:21,797 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:32:21
2023-11-12 17:32:23,381 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:32:23
2023-11-12 17:34:54,386 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:34:54
2023-11-12 17:34:54,535 fail2ban.actions        [840]: NOTICE  [sshd] Ban 134.17.94.229
2023-11-12 17:34:56,263 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:34:56
2023-11-12 17:35:54,572 fail2ban.utils          [840]: ERROR   7f4c7c7c3250 -- exec: ports="$(echo 'ssh' | sed s/:/-/g)"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule="rule family='ipv4' source address='134.17.94.229' port port='$p' protocol='tcp' reject type='icmp-port-unreachable'"; done
2023-11-12 17:35:54,773 fail2ban.utils          [840]: ERROR   ports="$(echo 'ssh' | sed s/:/-/g)"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule="rule family='ipv4' source address='134.17.94.229' port port='$p' protocol='tcp' reject type='icmp-port-unreachable'"; done -- failed with [Errno 3] No such process
2023-11-12 17:35:54,774 fail2ban.actions        [840]: ERROR   Failed to execute ban jail 'sshd' action 'firewallcmd-rich-rules' info 'ActionInfo({'ip': '134.17.94.229', 'fid': <function <lambda> at 0x7f4c7d754140>, 'family': 'inet4', 'raw-ticket': <function <lambda> at 0x7f4c7d7546e0>})': Error banning 134.17.94.229
2023-11-12 17:36:03,667 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:36:03
2023-11-12 17:36:05,685 fail2ban.filter         [840]: INFO    [sshd] Found 134.17.94.229 - 2023-11-12 17:36:05
2023-11-12 17:36:24,585 fail2ban.actions        [840]: WARNING [sshd] 134.17.94.229 already banned
```

##### Other entries in same log file
```
2023-11-12 04:48:27,653 fail2ban.filter         [840]: INFO    [sshd] Found 202.157.189.179 - 2023-11-12 04:48:27
2023-11-12 04:48:28,988 fail2ban.filter         [840]: INFO    [sshd] Found 202.157.189.179 - 2023-11-12 04:48:28
2023-11-12 04:48:29,480 fail2ban.actions        [840]: NOTICE  [sshd] Ban 202.157.189.179

2023-11-12 04:50:26,074 fail2ban.filter         [840]: INFO    [sshd] Found 49.212.203.232 - 2023-11-12 04:50:26
2023-11-12 04:50:26,274 fail2ban.actions        [840]: NOTICE  [sshd] Ban 49.212.203.232
2023-11-12 04:50:28,433 fail2ban.filter         [840]: INFO    [sshd] Found 49.212.203.232 - 2023-11-12 04:50:28
2023-11-12 04:50:28,614 fail2ban.filter         [840]: INFO    [sshd] Found 43.156.131.197 - 2023-11-12 04:50:28
2023-11-12 04:50:28,955 fail2ban.actions        [840]: NOTICE  [sshd] Ban 43.156.131.197
2023-11-12 04:50:39,363 fail2ban.filter         [840]: INFO    [sshd] Found 129.226.144.58 - 2023-11-12 04:50:39
2023-11-12 04:50:39,715 fail2ban.actions        [840]: NOTICE  [sshd] Ban 129.226.144.58
2023-11-12 04:51:11,624 fail2ban.filter         [840]: INFO    [sshd] Found 43.143.248.69 - 2023-11-12 04:51:11
2023-11-12 04:51:12,261 fail2ban.actions        [840]: NOTICE  [sshd] Ban 43.143.248.69
```

#### Relevant lines from monitored log files:

```
Nov 12 17:32:21 www sshd[21361]: reverse mapping checking getaddrinfo for 229-94-17-134-cloud.mts.by [134.17.94.229] failed - POSSIBLE BREAK-IN ATTEMPT!
Nov 12 17:32:21 www sshd[21361]: Invalid user odoo from 134.17.94.229 port 59160
Nov 12 17:32:21 www sshd[21361]: input_userauth_request: invalid user odoo [preauth]
Nov 12 17:32:21 www sshd[21361]: pam_unix(sshd:auth): check pass; user unknown
Nov 12 17:32:21 www sshd[21361]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=134.17.94.229
Nov 12 17:32:23 www sshd[21361]: Failed password for invalid user odoo from 134.17.94.229 port 59160 ssh2
Nov 12 17:32:23 www sshd[21361]: Received disconnect from 134.17.94.229 port 59160:11: Bye Bye [preauth]
Nov 12 17:32:23 www sshd[21361]: Disconnected from 134.17.94.229 port 59160 [preauth]

Nov 12 17:34:54 www sshd[21591]: reverse mapping checking getaddrinfo for 229-94-17-134-cloud.mts.by [134.17.94.229] failed - POSSIBLE BREAK-IN ATTEMPT!
Nov 12 17:34:54 www sshd[21591]: Invalid user deployer from 134.17.94.229 port 59161
Nov 12 17:34:54 www sshd[21591]: input_userauth_request: invalid user deployer [preauth]
Nov 12 17:34:54 www sshd[21591]: pam_unix(sshd:auth): check pass; user unknown
Nov 12 17:34:54 www sshd[21591]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=134.17.94.229

Nov 12 17:34:56 www sshd[21591]: Failed password for invalid user deployer from 134.17.94.229 port 59161 ssh2
Nov 12 17:34:56 www sshd[21591]: Received disconnect from 134.17.94.229 port 59161:11: Bye Bye [preauth]
Nov 12 17:34:56 www sshd[21591]: Disconnected from 134.17.94.229 port 59161 [preauth]
Nov 12 17:36:03 www sshd[21669]: reverse mapping checking getaddrinfo for 229-94-17-134-cloud.mts.by [134.17.94.229] failed - POSSIBLE BREAK-IN ATTEMPT!
Nov 12 17:36:03 www sshd[21669]: Invalid user web from 134.17.94.229 port 59162
Nov 12 17:36:03 www sshd[21669]: input_userauth_request: invalid user web [preauth]
Nov 12 17:36:03 www sshd[21669]: pam_unix(sshd:auth): check pass; user unknown
Nov 12 17:36:03 www sshd[21669]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=134.17.94.229
Nov 12 17:36:05 www sshd[21669]: Failed password for invalid user web from 134.17.94.229 port 59162 ssh2
Nov 12 17:36:05 www sshd[21669]: Received disconnect from 134.17.94.229 port 59162:11: Bye Bye [preauth]
Nov 12 17:36:05 www sshd[21669]: Disconnected from 134.17.94.229 port 59162 [preauth]
```

**Comment by sebres** [comment] 2023-11-16 00:40
Basically the issue is - the actions timeouts after 60 seconds (and fail2ban stops its execution). As you can see the ban starts at 17:34:54 and error (well basically an aftereffect of timeout) at 17:35:54, exactly 1 minute later.
Although I already saw similar issues, I have no idea why firewalld may hang or which reason can cause that, because neither use it nor recommend to use intermediate layers like that as fail2ban actions (always use native net-filter instead).

Closed as duplicate of #3044 or a 3rd party issue.

**Closed by sebres** 2023-11-16 00:40 UTC
Labels: 3rd party  issue, closed-as-duplicate
