### ISSUE TITLE
Fails to notice new lines in monitored logfile and fails to ban ip

### ISSUE THREAD

**Issue by JeffZwolle** [fail2ban/fail2ban#2156] opened 2018-06-16 17:57 UTC
Ubuntu 16.04.04 server

filter.d/openvpnas.conf
```INI
failregex = <HOST>:[0-9]+\sSENT\sCONTROL\s.*?AUTH_FAILED.*
ignoreregex = <HOST>:[0-9]+\sSENT\sCONTROL\s.*?AUTH_FAILED,SESSION
```
jail.d/openvpnas.conf
```INI
[openvpnasudp]
enabled  = true
port     = 1194
protocol = udp
filter   = openvpnas
logpath  = /var/log/openvpnas.log
maxretry = 3
bantime  = 300
findtime = 600

[openvpnastcp]
enabled  = true
port     = 7002
protocol = tcp
filter   = openvpnas
logpath  = /var/log/openvpnas.log
maxretry = 3
bantime  = 300
findtime = 600
```
/var/log/fail2ban.log
```
2018-06-16 19:48:06,328 fail2ban.server         [1808]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.3
2018-06-16 19:48:06,329 fail2ban.database       [1808]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2018-06-16 19:48:06,333 fail2ban.jail           [1808]: INFO    Creating new jail 'sshd'
2018-06-16 19:48:06,355 fail2ban.jail           [1808]: INFO    Jail 'sshd' uses pyinotify
2018-06-16 19:48:06,368 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,373 fail2ban.jail           [1808]: INFO    Initiated 'pyinotify' backend
2018-06-16 19:48:06,378 fail2ban.filter         [1808]: INFO    Added logfile = /var/log/auth.log
2018-06-16 19:48:06,380 fail2ban.actions        [1808]: INFO    Set banTime = 600
2018-06-16 19:48:06,381 fail2ban.filter         [1808]: INFO    Set findtime = 600
2018-06-16 19:48:06,381 fail2ban.filter         [1808]: INFO    Set maxRetry = 5
2018-06-16 19:48:06,382 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,382 fail2ban.filter         [1808]: INFO    Set maxlines = 10
2018-06-16 19:48:06,440 fail2ban.server         [1808]: INFO    Jail sshd is not a JournalFilter instance
2018-06-16 19:48:06,445 fail2ban.jail           [1808]: INFO    Creating new jail 'openvpnasudp'
2018-06-16 19:48:06,445 fail2ban.jail           [1808]: INFO    Jail 'openvpnasudp' uses pyinotify
2018-06-16 19:48:06,447 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,451 fail2ban.jail           [1808]: INFO    Initiated 'pyinotify' backend
2018-06-16 19:48:06,454 fail2ban.filter         [1808]: INFO    Added logfile = /var/log/openvpnas.log
2018-06-16 19:48:06,456 fail2ban.actions        [1808]: INFO    Set banTime = 300
2018-06-16 19:48:06,457 fail2ban.filter         [1808]: INFO    Set findtime = 600
2018-06-16 19:48:06,457 fail2ban.filter         [1808]: INFO    Set maxRetry = 3
2018-06-16 19:48:06,458 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,464 fail2ban.jail           [1808]: INFO    Creating new jail 'openvpnastcp'
2018-06-16 19:48:06,464 fail2ban.jail           [1808]: INFO    Jail 'openvpnastcp' uses pyinotify
2018-06-16 19:48:06,465 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,470 fail2ban.jail           [1808]: INFO    Initiated 'pyinotify' backend
2018-06-16 19:48:06,473 fail2ban.filter         [1808]: INFO    Added logfile = /var/log/openvpnas.log
2018-06-16 19:48:06,475 fail2ban.actions        [1808]: INFO    Set banTime = 300
2018-06-16 19:48:06,476 fail2ban.filter         [1808]: INFO    Set findtime = 600
2018-06-16 19:48:06,476 fail2ban.filter         [1808]: INFO    Set maxRetry = 3
2018-06-16 19:48:06,477 fail2ban.filter         [1808]: INFO    Set jail log file encoding to UTF-8
2018-06-16 19:48:06,484 fail2ban.jail           [1808]: INFO    Jail 'sshd' started
2018-06-16 19:48:06,491 fail2ban.jail           [1808]: INFO    Jail 'openvpnasudp' started
2018-06-16 19:48:06,495 fail2ban.jail           [1808]: INFO    Jail 'openvpnastcp' started
```
fail2ban-regex -v --print-all-matched /var/log/openvpnas.log /etc/fail2ban/filter.d/openvpnas.conf
(partially displayed)
```
|  2018-06-16 19:48:53+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:53 2018 62.140.132.14:3956 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:54+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:54 2018 62.140.132.14:24617 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:55+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:55 2018 62.140.132.14:9946 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:56+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:56 2018 62.140.132.14:17891 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:57+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:57 2018 62.140.132.14:28589 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:58+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:58 2018 62.140.132.14:8555 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
|  2018-06-16 19:48:59+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:59 2018 62.140.132.14:6463 SENT CONTROL [jeff]: 'AUTH_FAILED' (status=1)"
```
There will not come up any new log information in fail2ban.log

The information here is just an example.
Already tried: restarting fail2ban service, rebooting, deleting /var/lib/fail2ban/fail2ban.sqlite3

At some point it did function (ban-notices came up in fail2ban.log), but then the ban (which did come up in fail2ban.log) did not really ban the ipaddress. So I added some action in jail.d/openvpnas.conf . But then no new lines in fail2ban.log . So I removed the actions again and restarted fail2ban service. And then no new lines in fail2ban.log for failed login attempts.

Bans for sshd are functioning ok.

**Comment by masterkain** [comment] 2018-06-18 19:02
I have the same issue, maybe some package upgrade?

**Comment by masterkain** [comment] 2018-06-18 19:18
I installed latest version from git and that works.

**Comment by sebres** [comment] 2018-06-18 19:18
Again, I cannot evaluate what the cause it, without more information, that I already requested.

It could be:
- some wrong configuration (or its part);
- lack of pyinotify backend (in v.0.9.3) or pyinotify-module of python (would be strange because sshd seems to work with the same backend);
- wrong timezone ([search for TZ issue](https://github.com/fail2ban/fail2ban/search?q=TZ&type=Issues) here);
- something else...

**Comment by sebres** [comment] 2018-06-18 19:56
> How do I set the loglevel more permanent?

/etc/fail2ban/fail2ban.local:
```INI
[Definition]
loglevel = DEBUG
```
But why do you need it permanent (it is enough to set via command line after start, and wait until any failure or produce the failure manually).

Another question as regards the failure time from example above (`2018-06-16 19:48:53+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:53 2018 ...`):
I assume that the time 17:48:53 is correct there? 
So do you try to catch 2 hours old failures... if yes, then it will not work:
- either because they may be already marked as passed (fail2ban saves the last position of log in the sql-database);
- or because the time of failure is smaller than the time `now - findtime` (10 minutes from now);

See first question in FAQ of our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for more info.

**Comment by JeffZwolle** [comment] 2018-06-18 20:28
@sebres 

> But why do you need it permanent (it is enough to set via command line after start, and wait until any failure or produce the failure manually).

Because the failures do not show up in the log as has been shown in my given logfiles.

> Another question as regards the failure time from example above (2018-06-16 19:48:53+0200 [-] OVPN 1 OUT: "Sat Jun 16 17:48:53 2018 ...):
> I assume that the time 17:48:53 is correct there?

Local time is 19:48 CET
17:48 must be UTC time

So OpenVPNas is putting 2 times in the log: Local time at beginning of the log entry, and UTC time in the entry itself.
And Fail2ban is comparing to the latter.

Changing the findtimes in openvpnas.conf to 7800 seconds (2 hours and 10 minutes) does work.
Now I do see filter-messages come up in fail2ban.log for failed logins.

But changing the findtimes every 6 months because of Dailight Savings Time is annoying. I could script it, but it remains annoying.

Could there be a better way?

Issue from 2011:
https://forums.openvpn.net/viewtopic.php?t=9496

**Comment by sebres** [comment] 2018-06-18 20:56
> Changing the findtimes in openvpnas.conf to 7800 seconds (2 hours and 10 minutes) does work.

So now I know what it is:
because there are 2 date-pattern in the log-entry, fail2ban can get the second date-time (just because by trying to find, the first matched of the date-detector can win and there is a wrong time-zone for this date-time, because fail2ban works in the system time-zone per default).
For example to retrieve which time exactly it's, see https://github.com/fail2ban/fail2ban/issues/2149#issuecomment-395046240 for similar issue.

Newer version (>= 0.10, as @masterkain confirmed) works out of the box, because the date-templates, that are anchored at begin the line, will be preferred there (so the first date-pattern wins).

In your case for v.0.9.x you must specify the date pattern self:
```diff
-$ fail2ban-regex -v                           "$log" '<HOST>:[0-9]+\sSENT\sCONTROL\s.*?AUTH_FAILED'
+$ fail2ban-regex -v -d '^%Y-%m-%d %H:%M:%S%z' "$log" '<HOST>:[0-9]+\sSENT\sCONTROL\s.*?AUTH_FAILED'
...
-|      62.140.132.14  Sat Jun 16 17:48:53 2018
+|      62.140.132.14  Sat Jun 16 19:48:53 2018
...
```

So just specify this precise date-pattern in your filter:
```INI
[Init]
datepattern = ^%%Y-%%m-%%d %%H:%%M:%%S%%z
```

**Closed by sebres** 2018-06-18 20:56 UTC
Labels: moreinfo

**Comment by JeffZwolle** [comment] 2018-06-18 21:17
@sebres 

> So just specify this precise date-pattern in your filter:
> [Init]
> datepattern = ^%%Y-%%m-%%d %%H:%%M:%%S%%z

Yes, that did the job :+1: 
Thank you  :-)
