### ISSUE TITLE
[BR]: Failed during configuration: Have not found any log file for sshd jail

### ISSUE THREAD

**Issue by whanklee** [fail2ban/fail2ban#3819] opened 2024-08-19 04:01 UTC
Hi.

After installation, I copied the jail.conf file as jail.local. I didn't rewrite anything, I didn't say anything in the file, I'm trying to start with the default values.

I followed this description for installation: https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-ubuntu-22-04

OS version: 24.04

If I delete the jail.local file, the application starts, no error. When I copy the jail.conf named jail.local Fail2ban won't start and I get an error:

```
Aug 19 05:47:41 fail2ban.local fail2ban-server[1805969]: 2024-08-19 05:47:41,690 fail2ban                [1805969]: ERROR   Failed during configuration: Have not found any log file for sshd jail
Aug 19 05:47:41 fail2ban.local fail2ban-server[1805969]: 2024-08-19 05:47:41,690 fail2ban                [1805969]: ERROR   Async configuration of server failed
```
I don't get this error on Ubuntu 22.04. Is this a bug on Ubuntu 24?

**Comment by sebres** [comment] 2024-08-21 10:45
Duplicate of #3292 (take a look into the issue for the solution).

> After installation, I copied the jail.conf file as jail.local.

Please don't do that. jail.local must only contain option you want to overwrite... See [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration)

**Closed by sebres** 2024-08-21 10:45 UTC
Labels: bug

**Comment by DaWe35** [comment] 2024-12-14 17:19
> Please don't do that. jail.local must only contain option you want to overwrite... See [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration)

Good to know, since many tutorials recommend copying the file.
