### ISSUE TITLE
ERROR   NOK: (13, 'Permission denied')

### ISSUE THREAD

**Issue by q920447939** [fail2ban/fail2ban#3655] opened 2024-01-02 09:21 UTC
### Environment:

- Fail2Ban version  :  0.11.2
- OS, including release name/version :   Linux localhost.localdomain 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- [x ] Fail2Ban installed via OS/distribution mechanisms  **I use yum install** 
- [√ ] You have not applied any additional foreign patches to the codebase
- [ √ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I want to add a listener to nginx access.log. I try to modify the nginx-limit-req section in the jill-.conf file, but when I use the fail2ban-client reload command, Permission denied

#### Steps to reproduce
`vi /etc/fail2ban/jail.conf  `
find `nginx-limit-req` section, modify result is 
```
[nginx-limit-req]
enabled = true
port    = 60080
filter= nginx-limit-request
logpath = /home/nginx/log/access.log
bantime = 1m
findtime = 1m
maxretry = 3
```
then i use command  `fail2ban-client reload` ,
log tip 
```
2024-01-02 12:16:41,962 fail2ban                [11666]: ERROR   NOK: (13, 'Permission denied')
[Errno 13] Permission denied: '/home/nginx/log/access.log'
[root@localhost fail2ban]# pwd
/etc/fail2ban

[root@localhost fail2ban]# ll /home/nginx/log/access.log
-rwxr-xr-x. 1 root root 2146 Jan  2 02:49 /home/nginx/log/access.log
[root@localhost fail2ban]# ll
total 88
drwxr-xr-x. 2 root root  4096 Jan  2 11:35 action.d
-rw-r--r--. 1 root root  2816 Nov 23  2020 fail2ban.conf
drwxr-xr-x. 2 root root     6 Oct 13  2021 fail2ban.d
-rw-r--r--. 1 root root  2816 Jan  2 11:35 fail2ban.local.bak
drwxr-xr-x. 3 root root  4096 Jan  2 11:41 filter.d
-rw-r--r--. 1 root root 25014 Jan  2 12:16 jail.conf
drwxr-xr-x. 2 root root    31 Jan  2 11:35 jail.d
-rw-r--r--. 1 root root 25082 Jan  2 12:16 jail.local
-rw-r--r--. 1 root root  2827 Nov 23  2020 paths-common.conf
-rw-r--r--. 1 root root   930 Nov 23  2020 paths-fedora.conf
```

#### Expected behavior
     command  `fail2ban-client reload`  result is success
#### Observed behavior
       command  `fail2ban-client reload`  result is fail
#### Any additional information
     i try modify  `/etc/fail2ban/jail.conf  or /etc/fail2ban/jail.local`  ,but result all is fail,
    i use root user,I think I have the highest authority

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2024-01-02 12:16:41,961 fail2ban.jail           [1788]: INFO    Jail 'sshd' stopped
2024-01-02 12:16:41,961 fail2ban.server         [1788]: INFO    Reload finished.
2024-01-02 12:16:41,961 fail2ban.transmitter    [1788]: WARNING Command ['reload', '--all', [], [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'INFO'], ['set', 'logtarget', '/var/log/fail2ban.log'], ['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3'], ['set', 'dbmaxmatches', 10], ['set', 'dbpurgeage', '1d'], ['add', 'sshd', 'systemd'], ['set', 'sshd', 'usedns', 'warn'], ['set', 'sshd', 'prefregex', '^<F-MLFID>\\s*(?:\\S+\\s+)?(?:sshd(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$'], ['set', 'sshd', 'maxlines', 1], ['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^Failed publickey for invalid user <F-USER>(?P<cond_user>\\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^Failed (?:<F-NOFAIL>publickey</F-NOFAIL>|\\S+) for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED FROM <HOST>', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because not listed in AllowUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because listed in DenyUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because not in any group(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^refused connect from \\S+ \\(<HOST>\\)', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*3: .*: Auth fail(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because a group is listed in DenyGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', "^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$", '^<F-NOFAIL>pam_[a-z]+\\(sshd:auth\\):\\s+authentication failure;</F-NOFAIL>(?:\\s+(?:(?:logname|e?uid|tty)=\\S*)){0,4}\\s+ruser=<F-ALT_USER>\\S*</F-ALT_USER>\\s+rhost=<HOST>(?:\\s+user=<F-USER>\\S*</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> not allowed because account is locked(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>(?: from)?(?: (?:invalid|authenticating)) user <F-USER>\\S+</F-USER> <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*Change of username or service not allowed:\\s*.*\\[preauth\\]\\s*$', '^Disconnecting: Too many authentication failures(?: for <F-USER>\\S+|.*?</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*11:', '^<F-NOFAIL><F-MLFFORGET>(Connection closed|Disconnected)</F-MLFFORGET></F-NOFAIL> (?:by|from)(?: (?:invalid|authenticating) user <F-USER>\\S+|.*?</F-USER>)? <HOST>(?:(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*|\\s*)$', '^<F-MLFFORGET><F-MLFGAINED>Accepted \\w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\\S+</F-USER> from <HOST>(?:\\s|$)', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']], ['set', 'sshd', 'datepattern', '{^LN-BEG}'], ['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd'], ['set', 'sshd', 'maxmatches', 2], ['set', 'sshd', 'maxretry', 2], ['set', 'sshd', 'logencoding', 'auto'], ['set', 'sshd', 'ignorecommand', ''], ['set', 'sshd', 'findtime', '10m'], ['set', 'sshd', 'bantime', '120'], ['set', 'sshd', 'addaction', 'iptables-multiport'], ['multi-set', 'sshd', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-sshd -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-sshd'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd\n<iptables> -F f2b-sshd\n<iptables> -X f2b-sshd'], ['actionstart', '<iptables> -N f2b-sshd\n<iptables> -A f2b-sshd -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd'], ['actionban', '<iptables> -I f2b-sshd 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sshd[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'sshd'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'DROP'], ['actname', 'iptables-multiport'], ['port', 'ssh']]], ['add', 'nginx-limit-req', 'auto'], ['set', 'nginx-limit-req', 'usedns', 'warn'], ['set', 'nginx-limit-req', 'addfailregex', '<HOST>.*-.*-.*$'], ['set', 'nginx-limit-req', 'maxmatches', 3], ['set', 'nginx-limit-req', 'maxretry', 3], ['set', 'nginx-limit-req', 'logencoding', 'auto'], ['set', 'nginx-limit-req', 'ignorecommand', ''], ['set', 'nginx-limit-req', 'findtime', '1m'], ['set', 'nginx-limit-req', 'bantime', '1m'], ['set', 'nginx-limit-req', 'addlogpath', '/home/nginx/log/access.log', 'head'], ['set', 'nginx-limit-req', 'addaction', 'iptables-multiport'], ['multi-set', 'nginx-limit-req', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-nginx-limit-req -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-nginx-limit-req'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports 60080 -j f2b-nginx-limit-req\n<iptables> -F f2b-nginx-limit-req\n<iptables> -X f2b-nginx-limit-req'], ['actionstart', '<iptables> -N f2b-nginx-limit-req\n<iptables> -A f2b-nginx-limit-req -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports 60080 -j f2b-nginx-limit-req'], ['actionban', '<iptables> -I f2b-nginx-limit-req 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-nginx-limit-req[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'nginx-limit-req'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'DROP'], ['actname', 'iptables-multiport'], ['port', '60080']]], ['start', 'sshd'], ['start', 'nginx-limit-req']]] has failed. Received IOError(13, 'Permission denied')
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment] 2024-01-03 13:34
Hmm... 
I guess selinux issue? Otherwise I cannot explain how root (fail2ban service is working normally as root) is not able to read some log-file (although it seems to be visible).

See #2960, #3414 and [others](https://github.com/fail2ban/fail2ban/issues?q=is%3Aissue+selinux).
Or try to [google for this issue](https://www.google.com/search?q=selinux+fail2ban+permissions+denied).

I'll close it for now as duplicate, but... don't hesitate to ping me here if it the issue is something else.

**Closed by sebres** 2024-01-03 13:34 UTC
Labels: 3rd party  issue, closed-as-duplicate
