### ISSUE TITLE
Apache filters not matching when basedir is /etc/fail2ban

### ISSUE THREAD

**Issue by tantoinet** [fail2ban/fail2ban#2483] opened 2019-07-29 13:39 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): net-analyzer/fail2ban-0.10.4 and 0.11.0.dev3
- OS, including release name/version: Gentoo Linux amd64 default/linux/amd64/17.1
- [ ] Fail2Ban installed via OS/distribution mechanisms: tried both, yes
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

Tried python2.7, python3.5 and python3.6

filter file:
```
# cat /tmp/apache-test.conf

[INCLUDES]

# overwrite with apache-common.local if _apache_error_client is incorrect.
before = apache-common.conf

[Definition]

failregex =  ^<HOST> -.+" 404 .

ignoreregex = ^<HOST> -.*(ignore-me.+" 404 |" 404 .+"ignore-me2\/).
```

### The issue:

On Gentoo linux, it seems that the fail2ban net-analyzer/fail2ban-0.10.4 as well as the one from this git repo 0.11.0.dev3 are having issues processing apache access logs.
This can easily be reproduced using the gentoo livecd (didn't try another distro).

The following command fails (more below):
`fail2ban-regex /var/log/access_log /etc/fail2ban/filter.d/apache-nohome.conf`
The following one succeed:
```
fail2ban-regex /var/log/access_log /tmp/apache-nohome.conf
fail2ban-regex /var/log/access_log 'failregex =  ^<HOST> -.+" 404 .'
```

Using fail2ban-0.9.4 works fine though.

#### Steps to reproduce

This is failing:
```

# fail2ban-regex /var/log/apache2/access_log /etc/fail2ban/filter.d/apache-test.conf -vvvv

Running tests
=============

Use   failregex filter file : apache-test, basedir: /etc/fail2ban
Real  filter options : {'logtype': 'file', 'datepattern': '{^LN-BEG}'}
Use      datepattern : Default Detectors
Use         log file : /var/log/apache2/access_log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^<HOST> -.+" 404 .
`-

Ignoreregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^<HOST> -.*(ignore-me.+" 404 |" 404 .+"ignore-me2\/).
`-

Date template hits:
|- [# of hits] date format
|  [0] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}(?:DAY )?MON Day ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Day(?P<_sep>[-/])Month(?P=_sep)(?:ExYear|ExYear2) %k:Minute:Second
|  [0] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] {^LN-BEG}Month/Day/ExYear:24hour:Minute:Second
|  [0] {^LN-BEG}Month-Day-ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Epoch
|  [0] {^LN-BEG}ExYear2ExMonthExDay  ?24hour:Minute:Second
|  [0] {^LN-BEG}MON Day, ExYear 12hour:Minute:Second AMPM
|  [0] {^LN-BEG}ExYearExMonthExDay(?:T|  ?)Ex24hourExMinuteExSecond(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:Zone name )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}(?:Zone offset )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}TAI64N
|  [0] {^LN-BEG}24hour:Minute:Second
|  [0] ^<Month/Day/ExYear2@24hour:Minute:Second>
|  [0] ^MON-Day-ExYear2 %k:Minute:Second
`-

Lines: 78 lines, 0 ignored, 0 matched, 78 missed
[processed in 0.20 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 78 lines
```

And This succeeds:
```
# cp /etc/fail2ban/filter.d/apache-test.conf /tmp/
# fail2ban-regex /var/log/apache2/access_log /tmp/apache-test.conf -vvvv
Running tests
=============

Use   failregex file : /tmp/apache-test.conf
Real  filter options : {'logtype': 'file'}
Use         log file : /var/log/apache2/access_log
Use         encoding : UTF-8


Results
=======

Failregex: 39 total
|-  #) [# of hits] regular expression
|   1) [39] ^<HOST> -.+" 404 .
|      1.2.3.4  Sun Jul 28 15:17:58 2019
`-

Ignoreregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^<HOST> -.*(ignore-me.+" 404 |" 404 .+"ignore-me2\/).
`-

Date template hits:
|- [# of hits] date format
|  [78] Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}(?:DAY )?MON Day ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Day(?P<_sep>[-/])Month(?P=_sep)(?:ExYear|ExYear2) %k:Minute:Second
|  [0] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] {^LN-BEG}Month/Day/ExYear:24hour:Minute:Second
|  [0] {^LN-BEG}Month-Day-ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] {^LN-BEG}Epoch
|  [0] {^LN-BEG}ExYear2ExMonthExDay  ?24hour:Minute:Second
|  [0] {^LN-BEG}MON Day, ExYear 12hour:Minute:Second AMPM
|  [0] {^LN-BEG}ExYearExMonthExDay(?:T|  ?)Ex24hourExMinuteExSecond(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] {^LN-BEG}(?:Zone name )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}(?:Zone offset )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] {^LN-BEG}TAI64N
|  [0] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] (?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] (?:DAY )?MON Day ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:ExYear|ExYear2) %k:Minute:Second
|  [0] Month/Day/ExYear:24hour:Minute:Second
|  [0] Month-Day-ExYear %k:Minute:Second(?:\.Microseconds)?
|  [0] Epoch
|  [0] {^LN-BEG}24hour:Minute:Second
|  [0] ^<Month/Day/ExYear2@24hour:Minute:Second>
|  [0] ExYear2ExMonthExDay  ?24hour:Minute:Second
|  [0] MON Day, ExYear 12hour:Minute:Second AMPM
|  [0] ^MON-Day-ExYear2 %k:Minute:Second
|  [0] ExYearExMonthExDay(?:T|  ?)Ex24hourExMinuteExSecond(?:[.,]Microseconds)?(?:\s*Zone offset)?
|  [0] (?:Zone name )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] (?:Zone offset )?(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  [0] TAI64N
`-

Lines: 78 lines, 0 ignored, 39 matched, 39 missed
[processed in 0.35 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 39 lines
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
2019-07-29 15:15:17,243 fail2ban.server         [9578]: INFO    Starting Fail2ban v0.11.0.dev3
2019-07-29 15:15:17,246 fail2ban.server         [9578]: INFO    Daemon started
2019-07-29 15:15:17,247 fail2ban.server         [9578]: DEBUG   Creating PID file /var/run/fail2ban/fail2ban.pid
2019-07-29 15:15:17,249 fail2ban.observer       [9578]: INFO    Observer start...
2019-07-29 15:15:17,250 fail2ban.server         [9578]: DEBUG   Starting communication
2019-07-29 15:15:17,555 fail2ban.database       [9578]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2019-07-29 15:15:17,559 fail2ban.jail           [9578]: INFO    Creating new jail 'apache-test'
2019-07-29 15:15:17,617 fail2ban.jail           [9578]: INFO    Jail 'apache-test' uses pyinotify {}
2019-07-29 15:15:17,619 fail2ban.filter         [9578]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('apache-test'))
2019-07-29 15:15:17,619 fail2ban.filter         [9578]: DEBUG   Created FilterPyinotify(Jail('apache-test'))
2019-07-29 15:15:17,629 fail2ban.filterpyinotif [9578]: DEBUG   Created FilterPyinotify
2019-07-29 15:15:17,630 fail2ban.jail           [9578]: INFO    Initiated 'pyinotify' backend
2019-07-29 15:15:17,631 fail2ban.server         [9578]: DEBUG     ignoreregex: '^<HOST> -.*(ignore-me.+" 404 |" 404 .+"ignore-me2\/).'
2019-07-29 15:15:17,640 fail2ban.server         [9578]: DEBUG     failregex: '^<HOST> -.+" 404 .'
2019-07-29 15:15:17,669 fail2ban.filter         [9578]: INFO      maxRetry: 2
2019-07-29 15:15:17,671 fail2ban.filter         [9578]: INFO      findtime: 600
2019-07-29 15:15:17,672 fail2ban.actions        [9578]: INFO      banTime: 60
2019-07-29 15:15:17,672 fail2ban.filter         [9578]: DEBUG   Setting usedns = warn for FilterPyinotify(Jail('apache-test'))
2019-07-29 15:15:17,673 fail2ban.filter         [9578]: INFO      encoding: UTF-8
2019-07-29 15:15:17,675 fail2ban.filter         [9578]: INFO    Added logfile: '/var/log/apache2/access_log' (pos = 0, hash = 512fa527d7eb8b87c846764d010ba628bd70ca2e)
2019-07-29 15:15:17,676 fail2ban.filterpyinotif [9578]: DEBUG   New <Watch wd=1 path=/var/log/apache2 mask=1073745280 proc_fun=None auto_add=False exclude_filter=<function WatchManager.<lambda> at 0x7f0015222b70> dir=True >
2019-07-29 15:15:17,678 fail2ban.filterpyinotif [9578]: DEBUG   Added monitor for the parent directory /var/log/apache2
2019-07-29 15:15:17,679 fail2ban.filterpyinotif [9578]: DEBUG   New <Watch wd=2 path=/var/log/apache2/access_log mask=2 proc_fun=None auto_add=False exclude_filter=<function WatchManager.<lambda> at 0x7f0015222b70> dir=False >
2019-07-29 15:15:17,680 fail2ban.filterpyinotif [9578]: DEBUG   Added file watcher for /var/log/apache2/access_log
2019-07-29 15:15:17,681 fail2ban.filter         [9578]: DEBUG   Seek to find time 1564405517.6816459 (2019-07-29 15:05:17), file size 12675
2019-07-29 15:15:17,852 fail2ban.filter         [9578]: DEBUG   Position 7647 from 12675, found time None () within 9 seeks
2019-07-29 15:15:17,854 fail2ban.CommandAction  [9578]: DEBUG   Created <class 'fail2ban.server.action.CommandAction'>
2019-07-29 15:15:17,854 fail2ban.CommandAction  [9578]: DEBUG     Set actionstart = '<iptables> -N f2b-apache-test\n<iptables> -A f2b-apache-test -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports http,https -j f2b-apache-test'
2019-07-29 15:15:17,855 fail2ban.CommandAction  [9578]: DEBUG     Set actionstop = '<iptables> -D INPUT -p tcp -m multiport --dports http,https -j f2b-apache-test\n<iptables> -F f2b-apache-test\n<iptables> -X f2b-apache-test'
2019-07-29 15:15:17,856 fail2ban.CommandAction  [9578]: DEBUG     Set actionflush = '<iptables> -F f2b-apache-test'
2019-07-29 15:15:17,856 fail2ban.CommandAction  [9578]: DEBUG     Set actioncheck = "<iptables> -n -L INPUT | grep -q 'f2b-apache-test[ \\t]'"
2019-07-29 15:15:17,857 fail2ban.CommandAction  [9578]: DEBUG     Set actionban = '<iptables> -I f2b-apache-test 1 -s <ip> -j <blocktype>'
2019-07-29 15:15:17,857 fail2ban.CommandAction  [9578]: DEBUG     Set actionunban = '<iptables> -D f2b-apache-test -s <ip> -j <blocktype>'
2019-07-29 15:15:17,858 fail2ban.CommandAction  [9578]: DEBUG     Set name = 'apache-test'
2019-07-29 15:15:17,858 fail2ban.CommandAction  [9578]: DEBUG     Set port = 'http,https'
2019-07-29 15:15:17,859 fail2ban.CommandAction  [9578]: DEBUG     Set protocol = 'tcp'
2019-07-29 15:15:17,859 fail2ban.CommandAction  [9578]: DEBUG     Set chain = '<known/chain>'
2019-07-29 15:15:17,860 fail2ban.CommandAction  [9578]: DEBUG     Set actname = 'iptables-multiport'
2019-07-29 15:15:17,860 fail2ban.CommandAction  [9578]: DEBUG     Set blocktype = 'REJECT --reject-with icmp-port-unreachable'
2019-07-29 15:15:17,861 fail2ban.CommandAction  [9578]: DEBUG     Set returntype = 'RETURN'
2019-07-29 15:15:17,862 fail2ban.CommandAction  [9578]: DEBUG     Set lockingopt = '-w'
2019-07-29 15:15:17,862 fail2ban.CommandAction  [9578]: DEBUG     Set iptables = 'iptables <lockingopt>'
2019-07-29 15:15:17,863 fail2ban.CommandAction  [9578]: DEBUG     Set blocktype?family=inet6 = 'REJECT --reject-with icmp6-port-unreachable'
2019-07-29 15:15:17,863 fail2ban.CommandAction  [9578]: DEBUG     Set iptables?family=inet6 = 'ip6tables <lockingopt>'
2019-07-29 15:15:17,864 fail2ban.jail           [9578]: DEBUG   Starting jail 'apache-test'
2019-07-29 15:15:17,865 fail2ban.filterpyinotif [9578]: DEBUG   [apache-test] filter started (pyinotifier)
2019-07-29 15:15:17,868 fail2ban.jail           [9578]: INFO    Jail 'apache-test' started
2019-07-29 15:15:17,869 fail2ban.transmitter    [9578]: DEBUG   Status: ready
2019-07-29 15:16:15,554 fail2ban.filterpyinotif [9578]: DEBUG   Event queue size: 16
2019-07-29 15:16:15,555 fail2ban.filterpyinotif [9578]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2019-07-29 15:16:15,557 fail2ban.filter         [9578]: WARNING Found a match for '1.2.3.4 - - [28/Jul/2019:15:17:58 +0200] "GET /doesntexist HTTP/1.1" 404 271' but no valid date/time found for '1.2.3.4 - - [28/Jul/2019:15:17:58 +0200] "GET /doesntexist HTTP/1.1" 404 271'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```

#### Relevant lines from monitored log files in question:

```
1.2.3.4 - - [28/Jul/2019:15:17:58 +0200] "GET /doesntexist HTTP/1.1" 404 271
5.6.7.8 - - [28/Jul/2019:21:20:00 +0200] "GET / HTTP/1.1" 200 3123
```

**Comment by sebres** [comment] 2019-07-29 14:35
The title of the issue is wrong or at least confusing.
Filter `apache-nohome.conf` has nothing with your temp-filter (`/tmp/apache-test.conf`), because it is searching for AH00128-error "File does not exist".
So basically the issue has nothing with the place of the filter (or some used includes).

It looks like a duplicate of #2378, several original apache-filters are built to parse error-log (and access-log has simply another format).

> `failregex =  ^<HOST> -.+" 404 .`

Please don't do that - such wild catch-all's `.+`  may be dangerous, because it matches an address and then simply searches for 404 everywhere in log message (no matter where).
Better `failregex` for that is provided for example in https://github.com/fail2ban/fail2ban/issues/2294#issuecomment-445230607.

**Closed by sebres** 2019-07-29 14:35 UTC
Labels: closed-as-duplicate, closed-as-incorrect

**Comment by tantoinet** [comment] 2019-07-29 14:38
The issue was related to /etc/fail2ban/filter.d/apache-commin.conf being included where it sets the date pattern:
`datepattern = {^LN-BEG}`
Commenting that out, as well as the one in common.conf fixes the issue.
The apache-nohome.conf was a typo, sorry for that.
