### ISSUE TITLE
[BR]: 

### ISSUE THREAD

**Issue by steglicd** [fail2ban/fail2ban#3244] opened 2022-03-21 23:05 UTC
### Environment:
Updated my OS from debian 9 to debian 11. fail2ban installed via apt.
```
fail2ban-server --version
Fail2Ban v0.11.2
```
Had Fail2Ban v0.9.6 on debian 9 before.
### The issue:

config looks like this after update:
```
# [Definition]
# loglevel = 4
#

[Definition]

# Option: loglevel
# Notes.: Set the log level output.
#         1 = ERROR
#         2 = WARN
#         3 = INFO
#         4 = DEBUG
# Values: [ NUM ]  Default: 1
#
loglevel = 1
```
#### Steps to reproduce
`/etc/init.d/fail2ban start`
#### Expected behavior
logfile not flooded
#### Observed behavior
log file is flooded by a LOT of debug messages (looks like highes loglevel)
```
2022-03-22 00:02:45,306 fail2ban.datedetector   [70097]: HEAVY     try to match last anchored template #00 ...
2022-03-22 00:02:45,306 fail2ban.datedetector   [70097]: #06-Lev.   matched last time template #00
2022-03-22 00:02:45,306 fail2ban.datedetector   [70097]: #06-Lev.   got time 1647903763.000000 for '2022-03-22 00:02:43,045' using template {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
```
#### Any additional information

/var/log/fail2ban.log grows to about 1GB within 30 min.

**Comment by sebres** [comment] 2022-03-22 11:00
Duplicate of #2008 and #1968.
Shortly: it looks like very outdated config (I guess v.0.8 or even before), so simply remove loglevel (to use default) or set it to `INFO` (20).
https://github.com/fail2ban/fail2ban/blob/8c4d02403b4768fb1a76372a7a462fc903c2711e/config/fail2ban.conf#L14-L24
Also note - https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration :
*Don't change stock configuration in .conf-files (provide it in .local instead) and don't copy .conf to .local (create new files and set there the different values only).*

> Had Fail2Ban v0.9.6 on debian 9 before.

According to my knowledge 0.9 never supported numeric loglevel - it only allowed named (string) values.

**Closed by sebres** 2022-03-22 11:00 UTC
Labels: bug

**Comment by steglicd** [comment] 2022-03-25 11:16
@sebres thanks for answering and sorry I did not found https://github.com/fail2ban/fail2ban/issues/2008 and https://github.com/fail2ban/fail2ban/issues/1968.

Just one note:
You are right, I  migrated this config file over years from debian update to debian update. So the config is very outdated.
This year debian 9 runs out of support. The described behavior hit me when upgrading my debian 9 boxes to debian 11.

Probably other users may also be affected by this. So if the default behaviour would be to just print a error instead of filling up the hard disk with multiple Gigabyte of log per hour if log level is not recognized this would prevent others from breaking their debian boxes after upgrade.

**Comment by sebres** [comment] 2022-03-25 17:36
> So if the default behaviour would be to just print a error instead of filling up the hard disk ...

Well, how it should be possible if the numeric log-level are accepted now? Intended to made fine adjustment by logging or even to do some heavy debug.
Normally, such an error had reached you if your upgrade happened from v.0.8 to v.0.9.x at some point (so you did not overjump 0.9.x).
I must admit it is indeed not fortunate situation, but I'm afraid we cannot do something to protect users against that, without to disable numeric log-levels completely (which would then affect much more users probably).

**Comment by steglicd** [comment] 2022-03-27 22:07
Maybe I misunderstood the issue. I thought that numeric log level is not supported but instead it is supported and "1" is just the most verbose one.
