### ISSUE TITLE
Custom host definition expectations

### ISSUE THREAD

**Issue by Ziris85** [fail2ban/fail2ban#1467] opened 2016-06-19 16:56 UTC
### Environment:

- Fail2Ban version (including any possible distribution suffixes): fail2ban-0.9.3-1.el7.noarch
- OS, including release name/version: CentOS Linux release 7.2.1511 (Core)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I may have improper expectations here on what this is used for, but I am attempting to have fail2ban match other things than an IP address with its filters. Basically I am attempting to have fail2ban act not only as a service meant to ban IP's, but to also send email notifications when certain events happen on the system. For example, I have working an email notification when someone logs in via SSH.

My above mentioned example works because there is an IP to trap in the filter. However, something else I'd like to try to monitor (among other things) is the creation of new system users (which are logged in /var/log/secure). Those log entries do not include an IP address, but from what I was reading on the documentation page, the host flag could be customized:

http://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Filters

I've used [this site](https://www.debuggex.com/) to confirm that the regex I have set up matches the field I'm looking for (in my example, a username), but fail2ban is claiming it's not matching.

My assumption presently is that fail2ban will refuse to allow a match to occur if it is not an IP address - regardless of how you have it defined. If that is so, then what is the purpose of stating that this can be customized if it won't matter anyway? If it _should_ be matching, then I would appreciate any assistance in determining why it isn't presently.

#### Steps to reproduce
Create a filter with regex:
```^.* host useradd\[.*\]\: new user\: name=(?P<host>[\w]+)```

Test the regex against /var/log/secure:
```fail2ban-regex /var/log/secure <regex_file>```
#### Expected behavior
Match all lines for new user creation. Example:
```Jun 19 12:46:14 host useradd[71474]: new user: name=testingguywhat, UID=32013, GID=32014, home=/home/testingguywhat, shell=/bin/bash```
...should match `testingguywhat`
#### Observed behavior
No lines match.

#### Any additional information
I created a new line in my secure log with an IP in that field just to test, and that _does_ match:
```
|- Matched line(s):
|  Jun 19 09:15:46 host useradd[64871]: new user: name=192.168.1.254, UID=32013, GID=32014, home=/home/testingguy, shell=/bin/bash
```
#### Any customizations done to /etc/fail2ban/ configuration
```
None.
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
None.
```

#### Relevant lines from monitored log files in question:

```
Jun 19 12:46:14 host useradd[71474]: new user: name=testingguywhat, UID=32013, GID=32014, home=/home/testingguywhat, shell=/bin/bash
```

**Comment by sebres** [comment] 2016-06-19 21:52
This issue is a duplicate of #67.
It was fixed in #1454 for 0.9-branch (merged in master) resp. more efficient in #1459 for 0.10-version.

Will close now, please reopen if I'm wrong.

**Closed by sebres** 2016-06-19 21:52 UTC

**Comment by Ziris85** [comment] 2016-06-20 15:23
Hello,

Thanks for the follow-up. Unless I'm misunderstanding you, I don't believe this was resolved in the latest master branch for .9. I just pulled from the master a bit ago today and set it all up, and it's still not matching the username:

```
# fail2ban-client version
0.9.4.dev0

# fail2ban-regex /var/log/secure "^.* host useradd\[.*\]\: new user\: name=(?P<host>[\w]+)" --print-all-matched

|- Matched line(s):
|  Jun 19 09:15:46 host useradd[64871]: new user: name=192.168.1.254, UID=32013, GID=32014, home=/home/testingguy, shell=/bin/bash
```
```
# fail2ban-regex "Jun 19 12:46:14 host useradd[71474]: new user: name=testingguywhat, UID=32013, GID=32014, home=/home/testingguywhat, shell=/bin/bash" "^.* host useradd\[.*\]\: new user\: name=(?P<host>[\w]+)" --print-all-matched

|- Missed line(s):
|  Jun 19 12:46:14 host useradd[71474]: new user: name=testingguywhat, UID=32013, GID=32014, home=/home/testingguywhat, shell=/bin/bash
```

**Comment by Ziris85** [comment] 2016-06-20 15:29
Actually, I believe I did actually misunderstand.  I caught the bit about using the `raw`

**Comment by sebres** [comment] 2016-06-20 15:46
First, please use `ignoreip =`
Can you switch f2b logging to DEBUG or HEAVYDEBUG and then post here the excerpt round about found match if that will be found...

**Comment by Ziris85** [comment] 2016-06-20 16:20
Ok, thank you for that clarification! Kind of odd to specify something without giving it a value like that, but with that in place it's now matching like I'd want it to. Thanks for your help!

**Comment by sebres** [comment] 2016-06-21 10:16
> Kind of odd to specify something without giving it a value like that

Nope, this sets the option to an empty value.
Parameter `ignoreip` contains normally a list of IP's resp. host names (that should be ignored) or even nothing :)
