### ISSUE TITLE
Fail2Ban 0.10.4 base install does not integrate AbuseIPDB API V2

### ISSUE THREAD

**Issue by mc4bbs** [fail2ban/fail2ban#2594] opened 2020-01-10 21:48 UTC
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.4 downloaded from https://github.com/fail2ban/fail2ban/releases/tag/0.10.4
- OS, including release name/version: Linux TORMINT 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2Ban 0.10.4 base install does not integrate AbuseIPDB API V2, although I've been told it should.  Specifically, in /etc/fail2ban/actions.d/abuseipdb.conf, the cURL statement that sends the data to AbuseIPDB is using the API V1 format/URL which will NO LONGER WORK as of 1 February 2020.

Note: This is NOT a duplicate issue as with #2310 and it was NOT fixed in 521de5e. 

#### Steps to reproduce

Install AbuseIPDB and look for the cURL command to integrate with the AbuseIPDB API V2 URL.  There isn't one.

#### Expected behavior

When you install Fail2Ban v0.10.4 or greater with it advertised as AbuseIPDB functionality built-in, you would expect the code to report to the correct URL to be there.  It's not.

#### Observed behavior

Without the proper URL, V2 API keys won't report to AbuseIPDB and if one continues to send irrelevant data, might have their own IP banned from reporting!

#### Any additional information

Information about AbuseIPDB API V2 can be seen at [https://docs.abuseipdb.com/#introduction](https://docs.abuseipdb.com/#introduction)

#### Any customizations done to /etc/fail2ban/ configuration

NO CUSTOMISATIONS, other than my simple jail.local file to activate sshd and asterisk jails.

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

[fail2ban.log](https://github.com/fail2ban/fail2ban/files/4048137/fail2ban.log)

**Comment by sebres** [comment] 2020-01-10 22:03
Sure because V2 was firstly implemented in #2302 (see commit 8da9bfb83af4804a92f229f8d09c9ed0298835b1), so it is firstly released with 0.10.5.
Either update the config file [action.d/abuseipdb.conf](https://raw.githubusercontent.com/fail2ban/fail2ban/0.10/config/action.d/abuseipdb.conf) manually to newer version by yourself or wait for update for your distribution.

**Closed by sebres** 2020-01-10 22:03 UTC

**Comment by mc4bbs** [comment] 2020-01-10 22:28
1) There is no V2 support in 0.10.4, although I've been told there is.  The subject for this Incident is accurate, true and relevant.  The problem still exists.
2) You make a past-tense reference 0.10.5, where is that version?  "Implemented" is past-tense and indicates that it has already been released, is this the case?
3) Even when you make changes for V2 compatibility (as shown in the other case), it constantly reports **$f2bV_matches** a in the comments, which is not helpful and perhaps annoying to AbuseIPDB.
4) Closing the case without resolving the issue does NOT make the problem go away -- it irritates the person reporting the issue and makes them feel ignored.  It's very, very rude.

**Comment by mc4bbs** [comment] 2020-01-10 22:42
I managed to resolve this.  It's reporting properly now.

This was my first experience reporting a problem with fail2ban and I must admit I was not very impressed.  Reverse-engineering someone else's code is a PITA.

**Comment by sebres** [comment] 2020-01-11 00:34
1. Yes, for this purposes we're providing an update (0.10.5). The problem is solved. Version 0.10.4 is frozen by its release, version 0.10.5 contains a patch/update with newest version of this config file.
What do you want? 0.10.4.1? Then please get in touch with your maintainer and try to convince him, that it has highest priority to provide this patch.
This here is a developer repository. And the task is fixed by people contributing to this and other PR's, confirmed that this works, thus the work is ultimately done.
2. Yes. It is implemented before it got released (so as it was 0.10.5-dev), but it is also officially released from our side (see [fail2ban/releases](https://github.com/fail2ban/fail2ban/releases)).
What does not say you'll become an update soon (as already said it's matter of maintainer of packet for every distribution). Just note we're speaking about a config file. **Every configuration can be anytime updated by yourself** without any issue (at least you could try it).
3. Nope, it'll not. This is only possible if single quotes are used around `comment=<matches>`. I told you almost 10 times today about that.
4. The issue with `$f2bV_matches` is solved, firstly in fc76ccf19218f7eb14afcbf916fe47c3c9ccaa95 still for API V1, which was released already with v.0.10.3) and finally API V2 is also implement.
Where your (broken `$f2bV_matches`) config file is coming from remains a mystery to me (may be it occurs by update, or something else). I have neither the time nor the desire to check any linux distribution to find the "evildoer".
An yes, if a developer in his development repository means that the issue is solves, then perhaps he knows it better and can close it (e. g. to hold the issue list clear).
As I informed you that this file (from your initial comment) is never released by us with 0.10.4, why you won't believe me that firstly, and also why did not (re)open the issue by your distribution?
Sometimes I get the impression that everyone knows better, how the development of some open source project must take place... just we, that doing the job day after day, year by year (and I'd note totally gratis), don't know how it'd be made properly. It's simply frustrating.

BTW, I would be also pleased if we could provide the releases sooner, but everyone from us has primary jobs yet (as well as families, etc pp), so some things become lower precedence.
Moreover I had also other important issues expecting some fix and some work, (but also time to check it works), PRs expecting review, merge or rebase, all the things before it got released ultimately, so some release (like v.0.10.5) can take even longer as some other.

**Comment by looselyhuman** [comment] 2020-07-26 14:49
> I managed to resolve this. It's reporting properly now.
How? I read through the previous thread and am basically in the same boat. Hoping I can piggyback instead of wasting hours on this...
