### ISSUE TITLE
[BR]: Fails to build with Python 3.12 - ModuleNotFoundError: No module named 'asynchat'

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#3487] opened 2023-04-01 14:54 UTC
### Environment:

- Fail2Ban version  : 1.0.2
- OS, including release name/version : Fedora Rawhide + Python 3.12.0a5

### The issue:

fail2ban fails to build with Python 3.12.0a5.
```
+ /usr/bin/python3 bin/fail2ban-testcases --verbosity=2 --no-network
Traceback (most recent call last):
  File "/builddir/build/BUILD/fail2ban-1.0.2/bin/fail2ban-testcases", line 40,
in <module>
    from fail2ban.tests.utils import getOptParser, initProcess, gatherTests
  File "/builddir/build/BUILD/fail2ban-1.0.2/fail2ban/tests/utils.py", line 46,
in <module>
    from ..server import asyncserver
  File "/builddir/build/BUILD/fail2ban-1.0.2/fail2ban/server/asyncserver.py",
line 28, in <module>
    import asynchat
ModuleNotFoundError: No module named 'asynchat'
```
asynchat and asyncore have been removed according to the schedule in PEP 594,
having been deprecated in Python 3.6. Use asyncio instead. (Contributed by
Nikita Sobolev in gh-96580.)

https://github.com/python/cpython/issues/96580
https://docs.python.org/3.12/whatsnew/3.12.html

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.12/fedora-rawhide-x86_64/05573413-fail2ban/

For all our attempts to build fail2ban with Python 3.12, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.12/package/fail2ban/

Testing and mass rebuild of packages is happening in copr. You can follow these
instructions to test locally in mock if your package builds with Python 3.12:
https://copr.fedorainfracloud.org/coprs/g/python/python3.12/

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2176186

**Comment by opoplawski** [comment] 2023-06-15 01:53
Python 3.12 is hitting Fedora Rawhide now, so this would be nice to get address soon if possible.

**Comment by sebres** [comment] 2023-06-16 15:38
So the migration to 3.x is fulfilled (#2690 is closed) now...
Lets try to switch from asyncore to asyncio... 
Just it would be not so easy, since event loop of asyncio is not really suitable for usage together with threads (which is currently a basis of fail2ban). One could write some mixed code (integrate to the life span, etc), just it looks ugly, let alone coroutines are not intended for parallel execution in threads and the chain `asyncio <-> CORO <-> Thread <-> threaded code` would expects some interlayers and mockups at multiple cross points.
Better would by to switch from threading to asyncio completely (it would have also additional pros, like no GIL, fully asynchronous handling in all modules, etc), but it implies rewrite of everything, and the effort is enormous.

**Comment by 4nanook** [comment] 2023-07-09 20:01
Where do I got the version ported to 3.12?  I just grabbed from github and it is still failing with failure to find module asynchat.

**Comment by sebres** [comment] 2023-07-09 20:38
> Where do I got the version ported to 3.12

Nowhere at the moment. As you can see the issue is still open.

**Comment by 4nanook** [comment] 2023-07-09 20:41
My apologies, I should wake-up before I attempt to read this stuff.
Last failed login: Sun Jul  9 03:15:01 PDT 2023 from 180.101.88.248 on ssh:notty
There were 6132 failed login attempts since the last successful login.

**Comment by hobbes1069** [comment] 2023-07-30 11:57
Since this is still preventing me from building in Fedora Rawhide I thought I'd ask. Is the module used for all tests or just some? If only some, I could disable those tests?

**Comment by hroncok** [comment] 2023-09-27 16:26
Would it make sense to (at least temporarily) use [pyasynchat](https://pypi.org/project/pyasynchat/) (requires [pyasyncore](https://pypi.org/project/pyasyncore/)) on Python 3.12+? The imports should remain compatible, so it boilds down to declaring a dependency on it with an environment marker, e.g.:

```
pyasynchat;python_version>="3.12"
```

**Comment by AdamWill** [comment] 2023-09-27 17:02
Note that even with that resolved there's another issue - tests/action_d/test_smtp.py uses `smtpd`, which is also removed from Python 3.12. The recommended replacement is aiosmtpd, but it's definitely not just a drop-in replacement.

**Comment by sebres** [comment] 2023-09-27 23:42
As for `test_smtp.py` it is not a large issue, because we could disable it for 3.12 as known issue, and the action. which is only dynamically loaded, is unusable then, until becomes rewritten (there are enough another mailing actions and they are optional and even not really recommended).

Regarding pyasynchat and pyasyncore, I'm still unsure:
- are there always available?
- don't they get a mentioned problematic related to asyncio and threads... must try it.

**Comment by AdamWill** [comment] 2023-09-27 23:55
I don't think the smtpd removal affects any 'real' code - it's just the test case that uses it, as a way to check the smtp actions are doing what they should. So I think the actions should keep working fine (unless something breaks them and we don't notice because the test doesn't work :>), it's just the test case that can't work.

**Comment by sebres** [comment] 2023-09-28 00:30
This test covers `action.d/smtp.py` - I thought it may be affected similarly (didn't test it yet with 3.12), but if not, the action would be untested...

However another worse thing would be - disabling that test will decrease coverage for usage of pythonic actions under real circumstances (it was sole stock pythonic action tested completely), so we'd need either another pythonic (dummy-)action or another SMTP server for test.

**Comment by AdamWill** [comment] 2023-09-28 00:49
ah, yeah, that sucks. but yes, theoretically at least, the action should still work. it doesn't use `smtpd`, because `smtpd` is a *server* library, and the action only wants to act as a client. It uses client-y things - `smtplib`, `socket`, `email.(stuff)` - and those have not been removed.

It's just the test case that uses the server-y `smtpd`, because it needs to act like a server to test that the action is being a good client.

**Comment by pornmailbox** [comment] 2023-12-10 19:17
I installed pyasynchat from https://github.com/simonrob/pyasynchat and pyasyncore from https://github.com/simonrob/pyasyncore . This is a temporary method until a fail2ban will be rebased on asyncio (https://docs.python.org/3/library/asyncio.html). I don't use smtpd module. fail2ban works for me with python 3.12 on Gentoo linux fine.

**Comment by sebres** [comment] 2023-12-11 21:13
OK, there is new branch [python-3.12--asyncore](https://github.com/fail2ban/fail2ban/compare/7076af637f8931c21e2fe6b1ca2f8e7563bc0727...sebres:fail2ban:python-3.12--asyncore) that actually works with 3.12 in [CI of GHA](https://github.com/sebres/fail2ban/actions/runs/7173278607/job/19532298698). But:
- asyncore/asynchat will be installed via pip: `python -m pip install pyasynchat` and `python -m pip install pyasyncore`
- test_smpt is completely ignored
- testSetupInstallRoot fails, because of `setuptools` issue (probably because of missing `distutils`). No idea what is wrong here, either it is the issue on that Ubuntu box only, or `setuptools` is an issue with 3.12 basically.

**Comment by sebres** [comment] 2023-12-12 12:16
The issue with setuptools is [fixed now]() (it should be installed for python version used to test, whereas apt seems to install it for stock python version). Anyway it works now.

This can be closed (and get a TODO "rewrite f2b to asyncio"), but...

@fail2ban/maintainers, @opoplawski, @sylvestre what should we do with asynchat and asyncore now?

Please vote in following 2 comments, 👍 (in favor), 👎 (against) and 👀 (abstain). 
The choice 👍 for both variants means it'd try to import pyasynchat/pyasyncore and as fallback would use local asynchat/asyncore modules.

**Comment by sebres** [comment] 2023-12-12 12:16
### Variant I: 
we will use pyasynchat and pyasyncore packages provided by pip, distro packet-manager, etc

**Comment by sebres** [comment] 2023-12-12 12:16
### Variant 2: 
we shall add copies of asynchat and asyncore as local modules of fail2ban

**Comment by hobbes1069** [comment] 2023-12-12 12:53
Hopefully I interpreted things correctly but in the case of Fedora, internet access is not allowed during the build process. We would just need the two libraries bundled in fail2ban. Additionally we're almost to the point of having Python 3.13 in Rawhide and I'm not sure if that causes any additional issues or not...

**Comment by sebres** [comment] 2023-12-12 13:10
> internet access is not allowed during the build process

Well, one doesn't need them during build process. Variant I means that fail2ban package should get a dependency to pip- or distro- or whatever else package. No idea what exactly is possible and which packages are available in distros (I'm not maintainer).

> we would just need the two libraries bundled in fail2ban.

Then you'd vote for Variant II.

**Comment by sebres** [comment] 2023-12-12 13:31
> Additionally we're almost to the point of having Python 3.13 in Rawhide and I'm not sure if that causes any additional issues or not...

Yes it caused few compat issues (deprecated removals only)... 
I fixed it in other branch, see https://github.com/fail2ban/fail2ban/actions/runs/7182148498/job/19558003605
Would merge it to master soon.

**Closed** 2023-12-12 14:36 UTC
Labels: bug

**Comment by sebres** [comment] 2023-12-12 14:44
The bundled-in version is now in master (combination of variants I and II with a fallback to bundled-in libraries was not so complex, therefore I decided to do that).
Thus closed.
Would someone need an official release?

**Comment by AdamWill** [comment] 2023-12-12 16:19
> Hopefully I interpreted things correctly but in the case of Fedora, internet access is not allowed during the build process. We would just need the two libraries bundled in fail2ban. Additionally we're almost to the point of having Python 3.13 in Rawhide and I'm not sure if that causes any additional issues or not...

We've already fixed this for Fedora months back, adding dependencies on pyasyncore and pyasynchat downstream. Doing so upstream is totally fine; the Fedora build system will satisfy the dependencies from the Fedora packages, both are packaged in Fedora.

**Comment by sebres** [comment] 2023-12-12 17:11
> It would actually have been easier for Fedora not to have the libraries bundled...

Sorry for effort and delay which caused that... Too much to do vocational - as always the lack of time.

**Comment by hobbes1069** [comment] 2023-12-12 23:01
> > Hopefully I interpreted things correctly but in the case of Fedora, internet access is not allowed during the build process. We would just need the two libraries bundled in fail2ban. Additionally we're almost to the point of having Python 3.13 in Rawhide and I'm not sure if that causes any additional issues or not...
> 
> We've already fixed this for Fedora months back, adding dependencies on pyasyncore and pyasynchat downstream. Doing so upstream is totally fine; the Fedora build system will satisfy the dependencies from the Fedora packages, both are packaged in Fedora. It would actually have been easier for Fedora _not_ to have the libraries bundled, as now by policy we'll have to unbundle them again. :D

WHOOPS! I've slept too many times since then. Anything still to do for Python 3.13?

**Comment by sebres** [comment] 2023-12-13 01:00
> Anything still to do for Python 3.13?

@hobbes1069, as mentioned in https://github.com/fail2ban/fail2ban/issues/3487#issuecomment-1852041129, everything related 3.13 is fixed now... 
And I already merged it to master, which pass against 3.13 in CI too. However it is still alpha, so who know what it gets if python 3.13 gets ultimately released.

Or did you mean a some "rollback" or "revert" on your side? I guess no, since there were no new incompatible changes related deprecated libs removals.

**Comment by blshkv** [comment] 2023-12-29 09:36
a new release would be nice

**Comment by sebres** [comment] 2023-12-31 12:06
Just for the record, the issue with testing via smtpd is fixed also now (together with #3268, thx to @Logic-32).
To test it for python3.12+ test-suite requires `aiosmtpd`:
```bash
# either via distro package manager:
?apt|dnf|zypper|whatever? install python?3?-aiosmtpd
# or via pypi:
python3 -m pip install aiosmtpd
```

**Comment by AdamWill** [comment] 2023-12-31 18:07
awesome, will re-enable those tests on Fedora then. thanks!

**Comment by AdamWill** [comment] 2024-01-02 17:08
Oh, but +1 to @blshkv , a new release would be nice. 1.0.2 is old enough that the patch completely fails to apply to it. We could update our package to a git snapshot, but it'd be nice to have a new release...

**Comment by tiagocamargo** [comment] 2024-03-13 15:03
Will there be a fix #3685 before Ubuntu 24.04 is released?

```
fail2ban-server[10063]: 2024-03-13 11:37:17,232 fail2ban                [10063]: ERROR   No module named 'asynchat'
```

Installing fail2ban via apt, I have version `1.0.2`.
The python version is `3.12.2`.
Both from today's "ubuntu daily" build.

The pyasynchat package when installed with pip has the error "externally-managed-environment", which can be skipped using the "-break-system-packages" parameter.

I understand that this is not ideal behavior. When installed via apt, all dependencies should be taken into account and the service should be free from errors.

I am available for testing. 

Tanks!

**Comment by AdamWill** [comment] 2024-03-13 15:11
If you let the Ubuntu maintainer of the package know about this they should be able to handle it at the distro level, as we did for Fedora - https://src.fedoraproject.org/rpms/fail2ban/c/24c973f252f6d1b4231ee49ee4d5efac785a2fe8?branch=rawhide

**Comment by billkenney** [comment] 2024-03-19 18:16
I fixed this temporarily in Ubuntu 22.04 by modifying the systemd service file and adding /usr/bin/python3.10 to the ExecStart ExecStop and ExecReload

**Comment by kejilion** [comment] 2024-04-16 11:22
大概什么时候修复？3.12已经开始进入稳定通道了。我也已经受到影响 想知道何时发布新版本

**Comment by blshkv** [comment] 2024-04-16 11:36
> 大概什么时候修复？3.12已经开始进入稳定通道了。我也已经受到影响 想知道何时发布新版本
当你学习使用翻译器时

**Comment by kejilion** [comment] 2024-04-16 13:16
Dàgài shénme shíhòu xiūfù?3.12 Yǐjīng kāishǐ jìnrù wěndìng tōngdàole. Wǒ yě yǐjīng shòudào yǐngxiǎng xiǎng zhīdào hé shí fābù xīn bǎnběn

**Comment by kejilion** [comment] 2024-04-16 13:18
When will it be repaired? 3.12 has begun to enter the stable channel. I too have been affected and would like to know when the new version will be released

**Comment by Firefishy** [comment] 2024-04-23 13:37
I have reported the broken Ubuntu 24.04 fail2ban package upstream. Feel free to improve my poor attempt at a bug report ;-) https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/2063213

**Comment by kejilion** [comment] 2024-04-23 13:57
> The broken Ubuntu 24.04 fail2ban package has been reported upstream: https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/2055114



谢谢你 我已经用docker来部署fail2ban了  目前一切正常 再次感谢你的帮助和回复！

**Comment by AdamWill** [comment] 2024-04-25 22:06
awesome, thanks a lot!

**Comment by iamimmanuelraj** [comment] 2024-04-26 06:52
Hope this makes it inside 24.04 Soon

**Comment by sebres** [comment] 2024-04-26 10:58
[wiki :: Manual installation of debian upstream-package released here](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-of-debian-upstream-package-released-here)...
I assume, it'd be compatible to ubuntu 24.

**Comment by iamimmanuelraj** [comment] 2024-04-26 13:11
We so server management and use tools like Ansible. Doing manual installation on 1000's of servers is more of a headache and needs custom scripts to keep it updated. So hope Ubuntu finds this asap and uses a later version

**Comment by fozter** [comment] 2024-05-01 00:44
Im still getting **No module named 'asynchat'** when trying 1.1.0-1 upstream-package. What am i doing wrong? Running Ubuntu 24.04-rpi5.

**Comment by bymaer** [comment] 2024-05-01 19:57
same here

**Comment by fozter** [comment] 2024-05-02 01:58
> Im still getting **No module named 'asynchat'** when trying 1.1.0-1 upstream-package. What am i doing wrong? Running Ubuntu 24.04-rpi5.
> 
> Edit: I tried installing pyasynchat, didn't solve it

I'm not sure how, but i think i solved it by uninstalling f2b, re-installing 1.0.2 via apt, stopping the service and client, finally installing 1.1.0-1 over it.

**Comment by Xyaren** [comment] 2024-05-02 16:49
I can only recommend everybody who is affected to vote the bugreport
https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/2055114
by logging in and clicking the green text below the headline. You can mark yourself as affected by this.
Maybe the bug will gain enough attention to be fixed sooner.

**Comment by locvfx** [comment] 2024-05-05 05:50
Here is how to fix the problem 

```
wget https://launchpad.net/ubuntu/+source/fail2ban/1.1.0-1/+build/28291332/+files/fail2ban_1.1.0-1_all.deb
sudo dpkg -i fail2ban_1.1.0-1_all.deb
```

**Comment by mitchellvanbijleveld** [comment] 2024-05-14 16:21
> Here is how to fix the problem
> 
> ```
> wget https://launchpad.net/ubuntu/+source/fail2ban/1.1.0-1/+build/28291332/+files/fail2ban_1.1.0-1_all.deb
> sudo dpkg -i fail2ban_1.1.0-1_all.deb
> ```
> 
> ```
> systemctl enable fail2ban
> service fail2ban start
> fail2ban-client status
> ```

It really depends, whether whether this fixes the issue or not. At least for me, as a user of Plesk, some jails won't work anymore. Instead, installing the pyasynchat extension with pip actually fixes the issue. At least Plesk's fail2ban integration keeps working which is broken by installing the newer version from launchpad.

**Comment by AdamWill** [comment] 2024-05-14 16:28
At this point it sounds like maybe there's a downstream issue - Ubuntu and/or Debian maybe did not introduce a package dependency on the split-out asynchat/asyncore libraries when they packaged the new release. It might be better to report that to Debian/Ubuntu package maintainers? At least looking at https://packages.debian.org/sid/fail2ban , it doesn't look like any dependency on asynchat/asyncore is listed there. @sylvestre seems to be the Debian maintainer - did you miss this new dep, or am I misreading the Debian metadata?

**Comment by flavorgold1** [comment] 2024-05-16 02:27
Will the fix that comes along be able to solve our problems?

Or, will it require a reinstall?

**Comment by sebres** [comment] 2024-05-27 13:50
Well, there may be still an issue with `asyncore`: [GHA shows](https://github.com/fail2ban/fail2ban/actions/runs/9255756997/job/25460224706#step:7:26) that `pyinotify` may need it, so f2b may fail to initialize `pyinotify` backend.

Possible solution:
- newer version of `pyinotify` python module without a dependency to `asyncore`
- the fix 054e1d89ca3fa8b767ee21db1a3368f3d890baa8 (fallback to local libraries if import miss them) must be extended, e. g. extending a runtime PYTHONPATH to compat folder

**Comment by sebres** [comment] 2024-05-27 15:02
[Related to CI](https://github.com/fail2ban/fail2ban/actions/runs/9256861847/job/25463791039#step:7:26) it seems to be alright now (so 304c3cd56693c9ba90ace8b11c656ac2912648ca ultimately closes this).

**Comment by anildalar** [comment] 2024-05-31 01:52
> Here is how to fix the problem
> 
> ```
> wget https://launchpad.net/ubuntu/+source/fail2ban/1.1.0-1/+build/28291332/+files/fail2ban_1.1.0-1_all.deb
> sudo dpkg -i fail2ban_1.1.0-1_all.deb
> ```
> 
> ```
> systemctl enable fail2ban
> service fail2ban start
> fail2ban-client status
> ```

It Worked in Ubuntu 24.x. THanks

**Comment by william20210206** [comment] 2024-10-05 08:19
#3754 is the BEST way to solve these problem
