### ISSUE TITLE
Centos 7.3 install two Issues

### ISSUE THREAD

**Issue by AlexanderSk** [fail2ban/fail2ban#1782] opened 2017-05-18 12:45 UTC
### Environment:

- Fail2Ban version v0.10.0a2
- OS, including release name/version: Centos 7.3 fully updated
- [x] Did first a Yum fail2ban* remove to remove 9 version and the installed to lattes fail2ban manually (via git clone)
- [ ] You have not applied any additional foreign patches to the codebase: No additional patches
- [ ] Some customizations were done to the configuration (provide details below is so): no customizations

### The issue:

I just installed latest 0.10 version yesterday since i was on the latest yum version from the centos repo (9.3)

I did find two issues i would like to mention.

1)  All jails are working fine except recidivist that cannot find any actions. i the regex log also find nothing even though multiple bans have been performed.
2) when i make fail2ban-client reload 
All iptable rules are duplicated each time i perform that action the new rules are inserted but the old ones remain too!

Example: 

A) fail2ban-client reload recidive -> 
Chain f2b-recidive (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

B) fail2ban-client reload -> all iptable rules will be listed twice (X for the times reload is performed) in the iptables -L like the above one

I was thinking perhaps to completelly remove this and reinstall from schratch. i am not sure if any old fail2ban parts remains. yum remove fail2ban* has nothing more.

#### Any additional information
I have keept jail.local from version 9 as it was and contains the rules in that form:
```
[recidive]
enabled = true
logpath  = /var/log/fail2ban.log
banaction = iptables-allports
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 5
```
### Configuration, dump and another helpful excerpts
```
 fail2ban-client -d | grep 'recidive'
['add', 'recidive', 'polling']
['set', 'recidive', 'usedns', 'warn']
['set', 'recidive', 'addlogpath', '/var/log/fail2ban.log', 'head']
['set', 'recidive', 'maxretry', 5]
['set', 'recidive', 'logencoding', 'auto']
['set', 'recidive', 'bantime', '604800']
['set', 'recidive', 'ignorecommand', '']
['set', 'recidive', 'findtime', '86400']
['set', 'recidive', 'addfailregex', '^((?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.                   \\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?fail2ban\\.actions\\s*(?:\\(\\S+\\))?[\\]\\)                   ]?:?|[\\[\\(]?fail2ban\\.actions\\s*(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?|                    fail2ban\\.actions\\s*(?:\\[\\d+\\])?:\\s+)NOTICE\\s+\\[(?!recidive\\])(?:.*)\\]\\s+Ban\\s+<HOST>\\s*$']
['set', 'recidive', 'datepattern', '{^LN-BEG}']
['set', 'recidive', 'addjournalmatch', '_SYSTEMD_UNIT=fail2ban.service', 'PRIORITY=5']
['set', 'recidive', 'addaction', 'iptables-allports']
['multi-set', 'recidive', 'action', 'iptables-allports', [['actionstop', '<iptables> -D <chain> -p <protocol> -j f                   2b-<name>\n<actionflush>\n<iptables> -X f2b-<name>'], ['actioncheck', "<iptables> -n -L <chain> | grep -q 'f2b-<na                   me>[ \\t]'"], ['actionban', '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>'], ['actionstart', '<iptables> -N f                   2b-<name>\n<iptables> -A f2b-<name> -j <returntype>\n<iptables> -I <chain> -p <protocol> -j f2b-<name>'], ['action                   unban', '<iptables> -D f2b-<name> -s <ip> -j <blocktype>'], ['iptables', 'iptables <lockingopt>'], ['lockingopt',                    '-w'], ['known/lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['pr                   otocol', 'tcp'], ['name', 'recidive'], ['chain', 'INPUT'], ['known/iptables?family=inet6', 'ip6tables <lockingopt>                   '], ['known/protocol', 'tcp'], ['known/port', 'ssh'], ['known/returntype', 'RETURN'], ['known/iptables', 'iptables                    <lockingopt>'], ['known/chain', 'INPUT'], ['known/blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unrea                   chable'], ['known/name', 'default'], ['known/blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['iptables                   ?family=inet6', 'ip6tables <lockingopt>'], ['returntype', 'RETURN'], ['blocktype', 'REJECT --reject-with icmp-port                   -unreachable'], ['port', '0:65535'], ['bantime', '604800']]]
['start', 'recidive']
```
#### Any customizations done to /etc/fail2ban/ configuration
No customization

#### Relevant parts of /var/log/fail2ban.log file:
```
fail2ban-regex /var/log/fail2ban.log /etc/fail2ban/filter.d/recidive.conf

Running tests
=============

Use   failregex filter file : recidive, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG}
Use         log file : /var/log/fail2ban.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 7919 lines, 0 ignored, 0 matched, 7919 missed
[processed in 0.53 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 7919 lines
srv:/home/fail2ban#
```
#### Relevant lines from monitored log files in question:
Multiple ban actions like:
```
fail2ban-regex "2017-05-18 12:25:31,350 fail2ban.actions        [935]: NOTICE  [kippo] Ban 81.215.62.155" /etc/fail2ban/filter.d/recidive.conf
```

**Comment by sebres** [comment] 2017-05-18 13:19
1. I can not reproduce what's wrong with recidive-filter.
```bash
$ fail2ban-regex -v "2017-05-18 12:25:31,350 fail2ban.actions        [935]: NOTICE  [kippo] Ban 81.215.62.155" recidive

Running tests
=============

Use   failregex filter file : recidive, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use      single line : 2017-05-18 12:25:31,350 fail2ban.actions        [9...

Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^((?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?fail2ban\.actions\s*(?:\(\S+\))?[\]\)]?:?|[\[\(]?fail2ban\.actions\s*(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?| fail2ban\.actions\s*(?:\[\d+\])?:\s+)NOTICE\s+\[(?!recidive\])(?:.*)\]\s+Ban\s+<HOST>\s*$
|      81.215.62.155  Thu May 18 12:25:31 2017
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day[T ]24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
  * Which version of fail2ban exactly (revision of github) did you used?
  * Are the config-files under `/etc/fail2ban` were really updated (can you compare it with 0.10th configs)?
  * If older version was used (or some wrong configs), try it with the current version:
    - just get and unzip actual 0.10 from github into `/tmp/f2b-test`;
    - `cd /tmp/f2b-test`
    - `PYTHONPATH=. bin/fail2ban-regex -c ./config /var/log/fail2ban.log recidive`
2. I think as long as above mentioned issue does not resolved, I can not really analyse your second concern.

**Comment by AlexanderSk** [comment] 2017-05-18 13:31
Hi,

1) 
i did run git clone https://github.com/fail2ban/fail2ban.git
 fail2ban-client -v -> Fail2Ban v0.10.0a2 reads log file that contains password failure report
and bans the corresponding IP addresses using firewall rules.

2)
 as far as i checked with the repo yes they are updated. (also on ls -la i see the yesterdays date )

3)
i did re-download the latest version and run
fail2ban-regex: error: no such option: -c
myserver:/home/fail2ban#

Thank you for your time!

**Comment by sebres** [comment] 2017-05-18 13:47
> i did re-download the latest version and run
> fail2ban-regex: error: no such option: -c

This is impossible with latest version. The option was introduced in 0.10 for fail2ban-regex half year ago.
Just do it exactly I described above (`unzip into /tmp/f2b-test; cd /tmp/f2b-test; PYTHONPATH=. bin/fail2ban-regex -c ./config /var/log/fail2ban.log recidive`).
You should stay in the root of the fail2ban-folder (same directory as github-root with README and ChangeLog). Note the above mentioned thing will run only if current directory as well as PYTHONPATH points to the root-folder).

**Comment by sebres** [comment] 2017-05-18 14:42
2. I cannot reproduce "iptable rules duplication" also, neither using `reload` nor `restart`.

BTW(1) Normally `reload` (opposite to `restart`) does not touch something using actions (it should just reload the new config-values). Neiter unbanning/banning happens, nor the actionstop/actionstart will be executed.
BTW(2) In the current version a retarded starting was implemented (so actionstart will be executed on demand by the first ban corresponding IP-family).

Something seems to be really wrong with your fail2ban-installation.

**Comment by AlexanderSk** [comment] 2017-05-18 16:51
Hi About 1)
here is the whole console output
/tmp/f2b-test# dir
bin              COPYING   fail2ban-2to3                   FILTERS      MANIFEST.in     setup.cfg  Vagrantfile
ChangeLog        DEVELOP   fail2ban-testcases-all          kill-server  README.md       setup.py
config           doc       fail2ban-testcases-all-python3  man          README.Solaris  THANKS
CONTRIBUTING.md  fail2ban  files                           MANIFEST     RELEASE         TODO
srv:/tmp/f2b-test# PYTHONPATH=. bin/fail2ban-regex -c ./config /var/log/fail2ban.log recidive
Usage: bin/fail2ban-regex [OPTIONS] <LOG> <REGEX> [IGNOREREGEX]

Fail2Ban  reads log file that contains password failure report
and bans the corresponding IP addresses using firewall rules.

This tools can test regular expressions for "fail2ban".


LOG:
    string                  a string representing a log line
    filename                path to a log file (/var/log/auth.log)
    "systemd-journal"       search systemd journal (systemd-python required)

REGEX:
    string                  a string representing a 'failregex'
    filename                path to a filter file (filter.d/sshd.conf)

IGNOREREGEX:
    string                  a string representing an 'ignoreregex'
    filename                path to a filter file (filter.d/sshd.conf)

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko and Steven Hiscocks.

Report bugs to https://github.com/fail2ban/fail2ban/issues


fail2ban-regex: error: no such option: -c

Sometimes and somehow impossible is possible...  i am positive i am downloading the 0.10 branch.
I event looked into readme - release files after unzip

about 2)
Yes indeed.
Is there a way to perform an uninstall via setup.py ? i am thinking of removing all folders and reinstalling it from scratch with default configuration and checking it one by one rule...
Unfortunately i think i wont have that time soon ...
Kind regards.

**Comment by AlexanderSk** [comment] 2017-05-19 07:35
Update 19-5

I did remove all files i found for fail2ban

rm -rf /etc/fail2ban /etc/init.d/fail2ban /var/run/fail2ban /usr/share/doc/fail2ban /usr/local/bin/fail2ban* /usr/lib*/python*/site-packages/fail2ban /usr/local/lib*/python*/site-packages/fail2ban 

AND any folders - files in:

/usr/share/doc/fail2ban
/usr/bin/fail2ban-client
/usr/bin/fail2ban-python
/usr/bin/fail2ban-regex
/usr/bin/fail2ban-server
/usr/bin/fail2ban-testcases
/usr/lib/python2.7/site-packages/fail2ban
/var/lib/fail2ban
/usr/lib/systemd/system/fail2ban.service
/usr/lib/tmpfiles.d/fail2ban.conf
/etc/systemd/system/multi-user.target.wants/fail2ban.service

And reinstalled from git clone

I did copy some extra rules from my backup with copy -n (no replace) and also copied my jail.local file.

Good news so far:
1) Fail2ban starts no errors and the recidive sees and logs the bans :)
2) the reload restart now works as expected !!!

One note, i noticed that in the iptables only the chains that actually have a ban are visible, i gues this is the new 0.10 behavior?

fail2ban-client status shows all my jails and no errors in logs :)

**Comment by sebres** [comment] 2017-05-19 09:11
Glad it works... Thus closing.

> One note, i noticed that in the iptables only the chains that actually have a ban are visible, i gues this is the new 0.10 behavior?

As already said:
> In the current version a retarded starting was implemented (so actionstart will be executed on demand by the first ban corresponding IP-family).

**Closed by sebres** 2017-05-19 09:11 UTC
