### ISSUE TITLE
Port range for firewalld must use a dash, not colon

### ISSUE THREAD

**Issue by SpareSimian** [fail2ban/fail2ban#2821] opened 2020-09-02 21:26 UTC
In jail.conf is the line "port = 0:65535". This gets passed verbatim to firewall-cmd in direct rules which throws an error because it expects "0-65535". Adding "ports = 0-65535" to the [DEFAULT] section of jail.local eliminates the error.

In the log I see this:

     [4231]: ERROR   7f78734dacc8 -- exec: ports="0:65535"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule="rule family='ipv4' source address='64.56.74.121' port port='$p' protocol='tcp' reject type='icmp-port-unreachable'"; done
     [4231]: ERROR   7f78734dacc8 -- stderr: 'Error: INVALID_PORT: 0:65535'
     [4231]: ERROR   7f78734dacc8 -- returned 102
     [4231]: ERROR   Failed to execute ban jail 'recidive' action 'firewallcmd-rich-rules' info 'ActionInfo({'ip': '64.56.74.121', 'fid': <function <lambda> at 0x7f7873581de8>, 'family': 'inet4', 'raw-ticket': <function <lambda> at 0x7f7873582410>})': Error banning 64.56.74.121

### Environment:
fail2ban-0.11.1-9.el7.2.noarch
centos-release-7-8.2003.0.el7.centos.x86_64

**Comment by sebres** [comment] 2020-09-03 11:13
The same is valid as for #2765 (for nftables), inclusive possible solution like 62a6771b3343e32e9fcf89409edbed5541a7b27b.
Also note that default port range is normally unused if proper banaction is chosen (or its `actiontype` parameter set correctly), for instance `firewallcmd-allports` instead of `firewallcmd-multiport`.

**Comment by sebres** [comment] 2020-09-07 12:12
Fixed in a038fd5dfe8cb0714472833604735b83462a217d

**Closed by sebres** 2020-09-07 12:12 UTC

**Comment by kovacs-andras** [comment] 2021-10-30 10:08
This broke the Firewalld compatibility with iptables backend. :(

**Comment by sebres** [comment] 2021-11-01 10:21
I'm agree that we'd revert it... further in #3047

**Comment by berlin2123** [comment] 2022-10-14 09:51
is it not fixed in master branche?  This issue [appear again in newest version 1.0.1](https://forums.rockylinux.org/t/fail2ban-failed-to-ban-recidive-in-rocky-9/7549)

**Comment by sebres** [comment] 2022-10-17 10:30
It is reverted in 4b54a07d71a6ce1c85a3eae92bace6c0dadcdcfb (see #3047 for whole discussion).
The issue is - it is impossible to handle this correctly, because it is related to backend firewalld uses (it seems to supply the parameter unhandled directly to related backend and one may accept a colon another a dash, see https://github.com/fail2ban/fail2ban/issues/3047#issuecomment-868725757

Now this will be considered rather as an issue of firewalld, not of fail2ban.

**Comment by sebres** [comment] 2023-12-25 14:10
It is more or less a matter of configuration... Since the port isn't need if used allports action.

As already said in https://github.com/fail2ban/fail2ban/issues/2821#issuecomment-1280642028 there is no generalized solution possible, because fail2ban doesn't know which backend firewalld internally uses and therefore which syntax would be correct for this particular backend.

The ultimate solution is not to use firewalld actions at all, but instead switch to banaction talking to the native net-filter (like iptables-ipset or nftables). I never understand the pros of usage an intermediate layers like firewalld anyway.

Alternatively (if one nevertheless want to use firewalld action, one need to specify the `port` in jail in the syntax firewalld would accept it for the particular backend it uses and use allports action for all ports instead of multiport. 

For instance if it is firewalld with iptables backend (if I correct understand the port-range syntax, otherwise use it vice versa):
```ini
[DEFAULT]
## default banaction for multiport jails:
# banaction = firewallcmd-ipset[actiontype=<multiport>]
banaction = firewallcmd-multiport

## default banaction for allports jails:
# banaction_allports = firewallcmd-ipset[actiontype=<allports>]
banaction_allports = firewallcmd-allports

## basically no matter if allports uses correctly, but for completeness reason:
port = 0-65535

## stock multiport jail will be correct (no port range here, because `port = http,https`):
[nginx-http-auth]
enabled = true

## stock allport jail will be also correct (no ports used by allports action):
[pam-generic]
enabled = true

## own multiport jail (with own port range and multiport `banaction` by default):
[nginx-and-ws]
# banaction = firewallcmd-multiport
port = http,https,8080-8088
enabled = true

## own alloprts jail (without port range, `banaction` set to allports action):
[my-recidive-jail]
# banaction = firewallcmd-ipset[actiontype=<allports>]
banaction = firewallcmd-allports
enabled = true
```

If one'd use firewalld with nftables backend, it expect replacement `-` with `:` (minus with a colon) in all `port` ranges.
That's it.
