### ISSUE TITLE
speed fail2ban up?

### ISSUE THREAD

**Issue by techpulse** [fail2ban/fail2ban#1049] opened 2015-05-09 18:43 UTC
hi, are there any ways of speeding it up? giving more cores/threads/ram? 

i have 8 cores, curious how..

**Comment by leeclemens** [comment] 2015-05-09 19:47
Have you run it with a profiler or gathered some metrics as to what specifically you wish to speed up?  I believe the jails are loaded sequentially, so they would not utilize more CPU...although you are likely more disk-bound during the initial log parsing anyway. That is an assumption on my part...I'd need to profile it and my server before considering where to optimize.

**Comment by techpulse** [comment] 2015-05-09 19:49
i dont really now, i just though if there are any ways to make it faster for me?

i got 8 cores * Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GH...

+ 2GB ram, considering to get more ram tho

**Comment by leeclemens** [comment] 2015-05-09 20:05
I don't think anyone can help with this broad of a question. Is there something specific you noticed that is slower than you would expect?

**Comment by techpulse** [comment] 2015-05-09 20:06
I am using the CloudFlare BlackList option, i would think that it would block a little faster (its using curls) but maybe curl is delaying it. Or CF in general

**Comment by leeclemens** [comment] 2015-05-09 20:31
I think this is related to the issue you already raised https://github.com/fail2ban/fail2ban/issues/1040 ? And as discussed there, there can be a delay between fail2ban requestion CloudFlare block an IP and the actual implementation of that block - leading to requests from a 'blocked' IP still coming through to your web server until CloudFlare completes the implementation of your requested blacklist?

**Comment by leeclemens** [comment] 2015-05-09 20:45
I'm going to close this, as it seems to be a duplicate of (you just replied to it as well) #1040.

**Closed by leeclemens** 2015-05-09 20:45 UTC
