### ISSUE TITLE
Database will be not purged at all (currently no db.purge call, except test cases)

### ISSUE THREAD

**Issue by Ac314** [fail2ban/fail2ban#1267] opened 2015-12-07 14:31 UTC
If we restart the computer where fail2ban is running then after the computer boots and fail2ban starts the database is not purged (old entries are still there and banned). So dbpurge value is ignored (in my case it is set in fail2ban.local).
It seems database purging must be performed when fail2ban starts (before starting to ban anything) to avoid this behavior.

**Comment by sebres** [comment] 2015-12-07 16:54
The issue is known... for example see https://github.com/fail2ban/fail2ban/pull/1050#issuecomment-100832885
I've said already several times, purge will never called (only in test case):
https://github.com/fail2ban/fail2ban/search?utf8=%E2%9C%93&q=%22purge%28%29%22&type=Code

Currently fixed in #716 only.

**Comment by sebres** [comment] 2017-08-18 12:08
Fixed in 0.11th branch. 
Thus closing.

**Closed by sebres** 2017-08-18 12:08 UTC

**Comment by shaneonabike** [comment] 2020-08-20 00:55
Also just to note from other tickets that a solution for those of us with older versions you can add a cronjob to do a cleanup

`python -c "import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.INFO); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb('/var/lib/fail2ban/fail2ban.sqlite3'); db.purge()"`

Just verify that your fail2ban database is the same as above.
